// Feature-local classifier sheet for the ordinary World Bible wiki surface.
import { classifier } from '../../../runtime/classifier';
import { REGIONS } from '../shell/regions';

const MONO = 'monospace';

classifier({
  WB_IndexPanel: { type: 'Box', style: { width: REGIONS.contentBrowser.width, minWidth: REGIONS.contentBrowser.width, flexDirection: 'column', minHeight: 0, backgroundColor: 'theme:bgAlt', borderRightWidth: 1, borderRightColor: 'theme:border' } },
  WB_IndexHead: { type: 'Box', style: { height: 43, flexDirection: 'row', alignItems: 'center', gap: 8, paddingLeft: 10, paddingRight: 8, borderBottomWidth: 1, borderBottomColor: 'theme:border' } },
  WB_IndexTitle: { type: 'Text', fontSize: 11, color: 'theme:text', noWrap: true, style: { fontFamily: MONO, fontWeight: 900, letterSpacing: 0.7 } },
  WB_IconButton: { type: 'Pressable', style: { width: 26, height: 26, alignItems: 'center', justifyContent: 'center', borderRadius: 3, backgroundColor: 'theme:controlBg', borderWidth: 1, borderColor: 'theme:controlBorder' }, hoverStyle: { borderColor: 'theme:primary' } },
  WB_SearchWrap: { type: 'Box', style: { height: 42, padding: 7, borderBottomWidth: 1, borderBottomColor: 'theme:borderSoft' } },
  WB_SearchBox: { type: 'Box', style: { flexGrow: 1, flexDirection: 'row', alignItems: 'center', gap: 7, paddingLeft: 8, paddingRight: 7, backgroundColor: 'theme:controlBg', borderWidth: 1, borderColor: 'theme:controlBorder', borderRadius: 3 } },
  WB_SearchInput: { type: 'TextInput', style: { flexGrow: 1, minWidth: 0, height: 28, color: 'theme:text', fontSize: 10, fontFamily: MONO } },
  WB_FilterBar: { type: 'Box', style: { minHeight: 55, flexDirection: 'row', flexWrap: 'wrap', alignContent: 'center', gap: 4, padding: 7, borderBottomWidth: 1, borderBottomColor: 'theme:borderSoft' } },
  WB_Filter: { type: 'Pressable', style: { height: 20, justifyContent: 'center', paddingLeft: 7, paddingRight: 7, borderRadius: 2, backgroundColor: 'theme:controlBg', borderWidth: 1, borderColor: 'theme:borderSoft' }, hoverStyle: { borderColor: 'theme:textDim' } },
  WB_FilterOn: { type: 'Pressable', style: { height: 20, justifyContent: 'center', paddingLeft: 7, paddingRight: 7, borderRadius: 2, backgroundColor: 'theme:segActiveBg', borderWidth: 1, borderColor: 'theme:primary' } },
  WB_FilterText: { type: 'Text', fontSize: 7, color: 'theme:textDim', noWrap: true, style: { fontFamily: MONO, fontWeight: 800, letterSpacing: 0.4 } },
  WB_FilterTextOn: { type: 'Text', fontSize: 7, color: 'theme:segActiveText', noWrap: true, style: { fontFamily: MONO, fontWeight: 900, letterSpacing: 0.4 } },
  WB_PageList: { type: 'ScrollView', style: { flexGrow: 1, minHeight: 0 } },
  WB_PageRow: { type: 'Pressable', style: { minHeight: 50, flexDirection: 'row', alignItems: 'center', gap: 8, paddingLeft: 9, paddingRight: 8, paddingTop: 6, paddingBottom: 6, borderBottomWidth: 1, borderBottomColor: 'theme:borderSoft' }, hoverStyle: { backgroundColor: 'theme:surfaceHover' } },
  WB_PageRowOn: { type: 'Pressable', style: { minHeight: 50, flexDirection: 'row', alignItems: 'center', gap: 8, paddingLeft: 8, paddingRight: 8, paddingTop: 6, paddingBottom: 6, backgroundColor: 'theme:segActiveBg', borderLeftWidth: 2, borderLeftColor: 'theme:primary', borderBottomWidth: 1, borderBottomColor: 'theme:borderSoft' } },
  WB_KindMark: { type: 'Box', style: { width: 8, height: 8, borderRadius: 4, backgroundColor: 'theme:primary' } },
  WB_PageCopy: { type: 'Box', style: { flexGrow: 1, minWidth: 0, flexDirection: 'column', gap: 3 } },
  WB_PageName: { type: 'Text', fontSize: 10, color: 'theme:text', noWrap: true, numberOfLines: 1, style: { fontWeight: 800 } },
  WB_PageRef: { type: 'Text', fontSize: 7, color: 'theme:textFaint', noWrap: true, numberOfLines: 1, style: { fontFamily: MONO } },
  WB_StateTiny: { type: 'Text', fontSize: 6, noWrap: true, style: { fontFamily: MONO, fontWeight: 900, letterSpacing: 0.3 } },
  WB_IndexFoot: { type: 'Box', style: { minHeight: 28, flexDirection: 'row', alignItems: 'center', gap: 7, paddingLeft: 9, paddingRight: 8, borderTopWidth: 1, borderTopColor: 'theme:border' } },
  WB_MicroText: { type: 'Text', fontSize: 7, color: 'theme:textFaint', noWrap: true, style: { fontFamily: MONO, fontWeight: 700 } },

  WB_Surface: { type: 'Box', style: { width: '100%', height: '100%', flexDirection: 'column', minWidth: 0, minHeight: 0, backgroundColor: 'theme:surface' } },
  WB_SourceBanner: { type: 'Box', style: { minHeight: 34, flexDirection: 'row', alignItems: 'center', gap: 8, paddingLeft: 14, paddingRight: 12, backgroundColor: 'theme:bgAlt', borderBottomWidth: 1, borderBottomColor: 'theme:border' } },
  WB_StateBadge: { type: 'Box', style: { height: 18, justifyContent: 'center', paddingLeft: 7, paddingRight: 7, borderRadius: 2, backgroundColor: 'theme:controlBg', borderWidth: 1, borderColor: 'theme:controlBorder' } },
  WB_StateText: { type: 'Text', fontSize: 7, noWrap: true, style: { fontFamily: MONO, fontWeight: 900, letterSpacing: 0.6 } },
  WB_BannerText: { type: 'Text', fontSize: 8, color: 'theme:textDim', noWrap: true, numberOfLines: 1, style: { flexGrow: 1, minWidth: 0, fontFamily: MONO } },
  WB_DiscardConfirm: { type: 'Box', style: { minHeight: 52, flexDirection: 'row', alignItems: 'center', gap: 9, paddingLeft: 14, paddingRight: 12, paddingTop: 8, paddingBottom: 8, backgroundColor: 'theme:controlBg', borderBottomWidth: 1, borderBottomColor: 'theme:error' } },
  WB_DiscardCopy: { type: 'Box', style: { flexGrow: 1, minWidth: 0, flexDirection: 'column', gap: 4 } },
  WB_DiagnosticPanel: { type: 'Box', style: { minHeight: 62, maxHeight: 150, flexDirection: 'column', backgroundColor: 'theme:bgAlt', borderBottomWidth: 1, borderBottomColor: 'theme:warning' } },
  WB_DiagnosticHead: { type: 'Box', style: { minHeight: 30, flexDirection: 'row', alignItems: 'center', gap: 7, paddingLeft: 14, paddingRight: 12, borderBottomWidth: 1, borderBottomColor: 'theme:borderSoft' } },
  WB_DiagnosticList: { type: 'ScrollView', style: { flexGrow: 1, minHeight: 0 }, contentContainerStyle: { flexDirection: 'column' } },
  WB_DiagnosticRow: { type: 'Box', style: { minHeight: 54, flexDirection: 'row', alignItems: 'center', gap: 9, paddingLeft: 11, paddingRight: 12, paddingTop: 7, paddingBottom: 7, borderLeftWidth: 3, borderLeftColor: 'theme:warning', borderBottomWidth: 1, borderBottomColor: 'theme:borderSoft' } },
  WB_DiagnosticCopy: { type: 'Box', style: { flexGrow: 1, minWidth: 0, flexDirection: 'column', gap: 3 } },
  WB_PageHead: { type: 'Box', style: { minHeight: 80, flexDirection: 'row', alignItems: 'center', gap: 12, paddingLeft: 22, paddingRight: 18, paddingTop: 12, paddingBottom: 12, backgroundColor: 'theme:bgElevated', borderBottomWidth: 1, borderBottomColor: 'theme:border' } },
  WB_HeadCopy: { type: 'Box', style: { flexGrow: 1, minWidth: 0, flexDirection: 'column', gap: 5 } },
  WB_Kicker: { type: 'Text', fontSize: 7, color: 'theme:primary', noWrap: true, style: { fontFamily: MONO, fontWeight: 900, letterSpacing: 1.1 } },
  WB_Title: { type: 'Text', fontSize: 23, color: 'theme:text', noWrap: true, numberOfLines: 1, style: { fontWeight: 900 } },
  WB_Subtitle: { type: 'Text', fontSize: 8, color: 'theme:textDim', noWrap: true, numberOfLines: 1, style: { fontFamily: MONO } },
  WB_ActionRow: { type: 'Box', style: { flexDirection: 'row', alignItems: 'center', gap: 6 } },
  WB_Action: { type: 'Pressable', style: { height: 27, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingLeft: 9, paddingRight: 9, borderRadius: 3, backgroundColor: 'theme:controlBg', borderWidth: 1, borderColor: 'theme:controlBorder' }, hoverStyle: { borderColor: 'theme:primary' } },
  WB_ActionOn: { type: 'Pressable', style: { height: 27, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingLeft: 9, paddingRight: 9, borderRadius: 3, backgroundColor: 'theme:segActiveBg', borderWidth: 1, borderColor: 'theme:primary' } },
  WB_ActionDanger: { type: 'Pressable', style: { height: 27, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingLeft: 9, paddingRight: 9, borderRadius: 3, backgroundColor: 'theme:controlBg', borderWidth: 1, borderColor: 'theme:error' }, hoverStyle: { backgroundColor: 'theme:surfaceHover' } },
  WB_ActionText: { type: 'Text', fontSize: 7, color: 'theme:textSecondary', noWrap: true, style: { fontFamily: MONO, fontWeight: 900, letterSpacing: 0.4 } },
  WB_Content: { type: 'Box', style: { flexGrow: 1, minHeight: 0, flexDirection: 'row' } },
  WB_ArticleScroll: { type: 'ScrollView', style: { flexGrow: 1, minWidth: 0, minHeight: 0 } },
  WB_Article: { type: 'Box', style: { flexDirection: 'column', gap: 16, paddingLeft: 28, paddingRight: 28, paddingTop: 24, paddingBottom: 40 } },
  WB_Section: { type: 'Box', style: { flexDirection: 'column', gap: 8 } },
  WB_SectionHead: { type: 'Text', fontSize: 13, color: 'theme:text', style: { fontWeight: 900 } },
  WB_Paragraph: { type: 'Text', fontSize: 11, color: 'theme:textSecondary', style: { lineHeight: 18 } },
  WB_LinkLine: { type: 'Box', style: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center' } },
  WB_Link: { type: 'Pressable', style: { minHeight: 18, justifyContent: 'center', paddingLeft: 2, paddingRight: 2 } },
  WB_LinkText: { type: 'Text', fontSize: 11, color: 'theme:primary', style: { fontWeight: 800, lineHeight: 18 } },
  WB_AuthorMarkdown: { type: 'Box', style: { flexDirection: 'column', gap: 7, padding: 12, borderRadius: 4, backgroundColor: 'theme:controlBg', borderWidth: 1, borderColor: 'theme:warning' } },
  WB_Notes: { type: 'Box', style: { flexDirection: 'column', gap: 7, padding: 12, borderRadius: 4, backgroundColor: 'theme:controlBg', borderWidth: 1, borderColor: 'theme:info' } },
  WB_PublicPreview: { type: 'Box', style: { flexDirection: 'column', gap: 7, padding: 12, borderRadius: 4, backgroundColor: 'theme:controlBg', borderWidth: 1, borderColor: 'theme:success' } },
  WB_PublicPreviewFact: { type: 'Box', style: { minHeight: 30, flexDirection: 'row', alignItems: 'center', gap: 10, paddingTop: 5, paddingBottom: 5, borderTopWidth: 1, borderTopColor: 'theme:borderSoft' } },
  WB_Aside: { type: 'ScrollView', style: { width: 300, minWidth: 300, minHeight: 0, backgroundColor: 'theme:bgAlt', borderLeftWidth: 1, borderLeftColor: 'theme:border' }, contentContainerStyle: { flexDirection: 'column', padding: 14, gap: 10, paddingBottom: 28 } },
  WB_Logo: { type: 'Box', style: { height: 128, alignItems: 'center', justifyContent: 'center', gap: 8, borderRadius: 4, backgroundColor: 'theme:controlBg', borderWidth: 1, borderColor: 'theme:border' } },
  WB_Monogram: { type: 'Box', style: { width: 68, height: 68, alignItems: 'center', justifyContent: 'center', borderRadius: 34, backgroundColor: 'theme:onTrack', borderWidth: 2, borderColor: 'theme:accent' } },
  WB_MonogramText: { type: 'Text', fontSize: 18, color: 'theme:accent', noWrap: true, style: { fontFamily: MONO, fontWeight: 900 } },
  WB_Infobox: { type: 'Box', style: { flexDirection: 'column', borderRadius: 4, backgroundColor: 'theme:controlBg', borderWidth: 1, borderColor: 'theme:border', overflow: 'hidden' } },
  WB_InfoHead: { type: 'Box', style: { minHeight: 52, alignItems: 'center', justifyContent: 'center', gap: 3, padding: 9, borderBottomWidth: 1, borderBottomColor: 'theme:border' } },
  WB_InfoTitle: { type: 'Text', fontSize: 11, color: 'theme:text', noWrap: true, numberOfLines: 1, style: { fontWeight: 900 } },
  WB_InfoKind: { type: 'Text', fontSize: 7, color: 'theme:textFaint', noWrap: true, style: { fontFamily: MONO, fontWeight: 800, letterSpacing: 0.7 } },
  WB_FactRow: { type: 'Box', style: { minHeight: 46, flexDirection: 'row', gap: 8, padding: 9, borderBottomWidth: 1, borderBottomColor: 'theme:borderSoft' } },
  WB_FactLabelCol: { type: 'Box', style: { width: 88, flexDirection: 'column', gap: 4 } },
  WB_FactLabel: { type: 'Text', fontSize: 7, color: 'theme:textFaint', style: { fontFamily: MONO, fontWeight: 900, letterSpacing: 0.4 } },
  WB_FactValue: { type: 'Text', fontSize: 9, color: 'theme:textSecondary', style: { flexGrow: 1, minWidth: 0, lineHeight: 13 } },
  WB_ScopeText: { type: 'Text', fontSize: 6, noWrap: true, style: { fontFamily: MONO, fontWeight: 900, letterSpacing: 0.3 } },
  WB_SourceCard: { type: 'Box', style: { flexDirection: 'column', gap: 5, padding: 9, borderRadius: 4, backgroundColor: 'theme:controlBg', borderWidth: 1, borderColor: 'theme:borderSoft' } },
  WB_SourcePath: { type: 'Text', fontSize: 7, color: 'theme:textDim', style: { fontFamily: MONO, lineHeight: 11 } },
  WB_Backlink: { type: 'Pressable', style: { minHeight: 30, flexDirection: 'row', alignItems: 'center', gap: 7, paddingLeft: 8, paddingRight: 8, borderRadius: 3, backgroundColor: 'theme:controlBg', borderWidth: 1, borderColor: 'theme:borderSoft' }, hoverStyle: { borderColor: 'theme:primary' } },

  WB_EditScroll: { type: 'ScrollView', style: { flexGrow: 1, minHeight: 0 } },
  WB_EditBody: { type: 'Box', style: { flexDirection: 'column', gap: 18, paddingLeft: 28, paddingRight: 28, paddingTop: 22, paddingBottom: 44 } },
  WB_FormRow: { type: 'Box', style: { flexDirection: 'row', gap: 10 } },
  WB_Field: { type: 'Box', style: { flexGrow: 1, minWidth: 0, flexDirection: 'column', gap: 5 } },
  WB_FieldLabel: { type: 'Text', fontSize: 7, color: 'theme:textDim', noWrap: true, style: { fontFamily: MONO, fontWeight: 900, letterSpacing: 0.6 } },
  WB_Input: { type: 'TextInput', style: { height: 32, paddingLeft: 9, paddingRight: 9, borderRadius: 3, backgroundColor: 'theme:controlBg', borderWidth: 1, borderColor: 'theme:controlBorder', color: 'theme:text', fontSize: 10, fontFamily: MONO } },
  WB_InputReadOnly: { type: 'Box', style: { height: 32, justifyContent: 'center', paddingLeft: 9, paddingRight: 9, borderRadius: 3, backgroundColor: 'theme:bgAlt', borderWidth: 1, borderColor: 'theme:borderSoft' } },
  WB_FactEdit: { type: 'Box', style: { flexDirection: 'column', gap: 7, padding: 9, borderRadius: 4, backgroundColor: 'theme:bgAlt', borderWidth: 1, borderColor: 'theme:borderSoft' } },
  WB_FactEditHead: { type: 'Box', style: { flexDirection: 'row', alignItems: 'center', gap: 7 } },
  WB_FactKey: { type: 'Text', fontSize: 8, color: 'theme:primary', noWrap: true, style: { flexGrow: 1, minWidth: 0, fontFamily: MONO, fontWeight: 900 } },

  WB_Review: { type: 'Box', style: { flexGrow: 1, minHeight: 0, flexDirection: 'column', padding: 18, gap: 12, backgroundColor: 'theme:bgAlt' } },
  WB_ReviewMeta: { type: 'Box', style: { flexDirection: 'column', gap: 5, padding: 10, borderRadius: 4, backgroundColor: 'theme:controlBg', borderWidth: 1, borderColor: 'theme:warning' } },
  WB_ReviewCols: { type: 'Box', style: { flexGrow: 1, minHeight: 0, flexDirection: 'row', gap: 10 } },
  WB_ReviewCol: { type: 'Box', style: { flexGrow: 1, minWidth: 0, minHeight: 0, flexDirection: 'column', gap: 7, padding: 10, borderRadius: 4, backgroundColor: 'theme:surface', borderWidth: 1, borderColor: 'theme:border' } },
  WB_ReviewScroll: { type: 'ScrollView', style: { flexGrow: 1, minHeight: 0 } },
  WB_DiffText: { type: 'Text', fontSize: 8, color: 'theme:textSecondary', style: { fontFamily: MONO, lineHeight: 12 } },
  WB_ChangeRow: { type: 'Box', style: { flexDirection: 'column', gap: 4, padding: 8, borderBottomWidth: 1, borderBottomColor: 'theme:borderSoft' } },
});
