// Editor-owned canonical texture-shader catalog: every tunable
// WGSL recipe a texture can be authored from, each one NAMED, range-bounded,
// draggable parameters — never a bare data[] of magic numbers. (Lineage: lived as
// a prototype texture catalog; the active editor owns both the recipes and the
// authoring controls now.)
//
// A ShaderSpec here is a RECIPE: ShaderLab can still tune it and Materialize a
// custom frozen look. The registry also derives ShaderTexturePresets from these
// recipes so authored takes/quality grades are directly assignable without
// opening the lab. Canvas is always exactly 1 tile — wider looks decompose into
// per-tile materials.
//
// Two shader families:
//   • ROAD — the game's own layered road-tile shader (asphalt base + marking
//     overlays), imported from the W-2 render lane's roadTileFill.ts.
//   • THE FILL BOARDS — the effect_fills evaluation boards (A–O), one-material-
//     per-file under render3d/shaders/materials/, swept + generated by
//     render3d/shaders/build-shaders.ts. D[] selects [materialId, variant,
//     seed, quality, board]. Each board material becomes one spec with its three
//     authored takes as variants and seed/detail-grade as the tunable base.
//     FILL_BOARDS below is imported from the generated registry — do not
//     hand-edit it here; add/remove a material by adding/removing its .wgsl
//     file, then rerun build-shaders.ts.
import { ROAD_TILE_SHADER } from '../render3d/roadTileFill';
import { FILL_SHADER } from '../render3d/shaders/index';
import { FILL_BOARDS as GENERATED_FILL_BOARDS, MATERIALS, type FillBoard, type FillMaterial, type MaterialSlot } from '../render3d/shaders/_generated/registry';
import { packMissionData } from './missionCode';

export type { MaterialSlot };

export interface ShaderParam {
  key: string;
  label: string;
  default: number;
  min: number;
  max: number;
  step: number;
  unit?: string;
  integer?: boolean;
}

// One overlay child — sits on the shared base and adds its own layer.
export interface ShaderVariant {
  id: string;
  label: string;
  value: number; // the selector the shader reads to pick this overlay/take
  params: ShaderParam[]; // this overlay's own sliders (empty = nothing to tune)
}

export interface ShaderSpec {
  id: string;
  label: string;
  group: string; // visible material-browser shelf by purpose/use, never board family
  blurb: string;
  shader: string; // the real WGSL string — single source, no copies
  base: ShaderParam[]; // shared across every variant
  variants: ShaderVariant[]; // the overlay children (>= 1)
  // Pack base + overlay values into the exact data[] fs_main expects.
  buildData: (variantValue: number, base: Record<string, number>, overlay: Record<string, number>) => number[];
  // Palette slots (fill-board materials only): the baked vec3f colors the
  // material's WGSL uses, extracted by build-shaders.ts in mat_pal() index
  // order. Recolor by appending a palette to the data[] via withPalette().
  slots?: MaterialSlot[];
}

/** Append a palette section to a fill-material data[]: D[5] = slot count,
 *  D[6 + i*3 ..] = slot i RGB. Pass null/empty to keep the 5-float baked form
 *  (mat_pal falls back to the authored constants — pixel-identical). */
export function withPalette(data: number[], palette: Array<[number, number, number]> | null | undefined): number[] {
  if (!palette || palette.length === 0) return data;
  return [...data.slice(0, 5), palette.length, ...palette.flat()];
}

export type ShaderTexturePreset = {
  id: string;
  label: string;
  group: string;
  shaderId: string;
  shader: string;
  data: number[];
};

// Default value maps — the slider starting positions for the base or a variant.
export function paramDefaults(params: ShaderParam[]): Record<string, number> {
  const out: Record<string, number> = {};
  for (const p of params) out[p.key] = p.default;
  return out;
}

// A spec's out-of-the-box data[]: first variant + every default. THE way to get
// a default look (replaces hand-written default data arrays).
export function defaultShaderData(spec: ShaderSpec): number[] {
  return spec.buildData(spec.variants[0].value, paramDefaults(spec.base), paramDefaults(spec.variants[0].params));
}

// ── Road, decomposed into one-tile layered materials ─────────────────────────
// Base = asphalt (shared). Variants = the per-tile overlays a road is built from.
// See roadTileFill.ts for the D[] layout.
const ROAD: ShaderSpec = {
  id: 'road',
  label: 'Road',
  group: 'Pavement & Streets',
  blurb: 'One road tile: shared asphalt base + the lane/centerline/bike overlay.',
  shader: ROAD_TILE_SHADER,
  base: [
    { key: 'brightness', label: 'Asphalt brightness', default: 1, min: 0.4, max: 1.6, step: 0.05 },
    { key: 'speckle', label: 'Asphalt grain', default: 0.12, min: 0, max: 0.4, step: 0.01 },
  ],
  variants: [
    { id: 'asphalt', label: 'Asphalt (base)', value: 0, params: [] },
    {
      id: 'yellow', label: 'Yellow Center', value: 1, params: [
        { key: 'lineHalf', label: 'Line thickness', default: 0.05, min: 0.02, max: 0.2, step: 0.005, unit: 'm' },
        { key: 'doubleGap', label: 'Double-line gap', default: 0.12, min: 0, max: 0.4, step: 0.01, unit: 'm' },
      ],
    },
    {
      id: 'white', label: 'White Divider', value: 2, params: [
        { key: 'lineHalf', label: 'Line thickness', default: 0.05, min: 0.02, max: 0.2, step: 0.005, unit: 'm' },
        { key: 'dashPeriod', label: 'Dash period', default: 0.35, min: 0.1, max: 1, step: 0.05, unit: 'm' },
        { key: 'dashFrac', label: 'Dash on-fraction', default: 0.5, min: 0.05, max: 0.95, step: 0.05 },
      ],
    },
    {
      id: 'bike', label: 'Bike Lane', value: 3, params: [
        { key: 'bikeEdge', label: 'Edge-line thickness', default: 0.05, min: 0.02, max: 0.2, step: 0.005, unit: 'm' },
      ],
    },
  ],
  buildData: (variantValue, base, o) => [
    variantValue,
    base.brightness,
    base.speckle,
    o.lineHalf ?? 0.05,
    o.doubleGap ?? 0.12,
    o.dashPeriod ?? 0.35,
    o.dashFrac ?? 0.5,
    o.bikeEdge ?? 0.05,
  ],
};

// ── Cutout stencil — shapes authored in the cutout painter (/cutout) ─────────
// The painter Materializes an extracted cutout into THIS recipe: data carries
// a coarse stencil grid (row-major 0/1 cells) plus fill/background colors —
// fill inside the shape, background (or transparency) outside. The catalog's
// slider form edits the colors over a full tile; the painter packs the real
// cells (editors/cutout/extraction.ts packStencilData — the layout below is
// pinned by its P4 test).
//
// data D[]:
//   D[0] gridW   stencil grid width  (cells per row)
//   D[1] gridH   stencil grid height
//   D[2..4]      fill r,g,b
//   D[5..7]      background r,g,b
//   D[8]         background alpha (0 = the shape floats on transparency)
//   D[9]         reserved
//   D[10+]       cells, row-major, 0/1
export const CUTOUT_STENCIL_SHADER = `
@group(0) @binding(1) var<storage, read> D: array<f32>;
@fragment fn fs_main(in: VsOut) -> @location(0) vec4f {
  let gw = max(D[0], 1.0);
  let gh = max(D[1], 1.0);
  let igw = u32(gw);
  let cx = min(u32(floor(in.uv.x * gw)), igw - 1u);
  let cy = min(u32(floor(in.uv.y * gh)), u32(gh) - 1u);
  let m = D[10u + cy * igw + cx];
  if (m < 0.5) {
    return vec4f(D[5], D[6], D[7], D[8]);
  }
  return vec4f(D[2], D[3], D[4], 1.0);
}
`;

const STENCIL_SLIDER_GRID = 8; // the slider form's full-tile grid (all cells set)

const CUTOUT_STENCIL: ShaderSpec = {
  id: 'cutout-stencil',
  label: 'Cutout Stencil',
  group: 'Codes & Stencils',
  blurb: 'A shape painted in the cutout painter (/cutout), frozen as a stencil: fill color inside the shape, background or transparency outside. Materialize real shapes from /cutout; the sliders here tune a full tile.',
  shader: CUTOUT_STENCIL_SHADER,
  base: [
    { key: 'fillR', label: 'Fill red', default: 1, min: 0, max: 1, step: 0.05 },
    { key: 'fillG', label: 'Fill green', default: 1, min: 0, max: 1, step: 0.05 },
    { key: 'fillB', label: 'Fill blue', default: 1, min: 0, max: 1, step: 0.05 },
    { key: 'bgR', label: 'Background red', default: 0, min: 0, max: 1, step: 0.05 },
    { key: 'bgG', label: 'Background green', default: 0, min: 0, max: 1, step: 0.05 },
    { key: 'bgB', label: 'Background blue', default: 0, min: 0, max: 1, step: 0.05 },
    { key: 'bgAlpha', label: 'Background alpha', default: 1, min: 0, max: 1, step: 0.05 },
  ],
  variants: [{ id: 'full', label: 'Full tile', value: 0, params: [] }],
  buildData: (_variantValue, base) => {
    const data = [
      STENCIL_SLIDER_GRID, STENCIL_SLIDER_GRID,
      base.fillR ?? 1, base.fillG ?? 1, base.fillB ?? 1,
      base.bgR ?? 0, base.bgG ?? 0, base.bgB ?? 0,
      base.bgAlpha ?? 1,
      0,
    ];
    for (let i = 0; i < STENCIL_SLIDER_GRID * STENCIL_SLIDER_GRID; i++) data.push(1);
    return data;
  },
};

// ── Mission code (req_1620/1621) ─────────────────────────────────────────────
// A unique, decodable code minted from a mission key (game/textures/missionCode.ts
// owns the codec). The shader is a dumb grid sampler — finder patterns + payload
// are already baked into the packed modules; this just reads a module's bit and
// returns dark or light, with a quiet-zone border. data[] layout is documented in
// missionCode.ts. The catalog form below previews a sample code; real codes are
// generated per mission via missionCodeDoc() and ride the decal pipeline.
export const MISSION_CODE_SHADER = `
@group(0) @binding(1) var<storage, read> D: array<f32>;
@fragment fn fs_main(in: VsOut) -> @location(0) vec4f {
  let N = max(D[0], 1.0);
  let quiet = D[8];
  let span = N + quiet * 2.0;
  let mx = floor(in.uv.x * span) - quiet;
  let my = floor(in.uv.y * span) - quiet;
  let light = vec4f(D[4], D[5], D[6], D[7]);
  if (mx < 0.0 || my < 0.0 || mx >= N || my >= N) {
    return light;
  }
  let iN = u32(N);
  let idx = u32(my) * iN + u32(mx);
  let wordBits = u32(max(D[9], 1.0));
  let word = u32(D[11u + idx / wordBits]);
  let bit = (word >> (idx % wordBits)) & 1u;
  if (bit == 1u) {
    return vec4f(D[1], D[2], D[3], 1.0);
  }
  return light;
}
`;

const MISSION_CODE: ShaderSpec = {
  id: 'mission-code',
  label: 'Mission Code',
  group: 'Codes & Stencils',
  blurb: 'A unique, scannable code minted from a mission — finder patterns + the mission key, CRC-checked and decodable. Generated per mission (not hand-tuned); the sliders here recolor a sample.',
  shader: MISSION_CODE_SHADER,
  base: [
    { key: 'darkR', label: 'Module red', default: 0.04, min: 0, max: 1, step: 0.05 },
    { key: 'darkG', label: 'Module green', default: 0.04, min: 0, max: 1, step: 0.05 },
    { key: 'darkB', label: 'Module blue', default: 0.04, min: 0, max: 1, step: 0.05 },
    { key: 'lightR', label: 'Field red', default: 0.96, min: 0, max: 1, step: 0.05 },
    { key: 'lightG', label: 'Field green', default: 0.96, min: 0, max: 1, step: 0.05 },
    { key: 'lightB', label: 'Field blue', default: 0.96, min: 0, max: 1, step: 0.05 },
  ],
  variants: [{ id: 'sample', label: 'Sample', value: 0, params: [] }],
  buildData: (_variantValue, base) => packMissionData(
    'preview',
    [base.darkR ?? 0.04, base.darkG ?? 0.04, base.darkB ?? 0.04],
    [base.lightR ?? 0.96, base.lightG ?? 0.96, base.lightB ?? 0.96],
  ),
};

// ── The fill boards (effect_fills A–J) ───────────────────────────────────────
// D = [materialId, variant, seed, quality, board]. Each material's default seed
// follows the board's spread formula (coefA·materialId + coefB·variant + coefC),
// matching the evaluation cart's swatches exactly at variant 0; the seed is then
// a free slider. Detail grade is the PSX→Max quality axis.

export const FILL_GRADES = ['PSX', 'PS2', 'Preview', 'Std', 'Max'] as const;
export const FILL_GRADE_STD = 3;
export const FILL_SEED_MAX = 2200; // every board formula lands well under this

// Registry lookup for a fill material's palette slots, keyed board:materialId.
const SLOTS_BY_BOARD_MATERIAL = new Map(MATERIALS.map((m) => [`${m.boardIndex}:${m.materialId}`, m.slots]));

// FILL_BOARDS is generated by render3d/shaders/build-shaders.ts (see the
// import above) — do not hand-edit; add/remove a material by adding/
// removing its materials/*.wgsl file, then rerun build-shaders.ts.
const FILL_BOARDS: FillBoard[] = GENERATED_FILL_BOARDS;

// ── Editor shelves ───────────────────────────────────────────────────────────
// The catalog rail groups by authoring intent: where this material belongs or
// what it is made of. The effect_fills board letters still drive stable ids and
// WGSL board slots, but they are implementation detail, not UX vocabulary.
const TEXTURE_CATEGORIES = [
  'Pavement & Streets',
  'Terrain & Water',
  'Exterior Walls',
  'Storefronts & Facades',
  'Signs & Wall Fixtures',
  'Wallpaper & Interior Walls',
  'Floors & Tile',
  'Glass, Light & Gradients',
  'Metal & Industrial',
  'Wood, Fabric & Body',
  'Props & Clutter',
  'Codes & Stencils',
] as const;
type TextureCategory = typeof TEXTURE_CATEGORIES[number];

const CATEGORY_BY_SLUG: Record<string, TextureCategory> = {
  // Pavement & Streets — hard outdoor circulation surfaces.
  road: 'Pavement & Streets', asphalt: 'Pavement & Streets', sidewalk: 'Pavement & Streets',
  'sidewalk-grid': 'Pavement & Streets', 'sidewalk-utility': 'Pavement & Streets',
  'sidewalk-pavers': 'Pavement & Streets', 'curb-crosswalk': 'Pavement & Streets',
  'alley-concrete': 'Pavement & Streets', 'storm-drain': 'Pavement & Streets',
  'wet-asphalt': 'Pavement & Streets',
  // Terrain & Water — organic ground, landscape, and outdoor natural surfaces.
  sand: 'Terrain & Water', dune: 'Terrain & Water', water: 'Terrain & Water',
  'deep-water': 'Terrain & Water', grass: 'Terrain & Water', turf: 'Terrain & Water',
  'palm-canopy': 'Terrain & Water', 'salt-flat': 'Terrain & Water', 'ice-sheet': 'Terrain & Water',
  // Exterior Walls — bare wall/construction skins.
  brick: 'Exterior Walls', concrete: 'Exterior Walls', 'stone-wall': 'Exterior Walls',
  'stucco-facade': 'Exterior Walls', 'neon-stucco': 'Exterior Walls',
  'mold-wall': 'Exterior Walls', 'peel-paint': 'Exterior Walls',
  'mildew-brick': 'Exterior Walls', 'rot-siding': 'Exterior Walls', 'rust-sheet': 'Exterior Walls',
  'clapboard-siding': 'Exterior Walls', 'brick-herringbone': 'Exterior Walls',
  'cinder-block': 'Exterior Walls', fieldstone: 'Exterior Walls', 'marble-slab': 'Exterior Walls',
  // Storefronts & Facades — wall faces with baked architectural detail.
  'brick-apartment': 'Storefronts & Facades', 'brick-fire-escape': 'Storefronts & Facades',
  'brick-shopfront': 'Storefronts & Facades', 'brick-entrance': 'Storefronts & Facades',
  'brick-rollshutter': 'Storefronts & Facades', 'brick-bodega': 'Storefronts & Facades',
  // Signs & Wall Fixtures — things mounted onto wall faces.
  'wall-flag': 'Signs & Wall Fixtures', 'wall-plants': 'Signs & Wall Fixtures',
  'wall-billboard': 'Signs & Wall Fixtures', 'wall-sign': 'Signs & Wall Fixtures',
  'wall-ac': 'Signs & Wall Fixtures', 'neon-tube': 'Signs & Wall Fixtures',
  // Wallpaper & Interior Walls — paper, panel, ceiling, and wallcover.
  'peel-wallpaper': 'Wallpaper & Interior Walls', 'drop-ceiling': 'Wallpaper & Interior Walls',
  'floral-wallpaper': 'Wallpaper & Interior Walls', 'stripe-wallpaper': 'Wallpaper & Interior Walls',
  'motel-wallpaper': 'Wallpaper & Interior Walls', 'kids-wallpaper': 'Wallpaper & Interior Walls',
  'damask-wallpaper': 'Wallpaper & Interior Walls', 'smoke-stained-wallpaper': 'Wallpaper & Interior Walls',
  'office-wallcover': 'Wallpaper & Interior Walls', 'rose-trellis-wallpaper': 'Wallpaper & Interior Walls',
  'vine-wallpaper': 'Wallpaper & Interior Walls', 'chinoiserie-wallpaper': 'Wallpaper & Interior Walls',
  'art-deco-wallpaper': 'Wallpaper & Interior Walls', 'toile-wallpaper': 'Wallpaper & Interior Walls',
  'tropical-wallpaper': 'Wallpaper & Interior Walls', 'kitchen-wallpaper': 'Wallpaper & Interior Walls',
  'nursery-wallpaper': 'Wallpaper & Interior Walls', 'torn-layered-wallpaper': 'Wallpaper & Interior Walls',
  // Floors & Tile — indoor walkable/flat surfaces.
  linoleum: 'Floors & Tile', 'bath-tile': 'Floors & Tile', 'pool-tile': 'Floors & Tile',
  'motel-carpet': 'Floors & Tile', 'rotten-rug': 'Floors & Tile', 'pdx-carpet': 'Floors & Tile',
  'booth-vinyl': 'Floors & Tile', 'plank-deck': 'Floors & Tile', 'moss-carpet': 'Floors & Tile',
  'plywood-sheet': 'Floors & Tile', 'parquet-floor': 'Floors & Tile', 'plaza-terrazzo': 'Floors & Tile',
  // Glass, Light & Gradients — emissive, reflective, screen, and atmospheric looks.
  'sunset-sky': 'Glass, Light & Gradients', 'car-paint': 'Glass, Light & Gradients',
  'crt-screen': 'Glass, Light & Gradients', 'fogged-mirror': 'Glass, Light & Gradients',
  'stained-glass': 'Glass, Light & Gradients', 'sunset-gradient': 'Glass, Light & Gradients',
  'vapor-gradient': 'Glass, Light & Gradients', 'sodium-fog': 'Glass, Light & Gradients',
  'fluorescent-panel': 'Glass, Light & Gradients', 'hazard-gradient': 'Glass, Light & Gradients',
  'wet-neon-fade': 'Glass, Light & Gradients', 'grime-gradient': 'Glass, Light & Gradients',
  // Metal & Industrial — metal panels, doors, fences, and machine surfaces.
  'blade-steel': 'Metal & Industrial', gunmetal: 'Metal & Industrial',
  'grip-polymer': 'Metal & Industrial', 'tarnished-silver': 'Metal & Industrial',
  'charcoal-bed': 'Metal & Industrial', 'brushed-steel': 'Metal & Industrial',
  'copper-patina': 'Metal & Industrial', 'corrugated-metal': 'Metal & Industrial',
  'diamond-plate': 'Metal & Industrial', 'rusted-panel': 'Metal & Industrial',
  'chainlink-panel': 'Metal & Industrial', 'painted-metal-door': 'Metal & Industrial',
  // Wood, Fabric & Body — softer substances and character/prop skins.
  leather: 'Wood, Fabric & Body', denim: 'Wood, Fabric & Body', fabric: 'Wood, Fabric & Body',
  skin: 'Wood, Fabric & Body', wood: 'Wood, Fabric & Body',
  // Props & Clutter — discrete set dressing / evidence / mess.
  'cash-stack': 'Props & Clutter', 'product-baggie': 'Props & Clutter',
  'blood-pool': 'Props & Clutter', evidence: 'Props & Clutter', refuse: 'Props & Clutter',
  corkboard: 'Props & Clutter', substance: 'Props & Clutter',
};

export function textureCategory(slug: string): TextureCategory {
  return CATEGORY_BY_SLUG[slug] ?? 'Props & Clutter';
}

function fillSpec(b: FillBoard, materialId: number, m: FillMaterial): ShaderSpec {
  const [perMaterial, perVariant, offset] = b.seedCoef;
  const defaultSeed = perMaterial * materialId + offset; // variant-0 swatch seed
  return {
    id: `${b.letter.toLowerCase()}-${m.slug}`,
    label: m.name,
    group: textureCategory(m.slug),
    blurb: `${m.name} — three authored takes, seed + detail grade tunable.`,
    shader: FILL_SHADER,
    base: [
      { key: 'seed', label: 'Seed', default: defaultSeed, min: 0, max: FILL_SEED_MAX, step: 1, integer: true },
      {
        key: 'grade', label: `Detail grade (${FILL_GRADES.join(' → ')})`,
        default: FILL_GRADE_STD, min: 0, max: FILL_GRADES.length - 1, step: 1, integer: true,
      },
    ],
    variants: m.variants.map((label, v) => ({
      id: `v${v}`,
      label,
      value: v,
      // The board formula nudges the seed per variant; expose that as the
      // variant's own offset so each take starts on its authored swatch.
      params: [
        { key: 'seedShift', label: 'Take seed shift', default: perVariant * v, min: 0, max: FILL_SEED_MAX, step: 1, integer: true },
      ],
    })),
    buildData: (variantValue, base, o) => [
      materialId,
      variantValue,
      (base.seed ?? defaultSeed) + (o.seedShift ?? perVariant * variantValue),
      base.grade ?? FILL_GRADE_STD,
      b.board,
    ],
    slots: SLOTS_BY_BOARD_MATERIAL.get(`${b.board}:${materialId}`) ?? [],
  };
}

const FILL_SPECS: ShaderSpec[] = FILL_BOARDS.flatMap((b) => b.materials.map((m, i) => fillSpec(b, i, m)));

// ── The catalog ──────────────────────────────────────────────────────────────

export const EDITOR_SHADERS: ShaderSpec[] = [ROAD, CUTOUT_STENCIL, MISSION_CODE, ...FILL_SPECS];

function slugPart(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'preset';
}

function frozenData(spec: ShaderSpec, variant: ShaderVariant, basePatch: Record<string, number> = {}): number[] {
  return spec.buildData(
    variant.value,
    { ...paramDefaults(spec.base), ...basePatch },
    paramDefaults(variant.params),
  );
}

function shaderPresetsFor(spec: ShaderSpec): ShaderTexturePreset[] {
  const hasGrade = spec.base.some((p) => p.key === 'grade');
  if (hasGrade) {
    return spec.variants.flatMap((variant) => FILL_GRADES.map((grade, gradeValue) => ({
      id: `${spec.id}--${variant.id}--${slugPart(grade)}`,
      label: `${spec.label} · ${variant.label} · ${grade}`,
      group: spec.group,
      shaderId: spec.id,
      shader: spec.shader,
      data: frozenData(spec, variant, { grade: gradeValue }),
    })));
  }
  if (spec.id === 'road') {
    return spec.variants.map((variant) => ({
      id: `${spec.id}--${variant.id}`,
      label: `${spec.label} · ${variant.label}`,
      group: spec.group,
      shaderId: spec.id,
      shader: spec.shader,
      data: frozenData(spec, variant),
    }));
  }
  return [];
}

export const EDITOR_SHADER_PRESETS: ShaderTexturePreset[] = EDITOR_SHADERS.flatMap(shaderPresetsFor);
export const EDITOR_BROWSE_SHADER_PRESETS: ShaderTexturePreset[] = EDITOR_SHADER_PRESETS.filter((preset) => {
  const spec = shaderSpec(preset.shaderId);
  if (!spec) return false;
  return spec.id === 'road' || preset.id.endsWith('--std');
});

// ── Imported specs (dynamic) ─────────────────────────────────────────────────
// Imported textures (data/texturePackage.ts) register here at load so they are
// first-class materials: shaderSpec() resolves them, shaderGroups() shelves
// them, which makes them ink-pickable, bakeable, and replayable with zero
// special-casing downstream. Re-registering replaces the whole set (idempotent
// on reload).
let IMPORTED_SPECS: ShaderSpec[] = [];

export function registerImportedSpecs(specs: ShaderSpec[]): void {
  IMPORTED_SPECS = specs;
}

/** The imported set alone — the sticker rail (req_3025) lists what's stampable. */
export function importedSpecs(): readonly ShaderSpec[] {
  return IMPORTED_SPECS;
}

export function shaderSpec(id: string): ShaderSpec | undefined {
  return EDITOR_SHADERS.find((s) => s.id === id) ?? IMPORTED_SPECS.find((s) => s.id === id);
}

export function shaderTexturePreset(id: string): ShaderTexturePreset | undefined {
  return EDITOR_SHADER_PRESETS.find((p) => p.id === id);
}

// Group order for catalog rails: the purpose categories in their declared order
// (TEXTURE_CATEGORIES), with any stragglers appended in first-seen order.
export function shaderGroups(): { group: string; specs: ShaderSpec[] }[] {
  const out: { group: string; specs: ShaderSpec[] }[] = [];
  for (const spec of [...EDITOR_SHADERS, ...IMPORTED_SPECS]) {
    const g = out.find((x) => x.group === spec.group);
    if (g) g.specs.push(spec); else out.push({ group: spec.group, specs: [spec] });
  }
  const rank = (group: string) => {
    const i = (TEXTURE_CATEGORIES as readonly string[]).indexOf(group);
    return i === -1 ? TEXTURE_CATEGORIES.length : i;
  };
  return out.sort((a, b) => rank(a.group) - rank(b.group));
}
