import type { DocIndex } from '../types';

export const game_item_gallery: DocIndex = {
  name: 'game_item_gallery',
  file: 'game_item_gallery.md',
  cart: 'cart/game_item_gallery/index.tsx',
  purpose: ['item', 'rendering', 'geometry', 'shader', 'texture_bake', 'camera'],
  loc: 780,
  summary:
    'A low-poly 3D item viewer that shows one hand-authored game prop at a time in a Scene3D stage with drag-to-orbit and a scrollable picker, demonstrating many ways a prop becomes readable without importing models.',
  interfaces: [
    {
      name: 'GameItemGallery',
      purpose: ['item', 'ui', 'rendering'],
      kind: 'component',
      sourceFile: 'cart/game_item_gallery/index.tsx',
      codeRef: 'cart/game_item_gallery/index.tsx:699',
      description:
        'Default exported cart component. Owns selected item state, orbit yaw/pitch state, TV tick state, layout, drag math, and texture sources.',
      dependsOn: ['ITEMS', 'GalleryScene', 'ItemButton', 'TextureSources', 'OrbitCamera'],
      status: 'lab',
    },
    {
      name: 'V3',
      purpose: ['math', 'geometry'],
      kind: 'data_model',
      codeRef: 'cart/game_item_gallery/index.tsx:7',
      description: 'A [number, number, number] tuple type used for positions, rotations, and scales.',
      status: 'lab',
    },
    {
      name: 'ModelCtx',
      purpose: ['item', 'geometry'],
      kind: 'data_model',
      codeRef: 'cart/game_item_gallery/index.tsx:8',
      description:
        'Shared placement context { origin, yaw, scale, active } passed to every item model function so props are authored in local coordinates.',
      status: 'lab',
    },
    {
      name: 'ModelFn',
      purpose: ['item'],
      kind: 'data_model',
      codeRef: 'cart/game_item_gallery/index.tsx:9',
      description: 'Type alias for a function that accepts ModelCtx and returns React children for one prop.',
      status: 'lab',
    },
    {
      name: 'Item',
      purpose: ['item', 'ui'],
      kind: 'data_model',
      codeRef: 'cart/game_item_gallery/index.tsx:441',
      description: 'Registry entry shape { id, label, tone, note, model } for one prop.',
      status: 'lab',
    },
    {
      name: 'ITEMS',
      purpose: ['item', 'ui', 'rendering'],
      kind: 'registry',
      codeRef: 'cart/game_item_gallery/index.tsx:443',
      description:
        'The full item registry (19 ids: knife, pistol, pitchfork, bat, cash, vehicle, sailboat, surfboard, football, basketball, pillbottle, beer, liquor, pills, weed, cigarettes, backpack, medkit, tv) binding identity, label, accent tone, description, and renderer into one coherent data shape; drives both the picker and the model selection.',
      consumers: ['GameItemGallery', 'ItemButton', 'GalleryScene'],
      status: 'lab',
    },
    {
      name: 'TextureSources',
      purpose: ['texture_bake', 'rendering', 'ui'],
      kind: 'component',
      codeRef: 'cart/game_item_gallery/index.tsx:524',
      description:
        'Renders hidden/offscreen StaticSurface and Effect texture sources for item meshes; accepts tvTick and an optional itemId filter (implemented via show(...ids)) that the default render does not pass.',
      dependsOn: ['StaticSurface', 'Effect', 'Filter'],
      status: 'lab',
    },
    {
      name: 'show',
      purpose: ['texture_bake'],
      kind: 'utility',
      codeRef: 'cart/game_item_gallery/index.tsx:526',
      description:
        'Optional texture-source filter inside TextureSources: !itemId || ids.includes(itemId). Available but unused by the default gallery render.',
      status: 'dormant',
    },
    {
      name: 'GalleryScene',
      purpose: ['rendering', 'camera', 'item'],
      kind: 'component',
      codeRef: 'cart/game_item_gallery/index.tsx:472',
      description:
        'Owns the 3D stage: creates ctx { origin:[0,0.18,0], yaw:0, scale:1.95, active:true }, a full-size Scene3D with #111827 bg, OrbitCamera, procedural Skybox, ambient/directional/two point lights, floor box, pedestal, and calls item.model(ctx).',
      dependsOn: ['OrbitCamera', 'Pedestal', 'Scene3D'],
      status: 'lab',
    },
    {
      name: 'Pedestal',
      purpose: ['rendering', 'item'],
      kind: 'component',
      codeRef: 'cart/game_item_gallery/index.tsx:465',
      description: 'Renders two stacked boxes under the current item, coloring the active base from ctx.active and item.tone.',
      status: 'lab',
    },
    {
      name: 'ItemButton',
      purpose: ['ui', 'item'],
      kind: 'component',
      codeRef: 'cart/game_item_gallery/index.tsx:500',
      description:
        'One selectable item row in the picker: Pressable handles selection, background/border change when active, a colored dot uses item.tone, label bolds and note fades by active state.',
      status: 'lab',
    },
    {
      name: 'Part',
      purpose: ['geometry', 'item'],
      kind: 'utility',
      codeRef: 'cart/game_item_gallery/index.tsx:181',
      description:
        'Local wrapper around Scene3D.Mesh that applies ModelCtx transforms (local, scl, rot). Does not expose textureKey, so textured meshes use direct Scene3D.Mesh calls instead.',
      dependsOn: ['Scene3D.Mesh'],
      status: 'lab',
    },
    {
      name: 'local',
      purpose: ['math', 'geometry'],
      kind: 'utility',
      codeRef: 'cart/game_item_gallery/index.tsx:167',
      description: 'Scales a local point, rotates it around Y by ctx.yaw, and offsets it by ctx.origin.',
      status: 'lab',
    },
    {
      name: 'scl',
      purpose: ['math', 'geometry'],
      kind: 'utility',
      codeRef: 'cart/game_item_gallery/index.tsx:174',
      description: 'Applies ctx.scale to a scalar or vector scale.',
      status: 'lab',
    },
    {
      name: 'rot',
      purpose: ['math', 'geometry'],
      kind: 'utility',
      codeRef: 'cart/game_item_gallery/index.tsx:178',
      description: 'Adds ctx.yaw to a mesh Y rotation.',
      status: 'lab',
    },
    {
      name: 'def',
      purpose: ['geometry'],
      kind: 'utility',
      codeRef: 'cart/game_item_gallery/index.tsx:74',
      description: 'Local helper that creates a geometry-definition object with id, defaults, and generate, in the shape Scene3D.Mesh expects.',
      status: 'lab',
    },
    {
      name: 'tri',
      purpose: ['geometry'],
      kind: 'utility',
      codeRef: 'cart/game_item_gallery/index.tsx:86',
      description: 'Appends one triangle to a mesh() builder with a shared normal and UVs.',
      status: 'lab',
    },
    {
      name: 'quad',
      purpose: ['geometry'],
      kind: 'utility',
      codeRef: 'cart/game_item_gallery/index.tsx:90',
      description: 'Appends two triangles as a rectangle to a mesh() builder.',
      status: 'lab',
    },
    {
      name: 'nrm',
      purpose: ['geometry', 'math'],
      kind: 'utility',
      codeRef: 'cart/game_item_gallery/index.tsx:82',
      description: 'Computes a face normal using cross, sub, and normalize.',
      status: 'lab',
    },
    {
      name: 'Blade',
      purpose: ['geometry', 'item'],
      kind: 'utility',
      codeRef: 'cart/game_item_gallery/index.tsx:96',
      description: 'Custom wedge/triangular-prism geometry for a knife blade.',
      status: 'lab',
    },
    {
      name: 'Sail',
      purpose: ['geometry', 'item'],
      kind: 'utility',
      codeRef: 'cart/game_item_gallery/index.tsx:112',
      description: 'Custom thin triangular sail geometry with front, back, and edge faces.',
      status: 'lab',
    },
    {
      name: 'BoatHull',
      purpose: ['geometry', 'item'],
      kind: 'utility',
      codeRef: 'cart/game_item_gallery/index.tsx:127',
      description: 'Custom low-poly hull geometry with a rectangular top and keel faces.',
      status: 'lab',
    },
    {
      name: 'Surfboard',
      purpose: ['geometry', 'item'],
      kind: 'utility',
      codeRef: 'cart/game_item_gallery/index.tsx:144',
      description: 'Custom oval extruded board geometry built from a configurable segment loop; reused for the surfboard and for weed leaves at small scale.',
      status: 'lab',
    },
    {
      name: 'CASH_SHADER',
      purpose: ['shader', 'texture_bake'],
      kind: 'shader',
      codeRef: 'cart/game_item_gallery/index.tsx:28',
      description:
        'WGSL fragment shader for the cash/bill texture: green paper base, bands, border/edge ink, oval detail, sine-line variation. Used by the cash stack surface; passed only data={[0]}.',
      consumers: ['TextureSources'],
      status: 'lab',
    },
    {
      name: 'FOOTBALL_SHADER',
      purpose: ['shader', 'texture_bake'],
      kind: 'shader',
      codeRef: 'cart/game_item_gallery/index.tsx:44',
      description:
        'WGSL fragment shader for the football texture: brown leather variation, white side stripes, central seam, laces, lace ticks. Used by the football surface; passed only data={[0]}.',
      consumers: ['TextureSources'],
      status: 'lab',
    },
    {
      name: 'BASKETBALL_SHADER',
      purpose: ['shader', 'texture_bake'],
      kind: 'shader',
      codeRef: 'cart/game_item_gallery/index.tsx:59',
      description:
        'WGSL fragment shader for the basketball texture: orange pebble variation and black seam bands/arcs. Used by the basketball surface; passed only data={[0]}.',
      consumers: ['TextureSources'],
      status: 'lab',
    },
    {
      name: 'OrbitCamera',
      purpose: ['camera'],
      kind: 'component',
      sourceFile: 'runtime/cameras/index.tsx',
      codeRef: 'runtime/cameras/index.tsx:60-65',
      description:
        'Reusable camera component that solves yaw, pitch, distance, target, zoom, and fov in JavaScript and emits a Scene3D.Camera.',
      consumers: ['game_item_gallery'],
      status: 'live',
    },
    {
      name: 'Scene3D.Mesh',
      purpose: ['rendering', 'geometry', 'texture_bake'],
      kind: 'component',
      sourceFile: 'runtime/primitives.tsx',
      codeRef: 'runtime/primitives.tsx:535-708',
      description:
        'Accepts geometry definitions from @reactjit/geometries, runs/interns generators in JS, and emits host mesh props; for textureKey it emits scene3dTexKey.',
      consumes: ['@reactjit/geometries'],
      status: 'live',
    },
    {
      name: 'StaticSurface',
      purpose: ['texture_bake', 'rendering'],
      kind: 'component',
      sourceFile: 'runtime/primitives.tsx',
      codeRef: 'runtime/primitives.tsx:327-348',
      description:
        'Emits a host View marked staticSurface:true with a stable key so the subtree collapses into a render-to-texture surface.',
      consumers: ['TextureSources'],
      status: 'live',
    },
    {
      name: 'Effect',
      purpose: ['shader', 'texture_bake'],
      kind: 'component',
      sourceFile: 'runtime/primitives.tsx',
      codeRef: 'runtime/primitives.tsx:886-887',
      description: 'Emits an Effect host node and maps data to effectData; the one user-WGSL texture surface used here for cash, football, basketball.',
      consumers: ['TextureSources'],
      status: 'live',
    },
    {
      name: 'Filter',
      purpose: ['shader', 'rendering'],
      kind: 'component',
      sourceFile: 'runtime/primitives.tsx',
      codeRef: 'runtime/primitives.tsx:359-364',
      description: 'Emits a host View with filterName and filterIntensity; used here as a crt postprocess inside the TV screen texture source.',
      consumers: ['TextureSources'],
      status: 'live',
    },
    {
      name: 'mesh',
      purpose: ['geometry'],
      kind: 'utility',
      sourceFile: 'runtime/geometries',
      description: 'Geometry builder from @reactjit/geometries used (with normalize) for custom mesh generation in this cart.',
      status: 'live',
    },
  ],
  patterns: [
    {
      name: 'Item registry',
      purpose: ['item', 'ui', 'rendering'],
      description:
        'A single exported array binds gameplay identity, UI presentation, description, and model renderer into one coherent data shape (id/label/tone/note/model).',
      examples: ['game_item_gallery'],
      promoteTo: 'ITEMS',
      status: 'recurring',
    },
    {
      name: 'Model context',
      purpose: ['item', 'geometry'],
      description:
        'Every prop is authored in local coordinates and later placed/scaled/rotated by the host scene via a shared { origin, yaw, scale, active } context, so the model function does not know absolute gallery position or scale.',
      examples: ['game_item_gallery'],
      promoteTo: 'ModelCtx',
      status: 'recurring',
    },
    {
      name: 'Semantic texture keys',
      purpose: ['texture_bake', 'rendering'],
      description:
        'Texture identity is named by purpose (CIG_TOP_TEXTURE_KEY, TV_SCREEN_TEXTURE_KEY) rather than by file path, connecting StaticSurface outputs to Scene3D.Mesh textureKey props.',
      examples: ['game_item_gallery'],
      status: 'recurring',
    },
    {
      name: 'React UI as texture',
      purpose: ['texture_bake', 'ui', 'rendering'],
      description: 'StaticSurface turns ordinary ReactJIT layout into labels, packaging, and screens used as materials on 3D props.',
      examples: ['game_item_gallery'],
      status: 'recurring',
    },
    {
      name: 'Procedural texture effects',
      purpose: ['shader', 'texture_bake'],
      description: 'Small WGSL Effect shaders become materials procedurally without image assets.',
      examples: ['game_item_gallery'],
      status: 'recurring',
    },
    {
      name: 'Custom geometry defs',
      purpose: ['geometry'],
      description:
        'Simple local mesh generators (Blade, Sail, BoatHull, Surfboard) fill gaps between primitive shapes and full model imports, run through the @reactjit/geometries registry.',
      examples: ['game_item_gallery'],
      status: 'recurring',
    },
    {
      name: 'Declarative camera rig',
      purpose: ['camera'],
      description: 'OrbitCamera keeps camera math reusable and separate from scene content; the cart still hand-rolls its orbit yaw/pitch state math while delegating solving.',
      examples: ['game_item_gallery'],
      promoteTo: 'OrbitCamera',
      status: 'resolved',
    },
    {
      name: 'Single-item inspection stage',
      purpose: ['rendering', 'ui'],
      description: 'The cart isolates one selected item for close reading rather than showing all props at once.',
      examples: ['game_item_gallery'],
      status: 'recurring',
    },
  ],
  hazards: [
    {
      name: 'TextureSources itemId filter unused',
      purpose: ['texture_bake', 'rendering'],
      description:
        'TextureSources supports an itemId filter (show(...ids)) but the default cart render calls it without itemId, so every texture source subtree renders all the time.',
      evidence: ['cart/game_item_gallery/index.tsx:776 calls <TextureSources tvTick={tvTick} /> without itemId', 'show defined at index.tsx:526'],
      fix: 'Pass itemId to TextureSources to render only the surfaces the selected item needs.',
      severity: 'medium',
    },
    {
      name: 'Part cannot carry textureKey',
      purpose: ['geometry', 'texture_bake'],
      description:
        'The Part helper does not expose textureKey, so any textured mesh must use a direct Scene3D.Mesh call instead of the helper, splitting the authoring path.',
      evidence: ['cart/game_item_gallery/index.tsx:181-190'],
      severity: 'low',
    },
    {
      name: 'Shader data buffer declared but unused',
      purpose: ['shader'],
      description:
        'Each shader declares @group(0) @binding(1) var<storage, read> ys: array<f32>; matching the Effect data convention, but the cart passes only data={[0]} and uses no meaningful dynamic shader data.',
      evidence: ['cart/game_item_gallery/index.tsx:117'],
      severity: 'low',
    },
    {
      name: 'Single-sided item models',
      purpose: ['item', 'rendering'],
      description: 'Most item models only define the front/primary readable side; e.g. vehicle wheels are only defined for one visible side.',
      evidence: ['game_item_gallery.md limitations: Vehicle wheels only defined for one visible side'],
      severity: 'low',
    },
    {
      name: 'No centralized material system',
      purpose: ['rendering', 'maintenance'],
      description: 'Colors are inline hex strings in each model and texture surface; there is no shared material table.',
      evidence: ['game_item_gallery.md: The cart has no centralized material system'],
      severity: 'low',
    },
  ],
};
