import type { DocIndex } from '../types';

export const vehicle_lab: DocIndex = {
  name: 'vehicle_lab',
  file: 'vehicle_lab.md',
  cart: 'cart/vehicle_lab/index.tsx',
  purpose: ['vehicle', 'damage', 'animation', 'geometry', 'rendering', 'camera'],
  loc: 839,
  summary:
    'A semantic 3D vehicle rig lab where every rendered part has a named gameplay counterpart (meshes, damage hitboxes, critical parts, glass metadata, generated gas-tank placement, anchors), authored in TypeScript and rendered through Scene3D.',
  interfaces: [
    {
      name: 'VehicleLab',
      purpose: ['vehicle', 'ui', 'rendering'],
      kind: 'component',
      sourceFile: 'cart/vehicle_lab/index.tsx',
      codeRef: 'cart/vehicle_lab/index.tsx:627-839',
      description:
        'Default cart component rendering a two-panel editor/viewer: left control panel exposes the data contract in English labels and compact controls; right panel renders the generated vehicle in Scene3D with drag-orbit and a zoom knob.',
      dependsOn: ['buildVehicle', 'makeVehicle', 'VehicleMeshes', 'OrbitCamera', 'VEHICLE_STYLES', 'VEHICLE_ROLES', 'VEHICLE_POSES'],
      status: 'lab',
    },
    {
      name: 'VehicleStyleId',
      purpose: ['vehicle'],
      kind: 'data_model',
      sourceFile: 'cart/vehicle_lab/index.tsx',
      description: 'Visual/body class union: sedan, coupe, wagon, van, pickup, sports, ambulance, fire_truck.',
      status: 'lab',
    },
    {
      name: 'VehicleRoleId',
      purpose: ['vehicle'],
      kind: 'data_model',
      sourceFile: 'cart/vehicle_lab/index.tsx',
      description: 'Gameplay/service class union: civilian, police, medical, fire.',
      status: 'lab',
    },
    {
      name: 'VehiclePoseId',
      purpose: ['vehicle', 'animation'],
      kind: 'data_model',
      sourceFile: 'cart/vehicle_lab/index.tsx',
      description: 'Animation preset id union: parked, roll, turn, bounce, brake.',
      status: 'lab',
    },
    {
      name: 'DamageLevel',
      purpose: ['vehicle', 'damage'],
      kind: 'data_model',
      sourceFile: 'cart/vehicle_lab/index.tsx',
      description: 'Numeric part state: 0, 1, 2, or 3.',
      status: 'lab',
    },
    {
      name: 'VehiclePartId',
      purpose: ['vehicle', 'damage'],
      kind: 'data_model',
      sourceFile: 'cart/vehicle_lab/index.tsx',
      description:
        'Named part vocabulary shared by meshes, hitboxes, selection, and damage controls: body, cabin, trunk, bumper, windshield, driver_side, passenger_side, rear, front_lights, rear_lights, driver_door, passenger_door, hood, four wheels, gas_tank.',
      status: 'lab',
    },
    {
      name: 'VehicleMesh',
      purpose: ['vehicle', 'rendering', 'geometry'],
      kind: 'data_model',
      sourceFile: 'cart/vehicle_lab/index.tsx',
      description:
        'Visual part shape: id, label, kind (box/cylinder/sphere), params, position, rotation, scale, and material (color string or object with color/opacity/breakable/health).',
      status: 'lab',
    },
    {
      name: 'VehicleHitbox',
      purpose: ['vehicle', 'damage', 'physics'],
      kind: 'data_model',
      sourceFile: 'cart/vehicle_lab/index.tsx',
      description:
        'Gameplay/collision part shape: id (matching the visual part vocabulary), label, position, rotation, size, damage level, and critical flag. Explicitly authored, not inferred from mesh bounds.',
      status: 'lab',
    },
    {
      name: 'VehicleDoc',
      purpose: ['vehicle', 'persistence', 'world_gen'],
      kind: 'data_model',
      sourceFile: 'cart/vehicle_lab/index.tsx',
      description:
        'Generated/editable source document storing style, role, seed, paint color, trim color, gas side, gas Z placement, and a sparse damage map keyed by part id. The builder can recreate a whole vehicle from it.',
      status: 'lab',
    },
    {
      name: 'VehicleBuild',
      purpose: ['vehicle', 'rendering'],
      kind: 'data_model',
      sourceFile: 'cart/vehicle_lab/index.tsx',
      description: 'Derived runtime build storing the rendered meshes, hitboxes, and anchors.',
      status: 'lab',
    },
    {
      name: 'VEHICLE_STYLES',
      purpose: ['vehicle', 'geometry'],
      kind: 'registry',
      codeRef: 'cart/vehicle_lab/index.tsx:91-100',
      description:
        'Registry of eight body styles, each giving the builder fixed dimensions: label, length, width, bodyH, cabinH, cabinZ, cabinD, wheelR, clearance.',
      consumers: ['VehicleLab', 'buildVehicle'],
      status: 'lab',
    },
    {
      name: 'VEHICLE_ROLES',
      purpose: ['vehicle'],
      kind: 'registry',
      codeRef: 'cart/vehicle_lab/index.tsx:102-107',
      description:
        'Registry of four roles (civilian, police, medical, fire) that both constrain which styles make sense and supply default service livery colors.',
      consumers: ['VehicleLab', 'makeVehicle', 'buildVehicle'],
      status: 'lab',
    },
    {
      name: 'VEHICLE_POSES',
      purpose: ['vehicle', 'animation'],
      kind: 'registry',
      codeRef: 'cart/vehicle_lab/index.tsx:109-115',
      description:
        'Registry mapping pose ids to labels and animation DSL strings (e.g. roll -> [0.8,wheels,spin_loop;0.8,vehicle,drive_loop]).',
      consumers: ['VehicleLab'],
      dependsOn: ['parseAnimationDsl', 'sampleAnimationTimeline'],
      status: 'lab',
    },
    {
      name: 'makeVehicle',
      purpose: ['vehicle', 'world_gen', 'chance'],
      kind: 'utility',
      codeRef: 'cart/vehicle_lab/index.tsx:173-192',
      description:
        'Creates a deterministic VehicleDoc from a seed: seeded random picks role (civilian-biased), style from the role pool, paint/trim (fixed for service roles), gas side, rear-biased gas Z, and an empty sparse damage map.',
      dependsOn: ['VEHICLE_ROLES', 'VEHICLE_STYLES'],
      status: 'lab',
    },
    {
      name: 'buildVehicle',
      purpose: ['vehicle', 'rendering', 'geometry', 'damage', 'animation'],
      kind: 'utility',
      codeRef: 'cart/vehicle_lab/index.tsx:220-545',
      description:
        'Main semantic builder converting one VehicleDoc plus sampled animation actions into a VehicleBuild of meshes, explicit semantic hitboxes, and named anchors. Reads animation actions (wheels spin_loop, front_wheels steer_loop, suspension bounce_loop, vehicle drive_loop/brake) and derives style dimensions, positions, service flags, and cascading damage.',
      dependsOn: ['VehicleDoc', 'VEHICLE_STYLES', 'panelMaterial', 'glassMaterial', 'geometryFor'],
      status: 'lab',
    },
    {
      name: 'geometryFor',
      purpose: ['geometry'],
      kind: 'utility',
      codeRef: 'cart/vehicle_lab/index.tsx:194-196',
      description: 'Maps the cart three local mesh kinds to shared generator defs: box->Geometry.Box, cylinder->Geometry.Cylinder, sphere->Geometry.Sphere.',
      status: 'lab',
    },
    {
      name: 'panelMaterial',
      purpose: ['vehicle', 'damage', 'rendering'],
      kind: 'utility',
      sourceFile: 'cart/vehicle_lab/index.tsx',
      description: 'Returns the base color at damage 0 and progressively darker shaded colors at damage 1 through 3.',
      status: 'lab',
    },
    {
      name: 'glassMaterial',
      purpose: ['vehicle', 'damage', 'rendering'],
      kind: 'utility',
      sourceFile: 'cart/vehicle_lab/index.tsx',
      description: 'Returns HMSC glass metadata with lower opacity and darker color as damage increases.',
      dependsOn: ['Glass', 'AutoGlass'],
      status: 'lab',
    },
    {
      name: 'damageOf',
      purpose: ['vehicle', 'damage'],
      kind: 'utility',
      sourceFile: 'cart/vehicle_lab/index.tsx',
      description: 'Reads the sparse damage map for a part id, defaulting to 0.',
      status: 'lab',
    },
    {
      name: 'maxDamage',
      purpose: ['vehicle', 'damage'],
      kind: 'utility',
      sourceFile: 'cart/vehicle_lab/index.tsx',
      description: 'Cascades multiple part damage values into one worst visible state.',
      status: 'lab',
    },
    {
      name: 'setPartDamage',
      purpose: ['vehicle', 'damage'],
      kind: 'utility',
      sourceFile: 'cart/vehicle_lab/index.tsx',
      description: 'Writes a part damage level and deletes the key when the level is 0.',
      status: 'lab',
    },
    {
      name: 'randomDamage',
      purpose: ['vehicle', 'damage', 'chance'],
      kind: 'utility',
      sourceFile: 'cart/vehicle_lab/index.tsx',
      description: 'Loops all semantic parts and assigns random damage weighted toward undamaged or light damage.',
      status: 'lab',
    },
    {
      name: 'VehicleMeshes',
      purpose: ['vehicle', 'rendering'],
      kind: 'component',
      sourceFile: 'cart/vehicle_lab/index.tsx',
      description:
        'memo-wrapped component that maps build products to Scene3D.Mesh, renders hitbox overlays (blue/orange/red by state) when showHitboxes is on, and anchor spheres (yellow gasPort, green others) when showAnchors is on.',
      dependsOn: ['Scene3D'],
      status: 'lab',
    },
    {
      name: 'Chip',
      purpose: ['ui'],
      kind: 'component',
      sourceFile: 'cart/vehicle_lab/index.tsx',
      description: 'A styled Pressable used for toggles and choices in the left panel.',
      status: 'lab',
    },
    {
      name: 'Knob',
      purpose: ['ui'],
      kind: 'component',
      sourceFile: 'cart/vehicle_lab/index.tsx',
      description: 'A text label with minus and plus Pressable buttons; used for gas Z nudge and zoom.',
      status: 'lab',
    },
    {
      name: 'parseAnimationDsl',
      purpose: ['animation', 'scripting'],
      kind: 'dsl',
      sourceFile: 'cart/animationDsl.ts',
      codeRef: 'cart/animationDsl.ts:99-121',
      description: 'Shared timeline parser that turns bracket groups or pipe-separated chunks ([duration,target,action]) into timeline steps.',
      consumers: ['vehicle_lab'],
      status: 'live',
    },
    {
      name: 'sampleAnimationTimeline',
      purpose: ['animation', 'scripting'],
      kind: 'utility',
      sourceFile: 'cart/animationDsl.ts',
      codeRef: 'cart/animationDsl.ts:123-148',
      description: 'Samples the current step at a given second and returns actions with target, action, phase, weight, and args.',
      consumers: ['vehicle_lab'],
      status: 'live',
    },
    {
      name: 'Glass',
      purpose: ['vehicle', 'rendering'],
      kind: 'utility',
      sourceFile: 'cart/hmsc-int/render3d/materials.ts',
      description:
        'HMSC material helper returning a material object combining render props (color, opacity) with future gameplay props (breakable, health). SIDE_GLASS uses Glass({ color:#1f3441, opacity:0.42, health:18 }).',
      consumers: ['vehicle_lab'],
      status: 'live',
    },
    {
      name: 'AutoGlass',
      purpose: ['vehicle', 'rendering'],
      kind: 'utility',
      sourceFile: 'cart/hmsc-int/render3d/materials.ts',
      description: 'HMSC material helper for auto glass; GLASS uses AutoGlass({ opacity: 0.48 }). Carries dormant breakable/health metadata.',
      consumers: ['vehicle_lab'],
      status: 'live',
    },
    {
      name: 'OrbitCamera',
      purpose: ['camera'],
      kind: 'component',
      sourceFile: 'runtime/cameras/index.tsx',
      description: 'Resolves yaw/pitch/distance/target/fov to a Scene3D.Camera; used here with target [0,0.8,0], fov 42.',
      consumers: ['vehicle_lab'],
      status: 'live',
    },
  ],
  patterns: [
    {
      name: 'Semantic part id',
      purpose: ['vehicle', 'damage', 'physics'],
      description:
        'A single repeated name joins visual meshes, gameplay hitboxes, selection UI, damage state, and future rules (gas_tank, hood, wheel ids). Visual meshes and gameplay volumes share names but remain separate authored data.',
      examples: ['vehicle_lab'],
      promoteTo: 'VehiclePartId',
      status: 'promote',
    },
    {
      name: 'Vehicle document + builder + part vocab trio',
      purpose: ['vehicle', 'rendering', 'world_gen'],
      description:
        'The most reusable unit is VehicleDoc + buildVehicle(doc, actions) + the shared VehiclePartId vocabulary; future HMSC vehicle work connects to these without the debug panel.',
      examples: ['vehicle_lab'],
      promoteTo: 'buildVehicle',
      status: 'promote',
    },
    {
      name: 'Explicit authored hitboxes',
      purpose: ['physics', 'damage', 'vehicle'],
      description:
        'Gameplay hitboxes are authored after the visible pieces with matching semantic ids; they are not inferred by the host nor generated from mesh bounds. Critical hitboxes: hood, gas_tank, and all four wheels.',
      examples: ['vehicle_lab'],
      status: 'recurring',
    },
    {
      name: 'Named anchors',
      purpose: ['vehicle', 'interaction'],
      description:
        'Named points that are not collision boxes (driverSeat, passengerSeat, hoodLatch, gasPort tied to gas side/Z, towRear) as future connection points for entering, fuel targeting, towing, repair, AI, and mission scripting.',
      examples: ['vehicle_lab'],
      status: 'recurring',
    },
    {
      name: 'Damage cascade',
      purpose: ['damage', 'vehicle', 'rendering'],
      description: 'A visual grouping rule where one visible panel responds to the worst damage level across multiple semantic parts.',
      examples: ['vehicle_lab'],
      promoteTo: 'maxDamage',
      status: 'recurring',
    },
    {
      name: 'Transparent material metadata',
      purpose: ['vehicle', 'rendering', 'damage'],
      description:
        'An object material with opacity < 1 (usually from HMSC glass helpers) rendered as glass today, carrying breakable/health metadata for future damage systems.',
      examples: ['vehicle_lab'],
      status: 'recurring',
    },
    {
      name: 'Pose as DSL string',
      purpose: ['animation', 'vehicle'],
      description:
        'A named UI preset maps to an animation DSL string parsed/sampled by shared helpers, rather than a hardcoded frame function; the builder interprets only targets/actions it understands.',
      examples: ['vehicle_lab', 'head_lab'],
      promoteTo: 'sampleAnimationTimeline',
      status: 'recurring',
    },
    {
      name: 'JS interval animation clock',
      purpose: ['animation', 'game_loop'],
      description:
        'A JavaScript setInterval fires every 33ms incrementing frame; frames convert to seconds via (running ? frame : 0) / 60, so pausing resets the pose to its start.',
      examples: ['vehicle_lab'],
      status: 'recurring',
    },
    {
      name: 'Drag-to-orbit holdout state math',
      purpose: ['camera', 'input'],
      description:
        'Pointer drag updates orbit yaw (dx*0.38) and pitch (dy*0.3, clamped 5-82) in cart state while OrbitCamera does the actual camera solve; the manual orbit state is the hand-rolled holdout.',
      examples: ['vehicle_lab', 'game_item_gallery'],
      promoteTo: 'OrbitCamera',
      status: 'resolved',
    },
  ],
  hazards: [
    {
      name: 'breakable/health metadata consumed by nothing',
      purpose: ['vehicle', 'damage'],
      description:
        'The breakable and health material fields are authored and carried with the surface, but no damage simulation consumes them yet; no physics, collision response, health decrement, or shatter runs in this cart.',
      evidence: ['vehicle_lab.md: breakable and health fields are metadata for future systems', 'vehicle_lab.md: No physics, collision response, health decrement, or shatter simulation runs'],
      severity: 'medium',
    },
    {
      name: 'Non-deterministic UI seed source',
      purpose: ['vehicle', 'world_gen', 'chance'],
      description:
        'Generated vehicles are deterministic once the seed is known, but generate() makes the seed from Date.now() and Math.random(), so the UI seed source is intentionally non-deterministic.',
      evidence: ['cart/vehicle_lab/index.tsx:173-192 makeVehicle', 'vehicle_lab.md: UI seed source is intentionally non-deterministic'],
      severity: 'low',
    },
    {
      name: 'Fire-truck tandem wheels do not add semantic ids',
      purpose: ['vehicle', 'damage'],
      description:
        'Fire trucks receive tandem rear wheel duplicate meshes for silhouette, but the semantic wheel ids stay the four main ids, so the extra meshes have no hitbox/damage counterpart.',
      evidence: ['vehicle_lab.md: Fire trucks receive tandem rear wheel duplicates ... semantic wheel ids stay the four main ids'],
      severity: 'low',
    },
    {
      name: 'Proud debug hitboxes',
      purpose: ['physics', 'debug'],
      description:
        'Hitboxes intentionally use proud boxes that are visible and selectable as debugging geometry, not tight collision bounds; they are debug overlays in this lab.',
      evidence: ['vehicle_lab.md: hitboxes intentionally use proud boxes that are visible and selectable as debugging geometry'],
      severity: 'low',
    },
    {
      name: 'Builder is the unit, not the React component',
      purpose: ['vehicle', 'maintenance'],
      description:
        'The reusable unit is the VehicleDoc + buildVehicle + VehiclePartId trio, not the VehicleLab component; the likely consolidation is a shared vehicle module owning types, registries, generation, and builder, with the lab as one viewer.',
      evidence: ['vehicle_lab.md Integration notes: The most reusable unit is not the VehicleLab React component'],
      fix: 'Extract a shared vehicle module so HMSC vehicle work depends on the data types/builder, not the debug panel.',
      severity: 'low',
    },
  ],
};
