//! curve_pull.zig — split verbatim from framework/gpu/3d.zig (req_4375).
//! Generated by _tool/split3d.zig — edit 3d.zig's successor here, regenerate only from the manifest.
//! Cross-file references are qualified through the orchestrator (`z3d`).

const std = @import("std");
const builtin = @import("builtin");
const log = @import("../../diag/log.zig");
const wgpu = @import("wgpu");
const bu = @import("../buffer_upload.zig");
const shaders = @import("../shaders.zig");
const terrain_grid = @import("../terrain_grid.zig");
const core = @import("../../dev_modules/gpu_api.zig");
const capture = @import("../capture.zig");
const build_options = @import("build_options");
const math = @import("../../math/root.zig");
const layout = @import("../../layout.zig");
const effect_assemble = @import("../effect_assemble.zig");
const compile_progress = @import("../compile_progress.zig");
const static_instance_policy = @import("../static_instance_policy.zig");
const model_paint = @import("../model_paint.zig");
const gizmo_axis_map = @import("../gizmo_axis_map.zig");
const effects_ctx = @import("../effects_ctx.zig");
const paint_islands_mod = @import("../paint_islands.zig");
const paint_program = @import("../paint_program.zig");
const model_source = @import("../model_source.zig");
const meshdoc_format = @import("../meshdoc_format.zig");
const mesh_audit = @import("../mesh_audit.zig");
const mesh_face_table = @import("../mesh_face_table.zig");
const mesh_face_diff = @import("../mesh_face_diff.zig");
const mesh_face_field_candidate = @import("../mesh_face_field_candidate.zig");
const mesh_face_table_package = @import("../mesh_face_table_package.zig");
const mesh_face_table_worker = @import("../mesh_face_table_worker.zig");
const historical_preview = @import("../historical_preview.zig");
const mesh_edit = @import("../mesh_edit.zig");
const mesh_semantics = @import("../mesh_semantics.zig");
const mesh_semantic_restore = @import("../mesh_semantic_restore.zig");
const mesh_edge_semantics = @import("../mesh_edge_semantics.zig");
const indexed_edit_mesh = @import("../indexed_edit_mesh.zig");
const character_topology_promotion = @import("../character_topology_promotion.zig");
const mesh_journal_log = @import("../mesh_journal_log.zig");
const model_write_lease = @import("../model_write_lease.zig");
const model_adoption_receipt = @import("../model_adoption_receipt.zig");
const model_adoption_finalize = @import("../model_adoption_finalize.zig");
const path_array = @import("../path_array.zig");
const path_plane = @import("../path_plane.zig");
const stage_scale = @import("../stage_scale.zig");
const pack = @import("../pack.zig");
const stable_geometry_slot = @import("../stable_geometry_slot.zig");
const character_rig_session = @import("../../skeleton/character_rig_session.zig");
const character_skin_binding = @import("../../skeleton/skin_binding.zig");
const character_specimen = @import("../character_specimen.zig");
const mouse_state = @import("../../state/mouse_state.zig");
const Node = layout.Node;

const z3d = @import("root.zig");

pub fn curvePullAdaptiveReset() void {
    if (z3d.g_curve_pull_source_ids) |rows| std.heap.c_allocator.free(rows);
    if (z3d.g_curve_pull_source_stable) |rows| std.heap.c_allocator.free(rows);
    if (z3d.g_curve_pull_source_base) |rows| std.heap.c_allocator.free(rows);
    if (z3d.g_curve_pull_source_params) |rows| std.heap.c_allocator.free(rows);
    if (z3d.g_curve_pull_base_colors) |rows| std.heap.c_allocator.free(rows);
    if (z3d.g_curve_pull_mirror_points) |rows| std.heap.c_allocator.free(rows);
    z3d.g_curve_pull_source_ids = null;
    z3d.g_curve_pull_source_stable = null;
    z3d.g_curve_pull_source_base = null;
    z3d.g_curve_pull_source_params = null;
    z3d.g_curve_pull_base_colors = null;
    z3d.g_curve_pull_mirror_points = null;
    z3d.g_curve_pull_source_grab = 0;
    z3d.g_curve_pull_source_mode = .none;
    z3d.g_curve_pull_source_part = model_source.NO_PART;
    z3d.g_curve_pull_had_groups = false;
    z3d.g_curve_pull_part_count = 0;
    z3d.g_curve_pull_mirror_count = 0;
    z3d.g_curve_pull_mirror_parts = .{model_source.NO_PART} ** 7;
    z3d.g_curve_pull_cuts = 0;
    z3d.g_curve_pull_topology_changed = false;
    z3d.g_curve_pull_densify_blocked = false;
}

pub fn curvePullPointsSame(a: []const [3]f32, b: []const [3]f32) bool {
    if (a.len != b.len) return false;
    var forward = true;
    var reverse = true;
    for (a, 0..) |point, index| {
        if (z3d.vdot(z3d.vsub(point, b[index]), z3d.vsub(point, b[index])) > mesh_edit.curve_pull_tuning.topology_match_epsilon_sq) forward = false;
        const reversed = b[b.len - 1 - index];
        if (z3d.vdot(z3d.vsub(point, reversed), z3d.vsub(point, reversed)) > mesh_edit.curve_pull_tuning.topology_match_epsilon_sq) reverse = false;
    }
    return forward or reverse;
}

pub fn curvePullAdaptiveSource() ?mesh_edit.CurvePullPath {
    const ids = z3d.g_curve_pull_source_ids orelse return null;
    const stable = z3d.g_curve_pull_source_stable orelse return null;
    const base = z3d.g_curve_pull_source_base orelse return null;
    const params = z3d.g_curve_pull_source_params orelse return null;
    return .{
        .ids = ids,
        .stable = stable,
        .base = base,
        .params = params,
        .grab = z3d.g_curve_pull_source_grab,
        .mode = z3d.g_curve_pull_source_mode,
        .part = z3d.g_curve_pull_source_part,
    };
}

/// Freeze the gesture's original path and every real live-mirror twin before a
/// structural install resets selection topology.  The stored source is also what
/// lets scrubbing shallower REMOVE rings instead of accumulating cuts forever.
pub fn curvePullAdaptiveCapture() bool {
    z3d.curvePullAdaptiveReset();
    const path = mesh_edit.curvePullPath() orelse return false;
    if (z3d.g_guard_indexed_before == null) return false;
    const ids = std.heap.c_allocator.dupe(u32, path.ids) catch return false;
    const stable = std.heap.c_allocator.dupe(u32, path.stable) catch {
        std.heap.c_allocator.free(ids);
        return false;
    };
    const base = std.heap.c_allocator.dupe([3]f32, path.base) catch {
        std.heap.c_allocator.free(ids);
        std.heap.c_allocator.free(stable);
        return false;
    };
    const params = std.heap.c_allocator.dupe(f32, path.params) catch {
        std.heap.c_allocator.free(ids);
        std.heap.c_allocator.free(stable);
        std.heap.c_allocator.free(base);
        return false;
    };
    const colors = z3d.collectCurrentFaceColors() orelse {
        std.heap.c_allocator.free(ids);
        std.heap.c_allocator.free(stable);
        std.heap.c_allocator.free(base);
        std.heap.c_allocator.free(params);
        return false;
    };

    var mirror_points: ?[][3]f32 = null;
    const mirror_mask = mesh_edit.mirrorMask();
    if (mirror_mask != 0) {
        mirror_points = std.heap.c_allocator.alloc([3]f32, path.ids.len * 7) catch {
            std.heap.c_allocator.free(ids);
            std.heap.c_allocator.free(stable);
            std.heap.c_allocator.free(base);
            std.heap.c_allocator.free(params);
            std.heap.c_allocator.free(colors);
            return false;
        };
    }
    var mirror_count: usize = 0;
    if (mirror_points) |points| {
        var subset: u8 = 1;
        while (subset <= 7) : (subset += 1) {
            if ((subset & mirror_mask) != subset) continue;
            const candidate = points[mirror_count * path.ids.len .. (mirror_count + 1) * path.ids.len];
            var candidate_part: ?u32 = null;
            var valid = true;
            for (path.ids, 0..) |id, index| {
                const twin = mesh_edit.mirrorImageOfVertPub(id, subset) orelse {
                    valid = false;
                    break;
                };
                const part = mesh_edit.vertPartPub(twin) orelse {
                    valid = false;
                    break;
                };
                if (candidate_part) |owner| {
                    if (owner != part) {
                        valid = false;
                        break;
                    }
                } else candidate_part = part;
                candidate[index] = mesh_edit.vertPosPub(twin);
            }
            if (!valid or candidate_part == null or z3d.curvePullPointsSame(candidate, path.base)) continue;
            var duplicate = false;
            var prior: usize = 0;
            while (prior < mirror_count) : (prior += 1) {
                if (z3d.curvePullPointsSame(candidate, points[prior * path.ids.len .. (prior + 1) * path.ids.len])) {
                    duplicate = true;
                    break;
                }
            }
            if (duplicate) continue;
            z3d.g_curve_pull_mirror_parts[mirror_count] = candidate_part.?;
            mirror_count += 1;
        }
    }

    z3d.g_curve_pull_source_ids = ids;
    z3d.g_curve_pull_source_stable = stable;
    z3d.g_curve_pull_source_base = base;
    z3d.g_curve_pull_source_params = params;
    z3d.g_curve_pull_source_grab = path.grab;
    z3d.g_curve_pull_source_mode = path.mode;
    z3d.g_curve_pull_source_part = path.part;
    z3d.g_curve_pull_base_colors = colors;
    z3d.g_curve_pull_had_groups = model_source.faceGroupOf(0) != model_source.NO_FACE_GROUP;
    z3d.g_curve_pull_part_count = z3d.currentPartCount();
    z3d.g_curve_pull_mirror_points = mirror_points;
    z3d.g_curve_pull_mirror_count = mirror_count;
    return true;
}

/// Lower `indexed` and install it as the resident mesh, colors inherited from the
/// gesture's grab-time snapshot. Consumes nothing; adopts `indexed` on success.
/// Shared by the forward densify install and the failure rollback below.
fn curvePullInstallIndexed(indexed: *indexed_edit_mesh.Mesh, base_colors: []const u8) bool {
    var lowered = indexed.lower() catch return false;
    defer lowered.deinit();
    const colors = std.heap.c_allocator.alloc(u8, @as(usize, lowered.tri_count) * 4) catch return false;
    defer std.heap.c_allocator.free(colors);
    if (!mesh_edit.inheritFaceRgba(base_colors, lowered.source_triangles, colors)) return false;
    const install_groups: ?[]const u32 = if (z3d.g_curve_pull_had_groups) lowered.groups else null;
    if (!z3d.lcInstallLowered(
        lowered.positions,
        lowered.uvs,
        lowered.tri_count,
        install_groups,
        lowered.materials,
        lowered.semantic_regions,
        lowered.semantic_instances,
        colors,
        z3d.flattenedLogicalRows(lowered.triangle_vertices),
        @intCast(indexed.vertices.items.len),
    )) return false;
    if (z3d.g_curve_pull_part_count > 0) z3d.renormalizePartRanges(lowered.parts, z3d.g_curve_pull_part_count);
    z3d.adoptIndexedEditMesh(indexed, &lowered);
    return true;
}

/// Replace the current adaptive level from the exact grab-time indexed mesh, then
/// re-arm and apply the current absolute offset.  Only threshold crossings call this;
/// ordinary drag frames remain the same O(selected path) position mutation as v1.
/// TRANSACTIONAL (req_4671): a failure after the densified topology installs rolls
/// the resident mesh back to the grab-time snapshot — a half-applied rebuild used
/// to strand unadopted rings on the straight chords, and every retry gesture then
/// doubled the density again.
pub fn curvePullAdaptiveRebuild(offset: [3]f32, cuts: u32) bool {
    const source = z3d.curvePullAdaptiveSource() orelse return false;
    const before = if (z3d.g_guard_indexed_before) |*mesh| mesh else return false;
    const base_colors = z3d.g_curve_pull_base_colors orelse return false;
    var indexed = before.clone() catch return false;
    defer indexed.deinit();

    var mirrors: [7]mesh_edit.CurvePullMirrorSeed = undefined;
    if (z3d.g_curve_pull_mirror_points) |points| {
        var mirror: usize = 0;
        while (mirror < z3d.g_curve_pull_mirror_count) : (mirror += 1) {
            mirrors[mirror] = .{
                .base = points[mirror * source.ids.len .. (mirror + 1) * source.ids.len],
                .part = z3d.g_curve_pull_mirror_parts[mirror],
            };
        }
    }
    var dense = mesh_edit.curvePullDensifyIndexed(
        std.heap.c_allocator,
        &indexed,
        source,
        mirrors[0..z3d.g_curve_pull_mirror_count],
        cuts,
    ) catch |err| {
        z3d.topoRefuse(@errorName(err));
        return false;
    };
    defer dense.deinit();

    z3d.g_curve_pull_preserve_gizmo_guard = true;
    defer z3d.g_curve_pull_preserve_gizmo_guard = false;
    if (!curvePullInstallIndexed(&indexed, base_colors)) return false;
    const grab_t = source.params[source.grab];
    const rearmed = mesh_edit.curvePullAdoptDensified(&dense, source.mode, source.part, grab_t) and
        z3d.applyMeshMutation(mesh_edit.curvePullApply(offset));
    if (!rearmed) {
        // The rings are installed but the deformation could not re-arm over them.
        // Put the grab-time mesh back so no half-state survives the refusal.
        z3d.topoRefuse("CurvePullAdoptRefused");
        var restore = before.clone() catch return false;
        defer restore.deinit();
        if (!curvePullInstallIndexed(&restore, base_colors)) return false;
        _ = z3d.applyMeshMutation(mesh_edit.curvePullApply(offset));
        return false;
    }
    z3d.g_curve_pull_cuts = cuts;
    z3d.g_curve_pull_topology_changed = cuts > 0;
    return true;
}

pub fn meshCurvePullArm(on: bool) bool {
    z3d.g_curve_pull_armed = on;
    if (!on) {
        mesh_edit.curvePullEnd();
        z3d.curvePullAdaptiveReset();
    }
    return z3d.g_curve_pull_armed;
}

pub fn meshCurvePullArmed() bool {
    return z3d.g_curve_pull_armed;
}

pub fn meshGizmoBegin() void {
    z3d.curvePullAdaptiveReset();
    z3d.clearMeshGuardSnapshot();
    z3d.gizmoDragReset(); // stepped drags (req_2759): fresh accumulator + frozen pivot per grab
    // Curve Pull capture happens at grab, against pre-drag positions.
    const curve_started = z3d.g_curve_pull_armed and z3d.g_gizmo_tool == .move and mesh_edit.curvePullBegin();
    // Pre-drag journal snapshot — committed at release only if the drag moved something.
    z3d.journalDiscard(&z3d.g_gizmo_snap);
    z3d.g_gizmo_snap = z3d.journalSnapshotCurrent("transform");
    const pos = model_paint.positions() orelse return;
    z3d.g_guard_before = std.heap.c_allocator.dupe(f32, pos) catch null;
    if (z3d.ensureIndexedEditMesh()) {
        if (z3d.g_indexed_edit_mesh) |*mesh| z3d.g_guard_indexed_before = mesh.clone() catch null;
    }
    if (curve_started) _ = z3d.curvePullAdaptiveCapture();
    z3d.g_guard_face_count = model_paint.faceCount();
}

/// Grab bookkeeping the engine reports at press: WHICH handle was grabbed (the gold
/// glow) and where the cursor started — the uniform hub drag is RADIAL (the studio's
/// hypot(cursor − anchor) / startScreenDist), so it needs the grab point. Window px.
pub fn meshGizmoGrabAt(mx: f32, my: f32, code: i32) void {
    z3d.g_gizmo_active = code;
    z3d.g_gizmo_cursor = .{ z3d.vpLocalX(mx), z3d.vpLocalY(my) };
    z3d.g_gizmo_start_dist = 4;
    const pivot = mesh_edit.selectionPivot() orelse return;
    const cam = model_paint.Camera{ .eye = z3d.g_paint_eye, .target = z3d.g_paint_target, .fov_deg = z3d.g_paint_fov };
    const a = model_paint.project(cam, z3d.g_paint_vp_w, z3d.g_paint_vp_h, pivot) orelse return;
    const ddx = z3d.g_gizmo_cursor[0] - a[0];
    const ddy = z3d.g_gizmo_cursor[1] - a[1];
    z3d.g_gizmo_start_dist = @max(4.0, @sqrt(ddx * ddx + ddy * ddy));
}

pub fn meshGizmoFinish() bool {
    defer mesh_edit.curvePullEnd(); // the captured run is per-grab; release always drops it
    defer z3d.curvePullAdaptiveReset();
    z3d.g_gizmo_readout_len = 0; // the drag is ending — drop the live step readout
    z3d.g_gizmo_pivot0 = null;
    z3d.g_gizmo_active = -1; // release drops the gold glow
    z3d.g_gizmo_snap_ref0 = null; // req_3378: the vertex-snap lock ends with the drag
    z3d.g_gizmo_snap_marker = null;
    const before = z3d.g_guard_before orelse {
        z3d.journalDiscard(&z3d.g_gizmo_snap);
        return false;
    };
    const after = model_paint.positions() orelse {
        z3d.journalDiscard(&z3d.g_gizmo_snap);
        z3d.clearMeshGuardSnapshot();
        return false;
    };
    // A press that moved nothing leaves no undo step.
    const topology_changed = after.len != before.len or z3d.g_curve_pull_topology_changed;
    // A structural Curve Pull must restore like Loop Cut across undo/redo so its
    // interpolated authored-atlas coordinates and raster survive exactly.  Shallow
    // pulls that never crossed a density threshold remain ordinary transforms.
    if (topology_changed) {
        if (z3d.g_gizmo_snap) |*entry| entry.label = "curve pull";
    }
    if (!topology_changed and std.mem.eql(f32, before, after)) z3d.journalDiscard(&z3d.g_gizmo_snap) else z3d.journalCommit(&z3d.g_gizmo_snap);
    const fc: u32 = @intCast(@min(before.len / 9, after.len / 9));
    // Studio concave guard (req_0949 port): only an authored face NEWLY buckled into a
    // reflex polygon is unsafe. bad_list carries one member tri per buckled face (the
    // currency guardSplitPossible/guardSplitQuads already speak); the dialog count is
    // FACES, matching the studio's "N face(s) buckled — not convex".
    var bad_list: std.ArrayListUnmanaged(u32) = .empty;
    var bad_faces: u32 = 0;
    if (z3d.g_guard_indexed_before) |*before_mesh| {
        if (z3d.g_indexed_edit_mesh) |*after_mesh| {
            bad_faces = after_mesh.newlyConcaveComparedTo(before_mesh, &bad_list);
        }
    }
    if (bad_faces == 0) {
        bad_list.deinit(std.heap.c_allocator);
        z3d.clearMeshGuardSnapshot();
        return false;
    }
    z3d.g_guard_pending = true;
    z3d.g_guard_bad_faces = bad_faces;
    z3d.g_guard_face_count = fc;
    z3d.g_guard_bad_list = bad_list.toOwnedSlice(std.heap.c_allocator) catch null;
    z3d.g_guard_can_split = if (z3d.g_guard_bad_list) |bl| z3d.guardSplitPossible(bl) else false;
    return true;
}

pub fn meshEditGuardInfo() [4]u32 {
    return .{ if (z3d.g_guard_pending) 1 else 0, z3d.g_guard_bad_faces, z3d.g_guard_face_count, if (z3d.g_guard_pending and z3d.g_guard_can_split) 1 else 0 };
}

pub fn meshEditGuardResolve(action: u8) bool {
    if (!z3d.g_guard_pending) return false;
    var changed = false;
    if (action == 0) changed = z3d.guardSplitQuads();
    if (action == 2) {
        const before = z3d.g_guard_before orelse {
            z3d.clearMeshGuardSnapshot();
            return false;
        };
        const pos = model_paint.positionsMutable() orelse {
            z3d.clearMeshGuardSnapshot();
            return false;
        };
        if (before.len == pos.len) {
            @memcpy(pos, before);
            const fc: u32 = @intCast(pos.len / 9);
            if (fc > 0) {
                _ = z3d.copyPaintPositionsToEditVerts(0, fc - 1);
                _ = model_source.updateGeometryFromDisplayed(pos, 0, fc - 1);
                _ = z3d.patchActiveEditMesh(0, fc - 1);
                if (z3d.g_indexed_edit_mesh) |*mesh| {
                    const verts = z3d.g_edit_verts orelse {
                        z3d.clearIndexedEditMesh();
                        return false;
                    };
                    if (!mesh.updatePositionsFromInterleaved(verts, fc)) z3d.clearIndexedEditMesh();
                }
            }
            // The restore bypassed mesh_edit's mutation path, so its welded
            // vert positions (overlay dots/edges, gizmo pivot, picking) still
            // hold the pre-revert drag — resync them from the restored soup
            // (req_2539). Selection and topology stay.
            mesh_edit.refreshPositionsFromSoup();
            changed = true;
            // The revert returned the mesh to the exact state the newest journal entry
            // snapshots — undoing to it would be a visible no-op, so drop the entry.
            z3d.journalDropLast();
        }
    }
    z3d.clearMeshGuardSnapshot();
    return changed;
}
