//! gizmo_drag.zig — split verbatim from framework/gpu/3d.zig (req_4375).
//! Generated by _tool/split3d.zig — edit 3d.zig's successor here, regenerate only from the manifest.
//! Cross-file references are qualified through the orchestrator (`z3d`).

const std = @import("std");
const builtin = @import("builtin");
const log = @import("../../diag/log.zig");
const wgpu = @import("wgpu");
const bu = @import("../buffer_upload.zig");
const shaders = @import("../shaders.zig");
const terrain_grid = @import("../terrain_grid.zig");
const core = @import("../../dev_modules/gpu_api.zig");
const capture = @import("../capture.zig");
const build_options = @import("build_options");
const math = @import("../../math/root.zig");
const layout = @import("../../layout.zig");
const effect_assemble = @import("../effect_assemble.zig");
const compile_progress = @import("../compile_progress.zig");
const static_instance_policy = @import("../static_instance_policy.zig");
const model_paint = @import("../model_paint.zig");
const gizmo_axis_map = @import("../gizmo_axis_map.zig");
const effects_ctx = @import("../effects_ctx.zig");
const paint_islands_mod = @import("../paint_islands.zig");
const paint_program = @import("../paint_program.zig");
const model_source = @import("../model_source.zig");
const meshdoc_format = @import("../meshdoc_format.zig");
const mesh_audit = @import("../mesh_audit.zig");
const mesh_face_table = @import("../mesh_face_table.zig");
const mesh_face_diff = @import("../mesh_face_diff.zig");
const mesh_face_field_candidate = @import("../mesh_face_field_candidate.zig");
const mesh_face_table_package = @import("../mesh_face_table_package.zig");
const mesh_face_table_worker = @import("../mesh_face_table_worker.zig");
const historical_preview = @import("../historical_preview.zig");
const mesh_edit = @import("../mesh_edit.zig");
const mesh_semantics = @import("../mesh_semantics.zig");
const mesh_semantic_restore = @import("../mesh_semantic_restore.zig");
const mesh_edge_semantics = @import("../mesh_edge_semantics.zig");
const indexed_edit_mesh = @import("../indexed_edit_mesh.zig");
const character_topology_promotion = @import("../character_topology_promotion.zig");
const mesh_journal_log = @import("../mesh_journal_log.zig");
const model_write_lease = @import("../model_write_lease.zig");
const model_adoption_receipt = @import("../model_adoption_receipt.zig");
const model_adoption_finalize = @import("../model_adoption_finalize.zig");
const path_array = @import("../path_array.zig");
const path_plane = @import("../path_plane.zig");
const stage_scale = @import("../stage_scale.zig");
const pack = @import("../pack.zig");
const stable_geometry_slot = @import("../stable_geometry_slot.zig");
const character_rig_session = @import("../../skeleton/character_rig_session.zig");
const character_skin_binding = @import("../../skeleton/skin_binding.zig");
const character_specimen = @import("../character_specimen.zig");
const mouse_state = @import("../../state/mouse_state.zig");
const Node = layout.Node;

const z3d = @import("root.zig");

// ── Stepped gizmo drags (req_2759; the studio's req_1023 USER RULING, host-native) ────
// Every gizmo drag is STEPPED by default: the drag accumulates a RAW cumulative value
// from grab, the cumulative target snaps to the step grid, and only the difference to
// what's already applied lands on the mesh — so the mesh clicks between grid values
// instead of drifting freeform. Shift = the fine grid; Ctrl (or Alt, the old studio's
// key) = freeform. The pivot is FROZEN at grab so cumulative rotate/scale stay exact.
pub const GIZMO_STEP_M: f32 = z3d.STAGE_TILE_M / 16.0; // 1 modeling unit — the stage's fine sub-grid pitch
pub const GIZMO_STEP_FINE_M: f32 = z3d.STAGE_TILE_M / 64.0; // Shift: a quarter unit
pub const GIZMO_STEP_ROT: f32 = 15.0 * std.math.pi / 180.0;
pub const GIZMO_STEP_ROT_FINE: f32 = 1.0 * std.math.pi / 180.0;
pub const GIZMO_STEP_SCALE: f32 = 0.1;
pub const GIZMO_STEP_SCALE_FINE: f32 = 0.05;
pub const GIZMO_SNAP_PX: f32 = 18; // screen radius the lock engages within

pub fn snapStep(value: f32, step: f32, fine: f32, shift: bool, free: bool) f32 {
    if (free) return value;
    const s = if (shift) fine else step;
    if (s <= 0) return value;
    return @round(value / s) * s;
}

pub fn setGizmoReadout(comptime fmt: []const u8, args: anytype) void {
    const line = std.fmt.bufPrint(&z3d.g_gizmo_readout, fmt, args) catch {
        z3d.g_gizmo_readout_len = 0;
        return;
    };
    z3d.g_gizmo_readout_len = line.len;
}

/// The selection's vertex nearest its pivot — held V drags snap BY this vertex
/// (the predictable Blender read: single selected vert = that vert). Null only
/// when nothing is selected; the pivot itself is the fallback.
pub fn selectionSnapReference() ?[3]f32 {
    const pivot = mesh_edit.selectionPivot() orelse return null;
    if (!mesh_edit.ensureTopologyPub()) return pivot;
    var best: ?[3]f32 = null;
    var best_d: f32 = std.math.floatMax(f32);
    var i: u32 = 0;
    const n = mesh_edit.vertCount();
    while (i < n) : (i += 1) {
        if (!mesh_edit.vertSelectedPub(i) or !mesh_edit.vertInScopePub(i)) continue;
        const p = mesh_edit.vertPosPub(i);
        const ddx = p[0] - pivot[0];
        const ddy = p[1] - pivot[1];
        const ddz = p[2] - pivot[2];
        const d = ddx * ddx + ddy * ddy + ddz * ddz;
        if (d < best_d) {
            best_d = d;
            best = p;
        }
    }
    return best orelse pivot;
}

pub const VertexLock = struct { t: f32, vertex: [3]f32 };

/// Held-V candidate for an axis-constrained MOVE drag: among UNSELECTED in-scope
/// vertices, the one nearest the reference vertex's current drag position (within
/// a screen-px radius converted through the axis' px-per-unit). The lock value is
/// that vertex's exact projection onto the drag axis — the reference vertex lands
/// flush with it, the perpendicular offset stays (the arm remains an arm).
pub fn vertexSnapAlongAxis(axis: [3]f32, px_per_unit: f32) ?z3d.VertexLock {
    const ref0 = z3d.g_gizmo_snap_ref0 orelse return null;
    if (!mesh_edit.ensureTopologyPub()) return null;
    const radius = z3d.GIZMO_SNAP_PX / @max(px_per_unit, 0.0001);
    const at: [3]f32 = .{
        ref0[0] + axis[0] * z3d.g_gizmo_raw,
        ref0[1] + axis[1] * z3d.g_gizmo_raw,
        ref0[2] + axis[2] * z3d.g_gizmo_raw,
    };
    var best: ?z3d.VertexLock = null;
    var best_d = radius * radius;
    var i: u32 = 0;
    const n = mesh_edit.vertCount();
    while (i < n) : (i += 1) {
        if (mesh_edit.vertSelectedPub(i)) continue; // never lock onto the moving selection
        if (!mesh_edit.vertInScopePub(i)) continue;
        const p = mesh_edit.vertPosPub(i);
        const ddx = p[0] - at[0];
        const ddy = p[1] - at[1];
        const ddz = p[2] - at[2];
        const d = ddx * ddx + ddy * ddy + ddz * ddz;
        if (d < best_d) {
            best_d = d;
            best = .{
                .t = (p[0] - ref0[0]) * axis[0] + (p[1] - ref0[1]) * axis[1] + (p[2] - ref0[2]) * axis[2],
                .vertex = p,
            };
        }
    }
    return best;
}

/// Reset the stepped-drag accumulator — the grab site (meshGizmoBegin) calls this.
pub fn gizmoDragReset() void {
    z3d.g_gizmo_raw = 0;
    z3d.g_gizmo_applied = if (z3d.g_gizmo_tool == .scale) 1.0 else 0.0;
    z3d.g_gizmo_pivot0 = mesh_edit.selectionPivot();
    z3d.g_gizmo_readout_len = 0;
    z3d.g_gizmo_snap_ref0 = z3d.selectionSnapReference();
    z3d.g_gizmo_snap_marker = null;
}

pub fn meshGizmoDrag(axis_code: i32, dx: f32, dy: f32, shift: bool, free: bool, snap_vertex: bool) bool {
    if (axis_code < 0 or axis_code > z3d.GIZMO_NEG_BASE + 2 or z3d.meshEditModeRaw() == 0 or !model_paint.hasTarget()) return false;
    z3d.g_gizmo_active = axis_code; // the grabbed handle glows gold until release
    // The FROZEN grab pivot keeps cumulative rotate/scale exact (each step re-derives
    // from the same origin); the live pivot is only a fallback for a lost grab.
    const pivot = z3d.g_gizmo_pivot0 orelse (mesh_edit.selectionPivot() orelse return false);
    const cam = model_paint.Camera{ .eye = z3d.g_paint_eye, .target = z3d.g_paint_target, .fov_deg = z3d.g_paint_fov };
    z3d.g_gizmo_cursor[0] += dx;
    z3d.g_gizmo_cursor[1] += dy;
    // UNIFORM scale — the studio's center-hub grab: the factor is the cursor's RADIAL
    // screen distance from the anchor over the grab distance (pull away to grow, toward
    // to shrink), snapped on the studio's gizmoUniformStep grid, applied on all 3 axes.
    if (axis_code == z3d.GIZMO_UNIFORM_CODE) {
        if (z3d.g_gizmo_tool != .scale) return false;
        const anchor = model_paint.project(cam, z3d.g_paint_vp_w, z3d.g_paint_vp_h, pivot) orelse return false;
        const rdx = z3d.g_gizmo_cursor[0] - anchor[0];
        const rdy = z3d.g_gizmo_cursor[1] - anchor[1];
        const f_raw = @sqrt(rdx * rdx + rdy * rdy) / @max(z3d.g_gizmo_start_dist, 4.0);
        const target = std.math.clamp(
            z3d.snapStep(f_raw, z3d.GIZMO_STEP_UNIFORM, z3d.GIZMO_STEP_UNIFORM_FINE, shift, free),
            mesh_edit.scale_factor_tuning.min,
            mesh_edit.scale_factor_tuning.max,
        );
        z3d.setGizmoReadout("\u{00D7}{d:.2}", .{target});
        const rel = target / z3d.g_gizmo_applied;
        if (@abs(rel - 1.0) < 1e-6) return false;
        const m = mesh_edit.scaleSelectionUniform(pivot, rel);
        if (!z3d.applyMeshMutation(m)) return false;
        z3d.g_gizmo_applied = target;
        return true;
    }
    const neg = axis_code >= z3d.GIZMO_NEG_BASE;
    const axis: i32 = if (neg) axis_code - z3d.GIZMO_NEG_BASE else axis_code;
    const s = z3d.axisScreenInfo(cam, pivot, z3d.axisVec(axis)) orelse return false;
    // Studio dragWorldDistance: project the cursor delta onto the axis' screen direction,
    // divide by px-per-unit at the anchor. A negative-end square inverts — its outward
    // (grow) direction is −axis on screen.
    const px = (dx * s.dx + dy * s.dy) * @as(f32, if (neg) -1 else 1);
    const av = z3d.axisVec(axis);
    // BOUNDED px→world: dividing by the raw span alone let an axis aimed at the camera
    // turn one pixel into ~100 units (req_4160/4161). The floor is the same ratio the
    // arm has to clear to be grabbable at all, so the steepest legal arm moves at most
    // 1/min_axis_screen_fraction the face-on rate.
    const face_on = z3d.gizmoFaceOnPxPerUnit(cam, pivot);
    const move_px_per_unit = @max(s.px_per_unit, face_on * gizmo_axis_map.min_axis_screen_fraction);
    const move_wpp = 1.0 / move_px_per_unit;
    switch (z3d.g_gizmo_tool) {
        .move => {
            z3d.g_gizmo_raw += px * move_wpp;
            var target = z3d.snapStep(z3d.g_gizmo_raw, z3d.GIZMO_STEP_M, z3d.GIZMO_STEP_FINE_M, shift, free);
            // Held V (req_3378): the reference vertex locks onto the nearest
            // unselected vertex's exact axis projection — flush, not stepped.
            z3d.g_gizmo_snap_marker = null;
            if (snap_vertex) {
                if (z3d.vertexSnapAlongAxis(av, move_px_per_unit)) |lock| {
                    target = lock.t;
                    z3d.g_gizmo_snap_marker = lock.vertex;
                }
            }
            if (z3d.g_gizmo_snap_marker != null) {
                z3d.setGizmoReadout("snap {d:.2}u", .{target / z3d.GIZMO_STEP_M});
            } else {
                const units = target / z3d.GIZMO_STEP_M;
                z3d.setGizmoReadout("{s}{d:.2}u", .{ if (units < 0) "-" else "+", @abs(units) });
            }
            const d = target - z3d.g_gizmo_applied;
            if (@abs(d) < 1e-7) return false;
            // Curve Pull (req_4325): armed + a captured run → the drag bends
            // instead of translating. ABSOLUTE application from grab-time base
            // (the arc re-solves per frame), so g_gizmo_applied only gates the
            // per-frame no-op check, never compounds into the geometry.
            if (z3d.g_curve_pull_armed and mesh_edit.curvePullActive()) {
                const units = target / z3d.GIZMO_STEP_M;
                const offset = z3d.vmul(av, target);
                if (z3d.curvePullAdaptiveSource()) |source| {
                    const wanted_cuts = mesh_edit.curvePullAdaptiveCutsFor(source, offset, z3d.g_curve_pull_cuts);
                    if (wanted_cuts != z3d.g_curve_pull_cuts) {
                        if (!z3d.curvePullAdaptiveRebuild(offset, wanted_cuts)) {
                            z3d.setGizmoReadout("curve: adaptive loop cut refused", .{});
                            return false;
                        }
                        z3d.setGizmoReadout("bend {s}{d:.2}u · {d} cut/edge", .{ if (units < 0) "-" else "+", @abs(units), wanted_cuts });
                        z3d.g_gizmo_applied = target;
                        return true;
                    }
                }
                z3d.setGizmoReadout("bend {s}{d:.2}u · {d} cut/edge", .{ if (units < 0) "-" else "+", @abs(units), z3d.g_curve_pull_cuts });
                const m = mesh_edit.curvePullApply(offset);
                if (!z3d.applyMeshMutation(m)) return false;
                z3d.g_gizmo_applied = target;
                return true;
            }
            if (z3d.g_curve_pull_armed) z3d.setGizmoReadout("curve: select one vertex run", .{});
            const m = mesh_edit.translateSelection(z3d.vmul(av, d));
            if (!z3d.applyMeshMutation(m)) return false;
            z3d.g_gizmo_applied = target;
            return true;
        },
        .rotate => {
            z3d.g_gizmo_raw += px * 0.018;
            const target = z3d.snapStep(z3d.g_gizmo_raw, z3d.GIZMO_STEP_ROT, z3d.GIZMO_STEP_ROT_FINE, shift, free);
            const deg = target * 180.0 / std.math.pi;
            z3d.setGizmoReadout("{s}{d:.0}\u{00B0}", .{ if (deg < 0) "-" else "+", @abs(deg) });
            const d = target - z3d.g_gizmo_applied;
            if (@abs(d) < 1e-7) return false;
            const m = mesh_edit.rotateSelectionAxis(av, pivot, d);
            if (!z3d.applyMeshMutation(m)) return false;
            z3d.g_gizmo_applied = target;
            return true;
        },
        .scale => {
            z3d.g_gizmo_raw += px * 0.012;
            const target = std.math.clamp(
                1.0 + z3d.snapStep(z3d.g_gizmo_raw, z3d.GIZMO_STEP_SCALE, z3d.GIZMO_STEP_SCALE_FINE, shift, free),
                mesh_edit.scale_factor_tuning.min,
                mesh_edit.scale_factor_tuning.max,
            );
            z3d.setGizmoReadout("\u{00D7}{d:.2}", .{target});
            // Multiplicative bookkeeping: applying target/applied lands the mesh exactly
            // at the cumulative factor, whatever path the drag wandered.
            const rel = target / z3d.g_gizmo_applied;
            if (@abs(rel - 1.0) < 1e-6) return false;
            const m = mesh_edit.scaleSelectionAxis(av, pivot, rel);
            if (!z3d.applyMeshMutation(m)) return false;
            z3d.g_gizmo_applied = target;
            return true;
        },
    }
}

pub fn meshGizmoNudge(axis: u8, amount: f32) bool {
    if (axis > 2 or z3d.meshEditModeRaw() == 0 or !model_paint.hasTarget()) return false;
    var snap = z3d.journalSnapshotCurrent("nudge");
    const m = mesh_edit.translateSelection(z3d.vmul(z3d.axisVec(axis), amount));
    const ok = z3d.applyMeshMutation(m);
    if (ok) z3d.journalCommit(&snap) else z3d.journalDiscard(&snap);
    return ok;
}

/// Apply an exact uniform factor without a screen-distance drag. The selection
/// pivot is frozen once, the geometry changes in one mutation / one journal
/// entry, and the orbit is reframed to the result unless the camera is locked.
pub fn meshGizmoScaleBy(factor: f32) bool {
    if (z3d.meshEditModeRaw() == 0 or !model_paint.hasTarget()) return false;
    const pivot = mesh_edit.selectionPivot() orelse return false;
    var snap = z3d.journalSnapshotCurrent("scale by value");
    const m = mesh_edit.scaleSelectionUniform(pivot, factor);
    const ok = z3d.applyMeshMutation(m);
    if (ok) {
        z3d.journalCommit(&snap);
        if (!z3d.g_orbit.locked) {
            if (mesh_edit.selectionFrame()) |frame| z3d.orbitFrame(frame.center, frame.radius);
        }
    } else z3d.journalDiscard(&snap);
    return ok;
}

/// Straighten one selected vertex row or edge loop onto its nearest world-axis
/// plane. The mesh-edit core derives the axis from the smallest non-zero span,
/// preserves the selection, and reflects the same result to armed mirror twins.
/// Returns 0/1/2 for X/Y/Z so the caller can report what it aligned.
pub fn meshAlignLoop() ?u8 {
    if (z3d.meshEditModeRaw() == 0 or !model_paint.hasTarget()) return null;
    var snap = z3d.journalSnapshotCurrent("align loop");
    const alignment = mesh_edit.alignSelectedLoop() orelse {
        z3d.journalDiscard(&snap);
        return null;
    };
    const ok = z3d.applyMeshMutation(alignment.mutation);
    if (ok) {
        z3d.journalCommit(&snap);
        return alignment.axis;
    }
    z3d.journalDiscard(&snap);
    return null;
}

pub fn meshTransformTranslate(delta: [3]f32) bool {
    if (z3d.meshEditModeRaw() == 0 or !model_paint.hasTarget()) return false;
    var snap = z3d.journalSnapshotCurrent("translate exact");
    const ok = z3d.applyMeshMutation(mesh_edit.translateSelection(delta));
    if (ok) z3d.journalCommit(&snap) else z3d.journalDiscard(&snap);
    return ok;
}

pub fn meshTransformScaleAxis(axis: [3]f32, pivot: [3]f32, factor: f32) bool {
    if (z3d.meshEditModeRaw() == 0 or !model_paint.hasTarget()) return false;
    var snap = z3d.journalSnapshotCurrent("scale exact");
    const ok = z3d.applyMeshMutation(mesh_edit.scaleSelectionAxis(axis, pivot, factor));
    if (ok) z3d.journalCommit(&snap) else z3d.journalDiscard(&snap);
    return ok;
}

pub fn meshTransformRotateAxis(axis: [3]f32, pivot: [3]f32, radians: f32) bool {
    if (z3d.meshEditModeRaw() == 0 or !model_paint.hasTarget()) return false;
    var snap = z3d.journalSnapshotCurrent("rotate exact");
    const ok = z3d.applyMeshMutation(mesh_edit.rotateSelectionAxis(axis, pivot, radians));
    if (ok) z3d.journalCommit(&snap) else z3d.journalDiscard(&snap);
    return ok;
}
