//! topo_weld_delete.zig — split verbatim from framework/gpu/3d.zig (req_4375).
//! Generated by _tool/split3d.zig — edit 3d.zig's successor here, regenerate only from the manifest.
//! Cross-file references are qualified through the orchestrator (`z3d`).

const std = @import("std");
const builtin = @import("builtin");
const log = @import("../../diag/log.zig");
const wgpu = @import("wgpu");
const bu = @import("../buffer_upload.zig");
const shaders = @import("../shaders.zig");
const terrain_grid = @import("../terrain_grid.zig");
const core = @import("../../dev_modules/gpu_api.zig");
const capture = @import("../capture.zig");
const build_options = @import("build_options");
const math = @import("../../math/root.zig");
const layout = @import("../../layout.zig");
const effect_assemble = @import("../effect_assemble.zig");
const compile_progress = @import("../compile_progress.zig");
const static_instance_policy = @import("../static_instance_policy.zig");
const model_paint = @import("../model_paint.zig");
const gizmo_axis_map = @import("../gizmo_axis_map.zig");
const effects_ctx = @import("../effects_ctx.zig");
const paint_islands_mod = @import("../paint_islands.zig");
const paint_program = @import("../paint_program.zig");
const model_source = @import("../model_source.zig");
const meshdoc_format = @import("../meshdoc_format.zig");
const mesh_audit = @import("../mesh_audit.zig");
const mesh_face_table = @import("../mesh_face_table.zig");
const mesh_face_diff = @import("../mesh_face_diff.zig");
const mesh_face_field_candidate = @import("../mesh_face_field_candidate.zig");
const mesh_face_table_package = @import("../mesh_face_table_package.zig");
const mesh_face_table_worker = @import("../mesh_face_table_worker.zig");
const historical_preview = @import("../historical_preview.zig");
const mesh_edit = @import("../mesh_edit.zig");
const mesh_semantics = @import("../mesh_semantics.zig");
const mesh_semantic_restore = @import("../mesh_semantic_restore.zig");
const mesh_edge_semantics = @import("../mesh_edge_semantics.zig");
const indexed_edit_mesh = @import("../indexed_edit_mesh.zig");
const character_topology_promotion = @import("../character_topology_promotion.zig");
const mesh_journal_log = @import("../mesh_journal_log.zig");
const model_write_lease = @import("../model_write_lease.zig");
const model_adoption_receipt = @import("../model_adoption_receipt.zig");
const model_adoption_finalize = @import("../model_adoption_finalize.zig");
const path_array = @import("../path_array.zig");
const path_plane = @import("../path_plane.zig");
const stage_scale = @import("../stage_scale.zig");
const pack = @import("../pack.zig");
const stable_geometry_slot = @import("../stable_geometry_slot.zig");
const character_rig_session = @import("../../skeleton/character_rig_session.zig");
const character_skin_binding = @import("../../skeleton/skin_binding.zig");
const character_specimen = @import("../character_specimen.zig");
const mouse_state = @import("../../state/mouse_state.zig");
const Node = layout.Node;

const z3d = @import("root.zig");

/// Delete exactly the selected mesh elements: drop every triangle the current selection
/// marks (mesh_edit.buildDeleteMask — selected faces, or faces touching a selected vert/edge)
/// and rebuild the edit mesh from the survivors, carrying their face groups. Deleting
/// EVERYTHING is allowed and empties the model (req_2806 USER RULING: the old
/// refuse-to-empty guard "shouldn't exist" — it made the outliner remove its last row
/// while the host kept a ghost mesh). An empty result is journaled like any edit, so
/// undo restores it.
pub fn meshDeleteSelection() bool {
    if (!model_paint.hasTarget()) return false;
    const verts = z3d.g_edit_verts orelse return false;
    const tri_count = z3d.g_edit_count / 3;
    if (tri_count == 0) return false;

    const mask = std.heap.c_allocator.alloc(bool, tri_count) catch return false;
    defer std.heap.c_allocator.free(mask);
    const del = mesh_edit.buildDeleteMask(mask);
    if (del == 0) return false;
    // Mirror (req_3797): deleting a face deletes its twin — the mask extension is the
    // same door extrude uses.
    if (mesh_edit.mirrorMask() != 0) z3d.extendFaceMaskWithMirrorTwins(verts, tri_count, mask);
    const follow_before = if (mesh_edit.mode() == .face)
        mesh_edit.followPatchJson(std.heap.c_allocator, null, 2)
    else
        null;
    defer if (follow_before) |json| std.heap.c_allocator.free(json);
    const deleted = z3d.deleteMaskedFaces(verts, tri_count, mask, "delete selection");
    if (deleted) if (follow_before) |before| {
        z3d.g_follow_action_queue.append(
            std.heap.c_allocator,
            @intFromEnum(mesh_journal_log.ActionKind.delete_selection),
            @intFromEnum(z3d.g_mesh_action_source),
            before,
            "{\"version\":1,\"deleted\":true}",
        ) catch {};
    };
    return deleted;
}

/// WELD (req_3382) — the Blender Merge-at-Center verb: every vertex the active
/// selection affects (selected verts in vertex mode, edge endpoints in edge
/// mode) collapses to the selection centroid. Triangles the collapse degenerates
/// and authored faces whose whole boundary cancels leave in the SAME masked
/// rebuild, so the whole weld is one journal step ("weld") and one undo.
pub fn meshTopoWeldSelection() bool {
    if (!model_paint.hasTarget()) return false;
    const verts = z3d.g_edit_verts orelse return false;
    const tri_count = z3d.g_edit_count / 3;
    if (tri_count == 0) return false;
    if (!mesh_edit.ensureTopologyPub()) return false;
    const vert_count = mesh_edit.vertCount();
    if (vert_count == 0) return false;
    const affected = std.heap.c_allocator.alloc(bool, vert_count) catch return false;
    defer std.heap.c_allocator.free(affected);
    const affected_count = mesh_edit.affectedSelectionVertsPub(affected);
    if (affected_count < 2) return false;
    const center = mesh_edit.selectionPivot() orelse return false;

    // Final position per logical vertex: the centroid for affected vertices; with
    // mirror armed (req_3797), each affected vertex's twin collapses to the
    // REFLECTED centroid of its plane subset in the same rebuild. A twin that is
    // itself affected collapses to the selection centroid directly — never both.
    const collapse_to = std.heap.c_allocator.alloc(?[3]f32, vert_count) catch return false;
    defer std.heap.c_allocator.free(collapse_to);
    @memset(collapse_to, null);
    // Everything collapsing to one point must come out as ONE logical vertex, not a
    // stack of coincident twins: on explicit-topology documents the rebuild carries
    // stable ids verbatim, so the weld itself must hand it the identity groups to
    // fuse. Group 0 is the selection centroid; each mirror plane subset is its own
    // group at the reflected centroid.
    const collapse_groups = std.heap.c_allocator.alloc(u32, vert_count) catch return false;
    defer std.heap.c_allocator.free(collapse_groups);
    @memset(collapse_groups, NO_COLLAPSE_GROUP);
    var v: u32 = 0;
    while (v < vert_count) : (v += 1) {
        if (affected[v]) {
            collapse_to[v] = center;
            collapse_groups[v] = 0;
        }
    }
    if (mesh_edit.mirrorMask() != 0) {
        v = 0;
        while (v < vert_count) : (v += 1) {
            if (!affected[v]) continue;
            var subset: u8 = 1;
            while (subset <= 7) : (subset += 1) {
                const twin = mesh_edit.mirrorTwinOfVertPub(v, subset) orelse continue;
                if (twin >= vert_count or affected[twin] or collapse_to[twin] != null) continue;
                var reflected = center;
                inline for (0..3) |axis| {
                    if (subset & (@as(u8, 1) << @intCast(axis)) != 0)
                        reflected[axis] = mesh_edit.MIRROR_PLANE_CENTER[axis] * 2.0 - reflected[axis];
                }
                collapse_to[twin] = reflected;
                collapse_groups[twin] = subset;
            }
        }
    }

    // Faces with two coincident final corners are degenerate slivers — masked out
    // of the rebuild.
    const corner_positions = std.heap.c_allocator.alloc(f32, @as(usize, tri_count) * 9) catch return false;
    defer std.heap.c_allocator.free(corner_positions);
    const mask = std.heap.c_allocator.alloc(bool, tri_count) catch return false;
    defer std.heap.c_allocator.free(mask);
    const touched = std.heap.c_allocator.alloc(bool, tri_count) catch return false;
    defer std.heap.c_allocator.free(touched);
    var moved_any = false;
    var f: u32 = 0;
    while (f < tri_count) : (f += 1) {
        const soup_base = @as(usize, f) * 24;
        const cp_base = @as(usize, f) * 9;
        if (soup_base + 24 > verts.len) return false;
        var touched_face = false;
        var k: usize = 0;
        while (k < 3) : (k += 1) {
            const lv = mesh_edit.cornerVertPub(f, @intCast(k));
            const final_opt: ?[3]f32 = if (lv < vert_count) collapse_to[lv] else null;
            if (final_opt != null) {
                moved_any = true;
                touched_face = true;
            }
            const final = final_opt orelse [3]f32{ verts[soup_base + k * 8 + 0], verts[soup_base + k * 8 + 1], verts[soup_base + k * 8 + 2] };
            corner_positions[cp_base + k * 3 + 0] = final[0];
            corner_positions[cp_base + k * 3 + 1] = final[1];
            corner_positions[cp_base + k * 3 + 2] = final[2];
        }
        touched[f] = touched_face;
        mask[f] = z3d.weldTriangleDegenerate(corner_positions[cp_base .. cp_base + 9]);
    }
    if (!moved_any) return false;
    if (!z3d.maskMalformedWeldFaceGroups(verts, tri_count, corner_positions, touched, mask)) return false;
    return z3d.rebuildMaskedFaces(verts, tri_count, mask, "weld", corner_positions, collapse_groups);
}

/// Sentinel for `collapse_groups` rows: this dense vertex is not part of any weld
/// collapse and its carried stable identity passes through unchanged.
pub const NO_COLLAPSE_GROUP: u32 = std.math.maxInt(u32);

pub const MeshRetopoWeldPairsRequest = struct {
    pairs: []const [2]u32,
    /// Optional safety leash in model metres. Every pair is validated before
    /// any vertex moves, so one stale/cross-body id rejects the whole action.
    maxDistance: ?f32 = null,
};

pub const MeshRetopoNormalizeWidthsRequest = mesh_edit.NormalizeWidthsRequest;

/// Retopology seam close: collapse every explicit pair independently. The
/// ordinary Weld command correctly merges one selection to one centroid, but
/// applying it to a whole seam would collapse the seam into a single point.
/// This boundary keeps pair identity, validates scope/part/uniqueness first,
/// then removes any faces made degenerate in the same journal transaction.
pub fn meshRetopoWeldPairs(request: z3d.MeshRetopoWeldPairsRequest) bool {
    if (!model_paint.hasTarget() or request.pairs.len == 0 or request.pairs.len > 4096) return false;
    const max_distance = request.maxDistance;
    if (max_distance) |limit| if (!std.math.isFinite(limit) or limit <= 0) return false;
    const verts = z3d.g_edit_verts orelse return false;
    const tri_count = z3d.g_edit_count / 3;
    if (tri_count == 0 or !mesh_edit.ensureTopologyPub()) return false;
    const vert_count = mesh_edit.vertCount();
    if (vert_count == 0) return false;

    const affected = std.heap.c_allocator.alloc(bool, vert_count) catch return false;
    defer std.heap.c_allocator.free(affected);
    @memset(affected, false);
    const targets = std.heap.c_allocator.alloc(f32, @as(usize, vert_count) * 3) catch return false;
    defer std.heap.c_allocator.free(targets);
    @memset(targets, 0);
    // Each pair is its own identity group: the rebuild fuses the two carried stable
    // ids into one survivor per pair, never across pairs — two pairs that happen to
    // share a centroid still keep their own identities (seam order is authored).
    const collapse_groups = std.heap.c_allocator.alloc(u32, vert_count) catch return false;
    defer std.heap.c_allocator.free(collapse_groups);
    @memset(collapse_groups, NO_COLLAPSE_GROUP);

    for (request.pairs, 0..) |pair, pair_index| {
        const a = pair[0];
        const b = pair[1];
        if (a == b or a >= vert_count or b >= vert_count or affected[a] or affected[b] or
            !mesh_edit.vertInScopePub(a) or !mesh_edit.vertInScopePub(b)) return false;
        const part_a = mesh_edit.vertPartPub(a) orelse return false;
        const part_b = mesh_edit.vertPartPub(b) orelse return false;
        if (part_a != part_b) return false;
        const pa = mesh_edit.vertPosPub(a);
        const pb = mesh_edit.vertPosPub(b);
        const dx = pb[0] - pa[0];
        const dy = pb[1] - pa[1];
        const dz = pb[2] - pa[2];
        const distance = @sqrt(dx * dx + dy * dy + dz * dz);
        if (!std.math.isFinite(distance) or (max_distance != null and distance > max_distance.?)) return false;
        const center = [3]f32{ (pa[0] + pb[0]) * 0.5, (pa[1] + pb[1]) * 0.5, (pa[2] + pb[2]) * 0.5 };
        for (pair) |vertex| {
            affected[vertex] = true;
            collapse_groups[vertex] = @intCast(pair_index);
            const base = @as(usize, vertex) * 3;
            targets[base] = center[0];
            targets[base + 1] = center[1];
            targets[base + 2] = center[2];
        }
    }
    // A zero-distance pair is NOT a no-op: two stable ids stacked on one position
    // (the residue of an identity-less weld) fuse here without moving. Every
    // validated pair is two distinct ids, so there is always identity work to do.

    const corner_positions = std.heap.c_allocator.alloc(f32, @as(usize, tri_count) * 9) catch return false;
    defer std.heap.c_allocator.free(corner_positions);
    const mask = std.heap.c_allocator.alloc(bool, tri_count) catch return false;
    defer std.heap.c_allocator.free(mask);
    const touched = std.heap.c_allocator.alloc(bool, tri_count) catch return false;
    defer std.heap.c_allocator.free(touched);
    var face: u32 = 0;
    while (face < tri_count) : (face += 1) {
        const soup_base = @as(usize, face) * 24;
        const corner_base = @as(usize, face) * 9;
        if (soup_base + 24 > verts.len) return false;
        var touched_face = false;
        var corner: usize = 0;
        while (corner < 3) : (corner += 1) {
            const logical = mesh_edit.cornerVertPub(face, @intCast(corner));
            const dst = corner_base + corner * 3;
            if (logical < vert_count and affected[logical]) {
                touched_face = true;
                const src = @as(usize, logical) * 3;
                corner_positions[dst] = targets[src];
                corner_positions[dst + 1] = targets[src + 1];
                corner_positions[dst + 2] = targets[src + 2];
            } else {
                corner_positions[dst] = verts[soup_base + corner * 8];
                corner_positions[dst + 1] = verts[soup_base + corner * 8 + 1];
                corner_positions[dst + 2] = verts[soup_base + corner * 8 + 2];
            }
        }
        touched[face] = touched_face;
        mask[face] = z3d.weldTriangleDegenerate(corner_positions[corner_base .. corner_base + 9]);
    }
    if (!z3d.maskMalformedWeldFaceGroups(verts, tri_count, corner_positions, touched, mask)) return false;
    return z3d.rebuildMaskedFaces(verts, tri_count, mask, "weld vertex pairs", corner_positions, collapse_groups);
}

/// Equalize the edge widths of explicit ordered rows while retaining their
/// current polyline curvature. This is a positional edit, not a topology
/// rebuild, and therefore remains one ordinary journal unit.
pub fn meshRetopoNormalizeWidths(request: z3d.MeshRetopoNormalizeWidthsRequest) bool {
    if (!model_paint.hasTarget()) return false;
    var snap = z3d.journalSnapshotCurrent("normalize retopo widths");
    const mutation = mesh_edit.normalizeWidths(std.heap.c_allocator, request);
    const ok = z3d.applyMeshMutation(mutation);
    if (ok) z3d.journalCommit(&snap) else z3d.journalDiscard(&snap);
    return ok;
}

/// Two of a triangle's three FINAL corners coincide → the weld flattened it.
pub fn weldTriangleDegenerate(corners: []const f32) bool {
    const eps: f32 = 1e-6;
    var a: usize = 0;
    while (a < 3) : (a += 1) {
        var b: usize = a + 1;
        while (b < 3) : (b += 1) {
            if (@abs(corners[a * 3 + 0] - corners[b * 3 + 0]) < eps and
                @abs(corners[a * 3 + 1] - corners[b * 3 + 1]) < eps and
                @abs(corners[a * 3 + 2] - corners[b * 3 + 2]) < eps) return true;
        }
    }
    return false;
}

/// Weld and indexed-edit operations share one authored-boundary authority. A
/// per-triangle mask alone misses the opposite-corner quad collapse: both
/// surviving triangles have three distinct points, but together their boundary
/// cancels and loop cut cannot import the result.
pub fn maskMalformedWeldFaceGroups(
    verts: []const f32,
    tri_count: u32,
    corner_positions: []const f32,
    touched: []const bool,
    mask: []bool,
) bool {
    if (model_source.faceGroups() == null) return true;
    // Indexed edits can change the displayed triangle count without rewriting
    // the source-owned rows immediately. Use the same displayed-face snapshot
    // as every other topology transaction; reading faceGroups() directly here
    // rejects a valid weld after a cut because that slice still has the saved
    // triangle count.
    const groups = z3d.captureFaceGroups() orelse return false;
    defer std.heap.c_allocator.free(groups);
    if (groups.len < tri_count) return false;
    const parts = z3d.capturePartOfFaces();
    defer if (parts) |rows| std.heap.c_allocator.free(rows);
    _ = indexed_edit_mesh.maskMalformedWeldFaceGroups(
        std.heap.c_allocator,
        verts,
        corner_positions,
        tri_count,
        groups,
        parts,
        touched,
        mask,
    ) catch return false;
    return true;
}

/// Delete every face whose authored group id is in [lo, hi) — the outliner removing a
/// PART. Structural, not a selection gesture: it must not route through the interactive
/// selection doors, which the paint session makes inert (req_2662) — that routing made
/// an outliner delete mid-paint silently no-op while the row still left the list (req_2981).
pub fn meshDeleteGroupRange(lo: u32, hi: u32) bool {
    if (!model_paint.hasTarget()) return false;
    const verts = z3d.g_edit_verts orelse return false;
    const tri_count = z3d.g_edit_count / 3;
    if (tri_count == 0 or hi <= lo) return false;
    const live_ranges = model_source.partRanges() orelse return false;
    if (!mesh_journal_log.hasExactPartRange(live_ranges, lo, hi)) {
        std.log.err("[mesh-part] refused delete of stale/non-part range [{d},{d})", .{ lo, hi });
        return false;
    }

    const mask = std.heap.c_allocator.alloc(bool, tri_count) catch return false;
    defer std.heap.c_allocator.free(mask);
    var del: u32 = 0;
    var f: u32 = 0;
    while (f < tri_count) : (f += 1) {
        const g = model_source.faceGroupOf(f);
        mask[f] = g != model_source.NO_FACE_GROUP and g >= lo and g < hi;
        if (mask[f]) del += 1;
    }
    if (del == 0) return false;
    return z3d.deleteMaskedFaces(verts, tri_count, mask, "delete part");
}

/// Preserve the current atlas through a target swap, keyed by authored face group.
/// This is also the safe fallback when history restores UVs from an atlas coordinate
/// space that a later hide/show repack has already replaced.
pub fn beginPaintRasterCarry() void {
    // An empty target can be the midpoint of delete-last → undo. In that state the
    // previous target's carry is the only exact raster left; do not erase it by trying
    // to snapshot a nonexistent live atlas.
    if (model_paint.atlas() != null) {
        mesh_edit.suspendFaceTint();
        model_paint.snapshotAtlasForCarry();
        mesh_edit.resumeFaceTint();
    }
}

pub fn cancelPaintRasterCarry() void {
    model_paint.dropAtlasCarry();
}

/// Structural part operations preserve every surviving face's stable paint key
/// (authored group + intra-group ordinal). Arm both halves of the same-document
/// target swap together: exact atlas texels for the immediate image, and the full
/// stroke program/journal for later save, replay, and paint undo. Topology edits that
/// can change a survivor's key must not carry the program through this path.
pub fn beginPaintStableReplace() void {
    z3d.beginPaintRasterCarry();
    paint_program.carryProgramAcrossNextTarget();
}

pub fn cancelPaintStableReplace() void {
    z3d.cancelPaintRasterCarry();
    paint_program.cancelProgramCarry();
}

pub fn paintStableJournalLabel(label: []const u8) bool {
    return std.mem.eql(u8, label, "add part") or
        std.mem.eql(u8, label, "duplicate part") or
        std.mem.eql(u8, label, "mirror part") or
        std.mem.eql(u8, label, "delete part") or
        std.mem.eql(u8, label, "hide part") or
        std.mem.eql(u8, label, "show part") or
        // Identity-mapped replacements must carry the exact atlas/program on
        // undo instead of flattening every painted island to its centroid
        // colour. Symmetrize still marks the live layout stale because it
        // rewrites topology; carrying here only protects the return trip.
        std.mem.eql(u8, label, "transform") or
        std.mem.eql(u8, label, "nudge") or
        std.mem.eql(u8, label, "scale by value") or
        std.mem.eql(u8, label, "align loop") or
        std.mem.eql(u8, label, "symmetrize") or
        std.mem.eql(u8, label, "flip faces");
}

pub fn deleteMaskedFaces(verts: []const f32, tri_count: u32, mask: []const bool, label: []const u8) bool {
    return z3d.rebuildMaskedFaces(verts, tri_count, mask, label, null, null);
}

/// The masked-rebuild core delete shares with WELD (req_3382): drop masked faces,
/// carry groups/materials/parts, one journal step. `corner_positions` (xyz per
/// corner, tri_count×9) overrides surviving corners' positions while copying —
/// weld moves its collapsed vertices in the SAME transaction that removes the
/// faces the collapse degenerated, so undo is one step.
pub fn rebuildMaskedFaces(verts: []const f32, tri_count: u32, mask: []const bool, label: []const u8, corner_positions: ?[]const f32, collapse_groups: ?[]const u32) bool {
    // Drop the selection FIRST (same rule as detach/glass): the orange tint is
    // real atlas pixels with per-face saved patches, and both are keyed by the
    // CURRENT face indices. Restoring after the survivors compact would paint
    // the tint / patches onto whatever faces inherited those indices — the
    // "selection moved to the other side of the model" residue (req_2559).
    mesh_edit.clearSelection();

    const paint_stable = std.mem.eql(u8, label, "delete part");
    const has_groups = model_source.faceGroupOf(0) != model_source.NO_FACE_GROUP;
    const current_logical_ids = model_source.renderCornerLogicalIds();
    if (current_logical_ids) |rows| if (rows.len != @as(usize, tri_count) * 3) return false;
    const logical_vertex_count = model_source.logicalVertexCount();
    var out: std.ArrayListUnmanaged(f32) = .empty;
    var groups: std.ArrayListUnmanaged(u32) = .empty;
    defer groups.deinit(std.heap.c_allocator);
    var materials: std.ArrayListUnmanaged(u32) = .empty;
    defer materials.deinit(std.heap.c_allocator);
    var semantic_regions: std.ArrayListUnmanaged(u32) = .empty;
    defer semantic_regions.deinit(std.heap.c_allocator);
    var semantic_instances: std.ArrayListUnmanaged(u32) = .empty;
    defer semantic_instances.deinit(std.heap.c_allocator);
    var logical_ids: std.ArrayListUnmanaged(u32) = .empty;
    defer logical_ids.deinit(std.heap.c_allocator);
    // Weld identity fusion (req_4652): every collapse group keeps ONE stable id —
    // the first carried id seen in that group — and every other id in the group is
    // rewritten onto it. Without this the carried rows resurrect each collapsed
    // vertex as its own coincident twin: the dots stack, UI picking grabs both, and
    // the model LOOKS welded while UV stitching and watertightness stay broken.
    var collapse_survivors = std.AutoHashMapUnmanaged(u32, u32).empty;
    defer collapse_survivors.deinit(std.heap.c_allocator);
    var colors: std.ArrayListUnmanaged(u8) = .empty;
    defer colors.deinit(std.heap.c_allocator);
    var f: u32 = 0;
    while (f < tri_count) : (f += 1) {
        if (mask[f]) continue;
        const base = @as(usize, f) * 24; // 3 verts × 8 interleaved floats
        if (base + 24 > verts.len) break;
        if (!z3d.appendFloats(&out, verts[base .. base + 24])) {
            out.deinit(std.heap.c_allocator);
            return false;
        }
        // Weld's collapsed positions land on the just-appended corners (pos
        // floats only — normals/uvs ride the copy like every transform).
        if (corner_positions) |cp| {
            const cp_base = @as(usize, f) * 9;
            if (cp_base + 9 <= cp.len) {
                const tail = out.items[out.items.len - 24 ..];
                var k: usize = 0;
                while (k < 3) : (k += 1) {
                    tail[k * 8 + 0] = cp[cp_base + k * 3 + 0];
                    tail[k * 8 + 1] = cp[cp_base + k * 3 + 1];
                    tail[k * 8 + 2] = cp[cp_base + k * 3 + 2];
                }
            }
        }
        if (has_groups) groups.append(std.heap.c_allocator, model_source.faceGroupOf(f)) catch {};
        materials.append(std.heap.c_allocator, model_source.faceMaterialOf(f)) catch {};
        const semantic = model_source.faceSemanticOf(f);
        semantic_regions.append(std.heap.c_allocator, semantic.region) catch return false;
        semantic_instances.append(std.heap.c_allocator, semantic.instance) catch return false;
        if (current_logical_ids) |rows| {
            const logical_base = @as(usize, f) * 3;
            var corner: u32 = 0;
            while (corner < 3) : (corner += 1) {
                var stable = rows[logical_base + corner];
                if (collapse_groups) |vertex_groups| {
                    const dense = mesh_edit.cornerVertPub(f, @intCast(corner));
                    if (dense < vertex_groups.len and vertex_groups[dense] != NO_COLLAPSE_GROUP) {
                        const survivor = collapse_survivors.getOrPut(std.heap.c_allocator, vertex_groups[dense]) catch return false;
                        if (!survivor.found_existing) survivor.value_ptr.* = stable;
                        stable = survivor.value_ptr.*;
                    }
                }
                logical_ids.append(std.heap.c_allocator, stable) catch return false;
            }
        }
        if (paint_stable) {
            const color = z3d.trueFaceColor(f);
            colors.appendSlice(std.heap.c_allocator, &color) catch {
                out.deinit(std.heap.c_allocator);
                return false;
            };
        }
    }
    const kept: u32 = @intCast(out.items.len / 8);
    const owned = out.toOwnedSlice(std.heap.c_allocator) catch {
        out.deinit(std.heap.c_allocator);
        return false;
    };
    defer std.heap.c_allocator.free(owned);
    const had_retopo_bands = z3d.g_retopo_manual_bands != null;
    var retopo_bands = z3d.prepareRetopoBandCompaction(mask, @intCast(kept / 3));
    defer if (retopo_bands) |labels| std.heap.c_allocator.free(labels);
    // UV mask zones compact through the same survivor order (req_4152).
    const had_uv_zone = z3d.g_uv_zone != null;
    var uv_zone_carry = z3d.prepareZoneCompaction(&z3d.g_uv_zone, mask, @intCast(kept / 3));
    defer if (uv_zone_carry) |labels| std.heap.c_allocator.free(labels);
    const deleted_retopo_band: ?u16 = if (std.mem.eql(u8, label, "delete selection"))
        if (z3d.g_retopo_manual_bands) |labels| mesh_edit.uniformRetopoManualBand(labels, mask) else null
    else
        null;
    const retopo_carry_ready = !had_retopo_bands or retopo_bands != null;

    // A face delete can empty one Outliner part while leaving the rest of the
    // document alive. Carry the complete ownership partition (including hidden
    // host-stashed parts) through the transaction and drop only ranges that no
    // longer own a face. Leaving an empty range here deadlocks the next append:
    // the strict boundary must reject a declared part with no geometry.
    var compacted_ranges: ?[]u32 = null;
    defer if (compacted_ranges) |ranges| std.heap.c_allocator.free(ranges);
    if (has_groups) {
        if (model_source.partRanges()) |live_ranges| {
            var partition_groups: std.ArrayListUnmanaged(u32) = .empty;
            defer partition_groups.deinit(std.heap.c_allocator);
            partition_groups.appendSlice(std.heap.c_allocator, groups.items) catch return false;
            for (z3d.g_hidden_groups.items) |hidden| {
                partition_groups.appendSlice(std.heap.c_allocator, hidden.groups) catch return false;
            }
            compacted_ranges = mesh_journal_log.compactOccupiedPartRanges(
                std.heap.c_allocator,
                partition_groups.items,
                live_ranges,
            ) catch return false;
        }
    }

    var snap = z3d.journalSnapshotCurrent(label);
    // A non-empty Outliner delete is an indexed subset of the current soup: every
    // surviving vertex already carries the exact authored UV that samples the live
    // raster. Keep both byte-for-byte and merely retire the removed groups. Repacking
    // here made moved UVs jump on delete, then paired the old undo UVs with a twice-
    // resampled image on restore (req_3372). The all-deleted case has no resident
    // target to preserve and retains the carry-through-empty fallback.
    const preserve_indexed_atlas = paint_stable and
        kept >= 3 and
        has_groups and
        model_paint.atlas() != null and
        groups.items.len == kept / 3 and
        colors.items.len == @as(usize, kept / 3) * 4;
    const logical_replacement = z3d.logicalReplacementExactOrAbsent(
        if (current_logical_ids != null and kept > 0) logical_ids.items else null,
        kept,
        logical_vertex_count,
    );
    if (paint_stable and !preserve_indexed_atlas) z3d.beginPaintStableReplace();
    const ok = if (preserve_indexed_atlas)
        z3d.replaceActiveEditMeshPreservingAtlas(owned, kept, groups.items, colors.items, logical_replacement)
    else
        z3d.replaceActiveEditMesh(owned, kept, logical_replacement);
    if (!ok and paint_stable and !preserve_indexed_atlas) z3d.cancelPaintStableReplace();
    if (ok) {
        if (kept > 0) {
            model_source.setFaceMaterials(materials.items);
        } else {
            model_source.setFaceMaterials(&.{});
        }
        if (!model_source.setFaceSemantics(semantic_regions.items, semantic_instances.items)) {
            if (snap) |*before| _ = z3d.journalInstall(before);
            z3d.journalDiscard(&snap);
            return false;
        }
        if (has_groups) {
            model_source.setFaceGroups(groups.items);
            if (compacted_ranges) |ranges| model_source.setPartRanges(ranges);
            if (kept > 0 and !preserve_indexed_atlas) _ = z3d.refreshPaintLayout();
        } else if (kept == 0) {
            model_source.setPartRanges(&.{});
        }
        z3d.commitRetopoBandCarry(had_retopo_bands, &retopo_bands);
        z3d.commitZoneCarry(&z3d.g_uv_zone, had_uv_zone, &uv_zone_carry);
        if (retopo_carry_ready and deleted_retopo_band != null and z3d.g_retopo_manual_bands != null) {
            z3d.g_retopo_pending_band = deleted_retopo_band.?;
            z3d.g_retopo_pending_band_generation = z3d.g_edit_generation;
        } else if (std.mem.eql(u8, label, "delete selection")) {
            z3d.g_retopo_pending_band = mesh_edit.RETOPO_BAND_UNASSIGNED;
            z3d.g_retopo_pending_band_generation = 0;
        }
        z3d.journalCommit(&snap);
    } else z3d.journalDiscard(&snap);
    return ok;
}

// Snapshot the current mesh's per-face authored groups (before a replace resets them).
pub fn captureFaceGroups() ?[]u32 {
    const fc = z3d.g_edit_count / 3;
    const out = std.heap.c_allocator.alloc(u32, fc) catch return null;
    var f: u32 = 0;
    while (f < fc) : (f += 1) out[f] = model_source.faceGroupOf(f);
    return out;
}

/// Snapshot texture-role identity for an upcoming topology transaction. Existing
/// rows occupy the prefix; callers fill any requested appended rows explicitly.
pub fn captureFaceMaterials(total_faces: u32) ?[]u32 {
    const current_faces = z3d.g_edit_count / 3;
    if (total_faces < current_faces) return null;
    const out = std.heap.c_allocator.alloc(u32, total_faces) catch return null;
    var face: u32 = 0;
    while (face < current_faces) : (face += 1) out[face] = model_source.faceMaterialOf(face);
    if (total_faces > current_faces) @memset(out[current_faces..], indexed_edit_mesh.NO_MATERIAL);
    return out;
}

pub const SemanticRows = struct {
    regions: []u32,
    instances: []u32,

    pub fn deinit(rows: *z3d.SemanticRows) void {
        std.heap.c_allocator.free(rows.regions);
        std.heap.c_allocator.free(rows.instances);
        rows.* = undefined;
    }
};

/// Snapshot durable meaning for a topology transaction. Appended rows start as
/// explicit debt; each face-mint path must either inherit or assign a role before
/// committing the transaction.
pub fn captureFaceSemantics(total_faces: u32) ?z3d.SemanticRows {
    const current_faces = z3d.g_edit_count / 3;
    if (total_faces < current_faces) return null;
    const regions = std.heap.c_allocator.alloc(u32, total_faces) catch return null;
    const instances = std.heap.c_allocator.alloc(u32, total_faces) catch {
        std.heap.c_allocator.free(regions);
        return null;
    };
    var face: u32 = 0;
    while (face < current_faces) : (face += 1) {
        const semantic = model_source.faceSemanticOf(face);
        regions[face] = semantic.region;
        instances[face] = semantic.instance;
    }
    if (total_faces > current_faces) {
        @memset(regions[current_faces..], model_source.NO_SEMANTIC_ID);
        @memset(instances[current_faces..], model_source.NO_SEMANTIC_ID);
    }
    return .{ .regions = regions, .instances = instances };
}

pub fn optionalU32SlicesEqual(expected: ?[]const u32, actual: ?[]const u32) bool {
    if (expected == null or actual == null) return expected == null and actual == null;
    return std.mem.eql(u32, expected.?, actual.?);
}

pub fn optionalU8SlicesEqual(expected: ?[]const u8, actual: ?[]const u8) bool {
    if (expected == null or actual == null) return expected == null and actual == null;
    return std.mem.eql(u8, expected.?, actual.?);
}

pub fn hiddenModelStateHash() u64 {
    var hash: u64 = 0;
    for (z3d.g_hidden_groups.items) |hidden| {
        hash = std.hash.Wyhash.hash(hash, std.mem.asBytes(&hidden.lo));
        hash = std.hash.Wyhash.hash(hash, std.mem.asBytes(&hidden.hi));
        hash = std.hash.Wyhash.hash(hash, std.mem.sliceAsBytes(hidden.verts));
        hash = std.hash.Wyhash.hash(hash, std.mem.sliceAsBytes(hidden.source_verts));
        hash = std.hash.Wyhash.hash(hash, std.mem.sliceAsBytes(hidden.groups));
        hash = std.hash.Wyhash.hash(hash, std.mem.sliceAsBytes(hidden.materials));
        hash = std.hash.Wyhash.hash(hash, std.mem.sliceAsBytes(hidden.semantic_regions));
        hash = std.hash.Wyhash.hash(hash, std.mem.sliceAsBytes(hidden.semantic_instances));
        hash = std.hash.Wyhash.hash(hash, std.mem.asBytes(&hidden.logical_vertex_count));
        if (hidden.logical_ids) |rows| hash = std.hash.Wyhash.hash(hash, std.mem.sliceAsBytes(rows));
        hash = std.hash.Wyhash.hash(hash, hidden.colors);
    }
    return hash;
}

/// Exact resident-state guard for metadata-only mesh transactions. Geometry, UVs,
/// paint, source projection, visibility/part ownership, and document identity are
/// one state: changing an authored face id is allowed to change only the requested
/// group rows. A mismatch aborts before the journal entry is committed.
pub const ResidentMetadataGuard = struct {
    edit_verts: ?[]f32 = null,
    source_verts: ?[]f32 = null,
    groups: ?[]u32 = null,
    part_ranges: ?[]u32 = null,
    face_parts: ?[]u32 = null,
    materials: ?[]u32 = null,
    semantic_regions: ?[]u32 = null,
    semantic_instances: ?[]u32 = null,
    logical_ids: ?[]u32 = null,
    semantic_table_json: ?[]u8 = null,
    source_colors: ?[]u8 = null,
    face_colors: ?[]u8 = null,
    atlas_present: bool = false,
    atlas_len: usize = 0,
    atlas_hash: u64 = 0,
    atlas_w: u32 = 0,
    atlas_h: u32 = 0,
    edit_key: ?[]u8 = null,
    edit_count: u32,
    source_count: u32,
    paint_face_count: u32,
    edit_key_hash: u64,
    part_count: u32,
    logical_vertex_count: u32,
    hidden_part_count: usize,
    hidden_state_hash: u64,
    paint_layout_revision: u64,
    paint_layout_stale: bool,
    authored_atlas: bool,

    pub fn capture() ?z3d.ResidentMetadataGuard {
        const verts = z3d.g_edit_verts orelse return null;
        const need = @as(usize, z3d.g_edit_count) * 8;
        if (verts.len < need) return null;
        const current_groups = model_source.faceGroups() orelse return null;
        if (current_groups.len != z3d.g_edit_count / 3) return null;
        var guard = z3d.ResidentMetadataGuard{
            .edit_count = z3d.g_edit_count,
            .source_count = model_source.count(),
            .paint_face_count = model_paint.faceCount(),
            .edit_key_hash = z3d.g_edit_key_hash,
            .part_count = z3d.hostPartCount(),
            .logical_vertex_count = model_source.logicalVertexCount(),
            .hidden_part_count = z3d.g_hidden_groups.items.len,
            .hidden_state_hash = z3d.hiddenModelStateHash(),
            .paint_layout_revision = model_paint.layoutRevision(),
            .paint_layout_stale = z3d.g_paint_layout_stale,
            .authored_atlas = model_paint.hasAuthoredAtlas(),
        };
        errdefer guard.deinit();
        guard.edit_verts = std.heap.c_allocator.dupe(f32, verts[0..need]) catch return null;
        guard.groups = std.heap.c_allocator.dupe(u32, current_groups) catch return null;
        guard.face_colors = z3d.collectCurrentFaceColors() orelse return null;
        if (model_source.verts()) |rows|
            guard.source_verts = std.heap.c_allocator.dupe(f32, rows) catch return null;
        if (model_source.partRanges()) |rows|
            guard.part_ranges = std.heap.c_allocator.dupe(u32, rows) catch return null;
        if (z3d.capturePartOfFaces()) |rows| guard.face_parts = rows;
        if (model_source.faceMaterials()) |rows|
            guard.materials = std.heap.c_allocator.dupe(u32, rows) catch return null;
        if (model_source.faceSemanticRegions()) |rows|
            guard.semantic_regions = std.heap.c_allocator.dupe(u32, rows) catch return null;
        if (model_source.faceSemanticInstances()) |rows|
            guard.semantic_instances = std.heap.c_allocator.dupe(u32, rows) catch return null;
        if (model_source.renderCornerLogicalIds()) |rows|
            guard.logical_ids = std.heap.c_allocator.dupe(u32, rows) catch return null;
        if (model_source.semanticTableJson()) |json|
            guard.semantic_table_json = std.heap.c_allocator.dupe(u8, json) catch return null;
        if (model_source.colors()) |rows|
            guard.source_colors = std.heap.c_allocator.dupe(u8, rows) catch return null;
        if (model_paint.atlas()) |atlas| {
            guard.atlas_present = true;
            guard.atlas_len = atlas.rgba.len;
            guard.atlas_hash = std.hash.Wyhash.hash(0, atlas.rgba);
            guard.atlas_w = atlas.w;
            guard.atlas_h = atlas.h;
        }
        if (z3d.g_edit_key) |key| guard.edit_key = std.heap.c_allocator.dupe(u8, key) catch return null;
        return guard;
    }

    pub fn deinit(guard: *z3d.ResidentMetadataGuard) void {
        if (guard.edit_verts) |rows| std.heap.c_allocator.free(rows);
        if (guard.source_verts) |rows| std.heap.c_allocator.free(rows);
        if (guard.groups) |rows| std.heap.c_allocator.free(rows);
        if (guard.part_ranges) |rows| std.heap.c_allocator.free(rows);
        if (guard.face_parts) |rows| std.heap.c_allocator.free(rows);
        if (guard.materials) |rows| std.heap.c_allocator.free(rows);
        if (guard.semantic_regions) |rows| std.heap.c_allocator.free(rows);
        if (guard.semantic_instances) |rows| std.heap.c_allocator.free(rows);
        if (guard.logical_ids) |rows| std.heap.c_allocator.free(rows);
        if (guard.semantic_table_json) |json| std.heap.c_allocator.free(json);
        if (guard.source_colors) |rows| std.heap.c_allocator.free(rows);
        if (guard.face_colors) |rows| std.heap.c_allocator.free(rows);
        if (guard.edit_key) |key| std.heap.c_allocator.free(key);
        guard.* = undefined;
    }

    pub fn matchesGroupOnly(guard: *const z3d.ResidentMetadataGuard, expected_groups: []const u32) bool {
        if (z3d.g_edit_count != guard.edit_count or
            model_source.count() != guard.source_count or
            model_paint.faceCount() != guard.paint_face_count or
            z3d.g_edit_key_hash != guard.edit_key_hash or
            z3d.hostPartCount() != guard.part_count or
            model_source.logicalVertexCount() != guard.logical_vertex_count or
            z3d.g_hidden_groups.items.len != guard.hidden_part_count or
            z3d.hiddenModelStateHash() != guard.hidden_state_hash or
            model_paint.layoutRevision() != guard.paint_layout_revision or
            z3d.g_paint_layout_stale != guard.paint_layout_stale or
            model_paint.hasAuthoredAtlas() != guard.authored_atlas)
        {
            return false;
        }
        const live_verts = z3d.g_edit_verts orelse return false;
        const expected_edit_verts = guard.edit_verts orelse return false;
        if (live_verts.len < expected_edit_verts.len or !std.mem.eql(f32, expected_edit_verts, live_verts[0..expected_edit_verts.len]))
            return false;
        if (guard.source_verts) |expected| {
            const actual = model_source.verts() orelse return false;
            if (!std.mem.eql(f32, expected, actual)) return false;
        } else if (model_source.verts() != null) return false;
        const live_groups = model_source.faceGroups() orelse return false;
        if (!std.mem.eql(u32, expected_groups, live_groups)) return false;
        if (!z3d.optionalU32SlicesEqual(guard.part_ranges, model_source.partRanges())) return false;
        const live_face_parts = z3d.capturePartOfFaces();
        defer if (live_face_parts) |rows| std.heap.c_allocator.free(rows);
        if (!z3d.optionalU32SlicesEqual(guard.face_parts, live_face_parts)) return false;
        if (!z3d.optionalU32SlicesEqual(guard.materials, model_source.faceMaterials())) return false;
        if (!z3d.optionalU32SlicesEqual(guard.semantic_regions, model_source.faceSemanticRegions())) return false;
        if (!z3d.optionalU32SlicesEqual(guard.semantic_instances, model_source.faceSemanticInstances())) return false;
        if (!z3d.optionalU32SlicesEqual(guard.logical_ids, model_source.renderCornerLogicalIds())) return false;
        if (!z3d.optionalU8SlicesEqual(guard.semantic_table_json, model_source.semanticTableJson())) return false;
        if (!z3d.optionalU8SlicesEqual(guard.source_colors, model_source.colors())) return false;
        const live_colors = z3d.collectCurrentFaceColors() orelse return false;
        defer std.heap.c_allocator.free(live_colors);
        const expected_face_colors = guard.face_colors orelse return false;
        if (!std.mem.eql(u8, expected_face_colors, live_colors)) return false;
        if (guard.atlas_present) {
            const atlas = model_paint.atlas() orelse return false;
            if (atlas.w != guard.atlas_w or
                atlas.h != guard.atlas_h or
                atlas.rgba.len != guard.atlas_len or
                std.hash.Wyhash.hash(0, atlas.rgba) != guard.atlas_hash)
            {
                return false;
            }
        } else if (model_paint.atlas() != null) return false;
        if (guard.edit_key) |expected| {
            const actual = z3d.g_edit_key orelse return false;
            if (!std.mem.eql(u8, expected, actual)) return false;
        } else if (z3d.g_edit_key != null) return false;
        return true;
    }
};
