//! paint_program.zig — a model painting stored as its STROKE PROGRAM, not its pixels.
//!
//! GUIDING_LIGHT ("Worked Example: painted textures"): store the recipe (the strokes
//! + their params), never the rasterized atlas. Every authoring dab/fill on the model
//! paint target is APPENDED here as a resolution-independent op — face index + the hit's
//! barycentric, so it is camera-free and survives detail changes. Serialized, this tiny
//! program IS the durable form; replayed once at load it rebuilds the atlas exactly.
//!
//! Why it beats storing the atlas: a dither brush's scatter is the worst case for RLE
//! and bloats a PNG, but it is generated by a few numbers — so we keep the numbers (the
//! ops), never the scatter (the pixels). Shader inks embed their WGSL + params, so the
//! blob is SELF-CONTAINED: replay re-bakes the material with no catalog. Animation will
//! ride the same stream as frame-timing ops (not built yet).
//!
//! Recording lives in the authoring entry points (3d.zig paintStampAt/paintAt); replay
//! calls model_paint directly and suppresses recording, so it never re-records itself.

const std = @import("std");
const model_paint = @import("model_paint.zig");
const material_tex = @import("material_tex.zig");

const alloc = std.heap.c_allocator;

const OP_INK_COLOR: u8 = 0; // r,g,b
const OP_INK_MATERIAL: u8 = 1; // matIndex u16
const OP_DAB: u8 = 2; // face u32, u f32, v f32, radius f32, flow f32
const OP_FILL: u8 = 3; // face u32
const MAGIC = [4]u8{ 'R', 'J', 'P', 'P' };
const VERSION: u16 = 1;
const MAT_BAKE_SIZE: u32 = 256;

// A referenced shader ink, content-addressed by key. WGSL + params are stored so the
// program re-bakes the material at load with no catalog dependency.
const MatRecipe = struct { key: []u8, wgsl: []u8, data: []f32, tiles: f32 };

var g_ops: std.ArrayList(u8) = .{};
var g_mats: std.ArrayList(MatRecipe) = .{};

// Active-ink dedup so an INK op is emitted only when the ink actually changes.
var g_have_active: bool = false;
var g_active_is_mat: bool = false;
var g_active_mat: u16 = 0;
var g_active_rgb: [3]u8 = .{ 0, 0, 0 };

var g_recording: bool = true; // false during replay, so replay never re-records

fn freeMats() void {
    for (g_mats.items) |m| {
        alloc.free(m.key);
        alloc.free(m.wgsl);
        alloc.free(m.data);
    }
    g_mats.clearRetainingCapacity();
}

/// Wipe the recorded program (new paint target, or a cleared painting).
pub fn reset() void {
    g_ops.clearRetainingCapacity();
    freeMats();
    g_have_active = false;
    g_active_is_mat = false;
}

fn appendU16(v: u16) void {
    var b: [2]u8 = undefined;
    std.mem.writeInt(u16, &b, v, .little);
    g_ops.appendSlice(alloc, &b) catch {};
}
fn appendU32(v: u32) void {
    var b: [4]u8 = undefined;
    std.mem.writeInt(u32, &b, v, .little);
    g_ops.appendSlice(alloc, &b) catch {};
}
fn appendF32(v: f32) void {
    appendU32(@bitCast(v));
}

/// Register (dedup by key) a shader ink and mark it active. Called when JS sets a bucket;
/// the WGSL + params are captured so the program is self-contained.
pub fn activateMaterial(key: []const u8, wgsl: []const u8, data: []const f32, tiles: f32) void {
    var idx: u16 = 0;
    var found = false;
    for (g_mats.items, 0..) |m, i| {
        if (std.mem.eql(u8, m.key, key)) {
            idx = @intCast(i);
            found = true;
            break;
        }
    }
    if (!found) {
        const k = alloc.dupe(u8, key) catch return;
        const w = alloc.dupe(u8, wgsl) catch {
            alloc.free(k);
            return;
        };
        const d = alloc.dupe(f32, data) catch {
            alloc.free(k);
            alloc.free(w);
            return;
        };
        g_mats.append(alloc, .{ .key = k, .wgsl = w, .data = d, .tiles = tiles }) catch {
            alloc.free(k);
            alloc.free(w);
            alloc.free(d);
            return;
        };
        idx = @intCast(g_mats.items.len - 1);
    }
    g_active_is_mat = true;
    g_active_mat = idx;
    g_have_active = false; // force the next dab to emit this ink
}

/// The active ink returns to flat colour (JS cleared the material).
pub fn deactivateMaterial() void {
    g_active_is_mat = false;
    g_have_active = false;
}

fn emitInk(mat: bool, rgb: [3]u8) void {
    if (mat) {
        if (!g_have_active or !g_active_is_mat) {
            g_ops.append(alloc, OP_INK_MATERIAL) catch {};
            appendU16(g_active_mat);
            g_have_active = true;
            g_active_is_mat = true;
        }
    } else if (!g_have_active or g_active_is_mat or !std.mem.eql(u8, &g_active_rgb, &rgb)) {
        g_ops.append(alloc, OP_INK_COLOR) catch {};
        g_ops.appendSlice(alloc, &rgb) catch {};
        g_have_active = true;
        g_active_is_mat = false;
        g_active_rgb = rgb;
    }
}

/// Record one free-form dab (resolution-independent: face + barycentric).
pub fn recordDab(face: u32, u: f32, v: f32, radius: f32, flow: f32, mat: bool, rgb: [3]u8) void {
    if (!g_recording) return;
    emitInk(mat, rgb);
    g_ops.append(alloc, OP_DAB) catch {};
    appendU32(face);
    appendF32(u);
    appendF32(v);
    appendF32(radius);
    appendF32(flow);
}

/// Record one whole-face fill.
pub fn recordFill(face: u32, mat: bool, rgb: [3]u8) void {
    if (!g_recording) return;
    emitInk(mat, rgb);
    g_ops.append(alloc, OP_FILL) catch {};
    appendU32(face);
}

pub fn isEmpty() bool {
    return g_ops.items.len == 0;
}

fn u16le(v: u16) [2]u8 {
    var b: [2]u8 = undefined;
    std.mem.writeInt(u16, &b, v, .little);
    return b;
}
fn u32le(v: u32) [4]u8 {
    var b: [4]u8 = undefined;
    std.mem.writeInt(u32, &b, v, .little);
    return b;
}

// Build the blob body; any allocation error propagates so serialize() can free cleanly.
fn writeBlob(buf: *std.ArrayList(u8)) !void {
    try buf.appendSlice(alloc, &MAGIC);
    try buf.appendSlice(alloc, &u16le(VERSION));
    try buf.appendSlice(alloc, &u16le(@intCast(model_paint.detail())));
    try buf.appendSlice(alloc, &u32le(model_paint.faceCount()));
    try buf.appendSlice(alloc, &u16le(@intCast(g_mats.items.len)));
    for (g_mats.items) |m| {
        try buf.appendSlice(alloc, &u16le(@intCast(m.key.len)));
        try buf.appendSlice(alloc, m.key);
        try buf.appendSlice(alloc, &u32le(@intCast(m.wgsl.len)));
        try buf.appendSlice(alloc, m.wgsl);
        try buf.appendSlice(alloc, &u16le(@intCast(m.data.len)));
        for (m.data) |f| try buf.appendSlice(alloc, &u32le(@bitCast(f)));
        try buf.appendSlice(alloc, &u32le(@bitCast(m.tiles)));
    }
    try buf.appendSlice(alloc, &u32le(@intCast(g_ops.items.len)));
    try buf.appendSlice(alloc, g_ops.items);
}

/// Serialize the program (header + material table + ops) into a caller-owned blob, or
/// null if nothing was painted (or on allocation failure). Detail + facecount are stamped
/// from the live target.
pub fn serialize() ?[]u8 {
    if (g_ops.items.len == 0) return null;
    var buf: std.ArrayList(u8) = .{};
    writeBlob(&buf) catch {
        buf.deinit(alloc);
        return null;
    };
    return buf.toOwnedSlice(alloc) catch {
        buf.deinit(alloc);
        return null;
    };
}

// ── Replay ──────────────────────────────────────────────────────────────────────────
const Cursor = struct {
    b: []const u8,
    p: usize = 0,
    fn u8v(c: *Cursor) ?u8 {
        if (c.p >= c.b.len) return null;
        const v = c.b[c.p];
        c.p += 1;
        return v;
    }
    fn u16v(c: *Cursor) ?u16 {
        if (c.p + 2 > c.b.len) return null;
        const v = std.mem.readInt(u16, c.b[c.p..][0..2], .little);
        c.p += 2;
        return v;
    }
    fn u32v(c: *Cursor) ?u32 {
        if (c.p + 4 > c.b.len) return null;
        const v = std.mem.readInt(u32, c.b[c.p..][0..4], .little);
        c.p += 4;
        return v;
    }
    fn f32v(c: *Cursor) ?f32 {
        const u = c.u32v() orelse return null;
        return @bitCast(u);
    }
    fn bytes(c: *Cursor, n: usize) ?[]const u8 {
        if (c.p + n > c.b.len) return null;
        const s = c.b[c.p .. c.p + n];
        c.p += n;
        return s;
    }
};

// A material recipe borrowed from the blob (no copy) — baked on demand during replay.
const BorrowedMat = struct { key: []const u8, wgsl: []const u8, data: []f32, tiles: f32 };

fn bakeBorrowed(m: BorrowedMat) bool {
    const raw = material_tex.bakePixels(m.key, m.wgsl, m.data, MAT_BAKE_SIZE) orelse return false;
    defer std.heap.page_allocator.free(raw);
    if (raw.len < 8) return false;
    const w = std.mem.readInt(u32, raw[0..4], .little);
    const h = std.mem.readInt(u32, raw[4..8], .little);
    return model_paint.setMaterialInk(raw[8..], w, h, m.tiles);
}

/// Peek the detail (paint density, texels/meter — patch size in pre-island blobs) a program
/// was recorded at, without replaying. The caller sets this detail FIRST (it rebuilds the
/// atlas + re-uploads the mesh, which this module can't) before calling apply(). Null on a
/// malformed/incompatible blob.
pub fn programDetail(blob: []const u8) ?u16 {
    if (blob.len < 8) return null;
    if (!std.mem.eql(u8, blob[0..4], &MAGIC)) return null;
    if (std.mem.readInt(u16, blob[4..6], .little) != VERSION) return null;
    return std.mem.readInt(u16, blob[6..8], .little);
}

/// Rebuild the atlas by replaying a serialized program: clear to default, then apply every op
/// (re-baking shader inks from their embedded recipe). The caller must have already set the
/// program's detail (see programDetail). Returns false on a malformed/incompatible blob.
/// Recording is suppressed throughout so replay never re-records itself.
pub fn apply(blob: []const u8) bool {
    var c = Cursor{ .b = blob };
    const magic = c.bytes(4) orelse return false;
    if (!std.mem.eql(u8, magic, &MAGIC)) return false;
    if ((c.u16v() orelse return false) != VERSION) return false;
    _ = c.u16v() orelse return false; // detail (applied by the caller before apply — needs a mesh re-upload)
    _ = c.u32v() orelse return false; // facecount (advisory)
    const mat_count = c.u16v() orelse return false;

    // Parse the material table into borrowed recipes. data is copied to an aligned temp
    // (the blob's f32 run isn't guaranteed aligned); freed at the end.
    var mats = std.ArrayList(BorrowedMat){};
    defer {
        for (mats.items) |m| alloc.free(m.data);
        mats.deinit(alloc);
    }
    var mi: u16 = 0;
    while (mi < mat_count) : (mi += 1) {
        const klen = c.u16v() orelse return false;
        const key = c.bytes(klen) orelse return false;
        const wlen = c.u32v() orelse return false;
        const wgsl = c.bytes(wlen) orelse return false;
        const dlen = c.u16v() orelse return false;
        const data = alloc.alloc(f32, dlen) catch return false;
        var di: u16 = 0;
        while (di < dlen) : (di += 1) data[di] = c.f32v() orelse {
            alloc.free(data);
            return false;
        };
        const tiles = c.f32v() orelse {
            alloc.free(data);
            return false;
        };
        mats.append(alloc, .{ .key = key, .wgsl = wgsl, .data = data, .tiles = tiles }) catch {
            alloc.free(data);
            return false;
        };
    }
    _ = c.u32v() orelse return false; // ops byte length (advisory; we read to blob end)
    const ops_start = c.p;

    // ADOPT the loaded program as the live recorded program (req_2529). Loading a painting
    // then painting MORE on top must APPEND to it, so a later serialize returns the CUMULATIVE
    // work — not just this session's new strokes. Without this, replay painted the atlas but
    // left g_ops empty, so "load Painting 1, add a stroke, save Painting 2" dropped Painting 1's
    // strokes and reloading showed only the new stroke. Material order is preserved so the ops'
    // material indices stay valid; further painting dedups/extends g_mats from here.
    reset();
    for (mats.items) |m| {
        const k = alloc.dupe(u8, m.key) catch return false;
        const w = alloc.dupe(u8, m.wgsl) catch {
            alloc.free(k);
            return false;
        };
        const d = alloc.dupe(f32, m.data) catch {
            alloc.free(k);
            alloc.free(w);
            return false;
        };
        g_mats.append(alloc, .{ .key = k, .wgsl = w, .data = d, .tiles = m.tiles }) catch {
            alloc.free(k);
            alloc.free(w);
            alloc.free(d);
            return false;
        };
    }
    g_ops.appendSlice(alloc, blob[ops_start..]) catch return false;

    // Prepare the canvas: the caller already set detail (a mesh re-upload); wipe to default.
    // A replayed painting HAS a base (it was created with one), so activate it before the clear
    // lays it back under the strokes (req_2551).
    model_paint.activateBase();
    model_paint.clearAtlas();

    g_recording = false;
    defer g_recording = true;
    var mat_active = false;
    var rgb: [3]u8 = .{ 255, 255, 255 };
    while (c.p < c.b.len) {
        const tag = c.u8v() orelse break;
        switch (tag) {
            OP_INK_COLOR => {
                const cc = c.bytes(3) orelse return false;
                rgb = .{ cc[0], cc[1], cc[2] };
                mat_active = false;
                model_paint.clearMaterialInk();
            },
            OP_INK_MATERIAL => {
                const idx = c.u16v() orelse return false;
                if (idx >= mats.items.len) return false;
                mat_active = bakeBorrowed(mats.items[idx]); // fall back to colour if the bake fails
            },
            OP_DAB => {
                const face = c.u32v() orelse return false;
                const u = c.f32v() orelse return false;
                const v = c.f32v() orelse return false;
                const radius = c.f32v() orelse return false;
                const flow = c.f32v() orelse return false;
                if (mat_active) model_paint.paintStampTex(face, u, v, radius, flow) else model_paint.paintStamp(face, u, v, radius, .{ rgb[0], rgb[1], rgb[2], 255 }, flow);
            },
            OP_FILL => {
                const face = c.u32v() orelse return false;
                if (mat_active) model_paint.paintFaceTex(face) else model_paint.paintFace(face, .{ rgb[0], rgb[1], rgb[2], 255 });
            },
            else => return false,
        }
    }
    model_paint.clearMaterialInk();
    return true;
}
