//! paint_program.zig — a model painting stored as its STROKE PROGRAM, not its pixels.
//!
//! GUIDING_LIGHT ("Worked Example: painted textures"): store the recipe (the strokes
//! + their params), never the rasterized atlas. Every authoring dab/fill on the model
//! paint target is APPENDED here as a resolution-independent op. Serialized, this tiny
//! program IS the durable form; replayed once at load it rebuilds the atlas exactly.
//!
//! req_2672 grows the program into the painter's WHOLE editing model:
//!
//!   • STROKES — ops are grouped into strokes (pointer-down→up = one stroke; a fill
//!     click = one stroke). Each committed stroke is ONE undo unit in the stroke
//!     journal (undoStroke/redoStroke): undo drops the last unit and RE-RUNS the
//!     program onto the atlas — the program is the truth, so undo is replay, never a
//!     pixel diff. A baseline atlas snapshot (taken before the first stroke) anchors
//!     the replay so paint that predates the program (part tints, the atlas base)
//!     survives every undo. The baseline is a runtime cache only — persistence stays
//!     strokes-only.
//!
//!   • LAYERS — the stroke program IS the layer system (USER ASK req_2672: "i want to
//!     write some stupid shit like 'i like it' first and then fuck off everything
//!     behind it"). A layer is an ordered stroke GROUP (id, name, visible); every
//!     stroke records the ACTIVE layer's id; replay runs layers bottom→top, skipping
//!     invisible ones. Delete/reorder/merge are pure program edits + one replay — no
//!     pixel-layer compositor anywhere. Structural layer ops journal as undo units in
//!     the same stroke journal, so undoing a layer-delete restores it wholesale.
//!     Visibility is the exception (req_2752): the eye is VIEW state — never journaled,
//!     and undo/redo carry the live eye toggles across (see adoptSnapshot).
//!
//!   • HIDE-STABLE KEYS — v1 recorded dabs by DISPLAYED face index, which shifts when
//!     a part hides (a program saved while a part was hidden replayed misindexed).
//!     v2 ops key by (AUTHORED GROUP id, intra-group face ordinal): group ids survive
//!     hide/show verbatim and a group's faces keep their relative order, so the key
//!     resolves to the right face in whatever face order the mesh currently displays.
//!     v1 blobs still load (converted to one "Layer 1" stroke on the current mesh).
//!
//! Why it beats storing the atlas: a dither brush's scatter is the worst case for RLE
//! and bloats a PNG, but it is generated by a few numbers — so we keep the numbers (the
//! ops), never the scatter (the pixels). Shader inks embed their WGSL + params, so the
//! blob is SELF-CONTAINED: replay re-bakes the material with no catalog.
//!
//! Recording lives in the authoring entry points (3d.zig paintStampAt/paintAt); replay
//! calls model_paint directly and suppresses recording, so it never re-records itself.

const std = @import("std");
const host_io = @import("../host_io.zig");
const model_paint = @import("model_paint.zig");
const model_source = @import("model_source.zig");
const material_tex = @import("material_tex.zig");
const paint_ops = @import("paint_ops.zig");

const alloc = std.heap.c_allocator;

const OP_INK_COLOR = paint_ops.OP_INK_COLOR; // r,g,b
const OP_INK_MATERIAL = paint_ops.OP_INK_MATERIAL; // matIndex u16
const OP_DAB = paint_ops.OP_DAB; // v2: group u32, ord u32, u f32, v f32, radius f32, flow f32
const OP_FILL = paint_ops.OP_FILL; // v2: group u32, ord u32
// v3 (req_2831): OP_DAB + the brush footprint (the BRUSH_SHAPE_ID contract) — kind u32,
// hardness f32, angle_rad f32, aspect f32, scatter f32. Older blobs never contain it,
// so v1/v2 replay is untouched; newer blobs are version-gated at the header.
const OP_DAB_SHAPED = paint_ops.OP_DAB_SHAPED;
const MAGIC = [4]u8{ 'R', 'J', 'P', 'P' };
const VERSION: u16 = 3; // v1 = flat face-indexed stream, v2 = hide-stable keys — both readable
const MAT_BAKE_SIZE: u32 = 256;

/// Ungrouped faces carry this group key; the ordinal is then the raw face index.
const NO_GROUP: u32 = std.math.maxInt(u32);

// A referenced shader ink, content-addressed by key. WGSL + params are stored so the
// program re-bakes the material at load with no catalog dependency.
const MatRecipe = struct { key: []u8, wgsl: []u8, data: []f32, tiles: f32 };

// ── Program state: layers + strokes ─────────────────────────────────────────────────
const Layer = struct { id: u32, name: []u8, visible: bool };
const Stroke = struct { layer: u32, ops: []u8 };

var g_layers: std.ArrayList(Layer) = .empty; // bottom→top: the replay/composite order
var g_active_layer: u32 = 0; // the layer id new strokes land on
var g_next_layer_id: u32 = 1;
var g_strokes: std.ArrayList(Stroke) = .empty; // committed strokes, chronological
var g_mats: std.ArrayList(MatRecipe) = .empty;

// The OPEN stroke unit (between pointer-down and the stroke-end door). Ops accumulate
// here and commit as ONE stroke; a unit auto-opens on the first recorded op.
var g_open: std.ArrayList(u8) = .empty;
var g_open_live: bool = false;
var g_open_label: []const u8 = "stroke";

// Faces already fill-recorded in the OPEN unit with the CURRENT ink — a repeat fill of
// the same face is a hard-overwrite no-op, so recording it again only bloats the blob
// (the 69k-fill keyboard). Cleared on unit open, on any ink change, and on any dab
// (a dab layered on a face makes the next fill of it meaningful again).
var g_open_fill_seen: std.AutoHashMapUnmanaged(u64, void) = .{};

// Active-ink dedup so an INK op is emitted only when the ink actually changes. Reset at
// every stroke open so each stroke's op stream is SELF-CONTAINED (layer reorder/skip
// replays strokes out of recording order — each must start with its own ink).
var g_have_active: bool = false;
var g_active_is_mat: bool = false;
var g_active_mat: u16 = 0;
var g_active_rgb: [3]u8 = .{ 0, 0, 0 };

var g_recording: bool = true; // false during replay, so replay never re-records

// ── Baseline atlas (runtime-only undo anchor; never persisted) ──────────────────────
// Captured once, right before the first program op lands (or right after a loaded
// program's base-clear). replayAll restores it first, so paint that is NOT in the
// program — part tints laid at load, the chosen atlas base — survives undo instead of
// being wiped by the clear. Dropped on reset; a dimension mismatch (detail changed)
// falls back to clearAtlas + base.
var g_baseline: ?[]u8 = null;

fn dropBaseline() void {
    if (g_baseline) |b| alloc.free(b);
    g_baseline = null;
}

fn captureBaselineIfNeeded() void {
    if (g_baseline != null) return;
    const a = model_paint.atlas() orelse return;
    g_baseline = alloc.dupe(u8, a.rgba) catch null;
}

fn forceBaselineCapture() void {
    dropBaseline();
    captureBaselineIfNeeded();
}

// ── Hide-stable face keys: (authored group, intra-group ordinal) ────────────────────
// The ordinal cache maps displayed face → its rank among faces sharing its authored
// group, in display order. Rebuilt lazily whenever the face count changes; 3d.zig also
// invalidates it on every layout/grouping refresh (groups can change at a stable count).
var g_ord_cache: ?[]u32 = null;

pub fn invalidateFaceKeys() void {
    if (g_ord_cache) |c| alloc.free(c);
    g_ord_cache = null;
}

fn faceOrdinals() ?[]const u32 {
    const fc = model_paint.faceCount();
    if (fc == 0) return null;
    if (g_ord_cache) |c| {
        if (c.len == fc) return c;
        invalidateFaceKeys();
    }
    const ords = alloc.alloc(u32, fc) catch return null;
    var counts = std.AutoHashMapUnmanaged(u32, u32){};
    defer counts.deinit(alloc);
    var f: u32 = 0;
    while (f < fc) : (f += 1) {
        const g = model_source.faceGroupOf(f);
        if (g == model_source.NO_FACE_GROUP) {
            ords[f] = f; // ungrouped: the raw index is the (only) stable key we have
            continue;
        }
        const gop = counts.getOrPut(alloc, g) catch {
            ords[f] = f;
            continue;
        };
        if (!gop.found_existing) gop.value_ptr.* = 0;
        ords[f] = gop.value_ptr.*;
        gop.value_ptr.* += 1;
    }
    g_ord_cache = ords;
    return ords;
}

const FaceKey = struct { group: u32, ord: u32 };

fn faceKeyOf(face: u32) FaceKey {
    const grp = model_source.faceGroupOf(face);
    if (grp == model_source.NO_FACE_GROUP) return .{ .group = NO_GROUP, .ord = face };
    const ords = faceOrdinals() orelse return .{ .group = NO_GROUP, .ord = face };
    if (face >= ords.len) return .{ .group = NO_GROUP, .ord = face };
    return .{ .group = grp, .ord = ords[face] };
}

// Replay-side resolver: (group, ord) → the face displayed NOW. Built once per replay.
const Resolver = struct {
    map: std.AutoHashMapUnmanaged(u64, u32) = .{},
    fn deinit(self: *Resolver) void {
        self.map.deinit(alloc);
    }
};

fn resolverKey(group: u32, ord: u32) u64 {
    return (@as(u64, group) << 32) | ord;
}

fn buildResolver() Resolver {
    var res = Resolver{};
    const fc = model_paint.faceCount();
    var counts = std.AutoHashMapUnmanaged(u32, u32){};
    defer counts.deinit(alloc);
    var f: u32 = 0;
    while (f < fc) : (f += 1) {
        const g = model_source.faceGroupOf(f);
        if (g == model_source.NO_FACE_GROUP) continue; // resolved as raw index below
        const gop = counts.getOrPut(alloc, g) catch continue;
        if (!gop.found_existing) gop.value_ptr.* = 0;
        res.map.put(alloc, resolverKey(g, gop.value_ptr.*), f) catch {};
        gop.value_ptr.* += 1;
    }
    return res;
}

/// The face a recorded key lands on TODAY, or null (its part is hidden / deleted —
/// the op skips this replay and comes back when the faces do).
fn resolveFace(res: *const Resolver, group: u32, ord: u32) ?u32 {
    if (group == NO_GROUP) {
        return if (ord < model_paint.faceCount()) ord else null;
    }
    return res.map.get(resolverKey(group, ord));
}

// ── Memory helpers ──────────────────────────────────────────────────────────────────
fn freeMats() void {
    for (g_mats.items) |m| {
        alloc.free(m.key);
        alloc.free(m.wgsl);
        alloc.free(m.data);
    }
    g_mats.clearRetainingCapacity();
}

fn freeLayerList(list: *std.ArrayList(Layer)) void {
    for (list.items) |l| alloc.free(l.name);
    list.clearRetainingCapacity();
}

fn freeStrokeList(list: *std.ArrayList(Stroke)) void {
    for (list.items) |s| alloc.free(s.ops);
    list.clearRetainingCapacity();
}

// ── Layer table ─────────────────────────────────────────────────────────────────────
fn layerIndexOf(id: u32) ?usize {
    for (g_layers.items, 0..) |l, i| {
        if (l.id == id) return i;
    }
    return null;
}

fn appendLayer(name_src: ?[]const u8) ?u32 {
    const id = g_next_layer_id;
    var buf: [24]u8 = undefined;
    const fallback = std.fmt.bufPrint(&buf, "Layer {d}", .{id}) catch "Layer";
    const name = alloc.dupe(u8, name_src orelse fallback) catch return null;
    g_layers.append(alloc, .{ .id = id, .name = name, .visible = true }) catch {
        alloc.free(name);
        return null;
    };
    g_next_layer_id += 1;
    return id;
}

/// A program always paints ONTO a layer — materialize "Layer 1" the moment anything
/// needs one (first stroke, first layer op, a v1 blob load).
fn ensureLayers() void {
    if (g_layers.items.len > 0) return;
    if (appendLayer(null)) |id| g_active_layer = id;
}

// ── Layer carry across an EDIT mesh replace ─────────────────────────────────────────
// Every topology op replaces the resident mesh, which resets this module (strokes can't
// survive a topology change — the atlas texel carry preserves the pixels). The layer
// TABLE is the user's organizational setup though, and losing it to an eye toggle would
// be gratuitous: 3d.zig stashes it here right before the replace; the reset consumes it.
var g_carry_layers: ?[]Layer = null;
var g_carry_active: u32 = 0;
var g_carry_next: u32 = 1;

pub fn snapshotLayersForCarry() void {
    dropLayerCarry();
    if (g_layers.items.len == 0) return;
    const copy = alloc.alloc(Layer, g_layers.items.len) catch return;
    var n: usize = 0;
    for (g_layers.items) |l| {
        const nm = alloc.dupe(u8, l.name) catch break;
        copy[n] = .{ .id = l.id, .name = nm, .visible = l.visible };
        n += 1;
    }
    if (n != copy.len) {
        for (copy[0..n]) |l| alloc.free(l.name);
        alloc.free(copy);
        return;
    }
    g_carry_layers = copy;
    g_carry_active = g_active_layer;
    g_carry_next = g_next_layer_id;
}

fn dropLayerCarry() void {
    if (g_carry_layers) |ls| {
        for (ls) |l| alloc.free(l.name);
        alloc.free(ls);
    }
    g_carry_layers = null;
}

// ── The stroke journal (undo/redo) ──────────────────────────────────────────────────
// Each unit (committed stroke, structural layer op) pushes a deep-copy SNAPSHOT of the
// program state taken BEFORE the unit — layers, active id, strokes. Undo swaps the live
// state with the top snapshot and replays; the program is small (numbers, not pixels),
// so whole-state snapshots are cheap and uniformly correct for every op kind.
const Snapshot = struct {
    label: []const u8, // static string — the unit that FOLLOWED this state
    layers: []Layer,
    active: u32,
    next_id: u32,
    strokes: []Stroke,
};

const JOURNAL_CAP = 64;
const JOURNAL_BYTE_BUDGET: usize = 32 * 1024 * 1024;

var g_undo_snaps: std.ArrayList(Snapshot) = .empty;
var g_redo_snaps: std.ArrayList(Snapshot) = .empty;

fn snapshotBytes(s: *const Snapshot) usize {
    var total: usize = @sizeOf(Snapshot);
    for (s.layers) |l| total += @sizeOf(Layer) + l.name.len;
    for (s.strokes) |st| total += @sizeOf(Stroke) + st.ops.len;
    return total;
}

fn freeSnapshot(s: *Snapshot) void {
    for (s.layers) |l| alloc.free(l.name);
    alloc.free(s.layers);
    for (s.strokes) |st| alloc.free(st.ops);
    alloc.free(s.strokes);
}

fn freeSnapshotStack(stack: *std.ArrayList(Snapshot)) void {
    for (stack.items) |*s| freeSnapshot(s);
    stack.clearRetainingCapacity();
}

fn snapshotCurrent(label: []const u8) ?Snapshot {
    const layers = alloc.alloc(Layer, g_layers.items.len) catch return null;
    var ln: usize = 0;
    for (g_layers.items) |l| {
        const nm = alloc.dupe(u8, l.name) catch break;
        layers[ln] = .{ .id = l.id, .name = nm, .visible = l.visible };
        ln += 1;
    }
    if (ln != layers.len) {
        for (layers[0..ln]) |l| alloc.free(l.name);
        alloc.free(layers);
        return null;
    }
    const strokes = alloc.alloc(Stroke, g_strokes.items.len) catch {
        for (layers) |l| alloc.free(l.name);
        alloc.free(layers);
        return null;
    };
    var sn: usize = 0;
    for (g_strokes.items) |st| {
        const ops = alloc.dupe(u8, st.ops) catch break;
        strokes[sn] = .{ .layer = st.layer, .ops = ops };
        sn += 1;
    }
    if (sn != strokes.len) {
        for (strokes[0..sn]) |st| alloc.free(st.ops);
        alloc.free(strokes);
        for (layers) |l| alloc.free(l.name);
        alloc.free(layers);
        return null;
    }
    return .{ .label = label, .layers = layers, .active = g_active_layer, .next_id = g_next_layer_id, .strokes = strokes };
}

/// Push the CURRENT state as the pre-state of the unit about to apply. New units clear
/// the redo stack (standard journal semantics). Trimmed oldest-first by count + bytes.
fn pushUndo(label: []const u8) void {
    const snap = snapshotCurrent(label) orelse return;
    freeSnapshotStack(&g_redo_snaps);
    g_undo_snaps.append(alloc, snap) catch {
        var s = snap;
        freeSnapshot(&s);
        return;
    };
    var total: usize = 0;
    for (g_undo_snaps.items) |*s| total += snapshotBytes(s);
    while (g_undo_snaps.items.len > JOURNAL_CAP or (total > JOURNAL_BYTE_BUDGET and g_undo_snaps.items.len > 1)) {
        var old = g_undo_snaps.orderedRemove(0);
        total -= snapshotBytes(&old);
        freeSnapshot(&old);
    }
}

/// Adopt a snapshot as the live program state (takes ownership of its allocations).
/// Visibility is VIEW state, not history (req_2752): a layer that exists on both sides
/// keeps its LIVE eye toggle — undo/redo restore strokes/structure, never flip the eye.
fn adoptSnapshot(s: Snapshot) void {
    for (s.layers) |*l| {
        if (layerIndexOf(l.id)) |cur| l.visible = g_layers.items[cur].visible;
    }
    freeLayerList(&g_layers);
    g_layers.appendSlice(alloc, s.layers) catch {
        for (s.layers) |l| alloc.free(l.name);
    };
    alloc.free(s.layers);
    freeStrokeList(&g_strokes);
    g_strokes.appendSlice(alloc, s.strokes) catch {
        for (s.strokes) |st| alloc.free(st.ops);
    };
    alloc.free(s.strokes);
    g_active_layer = s.active;
    g_next_layer_id = s.next_id;
}

pub fn historyCounts() [2]u32 {
    return .{ @intCast(g_undo_snaps.items.len), @intCast(g_redo_snaps.items.len) };
}

pub fn undoLabel() []const u8 {
    if (g_undo_snaps.items.len == 0) return "";
    return g_undo_snaps.items[g_undo_snaps.items.len - 1].label;
}

pub fn redoLabel() []const u8 {
    if (g_redo_snaps.items.len == 0) return "";
    return g_redo_snaps.items[g_redo_snaps.items.len - 1].label;
}

/// Undo one unit: swap the live program with the top pre-state snapshot and re-run the
/// program onto the atlas. Commits any open stroke first (an undo mid-drag undoes THAT
/// stroke — never a stale older one). False when there's nothing to undo.
pub fn undoStroke() bool {
    _ = endStrokeUnit();
    if (g_undo_snaps.items.len == 0) return false;
    const pre = g_undo_snaps.items[g_undo_snaps.items.len - 1];
    g_undo_snaps.items.len -= 1;
    if (snapshotCurrent(pre.label)) |cur| {
        g_redo_snaps.append(alloc, cur) catch {
            var c = cur;
            freeSnapshot(&c);
        };
    }
    adoptSnapshot(pre);
    replayAll();
    return true;
}

pub fn redoStroke() bool {
    _ = endStrokeUnit();
    if (g_redo_snaps.items.len == 0) return false;
    const post = g_redo_snaps.items[g_redo_snaps.items.len - 1];
    g_redo_snaps.items.len -= 1;
    if (snapshotCurrent(post.label)) |cur| {
        g_undo_snaps.append(alloc, cur) catch {
            var c = cur;
            freeSnapshot(&c);
        };
    }
    adoptSnapshot(post);
    replayAll();
    return true;
}

// ── Reset / lifecycle ───────────────────────────────────────────────────────────────
/// Wipe the recorded program (new paint target, or a cleared painting). Consumes a
/// pending layer-table carry (snapshotLayersForCarry) so an edit-mesh replace keeps the
/// user's layer setup while dropping the strokes the new topology invalidated.
pub fn reset() void {
    g_open.clearRetainingCapacity();
    g_open_live = false;
    freeStrokeList(&g_strokes);
    freeLayerList(&g_layers);
    freeSnapshotStack(&g_undo_snaps);
    freeSnapshotStack(&g_redo_snaps);
    freeMats();
    g_have_active = false;
    g_active_is_mat = false;
    dropBaseline();
    invalidateFaceKeys();
    g_active_layer = 0;
    g_next_layer_id = 1;
    if (g_carry_layers) |ls| {
        g_layers.appendSlice(alloc, ls) catch {
            for (ls) |l| alloc.free(l.name);
            alloc.free(ls);
            g_carry_layers = null;
            return;
        };
        alloc.free(ls);
        g_carry_layers = null;
        g_active_layer = g_carry_active;
        g_next_layer_id = g_carry_next;
        if (layerIndexOf(g_active_layer) == null and g_layers.items.len > 0) {
            g_active_layer = g_layers.items[g_layers.items.len - 1].id;
        }
    }
}

// ── Recording ───────────────────────────────────────────────────────────────────────
fn appendOpenU16(v: u16) void {
    var b: [2]u8 = undefined;
    std.mem.writeInt(u16, &b, v, .little);
    g_open.appendSlice(alloc, &b) catch {};
}
fn appendOpenU32(v: u32) void {
    var b: [4]u8 = undefined;
    std.mem.writeInt(u32, &b, v, .little);
    g_open.appendSlice(alloc, &b) catch {};
}
fn appendOpenF32(v: f32) void {
    appendOpenU32(@bitCast(v));
}

/// Register (dedup by key) a shader ink and mark it active. Called when JS sets a bucket;
/// the WGSL + params are captured so the program is self-contained.
pub fn activateMaterial(key: []const u8, wgsl: []const u8, data: []const f32, tiles: f32) void {
    var idx: u16 = 0;
    var found = false;
    for (g_mats.items, 0..) |m, i| {
        if (std.mem.eql(u8, m.key, key)) {
            idx = @intCast(i);
            found = true;
            break;
        }
    }
    if (!found) {
        const k = alloc.dupe(u8, key) catch return;
        const w = alloc.dupe(u8, wgsl) catch {
            alloc.free(k);
            return;
        };
        const d = alloc.dupe(f32, data) catch {
            alloc.free(k);
            alloc.free(w);
            return;
        };
        g_mats.append(alloc, .{ .key = k, .wgsl = w, .data = d, .tiles = tiles }) catch {
            alloc.free(k);
            alloc.free(w);
            alloc.free(d);
            return;
        };
        idx = @intCast(g_mats.items.len - 1);
    }
    g_active_is_mat = true;
    g_active_mat = idx;
    g_have_active = false; // force the next dab to emit this ink
}

/// The active ink returns to flat colour (JS cleared the material).
pub fn deactivateMaterial() void {
    g_active_is_mat = false;
    g_have_active = false;
}

fn emitInk(mat: bool, rgb: [3]u8) void {
    if (mat) {
        if (!g_have_active or !g_active_is_mat) {
            g_open.append(alloc, OP_INK_MATERIAL) catch {};
            appendOpenU16(g_active_mat);
            g_open_fill_seen.clearRetainingCapacity();
            g_have_active = true;
            g_active_is_mat = true;
        }
    } else if (!g_have_active or g_active_is_mat or !std.mem.eql(u8, &g_active_rgb, &rgb)) {
        g_open.append(alloc, OP_INK_COLOR) catch {};
        g_open.appendSlice(alloc, &rgb) catch {};
        g_open_fill_seen.clearRetainingCapacity();
        g_have_active = true;
        g_active_is_mat = false;
        g_active_rgb = rgb;
    }
}

/// Called by the authoring entry points (3d.zig paintStampAt/paintAt) BEFORE the first
/// texel of a recorded gesture lands. The undo baseline must hold the PRE-stroke atlas;
/// recordDab/recordFill fire only AFTER the dab already painted, so anchoring there
/// leaked the first dab's texels into the baseline (they survived layer hide/delete).
pub fn beginRecordedOp() void {
    if (!g_recording) return;
    ensureLayers();
    captureBaselineIfNeeded();
}

fn openUnit(label: []const u8) void {
    if (g_open_live) return;
    ensureLayers();
    captureBaselineIfNeeded(); // anchor undo BEFORE the first program op mutates the atlas
    g_open.clearRetainingCapacity();
    g_open_fill_seen.clearRetainingCapacity();
    g_open_live = true;
    g_open_label = label;
    g_have_active = false; // each stroke's op stream re-states its ink (self-contained)
}

/// Record one free-form dab, keyed hide-stable (authored group + intra-group ordinal).
pub fn recordDab(face: u32, u: f32, v: f32, radius: f32, flow: f32, mat: bool, rgb: [3]u8) void {
    if (!g_recording) return;
    openUnit("stroke");
    emitInk(mat, rgb);
    g_open_fill_seen.clearRetainingCapacity();
    const key = faceKeyOf(face);
    g_open.append(alloc, OP_DAB) catch {};
    appendOpenU32(key.group);
    appendOpenU32(key.ord);
    appendOpenF32(u);
    appendOpenF32(v);
    appendOpenF32(radius);
    appendOpenF32(flow);
}

/// Record a SHAPED dab (req_2831): OP_DAB's fields + the brush footprint spec, so
/// program replay reproduces rakes/fans/sprays exactly (grain seeds derive from u/v).
pub fn recordDabShaped(face: u32, u: f32, v: f32, radius: f32, flow: f32, mat: bool, rgb: [3]u8, spec: model_paint.BrushShape) void {
    if (!g_recording) return;
    openUnit("stroke");
    emitInk(mat, rgb);
    g_open_fill_seen.clearRetainingCapacity();
    const key = faceKeyOf(face);
    g_open.append(alloc, OP_DAB_SHAPED) catch {};
    appendOpenU32(key.group);
    appendOpenU32(key.ord);
    appendOpenF32(u);
    appendOpenF32(v);
    appendOpenF32(radius);
    appendOpenF32(flow);
    appendOpenU32(spec.kind);
    appendOpenF32(spec.hardness);
    appendOpenF32(spec.angle_rad);
    appendOpenF32(spec.aspect);
    appendOpenF32(spec.scatter);
}

/// Record one whole-face fill (same hide-stable key).
pub fn recordFill(face: u32, mat: bool, rgb: [3]u8) void {
    if (!g_recording) return;
    openUnit("fill");
    emitInk(mat, rgb);
    const key = faceKeyOf(face);
    const seen_key = resolverKey(key.group, key.ord);
    if (g_open_fill_seen.contains(seen_key)) return; // idempotent repeat — record nothing
    g_open_fill_seen.put(alloc, seen_key, {}) catch {}; // OOM: fall through, over-record safely
    g_open.append(alloc, OP_FILL) catch {};
    appendOpenU32(key.group);
    appendOpenU32(key.ord);
}

/// Commit the open stroke unit: pointer-up (or any journal/serialize boundary). The
/// pre-state snapshot journals FIRST — the open ops aren't in g_strokes yet, so the
/// current committed state IS the pre-state. False when nothing was recorded.
pub fn endStrokeUnit() bool {
    if (!g_open_live) return false;
    g_open_live = false;
    if (g_open.items.len == 0) return false;
    const ops = alloc.dupe(u8, g_open.items) catch {
        g_open.clearRetainingCapacity();
        return false;
    };
    g_open.clearRetainingCapacity();
    pushUndo(g_open_label);
    g_strokes.append(alloc, .{ .layer = g_active_layer, .ops = ops }) catch {
        alloc.free(ops);
        return false;
    };
    return true;
}

pub fn isEmpty() bool {
    return g_strokes.items.len == 0 and (!g_open_live or g_open.items.len == 0);
}

// ── Layer ops ───────────────────────────────────────────────────────────────────────
pub const LayerInfo = struct { id: u32, name: []const u8, visible: bool, strokes: u32 };

pub fn layerCount() usize {
    return g_layers.items.len;
}

pub fn layerInfoAt(i: usize) LayerInfo {
    const l = g_layers.items[i];
    var n: u32 = 0;
    for (g_strokes.items) |st| {
        if (st.layer == l.id) n += 1;
    }
    return .{ .id = l.id, .name = l.name, .visible = l.visible, .strokes = n };
}

pub fn activeLayerId() u32 {
    return g_active_layer;
}

/// Add a fresh layer on TOP and make it active. Journaled. Returns the new id (0 = fail).
/// No replay — an empty layer changes no pixels.
pub fn layerAdd() u32 {
    _ = endStrokeUnit();
    ensureLayers();
    pushUndo("add layer");
    const id = appendLayer(null) orelse return 0;
    g_active_layer = id;
    return id;
}

/// Delete a layer AND its strokes (the "fuck off everything behind it" verb). Journaled —
/// undo restores the layer and every stroke, because the program is the truth. Replays.
pub fn layerDelete(id: u32) bool {
    _ = endStrokeUnit();
    const idx = layerIndexOf(id) orelse return false;
    pushUndo("delete layer");
    const removed = g_layers.orderedRemove(idx);
    alloc.free(removed.name);
    var w: usize = 0;
    for (g_strokes.items) |st| {
        if (st.layer == id) {
            alloc.free(st.ops);
            continue;
        }
        g_strokes.items[w] = st;
        w += 1;
    }
    g_strokes.items.len = w;
    if (g_layers.items.len == 0) ensureLayers(); // painting always has a target layer
    if (layerIndexOf(g_active_layer) == null) {
        g_active_layer = g_layers.items[g_layers.items.len - 1].id;
    }
    replayAll();
    return true;
}

/// Move a layer one step toward the top (up=true → composites later) or bottom. Journaled.
pub fn layerMove(id: u32, up: bool) bool {
    _ = endStrokeUnit();
    const idx = layerIndexOf(id) orelse return false;
    if (up and idx + 1 >= g_layers.items.len) return false;
    if (!up and idx == 0) return false;
    pushUndo("reorder layer");
    const other = if (up) idx + 1 else idx - 1;
    const tmp = g_layers.items[idx];
    g_layers.items[idx] = g_layers.items[other];
    g_layers.items[other] = tmp;
    replayAll();
    return true;
}

/// Show/hide a layer's strokes. NOT journaled (req_2752) — visibility is a VIEW toggle,
/// not a program edit: no stroke is added or removed, the eye just filters the composite.
/// Replays (the atlas is derived, so the composite must re-lay), and adoptSnapshot keeps
/// the live eye state through undo/redo so history never flips what you're looking at.
pub fn layerSetVisible(id: u32, on: bool) bool {
    _ = endStrokeUnit();
    const idx = layerIndexOf(id) orelse return false;
    if (g_layers.items[idx].visible == on) return true;
    g_layers.items[idx].visible = on;
    replayAll();
    return true;
}

/// Route new strokes to this layer. NOT journaled — picking a target changes no pixels,
/// and journaling it would bury real undo units under selection noise.
pub fn layerSetActive(id: u32) bool {
    if (layerIndexOf(id) == null) return false;
    _ = endStrokeUnit();
    g_active_layer = id;
    return true;
}

/// Rename in place. NOT journaled (metadata, no composite change).
pub fn layerRename(id: u32, name: []const u8) bool {
    const idx = layerIndexOf(id) orelse return false;
    const trimmed = std.mem.trim(u8, name, " \t\r\n");
    if (trimmed.len == 0) return false;
    const nm = alloc.dupe(u8, trimmed[0..@min(trimmed.len, 48)]) catch return false;
    alloc.free(g_layers.items[idx].name);
    g_layers.items[idx].name = nm;
    return true;
}

/// Fold a layer's strokes into the layer BELOW it and drop the layer. The merged strokes
/// keep their composite position: below's strokes stay first, the merged layer's follow.
/// Journaled; replays. False on the bottom layer (nothing below to merge into).
pub fn layerMergeDown(id: u32) bool {
    _ = endStrokeUnit();
    const idx = layerIndexOf(id) orelse return false;
    if (idx == 0) return false;
    pushUndo("merge layers");
    const below = g_layers.items[idx - 1].id;
    // Rebuild the stroke list so the merged layer's composite order survives inside ONE
    // layer id: others (chronological) + below's strokes + the merged layer's strokes.
    var rebuilt: std.ArrayList(Stroke) = .empty;
    var below_strokes: std.ArrayList(Stroke) = .empty;
    var top_strokes: std.ArrayList(Stroke) = .empty;
    defer rebuilt.deinit(alloc);
    defer below_strokes.deinit(alloc);
    defer top_strokes.deinit(alloc);
    var ok = true;
    for (g_strokes.items) |st| {
        if (st.layer == below) {
            below_strokes.append(alloc, st) catch {
                ok = false;
            };
        } else if (st.layer == id) {
            top_strokes.append(alloc, .{ .layer = below, .ops = st.ops }) catch {
                ok = false;
            };
        } else {
            rebuilt.append(alloc, st) catch {
                ok = false;
            };
        }
    }
    if (ok) {
        rebuilt.appendSlice(alloc, below_strokes.items) catch {
            ok = false;
        };
    }
    if (ok) {
        rebuilt.appendSlice(alloc, top_strokes.items) catch {
            ok = false;
        };
    }
    if (!ok or rebuilt.items.len != g_strokes.items.len) {
        // Allocation trouble mid-rebuild — keep the original list untouched (the pushed
        // journal entry is a harmless no-op undo) rather than risk dropped strokes.
        return false;
    }
    @memcpy(g_strokes.items, rebuilt.items);
    const removed = g_layers.orderedRemove(idx);
    alloc.free(removed.name);
    if (g_active_layer == id) g_active_layer = below;
    replayAll();
    return true;
}

// ── Replay ──────────────────────────────────────────────────────────────────────────
const Cursor = struct {
    b: []const u8,
    p: usize = 0,
    fn u8v(c: *Cursor) ?u8 {
        if (c.p >= c.b.len) return null;
        const v = c.b[c.p];
        c.p += 1;
        return v;
    }
    fn u16v(c: *Cursor) ?u16 {
        if (c.p + 2 > c.b.len) return null;
        const v = std.mem.readInt(u16, c.b[c.p..][0..2], .little);
        c.p += 2;
        return v;
    }
    fn u32v(c: *Cursor) ?u32 {
        if (c.p + 4 > c.b.len) return null;
        const v = std.mem.readInt(u32, c.b[c.p..][0..4], .little);
        c.p += 4;
        return v;
    }
    fn f32v(c: *Cursor) ?f32 {
        const u = c.u32v() orelse return null;
        return @bitCast(u);
    }
    fn bytes(c: *Cursor, n: usize) ?[]const u8 {
        if (c.p + n > c.b.len) return null;
        const s = c.b[c.p .. c.p + n];
        c.p += n;
        return s;
    }
};

fn bakeMatRecipe(key: []const u8, wgsl: []const u8, data: []const f32, tiles: f32) bool {
    const raw = material_tex.bakePixels(key, wgsl, data, MAT_BAKE_SIZE) orelse return false;
    defer std.heap.page_allocator.free(raw);
    if (raw.len < 8) return false;
    const w = std.mem.readInt(u32, raw[0..4], .little);
    const h = std.mem.readInt(u32, raw[4..8], .little);
    return model_paint.setMaterialInk(raw[8..], w, h, tiles);
}

// Ink state threads through the caller so consecutive strokes with the same ink don't
// re-bake a material per stroke. Ink ops only STATE intent; flushInk applies the last
// stated ink right before a dab/fill executes, so ink for fully-skipped ops never bakes.
const ReplayInk = struct {
    mat_active: bool = false,
    mat_idx: u16 = std.math.maxInt(u16),
    rgb: [3]u8 = .{ 255, 255, 255 },
    pending_mat: ?u16 = null,
    pending_rgb: ?[3]u8 = null,
};

fn flushInk(ink: *ReplayInk) void {
    if (ink.pending_rgb) |c| {
        ink.rgb = c;
        if (ink.mat_active) model_paint.clearMaterialInk();
        ink.mat_active = false;
        ink.pending_rgb = null;
    } else if (ink.pending_mat) |idx| {
        if (!ink.mat_active or ink.mat_idx != idx) {
            const m = g_mats.items[idx];
            ink.mat_active = bakeMatRecipe(m.key, m.wgsl, m.data, m.tiles);
            ink.mat_idx = idx;
        }
        ink.pending_mat = null;
    }
}

fn runStrokeOps(ops: []const u8, res: *const Resolver, ink: *ReplayInk, dabs: *usize) void {
    var skips: []usize = &.{};
    var skips_owned = false;
    if (paint_ops.redundantFillOffsets(alloc, ops)) |s| { skips = s; skips_owned = true; } else |_| {}
    defer if (skips_owned) alloc.free(skips);
    var skip_i: usize = 0;
    var c = Cursor{ .b = ops };
    while (c.p < c.b.len) {
        const op_off = c.p;
        const tag = c.u8v() orelse return;
        switch (tag) {
            OP_INK_COLOR => {
                const cc = c.bytes(3) orelse return;
                ink.pending_rgb = .{ cc[0], cc[1], cc[2] };
                ink.pending_mat = null;
            },
            OP_INK_MATERIAL => {
                const idx = c.u16v() orelse return;
                if (idx >= g_mats.items.len) return;
                ink.pending_mat = idx;
                ink.pending_rgb = null;
            },
            OP_DAB => {
                const group = c.u32v() orelse return;
                const ord = c.u32v() orelse return;
                const u = c.f32v() orelse return;
                const v = c.f32v() orelse return;
                const radius = c.f32v() orelse return;
                const flow = c.f32v() orelse return;
                dabs.* += 1;
                const face = resolveFace(res, group, ord) orelse continue;
                flushInk(ink);
                if (ink.mat_active) model_paint.paintStampTex(face, u, v, radius, flow) else model_paint.paintStamp(face, u, v, radius, .{ ink.rgb[0], ink.rgb[1], ink.rgb[2], 255 }, flow);
            },
            OP_DAB_SHAPED => {
                const group = c.u32v() orelse return;
                const ord = c.u32v() orelse return;
                const u = c.f32v() orelse return;
                const v = c.f32v() orelse return;
                const radius = c.f32v() orelse return;
                const flow = c.f32v() orelse return;
                const kind = c.u32v() orelse return;
                const hardness = c.f32v() orelse return;
                const angle = c.f32v() orelse return;
                const aspect = c.f32v() orelse return;
                const scatter = c.f32v() orelse return;
                dabs.* += 1;
                const face = resolveFace(res, group, ord) orelse continue;
                const spec = model_paint.BrushShape{ .kind = @intCast(@min(kind, 255)), .hardness = hardness, .angle_rad = angle, .aspect = aspect, .scatter = scatter };
                flushInk(ink);
                if (ink.mat_active) model_paint.paintStampTexShaped(face, u, v, radius, flow, spec) else model_paint.paintStampShaped(face, u, v, radius, .{ ink.rgb[0], ink.rgb[1], ink.rgb[2], 255 }, flow, spec);
            },
            OP_FILL => {
                const group = c.u32v() orelse return;
                const ord = c.u32v() orelse return;
                if (skip_i < skips.len and skips[skip_i] == op_off) { skip_i += 1; continue; }
                dabs.* += 1;
                const face = resolveFace(res, group, ord) orelse continue;
                // RGB-only fill: replay must not un-glass a face any more than the live fill does (req_2928).
                flushInk(ink);
                if (ink.mat_active) model_paint.paintFaceTex(face) else model_paint.paintFaceRgb(face, .{ ink.rgb[0], ink.rgb[1], ink.rgb[2] });
            },
            else => return,
        }
    }
}

/// Re-run the WHOLE program onto the atlas: restore the baseline (or clear + base), then
/// every visible layer's strokes bottom→top, strokes in chronological order inside each
/// layer. The one composite function behind undo/redo and every layer op. Logs its cost —
/// undo must never hitch the frame, and this line is the receipt.
pub fn replayAll() void {
    var timer = host_io.Timer.start() catch null;
    if (g_baseline) |b| {
        if (!model_paint.setAtlas(b)) model_paint.clearAtlas(); // detail changed → base fallback
    } else {
        model_paint.clearAtlas();
    }
    g_recording = false;
    defer g_recording = true;
    var res = buildResolver();
    defer res.deinit();
    var ink = ReplayInk{};
    var dabs: usize = 0;
    for (g_layers.items) |lay| {
        if (!lay.visible) continue;
        for (g_strokes.items) |st| {
            if (st.layer != lay.id) continue;
            runStrokeOps(st.ops, &res, &ink, &dabs);
        }
    }
    // Leave the LIVE brush ink the way the user had it — a replay that silently
    // switched the brush to the last replayed ink would betray the next stroke.
    if (g_active_is_mat and g_active_mat < g_mats.items.len) {
        const m = g_mats.items[g_active_mat];
        _ = bakeMatRecipe(m.key, m.wgsl, m.data, m.tiles);
    } else {
        model_paint.clearMaterialInk();
    }
    if (timer) |*t| {
        const ms = @as(f64, @floatFromInt(t.read())) / 1_000_000.0;
        std.debug.print("[paint-journal] replay: {d} strokes / {d} ops in {d:.2} ms\n", .{ g_strokes.items.len, dabs, ms });
    }
}

// ── Serialize ───────────────────────────────────────────────────────────────────────
fn u16le(v: u16) [2]u8 {
    var b: [2]u8 = undefined;
    std.mem.writeInt(u16, &b, v, .little);
    return b;
}
fn u32le(v: u32) [4]u8 {
    var b: [4]u8 = undefined;
    std.mem.writeInt(u32, &b, v, .little);
    return b;
}

// Build the v2 blob body; any allocation error propagates so serialize() can free cleanly.
fn writeBlob(buf: *std.ArrayList(u8)) !void {
    try buf.appendSlice(alloc, &MAGIC);
    try buf.appendSlice(alloc, &u16le(VERSION));
    try buf.appendSlice(alloc, &u16le(@intCast(model_paint.detail())));
    try buf.appendSlice(alloc, &u32le(model_paint.faceCount()));
    try buf.appendSlice(alloc, &u16le(@intCast(g_mats.items.len)));
    for (g_mats.items) |m| {
        try buf.appendSlice(alloc, &u16le(@intCast(m.key.len)));
        try buf.appendSlice(alloc, m.key);
        try buf.appendSlice(alloc, &u32le(@intCast(m.wgsl.len)));
        try buf.appendSlice(alloc, m.wgsl);
        try buf.appendSlice(alloc, &u16le(@intCast(m.data.len)));
        for (m.data) |f| try buf.appendSlice(alloc, &u32le(@bitCast(f)));
        try buf.appendSlice(alloc, &u32le(@bitCast(m.tiles)));
    }
    // Layer table (bottom→top) + the active id, then the stroke list.
    try buf.appendSlice(alloc, &u16le(@intCast(g_layers.items.len)));
    for (g_layers.items) |l| {
        try buf.appendSlice(alloc, &u32le(l.id));
        try buf.append(alloc, @intFromBool(l.visible));
        try buf.appendSlice(alloc, &u16le(@intCast(l.name.len)));
        try buf.appendSlice(alloc, l.name);
    }
    try buf.appendSlice(alloc, &u32le(g_active_layer));
    try buf.appendSlice(alloc, &u32le(@intCast(g_strokes.items.len)));
    for (g_strokes.items) |st| {
        try buf.appendSlice(alloc, &u32le(st.layer));
        try buf.appendSlice(alloc, &u32le(@intCast(st.ops.len)));
        try buf.appendSlice(alloc, st.ops);
    }
}

/// Serialize the program (header + material table + layers + strokes) into a caller-owned
/// blob, or null if nothing was painted (or on allocation failure). Commits any open
/// stroke first so a save mid-gesture keeps it.
pub fn serialize() ?[]u8 {
    _ = endStrokeUnit();
    if (g_strokes.items.len == 0) return null;
    var buf: std.ArrayList(u8) = .empty;
    writeBlob(&buf) catch {
        buf.deinit(alloc);
        return null;
    };
    return buf.toOwnedSlice(alloc) catch {
        buf.deinit(alloc);
        return null;
    };
}

// ── Load / apply ────────────────────────────────────────────────────────────────────
/// Peek the detail (paint density, texels/meter) a program was recorded at, without
/// replaying. The caller sets this detail FIRST (it rebuilds the atlas + re-uploads the
/// mesh, which this module can't) before calling apply(). Null on a malformed blob.
pub fn programDetail(blob: []const u8) ?u16 {
    if (blob.len < 8) return null;
    if (!std.mem.eql(u8, blob[0..4], &MAGIC)) return null;
    const ver = std.mem.readInt(u16, blob[4..6], .little);
    if (ver < 1 or ver > VERSION) return null;
    return std.mem.readInt(u16, blob[6..8], .little);
}

// Parse the shared material table into the LIVE g_mats (the loaded program is adopted as
// the live program, req_2529 — painting more must append to it).
fn parseMats(c: *Cursor) bool {
    const mat_count = c.u16v() orelse return false;
    var mi: u16 = 0;
    while (mi < mat_count) : (mi += 1) {
        const klen = c.u16v() orelse return false;
        const key = c.bytes(klen) orelse return false;
        const wlen = c.u32v() orelse return false;
        const wgsl = c.bytes(wlen) orelse return false;
        const dlen = c.u16v() orelse return false;
        const data = alloc.alloc(f32, dlen) catch return false;
        var di: u16 = 0;
        while (di < dlen) : (di += 1) data[di] = c.f32v() orelse {
            alloc.free(data);
            return false;
        };
        const tiles = c.f32v() orelse {
            alloc.free(data);
            return false;
        };
        const k = alloc.dupe(u8, key) catch {
            alloc.free(data);
            return false;
        };
        const w = alloc.dupe(u8, wgsl) catch {
            alloc.free(k);
            alloc.free(data);
            return false;
        };
        g_mats.append(alloc, .{ .key = k, .wgsl = w, .data = data, .tiles = tiles }) catch {
            alloc.free(k);
            alloc.free(w);
            alloc.free(data);
            return false;
        };
    }
    return true;
}

// Convert a v1 flat op stream (face-indexed) into ONE v2 stroke keyed against the
// CURRENT mesh — the migration the hide-stable keys need. v1 replay used raw face
// indices on this same mesh, so mapping each index through faceKeyOf preserves exactly
// the faces v1 would have painted, while making the result hide-stable from here on.
fn convertV1OpsInner(ops: []const u8, out: *std.ArrayList(u8)) !void {
    var c = Cursor{ .b = ops };
    while (c.p < c.b.len) {
        const tag = c.u8v() orelse break;
        switch (tag) {
            OP_INK_COLOR => {
                const cc = c.bytes(3) orelse return error.Malformed;
                try out.append(alloc, OP_INK_COLOR);
                try out.appendSlice(alloc, cc);
            },
            OP_INK_MATERIAL => {
                const idx = c.u16v() orelse return error.Malformed;
                try out.append(alloc, OP_INK_MATERIAL);
                try out.appendSlice(alloc, &u16le(idx));
            },
            OP_DAB => {
                const face = c.u32v() orelse return error.Malformed;
                const u = c.u32v() orelse return error.Malformed;
                const v = c.u32v() orelse return error.Malformed;
                const radius = c.u32v() orelse return error.Malformed;
                const flow = c.u32v() orelse return error.Malformed;
                const key = faceKeyOf(face);
                try out.append(alloc, OP_DAB);
                try out.appendSlice(alloc, &u32le(key.group));
                try out.appendSlice(alloc, &u32le(key.ord));
                try out.appendSlice(alloc, &u32le(u));
                try out.appendSlice(alloc, &u32le(v));
                try out.appendSlice(alloc, &u32le(radius));
                try out.appendSlice(alloc, &u32le(flow));
            },
            OP_FILL => {
                const face = c.u32v() orelse return error.Malformed;
                const key = faceKeyOf(face);
                try out.append(alloc, OP_FILL);
                try out.appendSlice(alloc, &u32le(key.group));
                try out.appendSlice(alloc, &u32le(key.ord));
            },
            else => return error.Malformed,
        }
    }
}

fn convertV1Ops(ops: []const u8) ?[]u8 {
    var out: std.ArrayList(u8) = .empty;
    convertV1OpsInner(ops, &out) catch {
        out.deinit(alloc);
        return null;
    };
    return out.toOwnedSlice(alloc) catch {
        out.deinit(alloc);
        return null;
    };
}

/// Rebuild the atlas by replaying a serialized program, ADOPTING it as the live recorded
/// program (req_2529: painting more appends; a later save returns the cumulative work).
/// v2 blobs restore their layer table; v1 blobs load as one "Layer 1" stroke. The caller
/// must have already set the program's detail (see programDetail). The stroke journal
/// starts fresh — the loaded painting is the new floor, not an undoable unit.
pub fn apply(blob: []const u8) bool {
    var c = Cursor{ .b = blob };
    const magic = c.bytes(4) orelse return false;
    if (!std.mem.eql(u8, magic, &MAGIC)) return false;
    const ver = c.u16v() orelse return false;
    if (ver < 1 or ver > VERSION) return false;
    _ = c.u16v() orelse return false; // detail (applied by the caller before apply)
    _ = c.u32v() orelse return false; // facecount (advisory)

    dropLayerCarry(); // the loaded program's table wins over any pending edit carry
    reset();
    if (!applyParse(&c, ver, blob)) {
        reset(); // never leave a half-adopted program behind a failed load
        return false;
    }

    // Prepare the canvas: the caller already set detail (a mesh re-upload); a replayed
    // painting HAS a base (it was created with one), so activate it before the clear lays
    // it back under the strokes (req_2551). The post-clear atlas is the undo baseline.
    model_paint.activateBase();
    model_paint.clearAtlas();
    forceBaselineCapture();
    replayAll();
    return true;
}

// Parse the mats + layers + strokes of a blob into the (already reset) live state.
// Any false return leaves partial state — apply() resets it.
fn applyParse(c: *Cursor, ver: u16, blob: []const u8) bool {
    if (!parseMats(c)) return false;
    if (ver == 1) {
        _ = c.u32v() orelse return false; // ops byte length (advisory; read to blob end)
        ensureLayers();
        const ops = convertV1Ops(blob[c.p..]) orelse return false;
        if (ops.len > 0) {
            g_strokes.append(alloc, .{ .layer = g_active_layer, .ops = ops }) catch {
                alloc.free(ops);
                return false;
            };
        } else {
            alloc.free(ops);
        }
        return true;
    }
    const layer_count = c.u16v() orelse return false;
    var li: u16 = 0;
    var max_id: u32 = 0;
    while (li < layer_count) : (li += 1) {
        const id = c.u32v() orelse return false;
        const vis = c.u8v() orelse return false;
        const nlen = c.u16v() orelse return false;
        const name = c.bytes(nlen) orelse return false;
        const nm = alloc.dupe(u8, name) catch return false;
        g_layers.append(alloc, .{ .id = id, .name = nm, .visible = vis != 0 }) catch {
            alloc.free(nm);
            return false;
        };
        if (id > max_id) max_id = id;
    }
    g_active_layer = c.u32v() orelse return false;
    g_next_layer_id = max_id + 1;
    if (g_layers.items.len == 0) ensureLayers();
    if (layerIndexOf(g_active_layer) == null) g_active_layer = g_layers.items[g_layers.items.len - 1].id;
    const stroke_count = c.u32v() orelse return false;
    var si: u32 = 0;
    while (si < stroke_count) : (si += 1) {
        const layer = c.u32v() orelse return false;
        const olen = c.u32v() orelse return false;
        const ops_src = c.bytes(olen) orelse return false;
        const ops = alloc.dupe(u8, ops_src) catch return false;
        g_strokes.append(alloc, .{ .layer = layer, .ops = ops }) catch {
            alloc.free(ops);
            return false;
        };
    }
    return true;
}
