// cli/commands/bake-geometry.ts - run @reactjit/geometries generators at build
// time and emit the intern seed (runtime/geometries/_baked.generated.ts).
//
//   rjit bake-geometry --manifest <path>     # generate + write the seed
//   rjit bake-geometry --manifest <path> --check   # diff vs on-disk; nonzero on drift
//   rjit bake-geometry --clear               # write the empty seed
//
// A geometry that is baked here costs ZERO generate() calls in V8 at runtime:
// intern.ts pre-seeds its cache from the emitted BAKED map, keyed by the SAME
// internKey() the runtime computes, so a baked mesh is a transparent cache hit.
//
// Input today is an explicit manifest [{ geometry: "<id>", params: {...} }] — the
// shared, proven backend. The const-taint analysis pass (the auto producer that
// colors the prop graph and folds un-tainted params) and per-cart manifest
// discovery are layered on top of this command; both emit through this same path.
// See runtime/geometries/BAKE.md.

import { fsExists, fsRead, fsWrite } from '../host/fs.ts';
import { err, out } from '../host/log.ts';
import { parseArgs } from '../host/argv.ts';
import { GEOMETRIES } from '../../runtime/geometries/index.ts';
import { bakeEntry, type InternedGeometry } from '../../runtime/geometries/intern.ts';

const SEED_PATH = 'runtime/geometries/_baked.generated.ts';

interface ManifestItem {
  geometry: string; // a GeometryDef id, e.g. "Box" | "Heightfield"
  params: Record<string, unknown>;
}

export async function run(argv: string[]): Promise<number> {
  const args = parseArgs(argv, { flags: { check: 'bool', clear: 'bool', manifest: 'string', out: 'string' } });
  const seedPath = (args.flags.out as string) ?? SEED_PATH;

  let entries: InternedGeometry[] = [];
  if (!args.flags.clear) {
    const manifestPath = args.flags.manifest as string | undefined;
    if (!manifestPath) {
      err('bake-geometry: --manifest <path> required (or --clear to empty the seed)');
      return 2;
    }
    if (!fsExists(manifestPath)) {
      err(`bake-geometry: manifest not found: ${manifestPath}`);
      return 2;
    }
    let items: ManifestItem[];
    try {
      items = JSON.parse(fsRead(manifestPath));
    } catch (e) {
      err(`bake-geometry: manifest is not valid JSON: ${(e as Error).message}`);
      return 2;
    }
    for (const item of items) {
      const def = GEOMETRIES[item.geometry];
      if (!def) {
        err(`bake-geometry: unknown geometry "${item.geometry}" (known: ${Object.keys(GEOMETRIES).join(', ')})`);
        return 1;
      }
      entries.push(bakeEntry(def, item.params ?? {}));
    }
  }

  const content = emitSeed(entries);

  if (args.flags.check) {
    const onDisk = fsExists(seedPath) ? fsRead(seedPath) : '';
    if (onDisk !== content) {
      err(`bake-geometry: ${seedPath} drift`);
      return 1;
    }
    out('bake-geometry: clean');
    return 0;
  }

  fsWrite(seedPath, content);
  out(`bake-geometry: wrote ${seedPath} (${entries.length} geometr${entries.length === 1 ? 'y' : 'ies'} baked)`);
  return 0;
}

function emitSeed(entries: InternedGeometry[]): string {
  const lines: string[] = [
    '// runtime/geometries/_baked.generated.ts — DO NOT EDIT.',
    '// Regenerated by `rjit bake-geometry`. Committed EMPTY so the import in intern.ts',
    '// always resolves; a build with bakeable geometry overwrites it with the seed.',
    '//',
    '// Each entry is an InternedGeometry (key/vertices/count/bounds) computed at build',
    '// time. intern.ts pre-seeds its cache from this, so a baked mesh\'s internGeometry',
    '// is a transparent cache hit and generate() never runs in V8. Keys are produced',
    '// by internKey() so they match the runtime keys exactly.',
    '',
    'export type BakedEntry = { key: string; vertices: number[]; count: number; bounds: number };',
    '',
  ];
  if (entries.length === 0) {
    lines.push('export const BAKED: Record<string, BakedEntry> = {};');
    lines.push('');
    return lines.join('\n');
  }
  lines.push('export const BAKED: Record<string, BakedEntry> = {');
  for (const e of entries) {
    // Verts as a compact one-line array; the file is generated + embedded in the
    // bundle, so density beats readability here.
    lines.push(`  ${JSON.stringify(e.key)}: { key: ${JSON.stringify(e.key)}, count: ${e.count}, bounds: ${e.bounds}, vertices: [${e.vertices.join(',')}] },`);
  }
  lines.push('};');
  lines.push('');
  return lines.join('\n');
}
