// cli/commands/codegen-bindings.ts - generate an independent binding snapshot.

import { fsExists, fsRead, fsWrite } from '../host/fs.ts';
import { err, out } from '../host/log.ts';
import { parseArgs } from '../host/argv.ts';

interface Ingredient {
  name: string;
  required: boolean;
  grepPrefix: string;
  regFn: string;
  moduleName: string;
  modulePath: string;
  hostFns: HostFn[];
  hasTickDrain: boolean;
}

interface HostFn {
  js: string;
  zig: string;
}

export async function run(argv: string[]): Promise<number> {
  const args = parseArgs(argv, { flags: { check: 'bool', strict: 'bool' } });
  const ingredients = loadIngredients();
  const zig = emitZig(ingredients);
  const dts = emitDts(ingredients);
  const json = emitJson(ingredients);

  const outputs = [
    { path: 'framework/_generated_bindings.zig', content: zig },
    { path: 'runtime/_generated_host_globals.d.ts', content: dts },
    { path: 'sdk/bindings.generated.json', content: json },
  ];

  if (args.flags.check) {
    let clean = true;
    for (const output of outputs) {
      if (!fsExists(output.path) || fsRead(output.path) !== output.content) {
        err(`codegen-bindings: ${output.path} drift`);
        clean = false;
      }
    }
    if (!clean) return 1;
    out('codegen-bindings: clean');
    return 0;
  }

  for (const output of outputs) fsWrite(output.path, output.content);
  out(`codegen-bindings: wrote ${outputs.map((x) => x.path).join(', ')}`);

  if (args.flags.strict) {
    out('codegen-bindings: strict lints are not active until hook declarations land');
  }
  return 0;
}

function loadIngredients(): Ingredient[] {
  const source = fsRead('framework/v8_ingredients.zig');
  const rows = source.match(/\.{ \.name = ".*? },/g) ?? [];
  return rows.map((row) => {
    const name = mustMatch(row, /\.name = "([^"]+)"/, row);
    const required = mustMatch(row, /\.required = (true|false)/, row) === 'true';
    const grepPrefix = mustMatch(row, /\.grep_prefix = "([^"]*)"/, row);
    const regFn = mustMatch(row, /\.reg_fn = "([^"]+)"/, row);
    const moduleName = mustMatch(row, /\.mod = (v8_bindings_[a-zA-Z0-9_]+)/, row);
    const modulePath = `framework/${moduleName}.zig`;
    const moduleSource = fsExists(modulePath) ? fsRead(modulePath) : '';
    return {
      name,
      required,
      grepPrefix,
      regFn,
      moduleName,
      modulePath,
      hostFns: moduleSource ? hostFnsForRegister(moduleSource, regFn) : [],
      hasTickDrain: /\bpub fn tickDrain\s*\(/.test(moduleSource),
    };
  });
}

function hostFnsForRegister(source: string, regFn: string): HostFn[] {
  const start = source.indexOf(`pub fn ${regFn}`);
  if (start < 0) return [];
  const bodyStart = source.indexOf('{', start);
  if (bodyStart < 0) return [];
  let depth = 0;
  let end = bodyStart;
  for (; end < source.length; end++) {
    const ch = source[end];
    if (ch === '{') depth++;
    else if (ch === '}') {
      depth--;
      if (depth === 0) {
        end++;
        break;
      }
    }
  }
  const body = source.slice(bodyStart, end);
  const fns: HostFn[] = [];
  const re = /registerHostFn\("([^"]+)",\s*([A-Za-z0-9_]+)\)/g;
  let match: RegExpExecArray | null;
  while ((match = re.exec(body)) !== null) {
    fns.push({ js: match[1]!, zig: match[2]! });
  }
  return fns;
}

function emitZig(ingredients: Ingredient[]): string {
  return [
    '// framework/_generated_bindings.zig - DO NOT EDIT.',
    '// Regenerated by `rjit codegen-bindings`.',
    '//',
    '// This independent slice intentionally re-exports the current hand-maintained',
    '// catalog. Runtime shells still import framework/v8_ingredients.zig directly',
    '// until the later integration slice replaces that wiring.',
    '',
    'pub const source = @import("v8_ingredients.zig");',
    'pub const Ingredient = source.Ingredient;',
    'pub const INGREDIENTS = source.INGREDIENTS;',
    'pub const enabledFor = source.enabledFor;',
    'pub const registerAll = source.registerAll;',
    'pub const tickDrain = source.tickDrain;',
    '',
    'pub const GENERATED_BINDING_COUNT = ' + String(ingredients.length) + ';',
    '',
  ].join('\n');
}

function emitDts(ingredients: Ingredient[]): string {
  const lines: string[] = [
    '// runtime/_generated_host_globals.d.ts - DO NOT EDIT.',
    '// Regenerated by `rjit codegen-bindings`.',
    '',
    'declare global {',
  ];
  for (const ingredient of ingredients) {
    lines.push(`  // ${ingredient.name} (${ingredient.modulePath})`);
    for (const fn of ingredient.hostFns) {
      lines.push(`  function ${fn.js}(...args: unknown[]): unknown;`);
    }
    lines.push('');
  }
  lines.push('}');
  lines.push('');
  lines.push('export {};');
  lines.push('');
  return lines.join('\n');
}

function emitJson(ingredients: Ingredient[]): string {
  return JSON.stringify({
    generatedFrom: 'framework/v8_ingredients.zig',
    bindings: Object.fromEntries(ingredients.map((ingredient) => [ingredient.name, {
      required: ingredient.required,
      module: ingredient.modulePath,
      registerFn: ingredient.regFn,
      grepPrefix: ingredient.grepPrefix,
      tickDrain: ingredient.hasTickDrain ? 'real' : 'noop',
      hostFns: ingredient.hostFns,
    }])),
  }, null, 2) + '\n';
}

function mustMatch(source: string, re: RegExp, context: string): string {
  const match = re.exec(source);
  if (!match) throw new Error(`cannot parse ingredient row: ${context}`);
  return match[1]!;
}
