// cli/commands/game.ts - `rjit game compile` / `rjit game verify` (V19).
//
// The game compile is a CLI any LLM can run at any time; verify boots the
// compiled output headless, replays every verify script (a recorded command
// sequence, compile/verify/*.cmds), runs every game/*.test.ts behavior suite,
// and exits with one verdict line. A feature is "done" when the COMPILED game
// carries it and this run proves it — compile constantly, the green light
// never goes dark.
//
//   rjit game compile   cart/hmsc-int/compile/main.ts -> zig-out/game/hmsc-headless.js
//   rjit game verify    compile fresh, then suites + scripts -> GREEN/RED + exit code

import { fsExists, fsList, fsMkdir, fsWrite, tryFsStat } from '../host/fs.ts';
import { err, out } from '../host/log.ts';
import { spawnSync } from '../host/process.ts';

const GAME_DIR = 'cart/hmsc-int/game';
/** every root whose *.test.ts suites the verify run owns (game + the V20 data layer + the editor routes) */
const SUITE_ROOTS = [GAME_DIR, 'cart/hmsc-int/data', 'cart/hmsc-int/editors'];
const COMPILE_ENTRY = 'cart/hmsc-int/compile/main.ts';
const VERIFY_DIR = 'cart/hmsc-int/compile/verify';
const OUT_DIR = 'zig-out/game';
const HEADLESS_BUNDLE = `${OUT_DIR}/hmsc-headless.js`;
const TEST_OUT_DIR = `${OUT_DIR}/tests`;
const ORACLE_INDEX_DIR = 'docs/game/_index';
const ORACLE_RECORDS_DIR = `${ORACLE_INDEX_DIR}/records`;
const ORACLE_SELF_CHECK_ENTRY = `${OUT_DIR}/oracle-self-check.ts`;
const ORACLE_SELF_CHECK_BUNDLE = `${OUT_DIR}/oracle-self-check.js`;
const ORACLE_SMOKE_QUERIES = [
  'physics',
  'kinds',
  'chance',
  'pathing',
  'commands',
  'perception',
  'figure',
  'items',
  'animation',
  'vehicle',
  'chrome',
  'camera',
  'cutscene',
  'telemetry',
] as const;

export async function run(argv: string[]): Promise<number> {
  const subcommand = argv[0];
  if (subcommand === 'compile') return compile(__cwd());
  if (subcommand === 'verify') return verify(__cwd());
  err('Usage: rjit game <compile|verify>');
  err('  compile  bundle the headless game output');
  err('  verify   compile, boot headless, replay verify scripts + behavior suites, exit with a verdict');
  return 2;
}

function bundle(root: string, entry: string, outFile: string): boolean {
  const result = spawnSync(`${root}/tools/esbuild`, [
    `${root}/${entry}`,
    '--bundle',
    `--outfile=${root}/${outFile}`,
    '--format=iife',
    '--platform=neutral',
    '--target=es2022',
    `--alias:@reactjit=${root}/runtime`,
    `--alias:@game=${root}/${GAME_DIR}`,
    '--log-level=warning',
  ]);
  if (result.stderr.trim()) err(result.stderr.trim());
  return result.code === 0;
}

function compile(root: string): number {
  fsMkdir(`${root}/${OUT_DIR}`);
  if (!bundle(root, COMPILE_ENTRY, HEADLESS_BUNDLE)) {
    err(`[game] compile FAILED: ${COMPILE_ENTRY}`);
    return 1;
  }
  out(`[game] compiled ${COMPILE_ENTRY} -> ${HEADLESS_BUNDLE}`);
  return 0;
}

function posixJoin(...parts: string[]): string {
  return parts.join('/').replace(/\/+/g, '/');
}

function jsString(value: string): string {
  return JSON.stringify(value);
}

function oracleSelfCheckSource(root: string, recordFiles: string[]): string {
  const recordImports = recordFiles.map((file, i) => {
    const abs = posixJoin(root, ORACLE_RECORDS_DIR, file);
    return `import * as record${i} from ${jsString(abs)};`;
  }).join('\n');
  const recordSpecs = recordFiles.map((file, i) => `{ file: ${jsString(`${ORACLE_RECORDS_DIR}/${file}`)}, module: record${i} }`).join(',\n  ');

  return `// Generated by rjit game verify. Do not edit.
import { DECISIONS } from ${jsString(posixJoin(root, ORACLE_INDEX_DIR, 'decisions.ts'))};
import { ALL_DOCS, ALL_INTERFACES, ALL_PATTERNS, ALL_HAZARDS } from ${jsString(posixJoin(root, ORACLE_INDEX_DIR, 'index.ts'))};
${recordImports}

declare const globalThis: any;

const recordSpecs = [
  ${recordSpecs},
];
const decisionStatuses = new Set(['ruled', 'revised', 'open', 'show-me']);
const failures: string[] = [];

function fail(message: string): void {
  failures.push(message);
}
function isObject(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}
function requireObject(value: unknown, path: string): Record<string, unknown> | null {
  if (!isObject(value)) {
    fail(\`\${path}: expected object\`);
    return null;
  }
  return value;
}
function requireString(value: unknown, path: string): string {
  if (typeof value !== 'string' || value.length === 0) fail(\`\${path}: expected non-empty string\`);
  return typeof value === 'string' ? value : '';
}
function requireStringArray(value: unknown, path: string): string[] {
  if (!Array.isArray(value) || value.some((item) => typeof item !== 'string')) {
    fail(\`\${path}: expected string[]\`);
    return [];
  }
  return value as string[];
}
function requireNonEmptyStringArray(value: unknown, path: string): string[] {
  const items = requireStringArray(value, path);
  if (items.length === 0) fail(\`\${path}: expected non-empty string[]\`);
  return items;
}
function requireArray(value: unknown, path: string): unknown[] {
  if (!Array.isArray(value)) {
    fail(\`\${path}: expected array\`);
    return [];
  }
  return value;
}
function requireOneOf(value: unknown, allowed: Set<string>, path: string): string {
  const text = requireString(value, path);
  if (text && !allowed.has(text)) fail(\`\${path}: unexpected value \${JSON.stringify(text)}\`);
  return text;
}

function validateInterface(record: unknown, path: string): void {
  const r = requireObject(record, path);
  if (!r) return;
  requireString(r.name, \`\${path}.name\`);
  requireNonEmptyStringArray(r.purpose, \`\${path}.purpose\`); // oracle searchInterfaces calls purpose.join()
  requireString(r.kind, \`\${path}.kind\`);
  requireString(r.description, \`\${path}.description\`);
  requireString(r.status, \`\${path}.status\`); // oracle interfaceLine prints status
}

function validatePattern(record: unknown, path: string): void {
  const r = requireObject(record, path);
  if (!r) return;
  requireString(r.name, \`\${path}.name\`);
  requireNonEmptyStringArray(r.purpose, \`\${path}.purpose\`); // oracle searchPatterns calls purpose.join()
  requireString(r.description, \`\${path}.description\`);
  requireStringArray(r.examples, \`\${path}.examples\`); // oracle patternLine calls examples.slice().join()
  requireString(r.status, \`\${path}.status\`); // oracle patternLine prints status
}

function validateHazard(record: unknown, path: string): void {
  const r = requireObject(record, path);
  if (!r) return;
  requireString(r.name, \`\${path}.name\`);
  requireNonEmptyStringArray(r.purpose, \`\${path}.purpose\`); // oracle searchHazards calls purpose.join()
  requireString(r.description, \`\${path}.description\`);
  requireStringArray(r.evidence, \`\${path}.evidence\`); // oracle searchHazards calls evidence.join()
  requireString(r.severity, \`\${path}.severity\`); // oracle hazardLine calls severity.toUpperCase()
}

function validateDoc(doc: unknown, file: string): string {
  const d = requireObject(doc, file);
  if (!d) return '';
  const name = requireString(d.name, \`\${file}.name\`);
  requireString(d.file, \`\${file}.file\`);
  requireNonEmptyStringArray(d.purpose, \`\${file}.purpose\`);
  requireString(d.summary, \`\${file}.summary\`);
  requireArray(d.interfaces, \`\${file}.interfaces\`).forEach((item, i) => validateInterface(item, \`\${file}.interfaces[\${i}]\`));
  requireArray(d.patterns, \`\${file}.patterns\`).forEach((item, i) => validatePattern(item, \`\${file}.patterns[\${i}]\`));
  requireArray(d.hazards, \`\${file}.hazards\`).forEach((item, i) => validateHazard(item, \`\${file}.hazards[\${i}]\`));
  return name;
}

const recordNames = new Map<string, string>();
for (const spec of recordSpecs) {
  const docs = Object.entries(spec.module)
    .filter(([, value]) => isObject(value) && 'summary' in value && 'interfaces' in value)
    .map(([, value]) => value);
  if (docs.length !== 1) {
    fail(\`\${spec.file}: expected exactly one DocIndex export, found \${docs.length}\`);
    continue;
  }
  const name = validateDoc(docs[0], spec.file);
  if (name) recordNames.set(name, spec.file);
}

if (!Array.isArray(ALL_DOCS)) fail('docs/game/_index/index.ts: ALL_DOCS must be an array');
for (const doc of ALL_DOCS as unknown[]) {
  const d = doc as any;
  const name = typeof d?.name === 'string' ? d.name : '<unnamed>';
  if (!recordNames.has(name)) fail(\`docs/game/_index/index.ts: ALL_DOCS includes \${name}, but no matching record file was validated\`);
}
for (const [name, file] of recordNames) {
  if (!(ALL_DOCS as any[]).some((doc) => doc?.name === name)) fail(\`docs/game/_index/index.ts: missing \${name} from ALL_DOCS (record file: \${file})\`);
}
if (!Array.isArray(ALL_INTERFACES) || !Array.isArray(ALL_PATTERNS) || !Array.isArray(ALL_HAZARDS)) {
  fail('docs/game/_index/index.ts: flattened oracle views must be arrays');
}

const ids = new Set<string>();
for (let i = 0; i < DECISIONS.length; i += 1) {
  const path = \`docs/game/_index/decisions.ts.DECISIONS[\${i}]\`;
  const d = requireObject(DECISIONS[i], path);
  if (!d) continue;
  const id = requireString(d.id, \`\${path}.id\`);
  if (id && !/^[VPR][0-9]+$/.test(id)) fail(\`\${path}.id: expected V*/P*/R* id, got \${JSON.stringify(id)}\`);
  if (id && ids.has(id)) fail(\`\${path}.id: duplicate id \${id}\`);
  if (id) ids.add(id);
  requireString(d.name, \`\${path}.name\`);
  requireOneOf(d.status, decisionStatuses, \`\${path}.status\`);
  requireString(d.ruling, \`\${path}.ruling\`);
  requireNonEmptyStringArray(d.keywords, \`\${path}.keywords\`);
  if ('retires' in d && d.retires !== undefined) requireStringArray(d.retires, \`\${path}.retires\`);
  if ('cites' in d && d.cites !== undefined) requireStringArray(d.cites, \`\${path}.cites\`);
}

if (failures.length > 0) {
  for (const failure of failures) console.error(\`[oracle-self-check] \${failure}\`);
  console.error(\`ORACLE SELF-CHECK RED — \${failures.length} failure(s)\`);
  globalThis.__exit?.(1);
} else {
  console.log(\`ORACLE SELF-CHECK GREEN — \${recordSpecs.length} records, \${DECISIONS.length} decisions\`);
}
`;
}

function runOracleSelfCheck(root: string): boolean {
  if (!fsExists(`${root}/${ORACLE_RECORDS_DIR}`)) {
    err(`[game] oracle self-check FAILED: missing ${ORACLE_RECORDS_DIR}`);
    return false;
  }
  fsMkdir(`${root}/${OUT_DIR}`);
  const recordFiles = fsList(`${root}/${ORACLE_RECORDS_DIR}`)
    .filter((name) => name.endsWith('.ts'))
    .sort();
  fsWrite(`${root}/${ORACLE_SELF_CHECK_ENTRY}`, oracleSelfCheckSource(root, recordFiles));
  if (!bundle(root, ORACLE_SELF_CHECK_ENTRY, ORACLE_SELF_CHECK_BUNDLE)) {
    err('[game] oracle self-check does not bundle');
    return false;
  }
  const result = spawnSync(`${root}/tools/v8cli`, [`${root}/${ORACLE_SELF_CHECK_BUNDLE}`]);
  if (result.stdout.trim()) out(result.stdout.trim());
  if (result.stderr.trim()) err(result.stderr.trim());
  if (result.code !== 0) {
    err('[game] oracle self-check FAILED: record/decision shape');
    return false;
  }

  for (const query of ORACLE_SMOKE_QUERIES) {
    const smoke = spawnSync(`${root}/tools/oracle`, [query]);
    if (smoke.stderr.trim()) err(smoke.stderr.trim());
    const stdout = smoke.stdout.trim();
    if (smoke.code !== 0) {
      err(`[game] oracle smoke FAILED: ${query} exited ${smoke.code}`);
      return false;
    }
    if (!stdout.includes('═══ RULINGS') || stdout.includes('(no ruling matches')) {
      err(`[game] oracle smoke FAILED: ${query} produced no matching RULINGS`);
      if (stdout) err(stdout.split('\n').slice(0, 8).join('\n'));
      return false;
    }
  }
  out(`[game] oracle smoke GREEN — ${ORACLE_SMOKE_QUERIES.length}/${ORACLE_SMOKE_QUERIES.length} queries`);
  return true;
}

/** Every *.test.ts under the suite roots, recursively — each is a P4 behavior suite. */
function findTestSuites(root: string, dir: string): string[] {
  if (!fsExists(`${root}/${dir}`)) return [];
  const suites: string[] = [];
  for (const name of fsList(`${root}/${dir}`)) {
    const path = `${dir}/${name}`;
    const stat = tryFsStat(`${root}/${path}`);
    if (stat?.isDir) suites.push(...findTestSuites(root, path));
    else if (name.endsWith('.test.ts')) suites.push(path);
  }
  return suites.sort();
}

function verify(root: string): number {
  if (compile(root) !== 0) {
    err('[game] VERDICT RED — the game does not compile');
    return 1;
  }

  // ── oracle self-check: docs/game/_index is part of the test surface ─────
  const oracleOk = runOracleSelfCheck(root);

  // ── the P4 behavior suites (dual-sided testing's TS side) ────────────────
  fsMkdir(`${root}/${TEST_OUT_DIR}`);
  const suites = SUITE_ROOTS.flatMap((suiteRoot) => findTestSuites(root, suiteRoot));
  let suitesPassed = 0;
  for (const suite of suites) {
    const name = suite.replace(/^cart\/hmsc-int\//, '').replace(/\//g, '_').replace(/\.test\.ts$/, '.test.js');
    const compiled = `${TEST_OUT_DIR}/${name}`;
    if (!bundle(root, suite, compiled)) {
      err(`[game] suite does not bundle: ${suite}`);
      continue;
    }
    const result = spawnSync(`${root}/tools/v8cli`, [`${root}/${compiled}`]);
    if (result.stdout.trim()) out(result.stdout.trim());
    if (result.stderr.trim()) err(result.stderr.trim());
    if (result.code === 0) suitesPassed += 1;
    else err(`[game] suite FAILED: ${suite}`);
  }

  // ── the verify scripts: boot headless, replay, demand the green verdict ──
  const scripts = fsExists(`${root}/${VERIFY_DIR}`)
    ? fsList(`${root}/${VERIFY_DIR}`).filter((name) => name.endsWith('.cmds')).sort()
    : [];
  let scriptsPassed = 0;
  for (const script of scripts) {
    const result = spawnSync(`${root}/tools/v8cli`, [`${root}/${HEADLESS_BUNDLE}`, `${root}/${VERIFY_DIR}/${script}`]);
    if (result.stdout.trim()) out(result.stdout.trim());
    if (result.stderr.trim()) err(result.stderr.trim());
    if (result.code === 0) scriptsPassed += 1;
    else err(`[game] verify script FAILED: ${VERIFY_DIR}/${script}`);
  }

  const green = oracleOk && suitesPassed === suites.length && scriptsPassed === scripts.length && scripts.length > 0;
  const tally = `${oracleOk ? 1 : 0}/1 oracle, ${suitesPassed}/${suites.length} suites, ${scriptsPassed}/${scripts.length} scripts`;
  if (!green) {
    err(`[game] VERDICT RED — ${tally}`);
    return 1;
  }
  out(`[game] VERDICT GREEN — ${tally}`);
  return 0;
}
