// Classifier sheet for the /play diegetic channel composition. Static dimensions
// describe the authored screen furniture; changing behavior/cadence lives in
// channelModel.ts's tuning table.
import { classifier, classifiers as P, setStyleTokens, setTokens } from '../../../runtime/classifier';
import { EDITOR_COLORS, EDITOR_STYLES } from '../theme';

setTokens(EDITOR_COLORS);
setStyleTokens(EDITOR_STYLES);

const MONO = 'monospace';

classifier({
  PL_Root: { type: 'Box', style: { width: '100%', height: '100%', position: 'relative', overflow: 'hidden' } },
  PL_Backdrop: { type: 'Box', style: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, backgroundColor: 'theme:stageBg' } },
  PL_WorldWash: { type: 'Box', style: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, backgroundColor: 'theme:bg', opacity: 0.16 } },
  PL_WorldBadge: { type: 'Box', style: { position: 'absolute', right: 18, top: 12, height: 22, flexDirection: 'row', alignItems: 'center', gap: 7, paddingLeft: 9, paddingRight: 9, borderRadius: 3, backgroundColor: 'theme:bgAlt', borderWidth: 1, borderColor: 'theme:border' } },
  PL_WorldDot: { type: 'Box', style: { width: 6, height: 6, borderRadius: 3, backgroundColor: 'theme:success' } },
  PL_WorldBadgeText: { type: 'Text', fontSize: 8, color: 'theme:textDim', noWrap: true, style: { fontFamily: MONO, fontWeight: 800, letterSpacing: 0.5 } },
  PL_KeyLegend: { type: 'Box', style: { position: 'absolute', left: 286, bottom: 18, height: 24, flexDirection: 'row', alignItems: 'center', gap: 10, paddingLeft: 9, paddingRight: 9, borderRadius: 3, backgroundColor: 'theme:bgAlt', borderWidth: 1, borderColor: 'theme:borderSoft' } },
  PL_KeyText: { type: 'Text', fontSize: 8, color: 'theme:textSecondary', noWrap: true, style: { fontFamily: MONO, fontWeight: 700 } },
  PL_Launchers: { type: 'Box', style: { position: 'absolute', right: 18, bottom: 18, flexDirection: 'column', alignItems: 'flex-end', gap: 7 } },
  PL_Launcher: { type: 'Pressable', style: { height: 34, flexDirection: 'row', alignItems: 'center', gap: 8, paddingLeft: 9, paddingRight: 12, borderRadius: 5, backgroundColor: 'theme:bgAlt', borderWidth: 1, borderColor: 'theme:primary' }, hoverStyle: { backgroundColor: 'theme:segActiveBg' } },
  PL_LauncherHotkey: { type: 'Box', style: { width: 19, height: 19, alignItems: 'center', justifyContent: 'center', borderRadius: 3, backgroundColor: 'theme:primary' } },
  PL_LauncherHotkeyText: { type: 'Text', fontSize: 9, color: 'theme:stageBadgeText', style: { fontFamily: MONO, fontWeight: 900 } },
  PL_LauncherText: { type: 'Text', fontSize: 9, color: 'theme:text', noWrap: true, style: { fontFamily: MONO, fontWeight: 800 } },

  // Shared wall channel. The complete subtree is captured once and repainted on
  // mutation; children remain in the hit tree for contract selection.
  PL_WallSurface: {
    type: 'StaticSurface',
    blocksPointerEvents: true,
    style: { position: 'absolute', left: 22, right: 22, top: 22, height: 510, flexDirection: 'column', backgroundColor: 'theme:bgAlt', borderWidth: 3, borderColor: 'theme:warning', borderRadius: 3, overflow: 'hidden', transform: { rotate: -0.35, scaleX: 0.985, scaleY: 0.985 } },
    bp: {
      lg: { style: { left: 126, right: 310, top: 20, height: 520 } },
      xl: { style: { left: 184, right: 356, top: 20, height: 526 } },
    },
  },
  PL_WallHeader: { type: 'Box', style: { height: 58, flexDirection: 'row', alignItems: 'center', paddingLeft: 14, paddingRight: 12, backgroundColor: 'theme:onTrack', borderBottomWidth: 1, borderBottomColor: 'theme:warning' } },
  PL_WallId: { type: 'Box', style: { width: 170, flexDirection: 'column', gap: 3 } },
  PL_WallIdText: { type: 'Text', fontSize: 8, color: 'theme:accent', noWrap: true, style: { fontFamily: MONO, fontWeight: 800, letterSpacing: 0.5 } },
  PL_WallBrand: { type: 'Box', style: { flexGrow: 1, minWidth: 0, alignItems: 'center', justifyContent: 'center', gap: 1 } },
  PL_WallBrandTitle: { type: 'Text', fontSize: 27, color: 'theme:warning', noWrap: true, style: { fontFamily: MONO, fontWeight: 900, letterSpacing: 2.5 } },
  PL_WallBrandStrap: { type: 'Text', fontSize: 8, color: 'theme:error', noWrap: true, style: { fontFamily: MONO, fontWeight: 700, letterSpacing: 0.6 } },
  PL_WallUser: { type: 'Box', style: { width: 170, alignItems: 'flex-end', gap: 3 } },
  PL_WallUserText: { type: 'Text', fontSize: 8, color: 'theme:textSecondary', noWrap: true, style: { fontFamily: MONO, fontWeight: 700 } },
  PL_CloseButton: { type: 'Pressable', style: { width: 22, height: 22, alignItems: 'center', justifyContent: 'center', marginLeft: 8, borderRadius: 3, backgroundColor: 'theme:controlBg', borderWidth: 1, borderColor: 'theme:controlBorder' }, hoverStyle: { borderColor: 'theme:error', backgroundColor: 'theme:surfaceHover' } },
  PL_CloseText: { type: 'Text', fontSize: 10, color: 'theme:textSecondary', style: { fontFamily: MONO, fontWeight: 900 } },
  PL_WallBody: { type: 'Box', style: { flexGrow: 1, minHeight: 0, flexDirection: 'row', padding: 10, gap: 10 } },
  PL_WallRail: { type: 'Box', style: { width: 156, flexDirection: 'column', gap: 7 } },
  PL_WallCenter: { type: 'Box', style: { flexGrow: 1, minWidth: 0, flexDirection: 'column', gap: 7 } },
  PL_WallNoticeRail: { type: 'Box', style: { width: 166, flexDirection: 'column', gap: 7 } },
  PL_InfoCard: { type: 'Box', style: { minHeight: 68, flexDirection: 'column', gap: 4, padding: 8, backgroundColor: 'theme:controlBg', borderWidth: 1, borderColor: 'theme:accent', borderRadius: 2 } },
  PL_InfoCardDanger: { type: 'Box', style: { minHeight: 76, flexDirection: 'column', gap: 4, padding: 8, backgroundColor: 'theme:controlBg', borderWidth: 1, borderColor: 'theme:error', borderRadius: 2 } },
  PL_InfoLabel: { type: 'Text', fontSize: 8, color: 'theme:textDim', noWrap: true, style: { fontFamily: MONO, fontWeight: 900, letterSpacing: 0.5 } },
  PL_InfoValue: { type: 'Text', fontSize: 18, color: 'theme:accent', noWrap: true, style: { fontFamily: MONO, fontWeight: 900 } },
  PL_InfoMeta: { type: 'Text', fontSize: 7, color: 'theme:textFaint', numberOfLines: 2, style: { fontFamily: MONO, lineHeight: 10 } },
  PL_DangerText: { type: 'Text', fontSize: 8, color: 'theme:error', numberOfLines: 2, style: { fontFamily: MONO, fontWeight: 800, lineHeight: 11 } },
  PL_SmallAction: { type: 'Pressable', style: { height: 22, alignItems: 'center', justifyContent: 'center', marginTop: 2, backgroundColor: 'theme:bgElevated', borderWidth: 1, borderColor: 'theme:controlBorder', borderRadius: 2 }, hoverStyle: { borderColor: 'theme:warning' } },
  PL_SmallActionText: { type: 'Text', fontSize: 7, color: 'theme:textSecondary', noWrap: true, style: { fontFamily: MONO, fontWeight: 900, letterSpacing: 0.4 } },
  PL_GridHead: { type: 'Box', style: { height: 24, flexDirection: 'row', alignItems: 'center', paddingLeft: 4, paddingRight: 4, backgroundColor: 'theme:onTrack', borderWidth: 1, borderColor: 'theme:warning' } },
  PL_GridHeadText: { type: 'Text', fontSize: 8, color: 'theme:warning', noWrap: true, style: { flexGrow: 1, minWidth: 0, fontFamily: MONO, fontWeight: 900, letterSpacing: 0.6 } },
  PL_Ticker: { type: 'Box', style: { flexDirection: 'row', alignItems: 'center', gap: 5 } },
  PL_TickerLabel: { type: 'Text', fontSize: 7, color: 'theme:textDim', noWrap: true, style: { fontFamily: MONO, fontWeight: 800 } },
  PL_TickerValue: { type: 'Text', fontSize: 9, color: 'theme:accent', noWrap: true, style: { fontFamily: MONO, fontWeight: 900 } },
  PL_GigGrid: { type: 'Box', style: { flexGrow: 1, minHeight: 0, flexDirection: 'row', flexWrap: 'wrap', alignContent: 'flex-start', gap: 6, overflow: 'hidden' } },
  PL_GigCard: { type: 'Pressable', style: { width: 106, height: 54, flexDirection: 'column', justifyContent: 'space-between', padding: 6, backgroundColor: 'theme:cardBg', borderWidth: 1, borderColor: 'theme:controlBorder', borderRadius: 2 }, hoverStyle: { backgroundColor: 'theme:surfaceHover' } },
  PL_GigTitle: { type: 'Text', fontSize: 8, color: 'theme:text', numberOfLines: 2, style: { fontFamily: MONO, fontWeight: 900, lineHeight: 10 } },
  PL_GigStrap: { type: 'Text', fontSize: 7, color: 'theme:textDim', noWrap: true, numberOfLines: 1, style: { fontFamily: MONO, fontWeight: 700 } },
  PL_GigFooter: { type: 'Box', style: { height: 9, flexDirection: 'row', alignItems: 'center', gap: 2 } },
  PL_RiskDot: { type: 'Box', style: { width: 4, height: 4, borderRadius: 2, backgroundColor: 'theme:border' } },
  PL_GigPayout: { type: 'Text', fontSize: 7, color: 'theme:valNum', noWrap: true, style: { marginLeft: 'auto', fontFamily: MONO, fontWeight: 900 } },
  PL_SelectedStrip: { type: 'Box', style: { minHeight: 68, flexDirection: 'row', alignItems: 'center', gap: 9, padding: 8, backgroundColor: 'theme:onTrack', borderWidth: 1, borderColor: 'theme:warning', borderRadius: 2 } },
  PL_SelectedCopy: { type: 'Box', style: { flexGrow: 1, minWidth: 0, gap: 3 } },
  PL_SelectedTitle: { type: 'Text', fontSize: 10, color: 'theme:warning', noWrap: true, numberOfLines: 1, style: { fontFamily: MONO, fontWeight: 900 } },
  PL_SelectedDetail: { type: 'Text', fontSize: 8, color: 'theme:textSecondary', numberOfLines: 2, style: { fontFamily: MONO, lineHeight: 11 } },
  PL_SelectedMeta: { type: 'Text', fontSize: 7, color: 'theme:textDim', noWrap: true, style: { fontFamily: MONO, fontWeight: 800 } },
  PL_PrimaryAction: { type: 'Pressable', style: { width: 128, height: 42, alignItems: 'center', justifyContent: 'center', paddingLeft: 6, paddingRight: 6, backgroundColor: 'theme:warning', borderWidth: 2, borderColor: 'theme:warning', borderRadius: 2 }, hoverStyle: { backgroundColor: 'theme:valNum' } },
  PL_PrimaryActionText: { type: 'Text', fontSize: 8, color: 'theme:bg', noWrap: true, style: { fontFamily: MONO, fontWeight: 900, letterSpacing: 0.4 } },
  PL_Notice: { type: 'Box', style: { minHeight: 54, flexDirection: 'column', gap: 4, padding: 7, backgroundColor: 'theme:controlBg', borderWidth: 1, borderColor: 'theme:controlBorder', borderRadius: 2 } },
  PL_NoticeTitle: { type: 'Text', fontSize: 8, color: 'theme:text', noWrap: true, style: { fontFamily: MONO, fontWeight: 900, letterSpacing: 0.4 } },
  PL_NoticeDetail: { type: 'Text', fontSize: 7, color: 'theme:textDim', numberOfLines: 2, style: { fontFamily: MONO, lineHeight: 10 } },
  PL_Premium: { type: 'Box', style: { minHeight: 66, alignItems: 'center', justifyContent: 'center', gap: 4, marginTop: 'auto', backgroundColor: 'theme:onTrack', borderWidth: 1, borderColor: 'theme:accent', borderRadius: 2 } },
  PL_PremiumTitle: { type: 'Text', fontSize: 11, color: 'theme:accent', noWrap: true, style: { fontFamily: MONO, fontWeight: 900 } },
  PL_PremiumText: { type: 'Text', fontSize: 7, color: 'theme:textSecondary', noWrap: true, style: { fontFamily: MONO, fontWeight: 700 } },

  // Player-owned phone channel. It is foreground furniture but consumes the
  // same retained document abstraction as the wall.
  PL_PhoneSurface: {
    type: 'StaticSurface',
    blocksPointerEvents: true,
    style: { position: 'absolute', right: 18, bottom: 18, width: 310, height: 610, flexDirection: 'column', backgroundColor: 'theme:bgAlt', borderWidth: 3, borderColor: 'theme:primary', borderRadius: 24, overflow: 'hidden', transform: { rotate: -1.8 } },
    bp: { xl: { style: { right: 28, bottom: 18, width: 318, height: 620 } } },
  },
  PL_PhoneTop: { type: 'Box', style: { height: 27, flexDirection: 'row', alignItems: 'center', paddingLeft: 15, paddingRight: 10, backgroundColor: 'theme:bg', borderBottomWidth: 1, borderBottomColor: 'theme:borderSoft' } },
  PL_PhoneTopText: { type: 'Text', fontSize: 8, color: 'theme:textSecondary', noWrap: true, style: { fontFamily: MONO, fontWeight: 800 } },
  PL_PhoneSignal: { type: 'Text', fontSize: 8, color: 'theme:primary', noWrap: true, style: { marginLeft: 'auto', fontFamily: MONO, fontWeight: 900 } },
  PL_PhoneClose: { type: 'Pressable', style: { width: 20, height: 20, alignItems: 'center', justifyContent: 'center', marginLeft: 8, borderRadius: 10, backgroundColor: 'theme:controlBg' }, hoverStyle: { backgroundColor: 'theme:error' } },
  PL_PhoneCloseText: { type: 'Text', fontSize: 9, color: 'theme:text', style: { fontFamily: MONO, fontWeight: 900 } },
  PL_PhoneAppHead: { type: 'Box', style: { height: 43, flexDirection: 'row', alignItems: 'center', gap: 8, paddingLeft: 11, paddingRight: 11, backgroundColor: 'theme:segActiveBg', borderBottomWidth: 1, borderBottomColor: 'theme:primary' } },
  PL_PhoneLogo: { type: 'Box', style: { width: 24, height: 24, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: 'theme:primary' } },
  PL_PhoneLogoText: { type: 'Text', fontSize: 12, color: 'theme:stageBadgeText', style: { fontFamily: MONO, fontWeight: 900 } },
  PL_PhoneAppTitle: { type: 'Text', fontSize: 11, color: 'theme:text', noWrap: true, style: { fontFamily: MONO, fontWeight: 900 } },
  PL_PhoneAppMeta: { type: 'Text', fontSize: 7, color: 'theme:primary', noWrap: true, style: { fontFamily: MONO, fontWeight: 800 } },
  PL_UnreadPill: { type: 'Pressable', style: { minWidth: 29, height: 20, alignItems: 'center', justifyContent: 'center', marginLeft: 'auto', paddingLeft: 6, paddingRight: 6, borderRadius: 10, backgroundColor: 'theme:error' }, hoverStyle: { backgroundColor: 'theme:warning' } },
  PL_UnreadText: { type: 'Text', fontSize: 8, color: 'theme:bg', noWrap: true, style: { fontFamily: MONO, fontWeight: 900 } },
  PL_PhoneTabs: { type: 'Box', style: { height: 28, flexDirection: 'row', backgroundColor: 'theme:surface', borderBottomWidth: 1, borderBottomColor: 'theme:borderSoft' } },
  PL_PhoneTab: { type: 'Pressable', style: { flexGrow: 1, alignItems: 'center', justifyContent: 'center', borderBottomWidth: 2, borderBottomColor: 'theme:borderSoft' } },
  PL_PhoneTabOn: { type: 'Pressable', style: { flexGrow: 1, alignItems: 'center', justifyContent: 'center', borderBottomWidth: 2, borderBottomColor: 'theme:primary', backgroundColor: 'theme:segActiveBg' } },
  PL_PhoneTabText: { type: 'Text', fontSize: 8, color: 'theme:textDim', noWrap: true, style: { fontFamily: MONO, fontWeight: 800 } },
  PL_PhoneTabTextOn: { type: 'Text', fontSize: 8, color: 'theme:primary', noWrap: true, style: { fontFamily: MONO, fontWeight: 900 } },
  PL_PhoneContent: { type: 'Box', style: { flexGrow: 1, minHeight: 0, flexDirection: 'column', backgroundColor: 'theme:cardBg', overflow: 'hidden' } },
  PL_Post: { type: 'Box', style: { minHeight: 86, flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: 'theme:borderSoft', backgroundColor: 'theme:cardBg' } },
  PL_PostAccent: { type: 'Box', style: { width: 3, height: '100%', backgroundColor: 'theme:primary' } },
  PL_PostBody: { type: 'Box', style: { flexGrow: 1, minWidth: 0, flexDirection: 'column', gap: 3, paddingLeft: 8, paddingRight: 8, paddingTop: 6, paddingBottom: 5 } },
  PL_PostHead: { type: 'Box', style: { height: 12, flexDirection: 'row', alignItems: 'center', gap: 5 } },
  PL_PostAuthor: { type: 'Text', fontSize: 8, color: 'theme:text', noWrap: true, numberOfLines: 1, style: { flexGrow: 1, minWidth: 0, fontFamily: MONO, fontWeight: 900 } },
  PL_PostAge: { type: 'Text', fontSize: 7, color: 'theme:textFaint', noWrap: true, style: { fontFamily: MONO } },
  PL_PostHandle: { type: 'Text', fontSize: 7, color: 'theme:primary', noWrap: true, style: { fontFamily: MONO, fontWeight: 700 } },
  PL_PostText: { type: 'Text', fontSize: 8, color: 'theme:textSecondary', numberOfLines: 2, style: { fontFamily: MONO, lineHeight: 11 } },
  PL_PostStats: { type: 'Box', style: { height: 10, flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 'auto' } },
  PL_PostStat: { type: 'Text', fontSize: 7, color: 'theme:textFaint', noWrap: true, style: { fontFamily: MONO, fontWeight: 700 } },
  PL_PhonePageBar: { type: 'Box', style: { height: 30, flexDirection: 'row', alignItems: 'center', gap: 8, paddingLeft: 9, paddingRight: 9, backgroundColor: 'theme:surface', borderTopWidth: 1, borderTopColor: 'theme:borderSoft' } },
  PL_PageButton: { type: 'Pressable', style: { width: 27, height: 20, alignItems: 'center', justifyContent: 'center', borderRadius: 3, backgroundColor: 'theme:controlBg', borderWidth: 1, borderColor: 'theme:controlBorder' }, hoverStyle: { borderColor: 'theme:primary' } },
  PL_PageButtonText: { type: 'Text', fontSize: 9, color: 'theme:textSecondary', style: { fontFamily: MONO, fontWeight: 900 } },
  PL_PageMeta: { type: 'Text', fontSize: 7, color: 'theme:textDim', noWrap: true, style: { flexGrow: 1, minWidth: 0, textAlign: 'center', fontFamily: MONO, fontWeight: 800 } },
  PL_MessageCard: { type: 'Box', style: { minHeight: 76, flexDirection: 'column', gap: 5, padding: 9, borderBottomWidth: 1, borderBottomColor: 'theme:borderSoft' } },
  PL_MessageTitle: { type: 'Text', fontSize: 9, color: 'theme:text', noWrap: true, style: { fontFamily: MONO, fontWeight: 900 } },
  PL_MessageBody: { type: 'Text', fontSize: 8, color: 'theme:textDim', numberOfLines: 2, style: { fontFamily: MONO, lineHeight: 11 } },
  PL_MarketHero: { type: 'Box', style: { minHeight: 150, alignItems: 'center', justifyContent: 'center', gap: 6, backgroundColor: 'theme:onTrack', borderBottomWidth: 1, borderBottomColor: 'theme:accent' } },
  PL_MarketLabel: { type: 'Text', fontSize: 8, color: 'theme:textDim', noWrap: true, style: { fontFamily: MONO, fontWeight: 900, letterSpacing: 0.7 } },
  PL_MarketPrice: { type: 'Text', fontSize: 28, color: 'theme:accent', noWrap: true, style: { fontFamily: MONO, fontWeight: 900 } },
  PL_MarketMeta: { type: 'Text', fontSize: 8, color: 'theme:warning', noWrap: true, style: { fontFamily: MONO, fontWeight: 800 } },
  PL_PhoneNav: { type: 'Box', style: { height: 30, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', paddingLeft: 8, paddingRight: 8, backgroundColor: 'theme:bg', borderTopWidth: 1, borderTopColor: 'theme:border' } },
  PL_PhoneNavText: { type: 'Text', fontSize: 7, color: 'theme:textDim', noWrap: true, style: { fontFamily: MONO, fontWeight: 800 } },

  // Lightweight identity channel. It deliberately remains a separate surface:
  // ticker updates cannot make its glyph buffer churn.
  PL_IdentitySurface: { type: 'StaticSurface', blocksPointerEvents: true, style: { position: 'absolute', left: 24, bottom: 22, width: 250, height: 244, flexDirection: 'column', padding: 10, gap: 8, backgroundColor: 'theme:bgAlt', borderWidth: 2, borderColor: 'theme:info', borderRadius: 3, transform: { rotate: 0.35 } } },
  PL_IdentityHead: { type: 'Box', style: { height: 18, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: 'theme:borderSoft' } },
  PL_IdentityLabel: { type: 'Text', fontSize: 8, color: 'theme:info', noWrap: true, style: { fontFamily: MONO, fontWeight: 900, letterSpacing: 0.7 } },
  PL_IdentityBody: { type: 'Box', style: { flexGrow: 1, minHeight: 0, flexDirection: 'row', gap: 10 } },
  PL_Portrait: { type: 'Box', style: { width: 70, height: 118, alignItems: 'center', justifyContent: 'center', backgroundColor: 'theme:controlBg', borderWidth: 1, borderColor: 'theme:info', borderRadius: 2 } },
  PL_PortraitHead: { type: 'Box', style: { width: 33, height: 38, borderRadius: 17, backgroundColor: 'theme:textDim', borderWidth: 1, borderColor: 'theme:textSecondary' } },
  PL_PortraitShoulders: { type: 'Box', style: { width: 56, height: 34, marginTop: 2, borderRadius: 19, backgroundColor: 'theme:textDim', borderWidth: 1, borderColor: 'theme:textSecondary' } },
  PL_Stats: { type: 'Box', style: { flexGrow: 1, minWidth: 0, flexDirection: 'column', gap: 5 } },
  PL_PlayerName: { type: 'Text', fontSize: 9, color: 'theme:text', noWrap: true, numberOfLines: 1, style: { fontFamily: MONO, fontWeight: 900 } },
  PL_PlayerMeta: { type: 'Text', fontSize: 7, color: 'theme:textDim', noWrap: true, style: { fontFamily: MONO } },
  PL_MeterRow: { type: 'Box', style: { height: 12, flexDirection: 'row', alignItems: 'center', gap: 5 } },
  PL_MeterLabel: { type: 'Text', fontSize: 7, color: 'theme:textDim', noWrap: true, style: { width: 55, fontFamily: MONO, fontWeight: 800 } },
  PL_MeterTrack: { type: 'Box', style: { flexGrow: 1, minWidth: 0, height: 5, backgroundColor: 'theme:track', borderRadius: 2, overflow: 'hidden' } },
  PL_MeterFill: { type: 'Box', style: { height: '100%', backgroundColor: 'theme:primary', borderRadius: 2 } },
  PL_MeterValue: { type: 'Text', fontSize: 7, color: 'theme:textSecondary', noWrap: true, style: { width: 24, textAlign: 'right', fontFamily: MONO, fontWeight: 800 } },
  PL_IdentityFoot: { type: 'Box', style: { minHeight: 35, flexDirection: 'column', gap: 5, paddingTop: 6, borderTopWidth: 1, borderTopColor: 'theme:borderSoft' } },
  PL_DebtText: { type: 'Text', fontSize: 8, color: 'theme:error', noWrap: true, style: { fontFamily: MONO, fontWeight: 900 } },
  PL_StatusLine: { type: 'Text', fontSize: 7, color: 'theme:textDim', noWrap: true, style: { fontFamily: MONO, fontWeight: 800 } },
});

export { P };
