// Auto-generated by scripts/bake-icons.js — do not edit.
// Names of icons present in the SDF atlas (framework/gpu/icon_atlas.zig).
// Icon.tsx checks membership before routing to the SDF primitive; misses
// fall through to the legacy <Graph.Path> renderer.

export const BAKED_ICON_NAMES: ReadonlySet<string> = new Set([
  "Heart",
  "Search",
  "ArrowRight",
  "Plus",
  "X",
  "Settings",
  "Star",
  "Home",
  "Eye",
  "User",
  "Bell",
  "Bookmark",
]);
