import type { DocIndex } from '../types';

export const cutout: DocIndex = {
  name: 'cutout',
  file: 'cutout.md',
  cart: 'cart/cutout/index.tsx',
  purpose: ['asset_pipeline', 'shader', 'texture_bake', 'persistence', 'ui'],
  loc: 0,
  summary:
    'A full image cutout and shader-quad-image editor: loads an image or blank canvas, builds a unified stack of mask layers (base smart-selection + brush override per layer), supports flood/SAM smart selection, previews masks through GPU shader overlays, and exports PNG cutouts, pixel-icon JSON, or self-contained .sqi.json documents.',
  interfaces: [
    {
      name: 'CutoutApp',
      purpose: ['ui'],
      kind: 'component',
      sourceFile: 'cart/cutout/index.tsx',
      codeRef: 'cart/cutout/index.tsx:20-47',
      description:
        'Default app component and layout shell. Calls useCutoutState() once, owns only effectDraft (custom-FX modal state), renders TopBar/Tools/Editor/Inspector/StatusBar and EffectModal; wires EffectModal.onAdd to s.addCustomSurface.',
      dependsOn: ['useCutoutState', 'TopBar', 'Tools', 'Editor', 'Inspector', 'StatusBar', 'EffectModal'],
      status: 'live',
    },
    {
      name: 'useCutoutState',
      purpose: ['ui', 'persistence', 'asset_pipeline'],
      kind: 'hook',
      sourceFile: 'cart/cutout/state.ts',
      codeRef: 'cart/cutout/state.ts:267',
      description:
        'Active state hook and behavior API; single source of truth for active behavior. One layer stack, two mask textures per layer, direct GPU writes for brush dabs, RLE/readback only at commit/export boundaries.',
      dependsOn: ['useHistory', 'SelectionBackend', 'paintableOps', 'useIFTTT'],
      consumes: ['cart/cutout/sessions/_last.txt', '__paintable_circle', '__paintable_polygon', '__paintable_clear', '__paintable_upload', '__paintable_readback'],
      emits: ['cart/cutout/sessions/<stem>.session.json', 'cart/pixel_icons/<stem>.cutout.png', 'cart/pixel_icons/<stem>.sqi.json'],
      consumers: ['cart/cutout'],
      status: 'live',
    },
    {
      name: 'CutoutState',
      purpose: ['ui'],
      kind: 'data_model',
      sourceFile: 'cart/cutout/state.ts',
      codeRef: 'cart/cutout/state.ts:125-234',
      description:
        'Public state API consumed by components: source identity, status, tool config, lasso ops, layer ops, smart-selection controls, FX defaults, export actions, autosave metadata, undo/redo, layer clipboard ops.',
      status: 'live',
    },
    {
      name: 'Layer',
      purpose: ['asset_pipeline', 'texture_bake'],
      kind: 'data_model',
      sourceFile: 'cart/cutout/state.ts',
      codeRef: 'cart/cutout/state.ts:83-97',
      description:
        'One editable mask layer: id/name/optional groupName, LayerConfig, baseId (smart-selection base paintable), brushId (manual override paintable), clicks (smart-select history).',
      dependsOn: ['LayerConfig', 'Paintable'],
      status: 'live',
    },
    {
      name: 'effectiveMask',
      purpose: ['asset_pipeline'],
      kind: 'utility',
      sourceFile: 'cart/cutout/state.ts',
      codeRef: 'cart/cutout/state.ts:114-123',
      description:
        'Composes base and brush bytes into a binary CPU mask for export, snapshotting, merge, and invert. Rule: force-remove wins, force-keep cancels base, otherwise smart base decides.',
      status: 'live',
    },
    {
      name: 'scaleMask',
      purpose: ['texture_bake'],
      kind: 'utility',
      sourceFile: 'cart/cutout/state.ts',
      codeRef: 'cart/cutout/state.ts:105-109',
      description: 'Converts backend 0/1 masks to 0/255 bytes for R8 texture sampling.',
      status: 'live',
    },
    {
      name: 'composeExportMask',
      purpose: ['asset_pipeline'],
      kind: 'utility',
      sourceFile: 'cart/cutout/state.ts',
      codeRef: 'cart/cutout/state.ts:856-867',
      description: 'Unions every unmuted layer effective mask into one source-resolution Uint8Array where 1 means removed.',
      status: 'live',
    },
    {
      name: 'saveCutout',
      purpose: ['asset_pipeline'],
      kind: 'utility',
      sourceFile: 'cart/cutout/state.ts',
      codeRef: 'cart/cutout/state.ts:882-894',
      description:
        'Writes a PNG cutout to cart/pixel_icons/<stem>.cutout.png; requires a source image and non-empty mask; delegates alpha composition to compositeCutout.',
      dependsOn: ['compositeCutout'],
      emits: ['cart/pixel_icons/<stem>.cutout.png'],
      status: 'live',
    },
    {
      name: 'saveIcons',
      purpose: ['asset_pipeline'],
      kind: 'utility',
      sourceFile: 'cart/cutout/state.ts',
      codeRef: 'cart/cutout/state.ts:896-907',
      description: 'Writes pixel-icon JSON (.64/.128/.512.json) via exportIcons; requires source image and non-empty mask.',
      dependsOn: ['exportIcons'],
      emits: ['cart/pixel_icons/<stem>.64.json', 'cart/pixel_icons/<stem>.128.json', 'cart/pixel_icons/<stem>.512.json'],
      status: 'live',
    },
    {
      name: 'saveSqi',
      purpose: ['asset_pipeline', 'format'],
      kind: 'utility',
      sourceFile: 'cart/cutout/state.ts',
      codeRef: 'cart/cutout/state.ts:909-939',
      description:
        'Bakes base pixel matrix via bakeMatrix, converts each visible layer effective mask to a 128x128 cell set, calls buildSqi, writes cart/pixel_icons/<stem>.sqi.json; requires source image and non-empty mask.',
      dependsOn: ['bakeMatrix', 'buildSqi'],
      emits: ['cart/pixel_icons/<stem>.sqi.json'],
      status: 'live',
    },
    {
      name: 'importSqi',
      purpose: ['asset_pipeline', 'format'],
      kind: 'utility',
      sourceFile: 'cart/cutout/state.ts',
      codeRef: 'cart/cutout/state.ts:941-992',
      description:
        'Opens an optional Zenity picker, parses a .sqi.json, creates a blank square canvas, adopts built-in/custom surfaces, inflates each SQI layer mask into a full-res base texture, queues paintable uploads.',
      dependsOn: ['parseSqi', 'adoptSurface'],
      consumes: ['execAsync'],
      status: 'live',
    },
    {
      name: 'applyDoc',
      purpose: ['persistence'],
      kind: 'utility',
      sourceFile: 'cart/cutout/state.ts',
      codeRef: 'cart/cutout/state.ts:1020-1074',
      description:
        'Restores a SessionDocument: reopens backend/grayscale resources, creates paintable upload work, restores layer state, FX defaults, custom surfaces, status.',
      dependsOn: ['SessionDocument'],
      status: 'live',
    },
    {
      name: 'LayerConfig',
      purpose: ['shader', 'ui'],
      kind: 'data_model',
      sourceFile: 'cart/cutout/domain.ts',
      codeRef: 'cart/cutout/domain.ts:39-55',
      description: 'Per-layer visual config: surface mode, blend, hue offset, phase offset, muted flag, color slots, dim alpha.',
      status: 'live',
    },
    {
      name: 'CompositionLayer',
      purpose: ['ui'],
      kind: 'data_model',
      sourceFile: 'cart/cutout/domain.ts',
      codeRef: 'cart/cutout/domain.ts:64-75',
      description: 'Models a composited layer entry with id, kind, name, group, source index, and visibility.',
      status: 'live',
    },
    {
      name: 'inflateSurface',
      purpose: ['shader', 'format'],
      kind: 'utility',
      sourceFile: 'cart/cutout/domain.ts',
      codeRef: 'cart/cutout/domain.ts:114-119',
      description: 'Converts a SurfaceId plus custom surface gallery into a self-contained export surface.',
      status: 'live',
    },
    {
      name: 'adoptSurface',
      purpose: ['shader', 'format'],
      kind: 'utility',
      sourceFile: 'cart/cutout/domain.ts',
      codeRef: 'cart/cutout/domain.ts:124-133',
      description: 'Imports a self-contained SQI surface into the in-memory custom surface gallery.',
      status: 'live',
    },
    {
      name: 'SelectionBackend',
      purpose: ['asset_pipeline'],
      kind: 'data_model',
      sourceFile: 'cart/cutout/backends/types.ts',
      codeRef: 'cart/cutout/backends/types.ts:46-62',
      description: 'Smart-selection backend contract: name, open, refine, close. Keeps UI independent from flood/SAM implementation.',
      status: 'live',
    },
    {
      name: 'createFloodBackend',
      purpose: ['asset_pipeline'],
      kind: 'utility',
      sourceFile: 'cart/cutout/backends/flood.ts',
      codeRef: 'cart/cutout/backends/flood.ts:33-194',
      description:
        'Always-available ImageMagick flood-fill backend. refine recomputes from complete click history; keep clicks flood-fill with a magenta sentinel + fuzz; reject clicks draw a disk mask; final mask unions keeps and subtracts rejects.',
      dependsOn: ['SelectionBackend'],
      consumes: ['run', 'readFile', 'writeFile', 'mkdir'],
      consumers: ['cart/cutout'],
      status: 'live',
    },
    {
      name: 'createSamBackend',
      purpose: ['asset_pipeline', 'perception'],
      kind: 'utility',
      sourceFile: 'cart/cutout/backends/sam.ts',
      codeRef: 'cart/cutout/backends/sam.ts:32-97',
      description:
        'MobileSAM/ONNX backend. open checks ONNX availability and opens the source image; refine clamps clicks, passes threshold/mask index to refineSegment, returns one fused mask with no per-keep layers.',
      dependsOn: ['SelectionBackend'],
      consumes: ['openImage', 'refineSegment', 'closeImage', 'isSegmentAvailable'],
      status: 'live',
    },
    {
      name: 'identify',
      purpose: ['asset_pipeline'],
      kind: 'utility',
      sourceFile: 'cart/cutout/magick.ts',
      codeRef: 'cart/cutout/magick.ts:13-20',
      description: "Runs magick identify -format '%w %h' to get image dimensions.",
      consumes: ['run'],
      status: 'live',
    },
    {
      name: 'compositeCutout',
      purpose: ['asset_pipeline'],
      kind: 'utility',
      sourceFile: 'cart/cutout/magick.ts',
      codeRef: 'cart/cutout/magick.ts:67-89',
      description: 'Writes a mask PGM and runs ImageMagick CopyOpacity to produce a PNG cutout.',
      consumes: ['run'],
      status: 'live',
    },
    {
      name: 'exportIcons',
      purpose: ['asset_pipeline', 'texture_bake'],
      kind: 'utility',
      sourceFile: 'cart/cutout/icons.ts',
      codeRef: 'cart/cutout/icons.ts:126-156',
      description: 'Writes cart/pixel_icons/<stem>.<size>.json for each requested size (64/128/512).',
      consumes: ['run'],
      emits: ['cart/pixel_icons/<stem>.<size>.json'],
      status: 'live',
    },
    {
      name: 'bakeMatrix',
      purpose: ['texture_bake', 'format'],
      kind: 'utility',
      sourceFile: 'cart/cutout/icons.ts',
      codeRef: 'cart/cutout/icons.ts:111-118',
      description: 'Writes one PGM mask and returns an encoded matrix for SQI base image embedding.',
      status: 'live',
    },
    {
      name: 'mask helpers',
      purpose: ['math', 'geometry'],
      kind: 'module',
      sourceFile: 'cart/cutout/mask.ts',
      description:
        'Pure CPU mask/geometry helpers: paintCircle, sobelMagnitudeSq, snapToStrongGradient, paintCircleEdgeAware, fillPolygon, hasAnyErased, sampleToCells, rowRuns.',
      status: 'live',
    },
    {
      name: 'rle (re-export)',
      purpose: ['format'],
      kind: 'import',
      sourceFile: 'cart/cutout/rle.ts',
      codeRef: 'cart/cutout/rle.ts:7',
      description: 'Compatibility shim re-exporting @reactjit/workspace/rle; the local RLE codec was promoted to shared workspace code.',
      imports: ['@reactjit/workspace/rle'],
      status: 'deprecated',
    },
    {
      name: 'SessionDocument',
      purpose: ['persistence', 'format'],
      kind: 'data_model',
      sourceFile: 'cart/cutout/session.ts',
      codeRef: 'cart/cutout/session.ts:60-96',
      description:
        'Active v2 working-session format (SESSION_VERSION=2): source identity, tool config, layer stack, active layer, effect defaults, custom surfaces, backend choice, backend tunables. Same serializable document powers autosave, restore, and undo/redo.',
      status: 'live',
    },
    {
      name: 'buildSession',
      purpose: ['persistence', 'format'],
      kind: 'utility',
      sourceFile: 'cart/cutout/session.ts',
      codeRef: 'cart/cutout/session.ts:177-213',
      description: 'Encodes layer base masks as binary RLE and brush overrides as arbitrary-value grid RLE.',
      status: 'live',
    },
    {
      name: 'parseSession',
      purpose: ['persistence', 'format'],
      kind: 'utility',
      sourceFile: 'cart/cutout/session.ts',
      codeRef: 'cart/cutout/session.ts:215-223',
      description: 'Accepts only kind cutout-session and version 2; intentionally does not parse v1 sessions.',
      status: 'live',
    },
    {
      name: 'session_old',
      purpose: ['persistence', 'format'],
      kind: 'data_model',
      sourceFile: 'cart/cutout/session_old.ts',
      description:
        'Legacy v1 session format storing a global mask, hasBrushLayer, click history, overlay cell layers, layer configs, custom surfaces, optional composition layers. Exports inflateSessionMasks (not v2 inflateSessionLayers). Not imported by the active app.',
      status: 'deprecated',
    },
    {
      name: 'SqiDocument',
      purpose: ['format', 'shader', 'asset_pipeline'],
      kind: 'data_model',
      sourceFile: 'cart/cutout/sqi.ts',
      codeRef: 'cart/cutout/sqi.ts:72-86',
      description:
        '.sqi.json self-contained shader quad image: kind sqi, version, metadata, thumbnail, size, stem, quantized base pixel matrix, and N shader FX layers. No external image path required; built-in surfaces by name, custom inline id/label/WGSL.',
      dependsOn: ['rle (re-export)'],
      status: 'live',
    },
    {
      name: 'buildSqi',
      purpose: ['format', 'shader'],
      kind: 'utility',
      sourceFile: 'cart/cutout/sqi.ts',
      codeRef: 'cart/cutout/sqi.ts:124-160',
      description: 'Converts layer masks/configs/custom surfaces into a v2 SQI document.',
      status: 'live',
    },
    {
      name: 'parseSqi',
      purpose: ['format'],
      kind: 'utility',
      sourceFile: 'cart/cutout/sqi.ts',
      codeRef: 'cart/cutout/sqi.ts:162-189',
      description: 'Validates SQI versions 1 and 2 and normalizes older custom surface fields.',
      status: 'live',
    },
    {
      name: 'ShaderQuadImage',
      purpose: ['shader', 'rendering'],
      kind: 'component',
      sourceFile: 'cart/cutout/components/ShaderQuadImage.tsx',
      codeRef: 'cart/cutout/components/ShaderQuadImage.tsx:25-31',
      description:
        'Drop-in renderer for .sqi.json documents: accepts a parsed SqiDocument or a filesystem src path, renders a fixed-size Box with BaseQuad and one LayerQuad per unmuted layer. BASE_SHADER renders the encoded base pixel matrix from a storage buffer.',
      dependsOn: ['parseSqi', 'MaskQuad'],
      consumes: ['readFile'],
      status: 'live',
    },
    {
      name: 'Editor',
      purpose: ['ui', 'rendering', 'interaction'],
      kind: 'component',
      sourceFile: 'cart/cutout/components/Editor.tsx',
      description:
        'Center workspace: Canvas with source Image/BlankSurface, two invisible Paintable primitives per layer (baseId/brushId), MaskQuad per visible layer, ClickMarkers, LassoPreview, BrushCursor, EditorHud. Separates screen, Canvas world, and source pixel coordinates (screenToWorld via __canvas_screen_to_graph, toSource).',
      dependsOn: ['MaskQuad', 'Paintable', 'Canvas'],
      consumes: ['__canvas_screen_to_graph'],
      status: 'live',
    },
    {
      name: 'MaskQuad',
      purpose: ['shader', 'rendering', 'texture_bake'],
      kind: 'component',
      sourceFile: 'cart/cutout/components/MaskQuad.tsx',
      codeRef: 'cart/cutout/components/MaskQuad.tsx:443-524',
      description:
        'Reusable GPU shader overlay for a mask: packs header values/color slots/optional cells into a numeric data array, uses texture mode when paintableId present (samples mask_tex + smart_tex reused as brush override), passes textures={[paintableId, overrideId]} to Effect. Major reusable game concept: a mask becomes a visible animated/materialized region without changing mask data.',
      dependsOn: ['Effect'],
      status: 'live',
    },
    {
      name: 'MaskSurface',
      purpose: ['shader'],
      kind: 'registry',
      sourceFile: 'cart/cutout/components/MaskQuad.tsx',
      codeRef: 'cart/cutout/components/MaskQuad.tsx:32',
      description: 'Built-in visual surface modes: rainbow, plasma, voronoi, fbm, solid, edges. Exported as MASK_SURFACES list.',
      status: 'live',
    },
    {
      name: 'CustomSurface',
      purpose: ['shader'],
      kind: 'data_model',
      sourceFile: 'cart/cutout/components/MaskQuad.tsx',
      codeRef: 'cart/cutout/components/MaskQuad.tsx:35-39',
      description: 'User-authored WGSL surface: id, label, shader. Built-in and custom surfaces share one SurfaceId model.',
      status: 'live',
    },
    {
      name: 'buildShader / buildTextureShader',
      purpose: ['shader'],
      kind: 'shader',
      sourceFile: 'cart/cutout/components/MaskQuad.tsx',
      codeRef: 'cart/cutout/components/MaskQuad.tsx:201-393',
      description:
        'WGSL builders: buildShader (201-257) creates cells-mode WGSL for cell-set masks; buildTextureShader (338-393) creates texture-mode WGSL sampling mask_tex/smart_tex. Cached in SHADER_CACHE and TEX_SHADER_CACHE.',
      status: 'live',
    },
    {
      name: 'TopBar',
      purpose: ['ui'],
      kind: 'component',
      sourceFile: 'cart/cutout/components/TopBar.tsx',
      codeRef: 'cart/cutout/components/TopBar.tsx:14-146',
      description:
        'Title strip and action toolbar (windowDrag title row), file actions, BrushSlider, WindowControls (__window_minimize/maximize/close), ContextMenu with reserved/disabled recent-files and multi-tab entries.',
      consumes: ['__window_minimize', '__window_maximize', '__window_close'],
      status: 'live',
    },
    {
      name: 'Tools',
      purpose: ['ui', 'interaction'],
      kind: 'component',
      sourceFile: 'cart/cutout/components/Tools.tsx',
      codeRef: 'cart/cutout/components/Tools.tsx:34-116',
      description:
        'Left tool rail: TOOLS (hand/brush/refine/lasso/smart), MODES (erase/restore), PALETTE swatches; calls s.setTool/setMode/clearMask/invertMask/setEffectColor.',
      status: 'live',
    },
    {
      name: 'Inspector',
      purpose: ['ui'],
      kind: 'component',
      sourceFile: 'cart/cutout/components/Inspector.tsx',
      codeRef: 'cart/cutout/components/Inspector.tsx:73-197',
      description:
        'Right panel with Tool/FX/Source tabs and resizable layer section. Sub-blocks: ToolProperties, BackendPicker, BackendTunables, SurfaceProperties, ParametersBlock, SourceProperties, CanvasSizeEditor, AdvancedProperties, LayersPanel, LayerRow, SurfacePreview, EffectModal.',
      dependsOn: ['MaskQuad'],
      status: 'live',
    },
    {
      name: 'AdvancedProperties',
      purpose: ['ui', 'debug'],
      kind: 'component',
      sourceFile: 'cart/cutout/components/Inspector.tsx',
      codeRef: 'cart/cutout/components/Inspector.tsx:811-844',
      description: 'ONNX runtime test UI; exists in Inspector.tsx but is NOT rendered by the active tab switch.',
      status: 'dormant',
    },
    {
      name: 'StatusBar',
      purpose: ['ui', 'telemetry'],
      kind: 'component',
      sourceFile: 'cart/cutout/components/StatusBar.tsx',
      codeRef: 'cart/cutout/components/StatusBar.tsx:16-65',
      description:
        'Bottom status strip: status text plus cells for FPS, zoom, canvas, size estimate, mask, layers, clicks, saved age. Uses useTelemetry({kind:fps}) and useTelemetry({kind:canvas}) polling every 1000 ms. estimateFileSize is display-only.',
      consumes: ['useTelemetry'],
      status: 'live',
    },
    {
      name: 'theme (COLORS/SIZES)',
      purpose: ['ui'],
      kind: 'module',
      sourceFile: 'cart/cutout/theme.ts',
      codeRef: 'cart/cutout/theme.ts:5-29',
      description: 'Shared dark UI palette (COLORS, 5-20) and layout sizes (SIZES, 22-29).',
      status: 'live',
    },
    {
      name: 'state_old',
      purpose: ['ui', 'maintenance'],
      kind: 'module',
      sourceFile: 'cart/cutout/state_old.ts',
      description:
        'Legacy useCutoutState model: global source-resolution mask/paint layer plus smart overlay cell layers and a smart-union paintable (compositionLayers, smartLayerMeta, maskId, smartUnionId). Replaced by the unified layer stack; not imported.',
      status: 'deprecated',
    },
    {
      name: 'Editor_old / Inspector_old',
      purpose: ['ui', 'maintenance'],
      kind: 'module',
      sourceFile: 'cart/cutout/components/Editor_old.tsx',
      description:
        'Legacy editor/inspector snapshots for the previous global-brush-plus-smart-layer mask architecture (global Paintable for maskId + smartUnionId, imported rowRuns). Reference only, not imported.',
      status: 'deprecated',
    },
  ],
  patterns: [
    {
      name: 'Layer as gameplay/render concept',
      purpose: ['asset_pipeline', 'rendering'],
      description: 'Layer ties identity, user-facing name, mask data, click history, and material config together into one object.',
      examples: ['cutout'],
      status: 'recurring',
    },
    {
      name: 'Dual-source mask composition',
      purpose: ['asset_pipeline'],
      description: 'A generated base plus a manual override mask, composed by force-remove/force-keep/smart-base rules — strong for tools where procedural output needs hand correction.',
      examples: ['cutout'],
      status: 'recurring',
    },
    {
      name: 'Declarative self-contained artifact format',
      purpose: ['format', 'asset_pipeline'],
      description: '.sqi.json contains base pixels, layer masks, and shader surfaces with no external asset dependencies.',
      examples: ['cutout'],
      status: 'recurring',
    },
    {
      name: 'Shader surface registry',
      purpose: ['shader'],
      description: 'Built-in and custom WGSL surfaces share one SurfaceId/CustomSurface model.',
      examples: ['cutout'],
      promoteTo: '@reactjit/effects',
      status: 'promote',
    },
    {
      name: 'Host texture as state',
      purpose: ['texture_bake'],
      description: 'Paintable keeps high-frequency pixel edits outside React state but still lets React declare where the texture exists; readback/upload only at discrete operations.',
      examples: ['cutout'],
      status: 'recurring',
    },
    {
      name: 'Backend interface seam',
      purpose: ['asset_pipeline'],
      description: 'SelectionBackend keeps UI independent from flood/SAM implementation details.',
      examples: ['cutout'],
      status: 'recurring',
    },
    {
      name: 'Session snapshot model',
      purpose: ['persistence'],
      description: 'One serializable SessionDocument powers autosave, restore, and undo/redo.',
      examples: ['cutout'],
      status: 'recurring',
    },
    {
      name: 'Source coordinate discipline',
      purpose: ['interaction', 'rendering'],
      description: 'Editor explicitly separates screen, Canvas world, and source pixel coordinates (screenToWorld then toSource).',
      examples: ['cutout'],
      status: 'recurring',
    },
    {
      name: 'Local RLE codec promoted to shared workspace',
      purpose: ['format', 'maintenance'],
      description: 'cart/cutout/rle.ts is now a re-export shim of @reactjit/workspace/rle; the local codec was promoted to shared workspace code.',
      examples: ['cutout'],
      promoteTo: '@reactjit/workspace/rle',
      status: 'resolved',
    },
  ],
  hazards: [
    {
      name: 'smart_tex is actually the brush override texture',
      purpose: ['shader', 'texture_bake'],
      description:
        'In texture-mode MaskQuad, the shader binding named smart_tex is reused as the brush override texture, not a smart-selection texture — a naming lie that will mislead an agent reading the shader.',
      evidence: ['cart/cutout/components/MaskQuad.tsx:283-336 — TEX_COMMON_PRELUDE samples mask_tex and smart_tex, where smart_tex is reused as the brush override texture'],
      severity: 'high',
    },
    {
      name: 'AdvancedProperties / ONNX test UI is dead',
      purpose: ['debug', 'ui'],
      description: 'AdvancedProperties and its ONNX runtime test UI exist in Inspector.tsx but are never rendered by the active tab switch.',
      evidence: ['cart/cutout/components/Inspector.tsx:811-844 — AdvancedProperties not rendered by active tab switch'],
      severity: 'low',
    },
    {
      name: 'Blank canvases are editable but not exportable',
      purpose: ['asset_pipeline'],
      description: 'saveCutout, saveIcons, and saveSqi all require srcPath, so a blank-canvas document cannot be exported through those paths despite being editable.',
      evidence: ['cart/cutout/state.ts:882-939 — export paths require srcPath'],
      severity: 'medium',
    },
    {
      name: 'MaskQuad has two modes (cell-set vs texture)',
      purpose: ['shader', 'rendering'],
      description: 'MaskQuad supports both cell-set and texture modes; the active editor uses texture mode while SQI rendering uses cell-set mode — easy to assume only one path exists.',
      evidence: ['cart/cutout/components/MaskQuad.tsx — texture mode for editor, cell-set mode for SQI render'],
      severity: 'medium',
    },
    {
      name: 'SAM emits no per-keep overlay layers',
      purpose: ['asset_pipeline', 'perception'],
      description: 'SAM returns one fused mask and no per-keep overlay layers; flood can emit per-keep cell sets, but the unified layer state uploads only the fused result to the layer base anyway.',
      evidence: ['cart/cutout/backends/sam.ts:60-87; backends/flood.ts:178-185'],
      severity: 'low',
    },
    {
      name: 'External subprocess deps (ImageMagick, Zenity)',
      purpose: ['asset_pipeline'],
      description: 'ImageMagick and Zenity are external subprocess dependencies; missing commands surface only as failed process results / status text, not hard errors.',
      evidence: ['cart/cutout/magick.ts; cart/cutout/state.ts pickFile/importSqi use execAsync for zenity'],
      severity: 'medium',
    },
    {
      name: 'Session v2 does not migrate v1',
      purpose: ['persistence', 'format'],
      description: 'parseSession intentionally accepts only kind cutout-session version 2; session_old.ts (v1) remains as reference, not a migration path.',
      evidence: ['cart/cutout/session.ts:215-223; session_old.ts'],
      severity: 'medium',
    },
    {
      name: 'Writes generated artifacts inside the repo',
      purpose: ['persistence', 'maintenance'],
      description: 'The app writes outputs and sessions inside the repo (cart/pixel_icons, cart/cutout/sessions), so generated artifacts appear as working-tree changes.',
      evidence: ['cart/cutout/state.ts — saveCutout/saveIcons/saveSqi write cart/pixel_icons; autosave writes cart/cutout/sessions'],
      severity: 'low',
    },
    {
      name: 'encodeMaskPGM inverts the cart mask convention',
      purpose: ['asset_pipeline'],
      description: 'encodeMaskPGM inverts the cart mask convention so ImageMagick alpha composition gets opaque/transparent correct — a sign-flip that will confuse anyone tracing mask values through magick.',
      evidence: ['cart/cutout/magick.ts:52-62'],
      severity: 'medium',
    },
    {
      name: '_old files are reference, not current behavior',
      purpose: ['maintenance'],
      description: 'state_old/session_old/Editor_old/Inspector_old remain in the folder but are not imported by the active path; they describe the superseded global-brush+smart-layer architecture and should not be read as current behavior.',
      evidence: ['cart/cutout — active imports are state.ts/Editor.tsx/Inspector.tsx/session.ts'],
      severity: 'medium',
    },
  ],
};
