import type { DocIndex } from '../types';

export const hmsc: DocIndex = {
  name: 'hmsc',
  file: 'hmsc.md',
  cart: 'cart/hmsc/index.tsx',
  purpose: [
    'world_gen',
    'rendering',
    'physics',
    'npc',
    'building',
    'pathing',
    'persistence',
    'scripting',
    'character',
  ],
  loc: 1203,
  summary:
    'HMSC ("Hitman Shitcity") is the main playable game cart — a blank game shell whose every mutation flows through commands, whose runtime is one JSON-serializable GameState, rendered as a Scene3D tree plus 2D StaticSurface/Effect texture captures, with grid authoring, host physics, events, zones, buildings, roads, props, landforms, NPCs, and in-cart labs.',
  interfaces: [
    // ---- cart shell / composition root ----
    {
      name: 'index.tsx (HMSC composition root)',
      purpose: ['game_loop', 'rendering', 'persistence'],
      kind: 'module',
      sourceFile: 'cart/hmsc/index.tsx',
      description:
        'Composition root. Seeds state via readStoredGameState() ?? createInitialGameState(), holds React state for gameState/commandLine/console, calls useHmscEventRules(setGameState), publishes game.booted, publishes a compact live player snapshot every DEFAULT_LIVE_SYNC_INTERVAL_MS, mirrors full state for hot reload every 2000ms, autosaves every DEFAULT_AUTOSAVE_INTERVAL_MS, advances sky every SKY_TICK_INTERVAL_MS, submits console text through runCommandLine, and renders HmscGameplayRig full-screen plus a Console overlay. Uses setInterval, Date.now and Math.random (console ids only).',
      dependsOn: ['runCommandLine', 'useHmscEventRules', 'HmscGameplayRig', 'gameState.ts'],
      emits: ['game.booted'],
      status: 'live',
    },
    {
      name: 'cart.json',
      purpose: ['format'],
      kind: 'data_model',
      sourceFile: 'cart/hmsc/cart.json',
      description: 'Manifest declaring cart name HMSC, description, and a default 1280x800 window.',
      status: 'live',
    },
    // ---- core state contract ----
    {
      name: 'GameState',
      purpose: ['persistence', 'format', 'world_gen'],
      kind: 'data_model',
      sourceFile: 'cart/hmsc/design.ts',
      description:
        'The single JSON-serializable state object: scene, config, command flags, story, event log, player, world, entity serial, and suspended interior worlds. design.ts also defines HMSC_STATE_SCHEMA_VERSION, intervals, grid cell size, chunk span, Vec3, GridCell, all tile kinds, player state, LivePlayerSnapshot, PlacedCell, SpawnedEntity, NPC state, event/story records, WorldState, building/prop/zone/road types, and command handler types. Type-only plus constants, no host calls.',
      status: 'live',
    },
    {
      name: 'WorldState',
      purpose: ['world_gen', 'format'],
      kind: 'data_model',
      sourceFile: 'cart/hmsc/design.ts',
      description:
        'The authored and live world container inside GameState: surface regions, placed cells, roads, junctions, props, buildings, interiors, landforms, zones, spawned entities, and NPCs.',
      status: 'live',
    },
    {
      name: 'LivePlayerSnapshot',
      purpose: ['persistence', 'telemetry', 'format'],
      kind: 'data_model',
      sourceFile: 'cart/hmsc/design.ts',
      description: 'Compact cross-cart/shared live-player state published on an interval.',
      status: 'live',
    },
    {
      name: 'state/defaults.ts',
      purpose: ['world_gen'],
      kind: 'module',
      sourceFile: 'cart/hmsc/state/defaults.ts',
      description:
        'Gameplay defaults and tuning numbers: player speeds, health, heat, money, event/console log limits, sky settings, view/draw radius, fog, physics, and drive constants (deadzone, max frame step, noclip floor, entity radii, burst counts). The main place tuning values live before becoming GameState.config values.',
      status: 'live',
    },
    {
      name: 'state/gameState.ts',
      purpose: ['persistence', 'world_gen', 'host_bridge'],
      kind: 'module',
      sourceFile: 'cart/hmsc/state/gameState.ts',
      description:
        'Owns save/load, hot-reload mirror, live-player publish, and initial seed world construction. Uses namespaced localstore first (__localstoreGet/__localstoreSet "hmsc") then generic __store_get/__store_set fallback; hot state via __hot_get/__hot_set. Builds a 2x2 seed world (sidewalk/road/sand/asphalt regions, roads, intersections, a cul-de-sac, props, landforms, many building examples). Computes initial player foot height; revives old saved state, rejects future schemas, merges defaults, repairs fields, handles layout-key mismatch. Host-backed persistence, no browser storage.',
      dependsOn: ['__localstoreGet', '__localstoreSet', '__store_get', '__store_set', '__hot_get', '__hot_set'],
      status: 'live',
    },
    {
      name: 'state/driveInScreens.ts',
      purpose: ['rendering'],
      kind: 'module',
      sourceFile: 'cart/hmsc/state/driveInScreens.ts',
      description:
        'Session-only singleton store for drive-in video source paths. Exposes getDriveInSource, setDriveInSource, subscribeDriveInSources, useDriveInSources. React state/subscriptions only, no host persistence.',
      status: 'live',
    },
    // ---- command system ----
    {
      name: 'runCommandLine',
      purpose: ['scripting', 'world_gen'],
      kind: 'utility',
      sourceFile: 'cart/hmsc/commands/registry.ts',
      description:
        'Source-of-truth command runner. Tokenizes input, looks up a command, executes it, then sends the result through recordCommandEvents (unknown commands pass through as failed command events). Uses __hmsc_spike_trace(1|0) from gv_perflog 2 when available. The stable user/tool mutation interface: console, triggers, interactions, labs, and authoring all go through it.',
      dependsOn: ['commands/parser.ts', 'recordCommandEvents'],
      consumes: ['__hmsc_spike_trace'],
      consumers: ['cart/hmsc/index.tsx', 'usePlayerDrive.ts', 'useBuildingInteract.ts'],
      status: 'live',
    },
    {
      name: 'commands/parser.ts',
      purpose: ['scripting', 'format'],
      kind: 'module',
      sourceFile: 'cart/hmsc/commands/parser.ts',
      description:
        'Tokenizes command lines: whitespace splitting plus single/double quoted strings, parses JSON-ish values (booleans, null, numbers, JSON objects/arrays, raw strings). Pure JS, no host calls.',
      status: 'live',
    },
    {
      name: 'HMSC command registry',
      purpose: ['scripting', 'world_gen'],
      kind: 'registry',
      sourceFile: 'cart/hmsc/commands/registry.ts',
      description:
        'The full command taxonomy by prefix (cmd_/gv_/pv_/wv_/ev_/lab_/a_): cmd_help, cmd_cheats; lab_list/spawn/exit; gv_controls/debug_hud/perflog/noise/sky/time/daycycle/weather/view/events/emit/state/config/save/load/reset/scene/set; pv_teleport/respawn/noclip/speed/where; ev_spawn/burst/despawn; wv_tile/place/fill/remove/trigger/path/road/intersection/culdesac/prop/signal/building/enter/leave/mountain/zone/validate. Includes helpers for success/failure, number/bool parsing, sky args, path read/write, spawn, and placement validation. Cheats gated through cmd_cheats; disabling cheats forces noclip off.',
      status: 'live',
    },
    // ---- events / story ----
    {
      name: 'events/gameEvents.ts',
      purpose: ['scripting', 'telemetry'],
      kind: 'module',
      sourceFile: 'cart/hmsc/events/gameEvents.ts',
      description:
        'HMSC event log + host/event-bus publishing. recordGameEvent appends a JSON-safe event (sequential ids like hmsc_evt_000001) with type/timestamp/source/scene/actor/subject/tags/player-snapshot/payload. publishGameEvent emits to the host event bus and ReactJIT IFTTT bus on root channel hmsc:event, typed channel hmsc:event:<type>, plus actor/subject/tag channels. recordAndPublishGameEvent combines mutation + emission. recordCommandEvents translates command results into standard events. Uses busEmit and hostEventBus.emit from @reactjit/hooks/useIFTTT.',
      dependsOn: ['busEmit', 'hostEventBus'],
      emits: ['hmsc:event', 'hmsc:event:*'],
      status: 'live',
    },
    {
      name: 'useHmscEventRules',
      purpose: ['scripting'],
      kind: 'hook',
      sourceFile: 'cart/hmsc/events/useHmscEventRules.ts',
      description:
        'Installs story rules with useIFTTT. Listens to hmsc:event:lab.entered (sets lab.<name>.visited flags) and hmsc:event:world.trigger.entered (sets trigger.<subjectId>.seen when a trigger label exists). Emits story.flag.set events when rules update story state.',
      dependsOn: ['useIFTTT'],
      consumes: ['hmsc:event:lab.entered', 'hmsc:event:world.trigger.entered'],
      emits: ['story.flag.set'],
      consumers: ['cart/hmsc/index.tsx'],
      status: 'live',
    },
    // ---- gameplay loop / input / physics ----
    {
      name: 'HmscGameplayRig',
      purpose: ['rendering', 'input', 'game_loop'],
      kind: 'component',
      sourceFile: 'cart/hmsc/gameplay/HmscGameplayRig.tsx',
      description:
        'Main playable surface wrapper. Renders Scene3D, sky, world, player, HUD, debug HUD, lab children, crosshair, interaction prompt, focus hint, and all offscreen texture captures. Calls usePlayerDrive, useTerrainColliders, useBuildingInteract. Reads host mouse via __mouse_delta/getMouseRightDown/getMouseX/getMouseY, captures via __mouse_capture(1|0), reads Escape via busOn(__keydown). rAF-or-setTimeout loop, performance.now-or-Date.now, JS yaw/pitch smoothing+clamping.',
      dependsOn: ['usePlayerDrive', 'useTerrainColliders', 'useBuildingInteract', 'GameWorld3D'],
      consumes: ['__mouse_delta', '__mouse_capture', 'getMouseRightDown', 'getMouseX', 'getMouseY', '__keydown'],
      status: 'live',
    },
    {
      name: 'gameplay/camera.ts',
      purpose: ['camera'],
      kind: 'module',
      sourceFile: 'cart/hmsc/gameplay/camera.ts',
      description:
        'Third-person camera constants: sensitivity, smoothing, frame clamp, pitch clamp, distance, height, target height, pitch target factor, fov, aim shoulder shift, aim fov. Exports value-clamp and degree-angle delta helpers.',
      status: 'live',
    },
    {
      name: 'input/controlContract.ts',
      purpose: ['input'],
      kind: 'module',
      sourceFile: 'cart/hmsc/input/controlContract.ts',
      description:
        'Canonical control action ids. Implemented/wired: mouse camera, right-hold aim, Shift run, Space jump, E/F interact. Reserved: primary action variants, reload, quick menu, crouch. Exposes inputBindingsForConsole() for gv_controls.',
      status: 'live',
    },
    {
      name: 'usePlayerDrive',
      purpose: ['input', 'physics', 'pathing'],
      kind: 'hook',
      sourceFile: 'cart/hmsc/state/usePlayerDrive.ts',
      description:
        'Drives player movement. Reads busOn(__keydown)/busOn(__keyup) and host scancodes via isKeyDown(scancode) for Shift/Space/Control/C. Frame loop rAF-or-setTimeout, performance.now-or-Date.now. Converts WASD/arrows into camera-yaw-relative basis, applies surface multipliers via movementSurfaceForPlayer. Noclip integrates x/y/z directly; normal mode prefers advanceHostPhysics, falling back to JS canOccupyWorldPosition + direct x/z. Emits player.cell.entered, runs placed-cell triggers via runCommandLine(source:world-trigger), handles save cells (respawn + save + world.save.recorded) and zone enter/exit. Suppresses cell triggers in labs.',
      dependsOn: ['advanceHostPhysics', 'movementSurfaceForPlayer', 'runCommandLine'],
      consumes: ['__keydown', '__keyup', 'isKeyDown'],
      emits: ['player.cell.entered', 'world.save.recorded'],
      status: 'live',
    },
    {
      name: 'useBuildingInteract',
      purpose: ['interaction', 'building'],
      kind: 'hook',
      sourceFile: 'cart/hmsc/state/useBuildingInteract.ts',
      description:
        'Resolves nearby building and drive-in interactions: interior doors (prompt wv_enter <id>), interior exit (wv_leave), drive-in booth. For drive-in movie selection calls execAsync("zenity --file-selection ...") then setDriveInSource. Listens to E/F via busOn(__keydown), sends interactions through runCommandLine.',
      dependsOn: ['execAsync', 'setDriveInSource', 'runCommandLine'],
      consumes: ['__keydown'],
      status: 'live',
    },
    {
      name: 'advanceHostPhysics (state/hostPhysics.ts)',
      purpose: ['physics', 'host_bridge'],
      kind: 'module',
      sourceFile: 'cart/hmsc/state/hostPhysics.ts',
      description:
        'Host physics bridge + JS packing layer. Calls __hmsc_physics_step(inputFloat32Array); returns null if absent so callers use fallback movement. Packs player state, spawned entities, axis-aligned rects, oriented rects, gravity, step height, movement surface, and counts into a Float32Array; parses the ArrayBuffer result back into player position/velocity/grounded and sorted entity states. Builds collision rects from surface regions, placed cells, roads, junctions, solid props, and buildings. Excludes landforms (registered as host heightfields via terrainColliders.ts). Supports oriented building collision when yaw is non-zero. Defines movement surface rules from the tile kind below the player.',
      consumes: ['__hmsc_physics_step'],
      status: 'live',
    },
    {
      name: 'useTerrainColliders (state/terrainColliders.ts)',
      purpose: ['physics', 'host_bridge'],
      kind: 'module',
      sourceFile: 'cart/hmsc/state/terrainColliders.ts',
      description:
        'Registers heightfield colliders with the host. Calls __hmsc_clear_heightfields() then __hmsc_register_heightfield(index, originX, originZ, cell, cols, rows, baseY, walkCos, heights, yaw, pivotX, pivotZ) for landforms and parking-garage ramp/deck colliders. No-ops cleanly if host functions are missing.',
      consumes: ['__hmsc_clear_heightfields', '__hmsc_register_heightfield'],
      status: 'live',
    },
    {
      name: 'state/perfWatch.ts',
      purpose: ['telemetry', 'debug'],
      kind: 'module',
      sourceFile: 'cart/hmsc/state/perfWatch.ts',
      description:
        'Diagnostic spike flight recorder toggled by gv_perflog. Reads __tel_history/__tel_frame/__tel_gpu/__tel_nodes/__tel_input, performance.now-or-Date.now, rAF-or-setTimeout, emits reports via console.warn. Tunable via configurePerfWatch.',
      consumes: ['__tel_history', '__tel_frame', '__tel_gpu', '__tel_nodes', '__tel_input'],
      status: 'live',
    },
    // ---- world model ----
    {
      name: 'world/scale.ts (HMSC_SCALE)',
      purpose: ['world_gen', 'math'],
      kind: 'module',
      sourceFile: 'cart/hmsc/world/scale.ts',
      description:
        'Physical scale constants establishing the rule 1 tile = 1 meter: player capsule height/radius, visual human min/max, door width/height, story height, car size, lane dimensions, step height.',
      status: 'live',
    },
    {
      name: 'world/grid.ts',
      purpose: ['world_gen', 'pathing'],
      kind: 'module',
      sourceFile: 'cart/hmsc/world/grid.ts',
      description:
        'Core grid/world query layer. Converts between continuous world coords and grid cells, builds cell/chunk keys, places/removes placed cells, adds surface regions, reads placed cell at grid/world position, sets cell triggers. Resolves tile kind by priority (landform water, placed cell, junction, road, landform tile, surface region) and ground top from surface regions, placed cells, roads, junctions, landforms. Checks pathability/occupancy, provides visible/nearby placed-cell helpers.',
      status: 'live',
    },
    {
      name: 'world/tileKinds.ts',
      purpose: ['world_gen', 'npc', 'pathing'],
      kind: 'registry',
      sourceFile: 'cart/hmsc/world/tileKinds.ts',
      description:
        'Registry of tile metadata: pathing, cover, door, visibility, traversal, NPC, surface, render, and altitude per tile kind. Distinguishes surface/embedded/gameplay/dev tiles. Where the meaning of road, door, bush, save, and directional lanes lives. Exports validation + console listing helpers.',
      status: 'live',
    },
    {
      name: 'world/tileTextureKeys.ts',
      purpose: ['texture_bake', 'world_gen'],
      kind: 'module',
      sourceFile: 'cart/hmsc/world/tileTextureKeys.ts',
      description:
        'Maps TileKind values to texture keys; road-like lane, junction, and crosswalk kinds share hmsc.tile.road. The stable contract for tile material keys.',
      status: 'live',
    },
    {
      name: 'world/surfaceHeights.ts',
      purpose: ['world_gen', 'rendering'],
      kind: 'module',
      sourceFile: 'cart/hmsc/world/surfaceHeights.ts',
      description:
        'Defines visual/physics top heights for surface regions and placed cells; keeps region mesh top slightly sunk where needed to avoid visual artifacts.',
      status: 'live',
    },
    {
      name: 'world/tileAltitude.ts',
      purpose: ['world_gen'],
      kind: 'module',
      sourceFile: 'cart/hmsc/world/tileAltitude.ts',
      description:
        'Samples altitude and tile source for a cell (especially when landform heightfields affect surface height). Distinguishes base, surface, follows-heightfield, and offset facts.',
      status: 'live',
    },
    {
      name: 'world/terrain.ts',
      purpose: ['world_gen', 'physics'],
      kind: 'utility',
      sourceFile: 'cart/hmsc/world/terrain.ts',
      description: 'Generic heightfield bake helpers producing terrain field and collider data from height samples. Pure data, no React.',
      status: 'live',
    },
    {
      name: 'world/rects.ts',
      purpose: ['math', 'physics'],
      kind: 'utility',
      sourceFile: 'cart/hmsc/world/rects.ts',
      description: 'Shared XZ rectangle math: Rect, rectsOverlap, rectGap, rectCenter. Used by placement and collision validation.',
      status: 'live',
    },
    {
      name: 'nextUniqueId (world/idgen.ts)',
      purpose: ['world_gen', 'maintenance'],
      kind: 'utility',
      sourceFile: 'cart/hmsc/world/idgen.ts',
      description:
        'Collision-proof sequential id allocator. nextUniqueId(prefix, existing) finds the first non-live id instead of using list length, preventing duplicate ids after removal.',
      status: 'live',
    },
    {
      name: 'world/noiseModel.ts',
      purpose: ['perception', 'npc'],
      kind: 'module',
      sourceFile: 'cart/hmsc/world/noiseModel.ts',
      description:
        'Surface noise materials and multipliers; movement noise modes (creep/walk, jog, sprint, jump/land, mantle/climb); maps tile kinds to noise materials; console formatting helpers for gv_noise. JS math only.',
      status: 'live',
    },
    {
      name: 'world/pathing.ts',
      purpose: ['pathing', 'ai_navigation', 'npc'],
      kind: 'module',
      sourceFile: 'cart/hmsc/world/pathing.ts',
      description:
        'A* grid pathfinding over HMSC tile kinds for pedestrian, runner, and vehicle agents; uses tile pathing/traversal/NPC metadata for movement cost; returns a grid-cell path or empty array.',
      status: 'live',
    },
    {
      name: 'world/zones.ts',
      purpose: ['world_gen', 'interaction'],
      kind: 'module',
      sourceFile: 'cart/hmsc/world/zones.ts',
      description:
        'Zone flags and mutations: add/remove zones, query zones at cells/world positions, pick the active smallest containing zone. Current availability logic is placeholder true.',
      status: 'live',
    },
    {
      name: 'world/traffic.ts',
      purpose: ['vehicle', 'pathing'],
      kind: 'module',
      sourceFile: 'cart/hmsc/world/traffic.ts',
      description:
        'Traffic signal cycle timing (performance.now-or-Date.now). Computes phase for traffic-control props, supports signal override, finds vehicle approach signals ahead of travel direction, returns whether a vehicle should yield.',
      status: 'live',
    },
    {
      name: 'world/placeables.ts',
      purpose: ['world_gen', 'ui'],
      kind: 'registry',
      sourceFile: 'cart/hmsc/world/placeables.ts',
      description:
        'Shared registry for authorable things used by painter/map/tree tooling. Layers: tile, zone, building, road, prop, mountain. Converts placeable selections into command strings (wv_fill, wv_zone, wv_building), centralizes swatch colors, converts hex to RGB floats for map/minimap shaders.',
      status: 'live',
    },
    {
      name: 'world/worldTree.ts',
      purpose: ['world_gen', 'ui'],
      kind: 'module',
      sourceFile: 'cart/hmsc/world/worldTree.ts',
      description:
        'Derived read model for the authored world: summarizes surface regions as chunks with base tile kind, sparse overrides, zones, and buildings; produces world totals and optional staged paint totals. Not a storage shape.',
      status: 'live',
    },
    {
      name: 'worldMarkers (world/worldView.ts)',
      purpose: ['ui', 'world_gen'],
      kind: 'module',
      sourceFile: 'cart/hmsc/world/worldView.ts',
      description:
        'Shared map/minimap landmark read model. worldMarkers(state) emits building, landform, zone, and prop markers using zone flag color rules, so in-game HUD and internal map tooling read the same landmark data.',
      consumers: ['render/Hud.tsx', 'cart/hmsc-int'],
      status: 'live',
    },
    {
      name: 'world/placementCheck.ts',
      purpose: ['world_gen', 'building'],
      kind: 'module',
      sourceFile: 'cart/hmsc/world/placementCheck.ts',
      description:
        'Non-blocking placement audit: normalizes buildings/props/landforms into PlacementSubject, checks tile-under-footprint, water/void/road placement, scale vs player/door, overlap, and road distance; formats issues for console. Used by wv_validate, wv_building, wv_prop.',
      consumers: ['wv_validate', 'wv_building', 'wv_prop'],
      status: 'live',
    },
    // ---- roads / buildings / props / landforms ----
    {
      name: 'world/roadProfile.ts',
      purpose: ['world_gen', 'vehicle'],
      kind: 'module',
      sourceFile: 'cart/hmsc/world/roadProfile.ts',
      description: 'Road scale constants and default profile; computes cross-section widths for lanes, bike lanes, sidewalks, centerlines, curbs, markings; exports road width helpers.',
      status: 'live',
    },
    {
      name: 'world/roads.ts',
      purpose: ['world_gen', 'physics', 'vehicle'],
      kind: 'module',
      sourceFile: 'cart/hmsc/world/roads.ts',
      description: 'Road footprint and top height; resolves road band kind at world positions; builds road physics bands; places/removes road segments.',
      status: 'live',
    },
    {
      name: 'world/roadJunctions.ts',
      purpose: ['world_gen', 'physics', 'vehicle'],
      kind: 'module',
      sourceFile: 'cart/hmsc/world/roadJunctions.ts',
      description:
        'Intersection and cul-de-sac footprints; junction top height; resolves road/sidewalk bands within intersections and cul-de-sacs; builds junction physics bands; places/removes junctions.',
      status: 'live',
    },
    {
      name: 'world/buildingKinds.ts',
      purpose: ['building', 'world_gen'],
      kind: 'registry',
      sourceFile: 'cart/hmsc/world/buildingKinds.ts',
      description:
        'Pure building kind registry: normal box buildings and open custom structures. Kinds: house, shop, tower, warehouse, parkingGarage, gasStation, usedCarLot, driveIn. Stores default footprint, storeys, wall tile kind, default enclosure, default skin, facade color, structure model. Exports validation + console listing helpers.',
      status: 'live',
    },
    {
      name: 'world/buildings.ts',
      purpose: ['building', 'physics', 'rendering'],
      kind: 'module',
      sourceFile: 'cart/hmsc/world/buildings.ts',
      description:
        'Building geometry and collision data: footprints, heights, top, door center/front cells/front point; collision/render boxes for sealed/hollow/interior buildings; open-structure collision via structureSolids; world-point blocking test; per-face skin roles (front/back/left/right/top); exterior face panels for facades; camera collision against box buildings; places/removes buildings and sets face skins.',
      status: 'live',
    },
    {
      name: 'world/buildingPlacement.ts',
      purpose: ['building', 'world_gen'],
      kind: 'module',
      sourceFile: 'cart/hmsc/world/buildingPlacement.ts',
      description:
        'Hard placement policy: rejects overlapping buildings, buildings on roads, and non-forced buildings too far from the road network; auto-snaps doorSide toward the nearest road; force bypasses the rules.',
      status: 'live',
    },
    {
      name: 'world/interiors.ts',
      purpose: ['building', 'world_gen', 'interaction'],
      kind: 'module',
      sourceFile: 'cart/hmsc/world/interiors.ts',
      description:
        'Interior world swap system. Creates generated interior spaces for buildings with enclosure:interior (larger inside than outside), adds wv_enter entry pads. enterBuildingInterior pushes the outer world to suspendedSpaces and replaces state.world; leaveCurrentInterior pops and returns to boot.console.',
      status: 'live',
    },
    {
      name: 'world/propKinds.ts',
      purpose: ['world_gen'],
      kind: 'registry',
      sourceFile: 'cart/hmsc/world/propKinds.ts',
      description:
        'Prop kind registry: labels, solidity, footprint radius, height, tile kind, traffic-control role. Props include rocks, hydrants, street signs, street lights, bush variants, stop signs, traffic lights, payphones, dumpsters, mailboxes, fences.',
      status: 'live',
    },
    {
      name: 'world/props.ts',
      purpose: ['world_gen', 'physics'],
      kind: 'module',
      sourceFile: 'cart/hmsc/world/props.ts',
      description: 'Prop footprint, top height, physics rect, picking, placement, removal, signal override. Bushes can be non-solid; fence footprints account for yaw.',
      status: 'live',
    },
    {
      name: 'world/structures.ts',
      purpose: ['building', 'physics', 'rendering'],
      kind: 'module',
      sourceFile: 'cart/hmsc/world/structures.ts',
      description:
        'JSX-free layout descriptions for open structures: parking garage, gas station, used car lot, drive-in. Produces parking-garage heightfield/collider data, drive-in screen texture keys and booth interaction points, and collision solids so render and physics share the same layout facts.',
      status: 'live',
    },
    {
      name: 'world/landforms/registry.ts (LandformKindDef)',
      purpose: ['world_gen', 'geometry'],
      kind: 'registry',
      sourceFile: 'cart/hmsc/world/landforms/registry.ts',
      description:
        'Defines LandformKindDef, registers/looks up landform kinds, computes heightfields, colliders, top height, tile kind, water kind, camera hits, and mutations. world/landforms/index.ts imports/registers kinds and re-exports the registry.',
      status: 'live',
    },
    {
      name: 'world/landforms/kinds.ts',
      purpose: ['world_gen', 'geometry'],
      kind: 'module',
      sourceFile: 'cart/hmsc/world/landforms/kinds.ts',
      description:
        'Built-in landforms: hills (rolling summed-cosine), mountain (cone with crater lake + spiral trail), estate (flat-topped dome with spiral road), heightfield (painted editable field). Exports mountain crater/trail helpers and estate road helpers.',
      status: 'live',
    },
    // ---- NPC subsystem ----
    {
      name: 'npc/index.ts',
      purpose: ['npc'],
      kind: 'module',
      sourceFile: 'cart/hmsc/npc/index.ts',
      description:
        'Barrel export for NPC kind/faction/role/spawn/chance/damage. Defines the axes: kind is what an NPC is, faction is who it fights, role is what it means to the player.',
      status: 'live',
    },
    {
      name: 'npc/kinds.ts',
      purpose: ['npc', 'perception', 'character'],
      kind: 'registry',
      sourceFile: 'cart/hmsc/npc/kinds.ts',
      description:
        'Closed registry of NPC kinds: civilian, paramedic, thug, police. Stores max health, walk/run speed, default faction, combat ability, weapon damage, and perception (vision range, field of view, hearing acuity, reaction time).',
      status: 'live',
    },
    {
      name: 'npc/factions.ts',
      purpose: ['npc'],
      kind: 'registry',
      sourceFile: 'cart/hmsc/npc/factions.ts',
      description:
        'Faction regard matrix (civilian, gang, police; target column includes player) with values hostile/wary/neutral/friendly. isHostileTo returns true only for hostile regard.',
      status: 'live',
    },
    {
      name: 'npc/roles.ts',
      purpose: ['npc', 'interaction'],
      kind: 'registry',
      sourceFile: 'cart/hmsc/npc/roles.ts',
      description:
        'Open role registry: none, personOfInterest, target, informant, witness, contact. Role metadata includes HUD marker color token, hostile-on-sight override, objective flag, and interactions; unknown roles fall back to none.',
      status: 'live',
    },
    {
      name: 'createNpc (npc/spawn.ts)',
      purpose: ['npc', 'character'],
      kind: 'utility',
      sourceFile: 'cart/hmsc/npc/spawn.ts',
      description:
        'Pure NPC factory + world mutation helpers. createNpc builds an NpcState from kind defaults plus id, position, optional faction/role/yaw/source; adds a stable gait phase offset by id so groups do not animate in lockstep. addNpcToWorld/removeNpcFromWorld/npcAt mutate/read world.npcs immutably.',
      status: 'live',
    },
    {
      name: 'npc/systems/chance.ts',
      purpose: ['chance', 'damage', 'npc'],
      kind: 'module',
      sourceFile: 'cart/hmsc/npc/systems/chance.ts',
      description:
        'Probabilistic hit model for NPC-to-player and NPC-to-NPC shots. Computes hit chance from range, cover fraction, target crouch, shooter skill. Uses Math.random by default for rollHit/rollZone but accepts injected RNG. Chooses landed zone from weighted damage zones.',
      status: 'live',
    },
    {
      name: 'npc/systems/damage.ts',
      purpose: ['damage', 'npc'],
      kind: 'module',
      sourceFile: 'cart/hmsc/npc/systems/damage.ts',
      description:
        'Applies resolved damage to NPC state, joining geometric player-aim hits and probabilistic zone shots. Uses humanoid zone multipliers from render3d/humanoid; sets NPC posture to down at zero health.',
      dependsOn: ['render3d/humanoid'],
      status: 'live',
    },
    // ---- labs ----
    {
      name: 'labs/labDefinitions.ts',
      purpose: ['debug'],
      kind: 'registry',
      sourceFile: 'cart/hmsc/labs/labDefinitions.ts',
      description: 'Defines in-cart labs scale, textures, aim — each with name, label, scene step, spawn position/yaw, exit position/yaw. Validation + scene-step lookup helpers.',
      status: 'lab',
    },
    {
      name: 'ScaleLabScene',
      purpose: ['debug', 'rendering'],
      kind: 'component',
      sourceFile: 'cart/hmsc/labs/ScaleLabScene.tsx',
      description: 'Scene3D lab for physical scale: player capsule, blocks, ledges, door frame, height lines, ruler ticks. Uses HMSC_SCALE. JS/React only.',
      status: 'lab',
    },
    {
      name: 'TextureLabScene',
      purpose: ['debug', 'texture_bake', 'rendering'],
      kind: 'component',
      sourceFile: 'cart/hmsc/labs/TextureLabScene.tsx',
      description: 'Scene3D material board rendering panels with texture keys from HMSC_TILE_TEXTURE_KEYS via textureKey on Scene3D.Mesh.',
      status: 'lab',
    },
    {
      name: 'AimLabScene',
      purpose: ['debug', 'damage', 'camera'],
      kind: 'component',
      sourceFile: 'cart/hmsc/labs/AimLabScene.tsx',
      description: 'Scene3D aim lab with bottles and target selection; computes an aim ray in JS from the gameplay camera context and highlights the bottle under the crosshair. No host raycast.',
      status: 'lab',
    },
    // ---- UI / diagnostics ----
    {
      name: 'ui/Console.tsx',
      purpose: ['ui', 'scripting'],
      kind: 'component',
      sourceFile: 'cart/hmsc/ui/Console.tsx',
      description:
        'Console panel UI: quick-command buttons, command history, TextInput. On submit calls parent onSubmitCommand. Quick commands include help, HUD, sky/time/weather, lab commands, player location, cheats/noclip, state, save, reset.',
      status: 'live',
    },
    {
      name: 'render/Hud.tsx',
      purpose: ['ui', 'rendering'],
      kind: 'component',
      sourceFile: 'cart/hmsc/render/Hud.tsx',
      description:
        'GTA-style HUD overlay: clock, money, armor, health, wanted stars, inventory item, minimap, zone name flash. Minimap uses a WGSL Effect shader fed a packed float array, colored from placeable swatches and worldMarkers. Smooths center/yaw rAF-or-setTimeout, performance.now-or-Date.now, listens to hmsc:event:zone.entered via busOn.',
      consumes: ['hmsc:event:zone.entered'],
      dependsOn: ['worldMarkers'],
      status: 'live',
    },
    {
      name: 'render/DebugHud.tsx',
      purpose: ['debug', 'telemetry', 'ui'],
      kind: 'component',
      sourceFile: 'cart/hmsc/render/DebugHud.tsx',
      description:
        'Debug overlay for frame/render/input/player/camera/world stats. Uses useTelemetry for fps/frame/gpu/nodes/input, shows host physics microseconds from the drive loop, reads movement surface from movementSurfaceForPlayer.',
      dependsOn: ['useTelemetry'],
      status: 'live',
    },
    {
      name: 'tools/runWorldScript.ts',
      purpose: ['debug', 'world_gen'],
      kind: 'module',
      sourceFile: 'cart/hmsc/tools/runWorldScript.ts',
      description:
        'Headless seed-world placement auditor: creates initial state and runs placement validation over seed buildings/props/landforms, writing to __writeStderr and exiting via __exit. Does not import renderer or command registry so it runs as a plain V8 CLI script.',
      consumes: ['__writeStderr', '__exit'],
      status: 'live',
    },
    // ---- 3D renderer ----
    {
      name: 'GameWorld3D',
      purpose: ['rendering', 'camera'],
      kind: 'component',
      sourceFile: 'cart/hmsc/render3d/GameWorld3D.tsx',
      description:
        'Main world renderer: skybox, lights, floor regions, roads, junctions, placed cells, props, buildings, facades, part-textured faces, landforms, player, scene children. Computes third-person camera position/target from player position/yaw/pitch/aim; uses building and landform camera-hit helpers to pull the camera forward when occluded. Uses Scene3D.Camera/Fog/Skybox/Mesh; surface floors are textured top-face slabs via floorTextureKey(region.id).',
      dependsOn: ['floorTextureKey'],
      status: 'live',
    },
    {
      name: 'render3d/sky.ts',
      purpose: ['rendering', 'color'],
      kind: 'module',
      sourceFile: 'cart/hmsc/render3d/sky.ts',
      description:
        'Pure sky model: named hours, weather presets; computes zenith, horizon, sun color, sun direction, ambient, directional light, fog, and background from hour/weather/gloom. No host calls.',
      status: 'live',
    },
    {
      name: 'render3d/materials.ts (Glass/AutoGlass/Storefront)',
      purpose: ['rendering'],
      kind: 'module',
      sourceFile: 'cart/hmsc/render3d/materials.ts',
      description: 'Small material object factory defining Glass, AutoGlass, Storefront presets with transparency/breakable-style metadata.',
      status: 'live',
    },
    {
      name: 'render3d/Building.tsx',
      purpose: ['rendering', 'building'],
      kind: 'component',
      sourceFile: 'cart/hmsc/render3d/Building.tsx',
      description:
        'Renders one placed building. Box buildings draw walls from the same buildingBoxes data used by physics; interior buildings get a visible door panel; open structures dispatch to custom structure components via buildingCustomModel. Also renders BuildingWindows.',
      status: 'live',
    },
    {
      name: 'render3d/BuildingWindows.tsx',
      purpose: ['rendering', 'building'],
      kind: 'component',
      sourceFile: 'cart/hmsc/render3d/BuildingWindows.tsx',
      description: 'Adds glass panes to box buildings based on skins, floors, and faces using the Glass material. Pure render logic.',
      status: 'live',
    },
    {
      name: 'render3d/BuildingFacades.tsx',
      purpose: ['rendering', 'building', 'texture_bake'],
      kind: 'component',
      sourceFile: 'cart/hmsc/render3d/BuildingFacades.tsx',
      description:
        'Legacy per-face building skin renderer: thin textured panels over box walls/roof. Resolves faces with resolveFaceSkin and tops with resolveTopSkin; skips panels owned by newer partTextures to avoid z-fighting; captures one StaticSurface per distinct (skin, cols, floors) bucket. Uses StaticSurface + React facade UI from buildingSkins.tsx.',
      dependsOn: ['StaticSurface', 'buildingSkins.tsx'],
      status: 'deprecated',
    },
    {
      name: 'render3d/buildingSkins.tsx',
      purpose: ['rendering', 'building'],
      kind: 'module',
      sourceFile: 'cart/hmsc/render3d/buildingSkins.tsx',
      description:
        '2D React facade skin renderers: office, residential, retail, industrial, internetCafe, gunShop, mall. plain means no facade texture. Exposes grid sizing and texture-key helpers.',
      status: 'live',
    },
    {
      name: 'render3d/buildingTransform.ts',
      purpose: ['building', 'math'],
      kind: 'utility',
      sourceFile: 'cart/hmsc/render3d/buildingTransform.ts',
      description: 'Shared yaw/position helpers: building yaw, center, rotated points around center, part placement, anchored yaw.',
      status: 'live',
    },
    {
      name: 'render3d/buildingModels.tsx',
      purpose: ['rendering', 'building'],
      kind: 'component',
      sourceFile: 'cart/hmsc/render3d/buildingModels.tsx',
      description: 'Dispatches open building kinds to custom model components: parking garage, gas station, used car lot, drive-in.',
      status: 'live',
    },
    {
      name: 'render3d/structures/Car.tsx',
      purpose: ['rendering', 'vehicle'],
      kind: 'component',
      sourceFile: 'cart/hmsc/render3d/structures/Car.tsx',
      description: 'Reusable car model from Scene3D primitives; deterministic color choice from structure data, not Math.random.',
      status: 'live',
    },
    {
      name: 'render3d/structures/ParkingGarage.tsx',
      purpose: ['rendering', 'building'],
      kind: 'component',
      sourceFile: 'cart/hmsc/render3d/structures/ParkingGarage.tsx',
      description: 'Renders parking garage using parkingGarageSpec and parkingGarageField (heightfield mesh, deck, pillars, parapets, stripes, cars). Exports parkingGarageParts for the part-texture system.',
      status: 'live',
    },
    {
      name: 'render3d/structures/GasStation.tsx',
      purpose: ['rendering', 'building'],
      kind: 'component',
      sourceFile: 'cart/hmsc/render3d/structures/GasStation.tsx',
      description: 'Renders gas station using gasStationSpec (canopy, store, pumps, signs, glass, pillars). Exports gasStationParts.',
      status: 'live',
    },
    {
      name: 'render3d/structures/UsedCarLot.tsx',
      purpose: ['rendering', 'building'],
      kind: 'component',
      sourceFile: 'cart/hmsc/render3d/structures/UsedCarLot.tsx',
      description: 'Renders used car lot using usedCarLotSpec (kiosk, sign, pennants, cables, cars). Exports usedCarLotParts.',
      status: 'live',
    },
    {
      name: 'render3d/structures/DriveIn.tsx',
      purpose: ['rendering', 'building'],
      kind: 'component',
      sourceFile: 'cart/hmsc/render3d/structures/DriveIn.tsx',
      description: 'Renders drive-in using driveInSpec and driveInScreenTextureKey (screen wall, booth, marquee, poles, live screen panel). Exports driveInParts.',
      status: 'live',
    },
    {
      name: 'render3d/driveInScreen.tsx',
      purpose: ['rendering', 'texture_bake'],
      kind: 'component',
      sourceFile: 'cart/hmsc/render3d/driveInScreen.tsx',
      description:
        'Offscreen capture path for drive-in screen textures: Video primitive when a source is selected, StaticSurface to capture a video/effect composition to driveInScreenTextureKey, ~30fps rAF-or-setTimeout. Reads current source via getDriveInSource and useDriveInSources.',
      dependsOn: ['StaticSurface', 'getDriveInSource', 'useDriveInSources'],
      status: 'live',
    },
    {
      name: 'render3d/Road.tsx',
      purpose: ['rendering', 'texture_bake'],
      kind: 'component',
      sourceFile: 'cart/hmsc/render3d/Road.tsx',
      description:
        'Renders each road as one textured slab whose top face samples a road texture captured from WGSL via RoadSurfaceCaptures (one StaticSurface per road). Road slab top matches host physics road top.',
      status: 'live',
    },
    {
      name: 'render3d/RoadJunctions.tsx',
      purpose: ['rendering', 'texture_bake'],
      kind: 'component',
      sourceFile: 'cart/hmsc/render3d/RoadJunctions.tsx',
      description: 'Renders intersections and cul-de-sacs as single textured slabs using WGSL captures for markings; junction top slightly above road slabs so markings cover overlaps.',
      status: 'live',
    },
    {
      name: 'render3d/Landform.tsx',
      purpose: ['rendering', 'geometry'],
      kind: 'component',
      sourceFile: 'cart/hmsc/render3d/Landform.tsx',
      description:
        'Renders each landform as a Geometry.Heightfield from the same source collider registration uses. Painted landforms use dynamic geometry keys so edits show live; mountain decor adds crater lake water; estate decor adds road ribbon mesh. Mounts natural/painted/water/road-ribbon StaticSurface captures.',
      status: 'live',
    },
    {
      name: 'render3d/heightfieldSurface.tsx',
      purpose: ['texture_bake', 'shader'],
      kind: 'component',
      sourceFile: 'cart/hmsc/render3d/heightfieldSurface.tsx',
      description: 'Captures per-cell tile paint for field-backed heightfields, building palette data from tile definitions and placeable colors via WGSL Effect into StaticSurface.',
      status: 'live',
    },
    {
      name: 'floorTextureKey (render3d/tileSurface.tsx)',
      purpose: ['texture_bake', 'shader'],
      kind: 'module',
      sourceFile: 'cart/hmsc/render3d/tileSurface.tsx',
      description:
        'Captures texture maps for rectangular surface regions; defines floorTextureKey(regionId); WGSL Effect + StaticSurface; stabilizes data/style identities to avoid rebakes during camera/player frames.',
      status: 'live',
    },
    {
      name: 'render3d/tileFill.ts',
      purpose: ['shader', 'texture_bake'],
      kind: 'shader',
      sourceFile: 'cart/hmsc/render3d/tileFill.ts',
      description: 'WGSL tile fill shader and material/variant ids for tile kinds; procedural base textures for tile surfaces.',
      status: 'live',
    },
    {
      name: 'roadTextureKey (render3d/roadFill.ts)',
      purpose: ['shader', 'texture_bake'],
      kind: 'shader',
      sourceFile: 'cart/hmsc/render3d/roadFill.ts',
      description: 'WGSL road cross-section shader; packs road profile data; provides roadTextureKey and capture dimension helpers.',
      status: 'live',
    },
    {
      name: 'render3d/roadTileFill.ts',
      purpose: ['shader', 'texture_bake'],
      kind: 'shader',
      sourceFile: 'cart/hmsc/render3d/roadTileFill.ts',
      description: 'Shader layer for road-tile-style fill; extends tile fill with lane/marking colors.',
      status: 'live',
    },
    {
      name: 'junctionTextureKey (render3d/junctionFill.ts)',
      purpose: ['shader', 'texture_bake'],
      kind: 'shader',
      sourceFile: 'cart/hmsc/render3d/junctionFill.ts',
      description: 'WGSL shaders and data packing for intersections and cul-de-sacs; provides junctionTextureKey.',
      status: 'live',
    },
    {
      name: 'landformTextureKey (render3d/landformFill.ts)',
      purpose: ['shader', 'texture_bake'],
      kind: 'shader',
      sourceFile: 'cart/hmsc/render3d/landformFill.ts',
      description: 'WGSL natural-blend shader for parametric landforms; packs landform kind/material/style data; provides landformTextureKey and capture dimension helpers.',
      status: 'live',
    },
    {
      name: 'waterTextureKey (render3d/waterFill.ts)',
      purpose: ['shader', 'texture_bake'],
      kind: 'shader',
      sourceFile: 'cart/hmsc/render3d/waterFill.ts',
      description: 'WGSL water texture shader; provides waterTextureKey.',
      status: 'live',
    },
    {
      name: 'render3d/roadRibbon.ts',
      purpose: ['geometry', 'shader', 'texture_bake'],
      kind: 'module',
      sourceFile: 'cart/hmsc/render3d/roadRibbon.ts',
      description: 'Mesh definition and WGSL texture capture for landform road ribbons; used by estate landforms.',
      status: 'live',
    },
    {
      name: 'render3d/fillShader.ts',
      purpose: ['shader', 'texture_bake'],
      kind: 'shader',
      sourceFile: 'cart/hmsc/render3d/fillShader.ts',
      description: 'Large shared WGSL fill shader catalog used by texture recipes; procedural material logic used by textureShaders.ts.',
      status: 'live',
    },
    {
      name: 'HMSC_SHADERS (render3d/textureShaders.ts)',
      purpose: ['shader', 'texture_bake'],
      kind: 'registry',
      sourceFile: 'cart/hmsc/render3d/textureShaders.ts',
      description: 'Texture recipe catalog defining shader params, variants, defaults, groups; includes the road recipe, the cutout-stencil recipe (CUTOUTQOL2-0605: a 0/1 cell grid rendered fill-inside/background-outside — /cutout Materializes extracted cutouts into it; data layout documented on the recipe, pinned by editors/cutout P4 test), plus many fill-board recipes. Exports HMSC_SHADERS, shaderSpec, shaderGroups.',
      dependsOn: ['fillShader.ts'],
      status: 'live',
    },
    {
      name: 'TEXTURE_REGISTRY (render3d/textures.tsx)',
      purpose: ['texture_bake', 'rendering'],
      kind: 'registry',
      sourceFile: 'cart/hmsc/render3d/textures.tsx',
      description:
        'Unified texture registry treating shader textures and React facade textures as one concept: a texture id that bakes to a StaticSurface and is sampled by textureKey. Hydrates custom saved materials via customTextures.ts. Exports TextureCapture, TEXTURE_REGISTRY, TEXTURE_IDS, allTextures, textureById.',
      dependsOn: ['customTextures.ts'],
      status: 'live',
    },
    {
      name: 'render3d/customTextures.ts',
      purpose: ['persistence', 'texture_bake'],
      kind: 'module',
      sourceFile: 'cart/hmsc/render3d/customTextures.ts',
      description:
        'Stored material layer for editor-authored textures. Reads/writes via hmscStoreGet/hmscStoreSet (ultimately host localstore/store). Emits hmsc:custom-textures-changed with busEmit, subscribes with busOn, stores records as {id,label,shaderId,data}.',
      emits: ['hmsc:custom-textures-changed'],
      status: 'live',
    },
    {
      name: 'render3d/parts.tsx (Part / TexturedParts / PartTextureCaptures)',
      purpose: ['rendering', 'texture_bake', 'building'],
      kind: 'module',
      sourceFile: 'cart/hmsc/render3d/parts.tsx',
      description:
        'General part-texture system. Part: stable id, label, geometry, params, world position, rotation, scale, material, textured faces, texture grid, default texture key, overlay flag. TexturedParts renders parts with resolved texture keys; PartTextureCaptures bakes one texture per distinct (textureId, cols, floors) bucket. The general replacement/extension for box-only face skins.',
      status: 'live',
    },
    {
      name: 'render3d/buildingParts.ts',
      purpose: ['building', 'texture_bake'],
      kind: 'module',
      sourceFile: 'cart/hmsc/render3d/buildingParts.ts',
      description:
        'Converts buildings into texturable Part[]: box buildings produce front/back/left/right/top panels; open structures delegate to structure-specific part exporters; folds legacy per-face skin into part-texture ids for backwards compatibility.',
      status: 'live',
    },
    {
      name: 'render3d/propParts.ts',
      purpose: ['texture_bake'],
      kind: 'module',
      sourceFile: 'cart/hmsc/render3d/propParts.ts',
      description: 'Converts props into texturable Part[]; currently only street signs expose texturable parts.',
      status: 'live',
    },
    {
      name: 'render3d/PartCaptures.tsx',
      purpose: ['texture_bake', 'rendering'],
      kind: 'component',
      sourceFile: 'cart/hmsc/render3d/PartCaptures.tsx',
      description: 'Mounts part texture captures for all building/prop part textures used in the world; renders additive textured face panels for box buildings when Building.partTextures is present.',
      status: 'live',
    },
    {
      name: 'render3d/Prop.tsx',
      purpose: ['rendering'],
      kind: 'component',
      sourceFile: 'cart/hmsc/render3d/Prop.tsx',
      description: 'Dispatches prop kind to prop model component: rock variants, hydrants, signs, lights, bushes, stop signs, traffic lights, payphones, dumpsters, mailboxes, fences.',
      status: 'live',
    },
    {
      name: 'render3d/PropCaptures.tsx',
      purpose: ['texture_bake', 'rendering'],
      kind: 'component',
      sourceFile: 'cart/hmsc/render3d/PropCaptures.tsx',
      description: 'Mounts prop-specific StaticSurface captures; currently the street sign face capture.',
      status: 'live',
    },
    {
      name: 'render3d/props (prop models)',
      purpose: ['rendering'],
      kind: 'component',
      sourceFile: 'cart/hmsc/render3d/props/',
      description:
        'Prop model components: place.ts (shared transform math), signFace.tsx (STREET_SIGN_TEXTURE_KEY 2D texture), StreetSign.tsx (exports streetSignParts, uses TexturedParts), StopSign.tsx, TrafficLight.tsx (trafficClockSeconds/trafficSignalPhase, setInterval 250ms), StreetLight.tsx, FireHydrant.tsx, Payphone.tsx, Dumpster.tsx, Mailbox.tsx, Fence.tsx, Rock.tsx, Bush.tsx (deterministic blob layout).',
      status: 'live',
    },
    {
      name: 'render3d/PlayerFigure.tsx',
      purpose: ['rendering', 'character'],
      kind: 'component',
      sourceFile: 'cart/hmsc/render3d/PlayerFigure.tsx',
      description: 'Renders the player humanoid by solving a rig from movement state using drivePose, solveHumanoid, Figure, PLAYER_PALETTE, PLAYER_FACE_KEY.',
      dependsOn: ['humanoid/index.ts'],
      status: 'live',
    },
    {
      name: 'render3d/NpcFigure.tsx',
      purpose: ['rendering', 'character', 'npc'],
      kind: 'component',
      sourceFile: 'cart/hmsc/render3d/NpcFigure.tsx',
      description: 'Renders NPC humanoids from NPC drive data, solving an NPC rig and using npcPalette and npcFaceKey.',
      dependsOn: ['humanoid/index.ts'],
      status: 'live',
    },
    {
      name: 'render3d/humanoid (rig system)',
      purpose: ['character', 'rendering', 'damage', 'animation'],
      kind: 'module',
      sourceFile: 'cart/hmsc/render3d/humanoid/index.ts',
      description:
        'Humanoid rig barrel: pose.ts (drivePose(animationSeconds,moving,running) gait), skeleton.ts (single source of truth for mesh parts AND hit capsules, solves body pose into render parts + damage-zone capsules + eye point, keeping hitboxes and rendered body aligned), Figure.tsx (renders a solved rig mapping material slots to a palette via Scene3D.Mesh), palette.ts (player/NPC palettes, hashes NPC id to a stable palette), face.tsx (2D React face texture baked via StaticSurface, supports preset/image/live-camera source, bakes all NPC combos so each npcFaceKey(id) exists), hitbox.ts (geometric raycast for player aim, ray-tests rig capsules for nearest hit zone, head/torso/arms/legs multipliers).',
      dependsOn: ['StaticSurface'],
      status: 'live',
    },
  ],
  patterns: [
    {
      name: 'Command-first mutation',
      purpose: ['scripting', 'world_gen'],
      description:
        'Everything important (UI, triggers, lab entry, save/load, world authoring, debug tools) mutates through runCommandLine. The stable user/tool interface for mutation.',
      examples: ['hmsc'],
      status: 'recurring',
    },
    {
      name: 'One JSON state object',
      purpose: ['persistence', 'format'],
      description: 'Runtime state is one JSON-serializable GameState; the active scene is selected by GameState.sceneStep, not by separate cart entrypoints.',
      examples: ['hmsc'],
      status: 'recurring',
    },
    {
      name: 'Grid authoring + continuous movement',
      purpose: ['world_gen', 'physics'],
      description: 'Constructed world data is grid or authored-object data (1 tile = 1 meter); player, entities, and NPCs move in continuous meters.',
      examples: ['hmsc'],
      status: 'recurring',
    },
    {
      name: 'Scene step instead of separate cart entrypoints',
      purpose: ['rendering', 'game_loop'],
      description: 'sceneStep (boot.console, lab.scale, lab.textures, lab.aim, interior.<id>) selects the active scene through one gameplay rig instead of multiple cart entrypoints.',
      examples: ['hmsc'],
      status: 'recurring',
    },
    {
      name: 'StaticSurface texture capture as a shared render primitive',
      purpose: ['texture_bake', 'rendering'],
      description:
        'Offscreen 2D surface captured by the host into a texture, used for floors, roads, junctions, building facades, part textures, props, faces, landforms, water, and drive-in screens.',
      examples: ['hmsc', 'billboard_demo'],
      status: 'recurring',
    },
    {
      name: 'Texture id as one concept, independent of shader-vs-React authoring',
      purpose: ['texture_bake'],
      description:
        'A texture can be authored by WGSL shader or React UI, but downstream it is just an id that bakes to a texture key (TEXTURE_REGISTRY in render3d/textures.tsx).',
      examples: ['hmsc'],
      status: 'recurring',
    },
    {
      name: 'Registry-driven kinds',
      purpose: ['world_gen', 'npc', 'building'],
      description: 'Registry-driven kinds for tiles, buildings, props, NPCs, roles, and landforms — kind->meaning tables that define behavior.',
      examples: ['hmsc'],
      status: 'recurring',
    },
    {
      name: 'Separate pure data model from JSX render components',
      purpose: ['rendering', 'world_gen'],
      description: 'Pure data/layout modules (world/structures.ts, buildings.ts) feed both physics and JSX render components so render and physics share the same layout facts.',
      examples: ['hmsc'],
      status: 'recurring',
    },
    {
      name: 'Event bus channels as story and UI integration points',
      purpose: ['scripting', 'telemetry'],
      description: 'Typed game events publish to hmsc:event / hmsc:event:<type> / actor / subject / tag channels; story rules and HUD subscribe via useIFTTT/busOn.',
      examples: ['hmsc'],
      status: 'recurring',
    },
    {
      name: 'Placement validation as a reusable authoring safety pass',
      purpose: ['world_gen', 'building'],
      description: 'A non-blocking PlacementSubject audit (placementCheck.ts) reused by wv_validate, wv_building, wv_prop.',
      examples: ['hmsc'],
      status: 'recurring',
    },
    {
      name: 'Shared map/read models instead of per-view duplicate derivation',
      purpose: ['ui', 'world_gen'],
      description: 'worldMarkers/worldView and worldTree give in-game HUD and internal map tooling the same derived landmark data rather than re-deriving per view.',
      examples: ['hmsc'],
      status: 'recurring',
    },
    {
      name: 'rAF-probe / setTimeout game loop',
      purpose: ['game_loop'],
      description: 'Camera, drive loop, minimap smoothing, drive-in refresh, and perf watch all probe requestAnimationFrame and fall back to setTimeout — the host has no rAF.',
      examples: ['hmsc', 'billboard_demo'],
      promoteTo: 'useGameLoop',
      status: 'promote',
    },
    {
      name: 'Host packed-buffer physics over per-body bindings',
      purpose: ['physics', 'host_bridge'],
      description:
        'JS packs the whole world into a Float32Array, crosses the bridge once per frame via __hmsc_physics_step, and parses an ArrayBuffer back — with a JS fallback only for simple player x/z movement.',
      examples: ['hmsc'],
      status: 'recurring',
    },
    {
      name: 'Skeleton as single source of render parts AND hit capsules',
      purpose: ['character', 'damage', 'rendering'],
      description: 'One humanoid skeleton solve produces both the rendered body parts and the damage-zone hit capsules, keeping hitboxes aligned with what is drawn.',
      examples: ['hmsc'],
      status: 'recurring',
    },
    {
      name: 'Part-texture system superseding box-only face skins',
      purpose: ['building', 'texture_bake'],
      description:
        'The general Part / TexturedParts / partTextures system replaces legacy per-face building skins; legacy skins are folded into part-texture ids for compatibility.',
      examples: ['hmsc'],
      promoteTo: 'render3d/parts.tsx Part system',
      status: 'resolved',
    },
  ],
  hazards: [
    {
      name: 'Namespaced localstore vs generic store fallback drift',
      purpose: ['persistence', 'host_bridge'],
      description:
        'gameState.ts and customTextures.ts use __localstoreGet/__localstoreSet("hmsc", ...) preferentially and fall back to __store_get/__store_set("hmsc:key"). The two stores key differently (namespace+key vs prefixed key); reading from the wrong one yields stale or missing state.',
      evidence: ['hmsc.md state/gameState.ts: localstore first, generic store fallback'],
      severity: 'medium',
    },
    {
      name: 'Host physics absent -> silent JS fallback movement',
      purpose: ['physics', 'host_bridge'],
      description:
        'advanceHostPhysics returns null if __hmsc_physics_step is missing; usePlayerDrive then falls back to a JS canOccupyWorldPosition + direct x/z move. The fallback is simpler than the host sim (no grounded/velocity/entity resolution), so behavior silently diverges when the host fn is unavailable.',
      evidence: ['hmsc.md hostPhysics.ts: returns null so caller can use fallback; usePlayerDrive.ts JS fallback'],
      severity: 'medium',
    },
    {
      name: 'Landforms excluded from rect collision by design',
      purpose: ['physics'],
      description:
        'hostPhysics.ts deliberately excludes landforms from the collision-rect set because they register as host heightfields via terrainColliders.ts. Adding landform collision to the rect packer (or forgetting to register heightfields) breaks terrain collision in non-obvious ways.',
      evidence: ['hmsc.md hostPhysics.ts: excludes landforms because they register as host heightfields'],
      fix: 'Register landform/garage colliders through useTerrainColliders; do not add them to the rect packer.',
      severity: 'medium',
    },
    {
      name: 'BuildingFacades is legacy, superseded by part textures',
      purpose: ['rendering', 'building'],
      description:
        'BuildingFacades.tsx is the legacy per-face skin renderer and must skip panels owned by newer partTextures to avoid z-fighting. Two facade systems coexist; authoring on the legacy path or both at once causes z-fighting.',
      evidence: ['hmsc.md BuildingFacades.tsx: legacy; skips panels owned by newer partTextures to avoid z-fighting'],
      fix: 'Prefer the parts.tsx part-texture system; legacy skins are folded into part-texture ids.',
      severity: 'medium',
    },
    {
      name: 'StaticSurface inline data/style identity forces rebake',
      purpose: ['texture_bake', 'rendering'],
      description:
        'tileSurface.tsx explicitly stabilizes data/style identities to avoid rebakes during camera/player frames — the documented per-frame StaticSurface rebake spike if inline props get fresh identities each render.',
      evidence: ['hmsc.md tileSurface.tsx: stabilizes data/style identities to avoid rebakes; memory static_surface_inline_props_rebake'],
      fix: 'Memo captures and useMemo data/style identities in any StaticSurface capture.',
      severity: 'high',
    },
    {
      name: 'Id allocation must not use list length',
      purpose: ['world_gen', 'maintenance'],
      description:
        'nextUniqueId finds the first non-live id rather than using list length; using length-based ids reintroduces duplicate ids after an object is removed.',
      evidence: ['hmsc.md idgen.ts: finds first non-live id instead of using list length'],
      fix: 'Always allocate ids via nextUniqueId(prefix, existing).',
      severity: 'medium',
    },
    {
      name: 'gv_perflog level 2 depends on optional host spike trace',
      purpose: ['telemetry', 'debug'],
      description:
        'The registry uses __hmsc_spike_trace(1|0) only when available; perfWatch reads __tel_* host telemetry. Diagnostics silently degrade if these host fns are missing, and reports only surface via console.warn (console.log is invisible in the terminal).',
      evidence: ['hmsc.md registry.ts uses __hmsc_spike_trace when available; perfWatch console.warn'],
      severity: 'low',
    },
    {
      name: 'Zone availability logic is a placeholder',
      purpose: ['world_gen', 'interaction'],
      description: 'world/zones.ts current availability logic is hardcoded placeholder true — zone gating is not actually implemented yet.',
      evidence: ['hmsc.md zones.ts: current availability logic is placeholder true'],
      severity: 'low',
    },
    {
      name: 'Cell triggers suppressed in labs only',
      purpose: ['scripting', 'world_gen'],
      description:
        'usePlayerDrive suppresses placed-cell triggers in labs but runs them in boot.console and interiors. Authoring trigger cells expecting lab-scene firing will silently not fire.',
      evidence: ['hmsc.md usePlayerDrive.ts: suppresses cell triggers in labs; triggers run in boot.console and interiors'],
      severity: 'low',
    },
    {
      name: 'Drive-in movie selection shells out to zenity',
      purpose: ['interaction', 'host_bridge'],
      description:
        'useBuildingInteract calls execAsync("zenity --file-selection ...") for drive-in movie selection — a host process dependency on zenity that fails on systems without it.',
      evidence: ['hmsc.md useBuildingInteract.ts: execAsync zenity --file-selection'],
      severity: 'low',
    },
    {
      name: 'Road-like tiles share one texture key',
      purpose: ['texture_bake', 'world_gen'],
      description:
        'tileTextureKeys.ts maps road-like lane, junction, and crosswalk kinds all to hmsc.tile.road; per-kind road texturing requires going through the road/junction shader capture path, not per-tile keys.',
      evidence: ['hmsc.md tileTextureKeys.ts: road-like lane, junction, crosswalk kinds share hmsc.tile.road'],
      severity: 'low',
    },
  ],
};
