// request_ledger — extraction of docs/game/REQUESTS.md (REQLEDGER-0606,
// four-state board REQBOARD-0607). The ledger is knowledge-layer
// infrastructure, not a game cart: user asks as durable jobs on a board
// (new → doing → review → done), accepted only by the user's word.

import type { DocIndex } from '../types';

export const request_ledger: DocIndex = {
  name: 'request_ledger',
  file: 'REQUESTS.md',
  purpose: ['maintenance'],
  summary: 'The request board: marker-gated user asks logged verbatim (docs/game/_requests/req_<seq>.json, V20 by-addition) move new → doing → review → done; workers claim and move to review with a paragraph + SHAs, only actor user accepts review→done; served by tools/oracle as the REQUEST LEDGER tier.',
  interfaces: [
    {
      name: 'tools/request',
      purpose: ['maintenance'],
      kind: 'module',
      sourceFile: 'docs/game/_index/requestCli.ts',
      description: 'The board CLI: `board [--since <ISO>]` (four columns + counts; --since appends the ACTIVITY event log — the supervisor\'s loop tool); `log "<verbatim>" --origin <...>` → lands in new; `move <id> <state> --by <actor> [--para] [--shas] [--note]` (validated by the one transition function); `note <id> --by <actor> "<text>"`; `resolve <id> --para --shas` = ALIAS for `move <id> review` (work lands in REVIEW, not done); `list [--open]` (= not done); `show <id>`; `migrate-board` (one-shot legacy open→new/resolved→done, idempotent). Thin argv/printing layer over requests.ts; runs under tools/v8cli via the auto-rebundling tools/request wrapper.',
      dependsOn: ['RequestRecord'],
      consumers: ['every worker pane (conduct rule in CLAUDE.md)', 'supervisor relays', 'the workbench requests source (WBREQUESTS)'],
      status: 'live',
    },
    {
      name: 'RequestRecord',
      purpose: ['maintenance', 'persistence'],
      kind: 'data_model',
      sourceFile: 'docs/game/_index/requests.ts',
      description: 'One board entry: id (req_<seq>), at, origin, text (the user\'s words BYTE-VERBATIM, job marker included), status new|doing|review|done, plus the append-only `events` array ({at, actor, kind state|note, from?, to?, text?} — transitions and notes only ever append) and the doing→review one-time field-fill resolvedAt/resolution (≥120-char paragraph)/shas. Legacy two-state files (open/resolved) normalize on read forever. Storage is one git-tracked JSON file per entry under docs/game/_requests/ — append-only set, asks and history never rewritten (V20 by-addition applied to process).',
      emits: ['docs/game/_requests/req_<seq>.json'],
      status: 'live',
    },
    {
      name: 'moveRequest (the transition function)',
      purpose: ['maintenance', 'persistence'],
      kind: 'utility',
      sourceFile: 'docs/game/_index/requests.ts',
      codeRef: 'docs/game/_index/requests.ts (moveRequest, LEGAL_MOVES)',
      description: 'THE one door for state changes, enforcing the board\'s legal graph: new→doing (worker claims, any actor); doing→review (REQUIRES para ≥ MIN_RESOLUTION_CHARS + shas — fields fill exactly once, a post-bounce re-review carries its paragraph on the event); review→done (ONLY actor \'user\' — the supervisor relays the user\'s word); review→new (bounce, note required); new→done (supervisor-only noise-close, note required, NEVER from doing/review); done terminal. Everything else rejected with the legal moves named. Siblings: loadRequests/logRequest (intake → new), noteRequest (append-only notes), resolveRequest (= moveRequest to review), migrateBoard.',
      dependsOn: ['RequestRecord'],
      consumers: ['tools/request', 'the workbench requests source (WBREQUESTS)'],
      status: 'live',
    },
    {
      name: 'hook auto-capture (request hook-prompt / hook-stop)',
      purpose: ['maintenance'],
      kind: 'utility',
      sourceFile: 'docs/game/_index/requests.ts',
      codeRef: 'docs/game/_index/requests.ts (hookCapturePrompt, requestsForSession)',
      description: 'BLANKET capture, restored by REQSEC-0607 (USER RULING: "we keep the hook on all the same, nothing changes, we just have a secretary" — REQBOARD-0607\'s marker-only gate is REMOVED). UserPromptSubmit captures every substantive prompt verbatim into new; only the original noise rule skips (ackPattern trivial acks, minPromptChars default 40, slash/!/# commands). dispatchPrefixes-matched prompts (default SUPERVISOR) capture with origin supervisor-dispatch — exempt from the board flow + stop nudge, hidden from list --open and the board unless --all. The Stop hook scans ONLY the session\'s entries in \'doing\' (claimed-but-not-reviewed is the worker\'s only debt) and nudges once per turn cycle (stop_hook_active guards loops). Config is P2 data in docs/game/_requests/_config.json (minPromptChars, ackPattern, stopReminder block-once|context|off, dispatchPrefixes). CODEX PARITY via .codex/hooks.json (--cli codex changes only the origin label; HOOKJSON-0606: every emission is valid JSON on both CLIs). Hook mode NEVER exits 2 (would block + erase the user\'s prompt); mark-dispatch amends mis-captures by origin field-fill.',
      dependsOn: ['RequestRecord', 'moveRequest (the transition function)'],
      emits: ['docs/game/_requests/req_<seq>.json'],
      consumers: ['every Claude session in this repo (.claude/settings.json hooks)', 'every trusted Codex session in this repo (.codex/hooks.json)'],
      status: 'live',
    },
    {
      name: 'the SCOPE GATE (one-offs)',
      purpose: ['maintenance'],
      kind: 'utility',
      sourceFile: 'docs/game/_index/requests.ts',
      codeRef: 'docs/game/_index/requests.ts (markOneOff, ONEOFF_ORIGIN, isOffBoard)',
      description: 'REQSCOPE-0705 (USER ASK: "if it is related to the editor/game building … the request can be picked up and forwarded into the pile otherwise to drop it off as one offs/unrelated"). Capture stays blanket — the hook can\'t judge scope; the SESSION can. The capture context line carries the gate: editor/game work → claim as ever; unrelated → `tools/request oneoff <id> --by <you>` flips origin to \'one-off\' (field-fill; ask/history untouched, one note event names who judged). Same exemption fold as dispatches via isOffBoard(): off the board columns, list --open, the stop nudge, and the --since activity — but the record stays durable and oracle-served. done entries can\'t be amended; re-oneoff is a no-op. Workbench: one-offs live behind their own view, no board verbs.',
      dependsOn: ['RequestRecord'],
      consumers: ['tools/request (oneoff)', 'every session receiving the capture context line', 'the workbench requests source (WBREQUESTS)'],
      status: 'live',
    },
    {
      name: 'the SECRETARY (tags)',
      purpose: ['maintenance'],
      kind: 'utility',
      sourceFile: 'docs/game/_index/requests.ts',
      codeRef: 'docs/game/_index/requests.ts (tagRequest, filterByTag, allTags, SEED_TAGS) + cart/hmsc-int/editors/workbench/requests/{secretary.ts,SecretaryBar.tsx}',
      description: 'REQSEC-0607 (USER ASK: "we can use the useAssistant hook and hit a model who can evaluate and categorize … if model doesnt know they dont do nada"). Tags are ORGANIZATION ONLY: tags?: string[] on the record, persisted solely through tagRequest (append-only union, junk dropped silently — it cannot move states or touch the resolve discipline / user-only done gate). The workbench requests surface runs untagged entries through the framework\'s existing useAssistant hook (claude_code, click-armed, async — capture is never blocked; model absent → everything works untagged) under secretary.ts\'s strict-JSON omit-when-unsure protocol; seed vocabulary bug/perf-log/ask/ruling/ux/idea, model-extensible. Search: CLI board --tag / list --tag / tags; workbench rail grows a #tag · n chip per tag in use.',
      dependsOn: ['RequestRecord'],
      consumers: ['tools/request (tag/tags/--tag)', 'the workbench requests source (WBREQUESTS)'],
      status: 'live',
    },
    {
      name: 'oracle REQUEST LEDGER tier',
      purpose: ['maintenance'],
      kind: 'utility',
      sourceFile: 'docs/game/_index/oracle.ts',
      codeRef: 'docs/game/_index/oracle.ts (searchRequests)',
      description: 'tools/oracle\'s second tier, between RULINGS and INDEX RECORDS: ranks entries over verbatim text (weight 3) + resolution (1) + id/origin (1), prints board status, ask, resolution slice, and commit SHAs (whenever the resolution is filled — doing→review onward). Ledger is read from disk at query time, so fresh logs serve immediately without a rebundle.',
      dependsOn: ['moveRequest (the transition function)'],
      status: 'live',
    },
  ],
  patterns: [
    {
      name: 'claim → review → stop (the worker contract)',
      purpose: ['maintenance'],
      description: 'A worker takes a board job by claiming it (move <id> doing --by <you>), works, then moves it to REVIEW with the resolution paragraph + SHAs — and STOPS. done is never the worker\'s to flip: only the user\'s word, relayed by the supervisor as --by user, accepts review→done. The commit message cites the req id (USER ASK req_NNNN). The supervisor watches `board --since <last pass>`, bounces review→new with a note, and noise-closes intake mistakes new→done.',
      examples: ['CLAUDE.md "User Asks: the Request Board"'],
      status: 'recurring',
    },
  ],
  hazards: [
    {
      name: 'paraphrasing the ask corrupts the record',
      purpose: ['maintenance'],
      description: 'The `text` field is the user\'s words BYTE-VERBATIM (job marker included) — the whole point is that git does not capture prompts. Summarizing, trimming, or "cleaning up" the ask destroys the evidence the ledger exists to keep. Quote the shell argument; the CLI rejects multi-positional input rather than joining words.',
      evidence: ['docs/game/REQUESTS.md "The shape"', 'requests.test.ts verbatim suite'],
      severity: 'high',
    },
    {
      name: 'flipping review→done as a worker',
      purpose: ['maintenance'],
      description: 'Acceptance belongs to the user alone. A worker (or the supervisor acting alone) moving review→done — or "helpfully" passing --by user without the user\'s actual word — forges the board\'s whole point. The transition function rejects any non-user actor; the human rule is stricter: --by user means the user actually said so.',
      evidence: ['docs/game/_index/requests.ts moveRequest', 'requests.test.ts "a worker may NEVER flip review→done"'],
      severity: 'high',
    },
    {
      name: 'parallel id allocation race',
      purpose: ['maintenance'],
      description: 'Two workers logging in the same instant can both allocate the same req_<seq> and the second write wins. Per-entry files make the window tiny but not zero. If your freshly-logged entry is missing or shows someone else\'s text, log it again — never edit the other entry.',
      evidence: ['docs/game/_index/requests.ts nextId()'],
      severity: 'low',
    },
  ],
};
