//! doc_sessions.zig — split verbatim from framework/gpu/3d.zig (req_4375).
//! Generated by _tool/split3d.zig — edit 3d.zig's successor here, regenerate only from the manifest.
//! Cross-file references are qualified through the orchestrator (`z3d`).

const std = @import("std");
const builtin = @import("builtin");
const log = @import("../../diag/log.zig");
const wgpu = @import("wgpu");
const bu = @import("../buffer_upload.zig");
const shaders = @import("../shaders.zig");
const terrain_grid = @import("../terrain_grid.zig");
const core = @import("../../dev_modules/gpu_api.zig");
const capture = @import("../capture.zig");
const build_options = @import("build_options");
const math = @import("../../math/root.zig");
const layout = @import("../../layout.zig");
const effect_assemble = @import("../effect_assemble.zig");
const compile_progress = @import("../compile_progress.zig");
const static_instance_policy = @import("../static_instance_policy.zig");
const model_paint = @import("../model_paint.zig");
const gizmo_axis_map = @import("../gizmo_axis_map.zig");
const effects_ctx = @import("../effects_ctx.zig");
const paint_islands_mod = @import("../paint_islands.zig");
const paint_program = @import("../paint_program.zig");
const model_source = @import("../model_source.zig");
const meshdoc_format = @import("../meshdoc_format.zig");
const mesh_audit = @import("../mesh_audit.zig");
const mesh_face_table = @import("../mesh_face_table.zig");
const mesh_face_diff = @import("../mesh_face_diff.zig");
const mesh_face_field_candidate = @import("../mesh_face_field_candidate.zig");
const mesh_face_table_package = @import("../mesh_face_table_package.zig");
const mesh_face_table_worker = @import("../mesh_face_table_worker.zig");
const historical_preview = @import("../historical_preview.zig");
const mesh_edit = @import("../mesh_edit.zig");
const mesh_semantics = @import("../mesh_semantics.zig");
const mesh_semantic_restore = @import("../mesh_semantic_restore.zig");
const mesh_edge_semantics = @import("../mesh_edge_semantics.zig");
const indexed_edit_mesh = @import("../indexed_edit_mesh.zig");
const character_topology_promotion = @import("../character_topology_promotion.zig");
const mesh_journal_log = @import("../mesh_journal_log.zig");
const model_write_lease = @import("../model_write_lease.zig");
const model_adoption_receipt = @import("../model_adoption_receipt.zig");
const model_adoption_finalize = @import("../model_adoption_finalize.zig");
const path_array = @import("../path_array.zig");
const path_plane = @import("../path_plane.zig");
const stage_scale = @import("../stage_scale.zig");
const pack = @import("../pack.zig");
const stable_geometry_slot = @import("../stable_geometry_slot.zig");
const character_rig_session = @import("../../skeleton/character_rig_session.zig");
const character_skin_binding = @import("../../skeleton/skin_binding.zig");
const character_specimen = @import("../character_specimen.zig");
const mouse_state = @import("../../state/mouse_state.zig");
const Node = layout.Node;

const z3d = @import("3d.zig");

pub const ModelSession = struct {
    token: u32,
    edit: mesh_edit.Session = .{},
    source: model_source.Session = .{},
    paint: model_paint.Session = .{},
    local: z3d.DocState = .{},
};

pub fn modelSessionActiveToken() u32 {
    return z3d.g_model_session_token;
}

pub const ModelWriteIdentityRequestV1 = struct {
    version: u32,
    actor: []const u8,
    operationId: []const u8,
    modelId: []const u8,
    sessionToken: []const u8,
    expectedGeneration: u64,
};

pub const ModelWriteLeaseReleaseRequestV1 = struct {
    version: u32,
    operation: enum { release, finalize_and_release } = .release,
    receiptId: u64,
    adoptionReceiptId: ?u64 = null,
    expectedTargetSha256: ?[]const u8 = null,
    publicationVerified: ?bool = null,
};

pub const ModelDocumentAdoptRequestV1 = struct {
    version: u32,
    actor: []const u8,
    operationId: []const u8,
    modelId: []const u8,
    sessionToken: []const u8,
    expectedGeneration: u64,
    leaseReceiptId: u64,
    expectedSha256: []const u8,
    journalKind: enum { historical_restore, field_edit } = .historical_restore,
};

pub const ModelFieldCandidateRequestV1 = struct {
    version: u32,
    actor: []const u8,
    operationId: []const u8,
    modelId: []const u8,
    sessionToken: []const u8,
    expectedGeneration: u64,
    leaseReceiptId: u64,
    expectedResidentSha256: []const u8,
    expectedObjectNamespaceHash: []const u8,
    address: z3d.FaceAddressRequestV1,
    field: mesh_face_field_candidate.Field,
    value: u32,
};

pub const ModelDocumentRollbackRequestV1 = struct {
    version: u32,
    actor: []const u8,
    operationId: []const u8,
    modelId: []const u8,
    sessionToken: []const u8,
    leaseGeneration: u64,
    expectedCurrentGeneration: u64,
    leaseReceiptId: u64,
    adoptionReceiptId: u64,
};

pub fn sha256Hex(bytes: []const u8) [64]u8 {
    var digest: [32]u8 = undefined;
    std.crypto.hash.sha2.Sha256.hash(bytes, &digest, .{});
    return std.fmt.bytesToHex(digest, .lower);
}

pub fn modelWriteIdentity(
    actor: []const u8,
    operation_id: []const u8,
    model_id: []const u8,
    session_token_text: []const u8,
    generation: u64,
) ?model_write_lease.Identity {
    if (generation == 0 or generation > std.math.maxInt(u32)) return null;
    const session_token = std.fmt.parseInt(u32, session_token_text, 10) catch return null;
    if (session_token == 0) return null;
    return .{
        .actor = actor,
        .operation_id = operation_id,
        .model_id = model_id,
        .session_token = session_token,
        .generation = @intCast(generation),
    };
}

pub fn modelWriteIdentityIsResident(identity: model_write_lease.Identity, require_generation: bool) bool {
    return z3d.modelSessionResident() and
        z3d.modelDocumentTokenForId(identity.model_id) == z3d.g_model_session_token and
        identity.session_token == z3d.g_model_session_token and
        (!require_generation or identity.generation == z3d.g_edit_generation);
}

pub fn leaseRefusedJsonAlloc(allocator: std.mem.Allocator) ![]u8 {
    if (z3d.g_model_write_leases.owner()) |owner| return std.json.Stringify.valueAlloc(allocator, .{
        .ok = false,
        .version = 1,
        .code = "lease_refused",
        .detail = "resident model already has an active writer",
        .owner = .{
            .actor = owner.actor,
            .operationId = owner.operation_id,
            .modelId = owner.model_id,
            .sessionToken = owner.session_token,
            .generation = owner.generation,
        },
    }, .{});
    return z3d.faceRecoveryErrorJsonAlloc(allocator, "lease_refused", "resident model write lease was refused", false);
}

/// Acquire the one writer receipt before any restore allocation or journal edit.
pub fn modelWriteLeaseAcquireJsonAlloc(
    allocator: std.mem.Allocator,
    request_json: []const u8,
) ![]u8 {
    var parsed = std.json.parseFromSlice(z3d.ModelWriteIdentityRequestV1, allocator, request_json, .{}) catch
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid model-write lease request", false);
    defer parsed.deinit();
    const request = parsed.value;
    const identity = z3d.modelWriteIdentity(
        request.actor,
        request.operationId,
        request.modelId,
        request.sessionToken,
        request.expectedGeneration,
    ) orelse return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid model-write lease identity", false);
    if (request.version != 1)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid model-write lease version", false);
    if (z3d.g_historical_preview.blocksResidentMutation())
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "lease_refused", "close the active historical preview before mutating the resident model", false);
    if (!z3d.modelSessionResident())
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "no_resident_session", "no resident model document", false);
    if (z3d.modelDocumentTokenForId(identity.model_id) != z3d.g_model_session_token or identity.session_token != z3d.g_model_session_token)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "wrong_model", "write lease targets a different resident session", false);
    if (identity.generation != z3d.g_edit_generation)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "stale_generation", "resident mesh generation changed", true);
    const receipt_id = z3d.g_model_write_leases.acquire(identity) catch |err| switch (err) {
        error.LeaseRefused => return z3d.leaseRefusedJsonAlloc(allocator),
        error.InvalidIdentity => return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid model-write lease identity", false),
        error.OutOfMemory => return error.OutOfMemory,
    };
    const response = std.json.Stringify.valueAlloc(allocator, .{
        .ok = true,
        .version = 1,
        .receiptId = receipt_id,
        .modelId = request.modelId,
        .sessionToken = request.sessionToken,
        .generation = z3d.g_edit_generation,
    }, .{}) catch |err| {
        _ = z3d.g_model_write_leases.release(receipt_id) catch {};
        return err;
    };
    return response;
}

/// Validate one guarded field candidate against the exact resident owner while
/// its cold coordinator holds the model write lease. The response contains
/// facts and hashes only; candidate bytes never cross JSON or JavaScript. The
/// cold coordinator independently builds and owns the authoritative bytes from
/// its exact `encodeCurrentAlloc` capture before adoption.
pub fn modelFieldCandidateJsonAlloc(
    allocator: std.mem.Allocator,
    request_json: []const u8,
) ![]u8 {
    var parsed = std.json.parseFromSlice(z3d.ModelFieldCandidateRequestV1, allocator, request_json, .{}) catch
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid guarded field-candidate request", false);
    defer parsed.deinit();
    const request = parsed.value;
    if (request.version != 1 or request.leaseReceiptId == 0 or
        request.expectedResidentSha256.len != 64 or request.expectedObjectNamespaceHash.len != 64 or
        !std.mem.eql(u8, request.actor, "field-edit-coordinator"))
    {
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid guarded field-candidate request", false);
    }
    if (z3d.g_historical_preview.blocksResidentMutation())
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "lease_refused", "close the active historical preview before editing resident fields", false);
    const identity = z3d.modelWriteIdentity(
        request.actor,
        request.operationId,
        request.modelId,
        request.sessionToken,
        request.expectedGeneration,
    ) orelse return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid guarded field-candidate identity", false);
    if (!z3d.modelWriteIdentityIsResident(identity, true))
        return if (identity.session_token != z3d.g_model_session_token or z3d.modelDocumentTokenForId(identity.model_id) != z3d.g_model_session_token)
            z3d.faceRecoveryErrorJsonAlloc(allocator, "wrong_model", "field candidate targets a different resident session", false)
        else
            z3d.faceRecoveryErrorJsonAlloc(allocator, "stale_generation", "resident mesh generation changed", true);
    z3d.g_model_write_leases.validate(request.leaseReceiptId, identity) catch
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "authorization_failed", "field candidate does not own the active write lease", false);
    const address = z3d.faceAddressView(request.address) orelse
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid guarded authored-face address", false);
    if (address.stability != .stable)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "guarded field edit requires a stable authored-face address", false);

    const resident_bytes = z3d.modelEncodeCurrentDocumentAlloc(allocator, request.modelId) catch |err| switch (err) {
        error.OutOfMemory => return error.OutOfMemory,
        error.WrongModel => return z3d.faceRecoveryErrorJsonAlloc(allocator, "wrong_model", "resident object namespace belongs to another model", false),
        error.ObjectIdsUnpublished => return z3d.faceRecoveryErrorJsonAlloc(allocator, "object_ids_unpublished", "resident stable object IDs are not published", false),
        else => return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "resident document cannot be encoded exactly", false),
    };
    defer allocator.free(resident_bytes);
    const resident_sha = z3d.sha256Hex(resident_bytes);
    if (!std.mem.eql(u8, &resident_sha, request.expectedResidentSha256))
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "stale_generation", "resident bytes changed after coordinator capture", true);
    var document = meshdoc_format.decodeDocument(allocator, resident_bytes) catch
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "resident document is not canonical RJMD", false);
    defer document.deinit(allocator);
    if (document.version != meshdoc_format.VERSION_LOGICAL_TOPOLOGY or document.range_object_ids == null)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "guarded field edit requires RJMD v5 stable object IDs", false);
    const namespace = meshdoc_format.objectNamespaceDigest(request.modelId, document.range_object_ids.?, document.ranges);
    const namespace_hex = std.fmt.bytesToHex(namespace, .lower);
    if (!std.mem.eql(u8, &namespace_hex, request.expectedObjectNamespaceHash))
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "wrong_model", "resident object namespace differs from the guarded face plane", false);

    var candidate = mesh_face_field_candidate.buildAlloc(allocator, .{
        .bytes = resident_bytes,
        .address = address,
        .field = request.field,
        .value = request.value,
    }) catch |err| return z3d.faceRecoveryErrorJsonAlloc(allocator, switch (err) {
        error.StaleAddress => "stale_address",
        error.UnstableAddress, error.AmbiguousAddress => "ambiguous_address",
        error.OutOfMemory => return error.OutOfMemory,
        else => "invalid_request",
    }, @errorName(err), false);
    defer candidate.deinit();
    const candidate_sha = z3d.sha256Hex(candidate.bytes);
    return std.json.Stringify.valueAlloc(allocator, .{
        .ok = true,
        .version = 1,
        .modelId = request.modelId,
        .sessionToken = request.sessionToken,
        .generation = z3d.g_edit_generation,
        .residentSha256 = &resident_sha,
        .candidateSha256 = &candidate_sha,
        .objectNamespaceHash = &namespace_hex,
        .field = candidate.facts.field,
        .before = candidate.facts.before,
        .after = candidate.facts.after,
        .triangleCount = candidate.facts.triangle_count,
    }, .{});
}

/// Release is idempotent for the exact receipt, but a plain finally-release may
/// never silently finalize an unpublished adoption. The coordinator must use the
/// explicit finalize operation only after package, manifest, and plane proof.
pub const ModelDocumentFinalizeReceipt = model_adoption_finalize.Receipt;

/// Allocation-free commit point for a document adoption.  Both receipt
/// registries expose read-only status checks, so every fallible authorization
/// check happens before either registry changes.  Once those checks pass the
/// two mutations cannot allocate and exact retries resolve through the bounded
/// tombstones retained by the registries.
pub fn modelDocumentFinalize(
    lease_receipt_id: u64,
    adoption_receipt_id: u64,
    target_sha256: model_adoption_receipt.HashHex,
) !z3d.ModelDocumentFinalizeReceipt {
    return model_adoption_finalize.commit(
        &z3d.g_model_write_leases,
        &z3d.g_model_adoption_receipts,
        lease_receipt_id,
        adoption_receipt_id,
        target_sha256,
    );
}

pub fn modelWriteLeaseReleaseJsonAlloc(
    allocator: std.mem.Allocator,
    request_json: []const u8,
) ![]u8 {
    var parsed = std.json.parseFromSlice(z3d.ModelWriteLeaseReleaseRequestV1, allocator, request_json, .{}) catch
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid model-write lease release", false);
    defer parsed.deinit();
    const request = parsed.value;
    if (request.version != 1 or request.receiptId == 0)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid model-write lease release", false);
    switch (request.operation) {
        .release => {
            if (z3d.g_model_adoption_receipts.active) |adoption| {
                if (adoption.lease_id == request.receiptId)
                    return z3d.faceRecoveryErrorJsonAlloc(allocator, "authorization_failed", "active adoption must be rolled back or explicitly finalized before lease release", false);
            }
            if (request.adoptionReceiptId != null or request.expectedTargetSha256 != null or request.publicationVerified != null)
                return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "plain lease release cannot carry publication proof", false);

            const release_status = z3d.g_model_write_leases.releaseStatus(request.receiptId) catch
                return z3d.faceRecoveryErrorJsonAlloc(allocator, "authorization_failed", "model-write lease receipt is not active", false);
            const response = try std.json.Stringify.valueAlloc(allocator, .{
                .ok = true,
                .version = 1,
                .released = release_status == .released,
                .alreadyReleased = release_status == .already_released,
                .alreadyFinalized = false,
            }, .{});
            errdefer allocator.free(response);
            const released = z3d.g_model_write_leases.release(request.receiptId) catch
                return z3d.faceRecoveryErrorJsonAlloc(allocator, "authorization_failed", "model-write lease release was refused", false);
            std.debug.assert(released == release_status);
            return response;
        },
        .finalize_and_release => {
            if (request.publicationVerified != true or request.adoptionReceiptId == null or
                request.expectedTargetSha256 == null or request.expectedTargetSha256.?.len != 64)
            {
                return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "finalize requires exact adoption and publication proof", false);
            }
            var target_sha256: model_adoption_receipt.HashHex = undefined;
            @memcpy(&target_sha256, request.expectedTargetSha256.?);
            const adoption_status = z3d.g_model_adoption_receipts.finalizeStatus(
                request.adoptionReceiptId.?,
                request.receiptId,
                target_sha256,
            ) catch |err| switch (err) {
                error.WrongTarget => return z3d.faceRecoveryErrorJsonAlloc(allocator, "hash_mismatch", "publication SHA differs from adopted target", false),
                else => return z3d.faceRecoveryErrorJsonAlloc(allocator, "authorization_failed", "adoption receipt is not active for finalization", false),
            };
            const release_status = z3d.g_model_write_leases.releaseStatus(request.receiptId) catch
                return z3d.faceRecoveryErrorJsonAlloc(allocator, "authorization_failed", "model-write lease receipt is not active", false);

            // Reserve the exact response before either receipt changes state.
            // If the caller loses this response, the bounded tombstones make an
            // exact retry return the same successful state.
            const response = try std.json.Stringify.valueAlloc(allocator, .{
                .ok = true,
                .version = 1,
                .released = release_status == .released,
                .alreadyReleased = release_status == .already_released,
                .alreadyFinalized = adoption_status == .already_finalized,
            }, .{});
            errdefer allocator.free(response);
            const finalized = z3d.modelDocumentFinalize(
                request.receiptId,
                request.adoptionReceiptId.?,
                target_sha256,
            ) catch unreachable;
            std.debug.assert(finalized.finalized == (adoption_status == .finalized));
            std.debug.assert(finalized.already_finalized == (adoption_status == .already_finalized));
            std.debug.assert(finalized.released == (release_status == .released));
            std.debug.assert(finalized.already_released == (release_status == .already_released));
            return response;
        },
    }
}

pub fn rollbackAdoptedJournalAction(
    adoption: model_adoption_receipt.Receipt,
    target_snapshot: *z3d.JournalEntry,
) bool {
    if (z3d.g_journal_undo.items.len == 0) return false;
    const top_index = z3d.g_journal_undo.items.len - 1;
    if (z3d.g_journal_undo.items[top_index].action_id != adoption.action_id) return false;
    var preimage = z3d.g_journal_undo.items[top_index];
    z3d.g_journal_undo.items.len = top_index;
    const restored = z3d.journalInstall(&preimage) and z3d.journalResidentDurableMatches(&preimage);
    if (!restored) {
        const target_restored = z3d.journalInstall(target_snapshot) and z3d.journalResidentDurableMatches(target_snapshot);
        if (!target_restored)
            std.log.err("[model-recovery] adoption rollback and target reinstatement both failed verification", .{});
        z3d.g_journal_undo.appendAssumeCapacity(preimage);
        return false;
    }
    const encoded = z3d.modelEncodeCurrentDocumentAlloc(z3d.jalloc, preimage.part_object_model_id orelse "") catch {
        _ = z3d.journalInstall(target_snapshot);
        z3d.g_journal_undo.appendAssumeCapacity(preimage);
        return false;
    };
    defer z3d.jalloc.free(encoded);
    const restored_sha = z3d.sha256Hex(encoded);
    if (!std.mem.eql(u8, &restored_sha, &adoption.preimage_sha256)) {
        _ = z3d.journalInstall(target_snapshot);
        z3d.g_journal_undo.appendAssumeCapacity(preimage);
        return false;
    }
    if (preimage.action_kind) |kind| z3d.enqueueMeshAction(
        preimage.action_id,
        kind,
        .undone,
        target_snapshot.count,
        preimage.count,
        z3d.partCountFromRanges(target_snapshot.part_ranges),
        z3d.partCountFromRanges(preimage.part_ranges),
    );
    z3d.enqueueFollowJournalAction(
        preimage.action_id,
        if (preimage.action_kind) |kind| @intFromEnum(kind) else 255,
        .undone,
        preimage.label,
        target_snapshot.count,
        preimage.count,
        z3d.partCountFromRanges(target_snapshot.part_ranges),
        z3d.partCountFromRanges(preimage.part_ranges),
    );
    z3d.journalFreeEntry(&preimage);
    z3d.journalFreeStack(&z3d.g_journal_redo);
    z3d.armIntegrityRollCall("historical restore rollback");
    return true;
}

/// Adopt caller-borrowed, capability-verified RJMD bytes as one exact journal
/// action. Decode and every target allocation complete before resident mutation.
pub fn modelDocumentAdoptBytesJsonAlloc(
    allocator: std.mem.Allocator,
    request_json: []const u8,
    bytes: []const u8,
) ![]u8 {
    var parsed = std.json.parseFromSlice(z3d.ModelDocumentAdoptRequestV1, allocator, request_json, .{}) catch
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid document-adopt request", false);
    defer parsed.deinit();
    const request = parsed.value;
    if (request.version != 1 or request.leaseReceiptId == 0 or request.expectedSha256.len != 64)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid document-adopt request", false);
    const identity = z3d.modelWriteIdentity(
        request.actor,
        request.operationId,
        request.modelId,
        request.sessionToken,
        request.expectedGeneration,
    ) orelse return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid document-adopt identity", false);
    if (!z3d.modelWriteIdentityIsResident(identity, true))
        return if (identity.session_token != z3d.g_model_session_token or z3d.modelDocumentTokenForId(identity.model_id) != z3d.g_model_session_token)
            z3d.faceRecoveryErrorJsonAlloc(allocator, "wrong_model", "document adopt targets a different resident session", false)
        else
            z3d.faceRecoveryErrorJsonAlloc(allocator, "stale_generation", "resident mesh generation changed", true);
    z3d.g_model_write_leases.validate(request.leaseReceiptId, identity) catch
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "authorization_failed", "document adopt does not own the active write lease", false);
    const journal_label: []const u8 = switch (request.journalKind) {
        .historical_restore => if (std.mem.eql(u8, request.actor, "recovery-coordinator"))
            "historical restore"
        else
            return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "historical restore adoption requires the recovery coordinator", false),
        .field_edit => if (std.mem.eql(u8, request.actor, "field-edit-coordinator"))
            "guarded field edit"
        else
            return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "field-edit adoption requires the field-edit coordinator", false),
    };
    if (z3d.g_model_adoption_receipts.active != null)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "lease_refused", "the active write lease already owns an adoption", false);

    const target_sha = z3d.sha256Hex(bytes);
    if (!std.mem.eql(u8, &target_sha, request.expectedSha256))
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "hash_mismatch", "candidate bytes differ from expected SHA-256", false);
    var document = meshdoc_format.decodeDocument(allocator, bytes) catch
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "candidate is not a readable current RJMD document", false);
    defer document.deinit(allocator);
    if (document.version != meshdoc_format.VERSION_LOGICAL_TOPOLOGY or document.range_object_ids == null)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "restore candidate must be RJMD v5 with stable object IDs", false);
    var target = z3d.journalEntryFromDocument(&document, request.modelId, journal_label) catch |err| switch (err) {
        error.OutOfMemory => return error.OutOfMemory,
        else => return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "restore candidate channels are incomplete", false),
    };
    defer z3d.journalFreeEntry(&target);

    const preimage_bytes = z3d.modelEncodeCurrentDocumentAlloc(allocator, request.modelId) catch |err| switch (err) {
        error.OutOfMemory => return error.OutOfMemory,
        error.WrongModel => return z3d.faceRecoveryErrorJsonAlloc(allocator, "wrong_model", "resident object namespace belongs to another model", false),
        error.ObjectIdsUnpublished => return z3d.faceRecoveryErrorJsonAlloc(allocator, "object_ids_unpublished", "resident stable object IDs are not published", false),
        else => return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "resident document cannot be encoded exactly", false),
    };
    defer allocator.free(preimage_bytes);
    const preimage_sha = z3d.sha256Hex(preimage_bytes);

    z3d.g_authorized_model_write_receipt = request.leaseReceiptId;
    defer z3d.g_authorized_model_write_receipt = 0;
    var preimage = z3d.journalSnapshotCurrent(journal_label) orelse
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "internal_error", "could not capture exact resident preimage", false);
    var preimage_live = true;
    defer if (preimage_live) z3d.journalFreeEntry(&preimage);

    if (!z3d.journalInstall(&target) or !z3d.journalResidentDurableMatches(&target)) {
        const rolled_back = z3d.journalInstall(&preimage) and z3d.journalResidentDurableMatches(&preimage);
        return z3d.faceRecoveryErrorJsonAlloc(
            allocator,
            "internal_error",
            if (rolled_back) "candidate adoption was refused and resident preimage was restored" else "candidate adoption and resident rollback both failed",
            false,
        );
    }
    const resident_bytes = z3d.modelEncodeCurrentDocumentAlloc(allocator, request.modelId) catch {
        _ = z3d.journalInstall(&preimage);
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "internal_error", "adopted resident could not be re-encoded", false);
    };
    defer allocator.free(resident_bytes);
    const resident_sha = z3d.sha256Hex(resident_bytes);
    if (!std.mem.eql(u8, &resident_sha, &target_sha)) {
        const rolled_back = z3d.journalInstall(&preimage) and z3d.journalResidentDurableMatches(&preimage);
        return z3d.faceRecoveryErrorJsonAlloc(
            allocator,
            "hash_mismatch",
            if (rolled_back) "adopted resident bytes differ from candidate; preimage restored" else "adopted bytes differ and resident rollback failed",
            false,
        );
    }

    var preimage_optional: ?z3d.JournalEntry = preimage;
    preimage_live = false;
    z3d.journalCommit(&preimage_optional);
    if (preimage_optional != null or z3d.g_last_committed_action_id == 0)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "internal_error", "historical restore could not enter the native journal", false);
    const adoption = z3d.g_model_adoption_receipts.issue(
        request.leaseReceiptId,
        z3d.g_last_committed_action_id,
        z3d.g_model_session_token,
        z3d.g_edit_generation,
        preimage_sha,
        target_sha,
    ) catch {
        var current_target = z3d.journalSnapshotCurrent(journal_label) orelse
            return z3d.faceRecoveryErrorJsonAlloc(allocator, "internal_error", "adoption receipt failed after journal commit", false);
        defer z3d.journalFreeEntry(&current_target);
        const synthetic = model_adoption_receipt.Receipt{
            .id = 0,
            .lease_id = request.leaseReceiptId,
            .action_id = z3d.g_last_committed_action_id,
            .session_token = z3d.g_model_session_token,
            .generation_after = z3d.g_edit_generation,
            .preimage_sha256 = preimage_sha,
            .target_sha256 = target_sha,
        };
        _ = z3d.rollbackAdoptedJournalAction(synthetic, &current_target);
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "internal_error", "adoption receipt registry refused the journal action", false);
    };
    return std.json.Stringify.valueAlloc(allocator, .{
        .ok = true,
        .version = 1,
        .adoptionReceiptId = adoption.id,
        .journalActionId = adoption.action_id,
        .preimageSha256 = &preimage_sha,
        .targetSha256 = &target_sha,
        .residentSha256 = &resident_sha,
        .generation = z3d.g_edit_generation,
        .journalActionKind = @tagName(request.journalKind),
    }, .{}) catch |err| {
        // The caller cannot roll back an adoption whose receipt never crossed
        // the boundary. Treat response allocation as part of the transaction.
        const rolled_back = z3d.rollbackAdoptedJournalAction(adoption, &target);
        if (rolled_back) {
            _ = z3d.g_model_adoption_receipts.consumeRollback(adoption.id, request.leaseReceiptId) catch {};
        } else {
            std.log.err("[model-recovery] response allocation failed and adoption rollback could not verify", .{});
        }
        return err;
    };
}

/// Roll back one adoption exactly once while its original write lease remains
/// active. The target is captured first so a late preimage failure can restore
/// the target plane before this function returns a refusal.
pub fn modelDocumentRollbackJsonAlloc(
    allocator: std.mem.Allocator,
    request_json: []const u8,
) ![]u8 {
    var parsed = std.json.parseFromSlice(z3d.ModelDocumentRollbackRequestV1, allocator, request_json, .{}) catch
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid document-rollback request", false);
    defer parsed.deinit();
    const request = parsed.value;
    if (request.version != 1 or request.leaseReceiptId == 0 or request.adoptionReceiptId == 0)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid document-rollback request", false);
    const identity = z3d.modelWriteIdentity(
        request.actor,
        request.operationId,
        request.modelId,
        request.sessionToken,
        request.leaseGeneration,
    ) orelse return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid document-rollback identity", false);
    if (!z3d.modelWriteIdentityIsResident(identity, false))
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "wrong_model", "document rollback targets a different resident session", false);
    z3d.g_model_write_leases.validate(request.leaseReceiptId, identity) catch
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "authorization_failed", "document rollback does not own the active write lease", false);
    const adoption = z3d.g_model_adoption_receipts.get(request.adoptionReceiptId, request.leaseReceiptId) catch
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "authorization_failed", "adoption receipt is not active for this lease", false);
    if (request.expectedCurrentGeneration != z3d.g_edit_generation or adoption.generation_after != z3d.g_edit_generation)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "stale_generation", "resident generation changed after adoption", true);
    const target_bytes = z3d.modelEncodeCurrentDocumentAlloc(allocator, request.modelId) catch
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "internal_error", "current adopted resident cannot be encoded", false);
    defer allocator.free(target_bytes);
    const target_sha = z3d.sha256Hex(target_bytes);
    if (!std.mem.eql(u8, &target_sha, &adoption.target_sha256))
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "hash_mismatch", "resident changed after adoption", false);

    z3d.g_authorized_model_write_receipt = request.leaseReceiptId;
    defer z3d.g_authorized_model_write_receipt = 0;
    var target_snapshot = z3d.journalSnapshotCurrent("historical restore") orelse
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "internal_error", "could not retain adopted target for rollback", false);
    defer z3d.journalFreeEntry(&target_snapshot);
    if (!z3d.rollbackAdoptedJournalAction(adoption, &target_snapshot))
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "internal_error", "exact adoption rollback could not be verified", false);
    _ = z3d.g_model_adoption_receipts.consumeRollback(request.adoptionReceiptId, request.leaseReceiptId) catch
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "internal_error", "rollback receipt could not be consumed", false);
    return std.json.Stringify.valueAlloc(allocator, .{
        .ok = true,
        .version = 1,
        .rolledBack = true,
        .adoptionReceiptId = request.adoptionReceiptId,
        .residentSha256 = &adoption.preimage_sha256,
        .generation = z3d.g_edit_generation,
    }, .{});
}

pub const HistoricalPreviewDegradationWireV1 = mesh_face_table.RecoveryDegradationWireV1;

pub const HistoricalPreviewOpenRequestV1 = struct {
    version: u32,
    operation: enum { open },
    modelId: []const u8,
    snapshotId: []const u8,
    resolvedRevision: []const u8,
    expectedSha256: []const u8,
    identityQuality: mesh_face_table.IdentityQuality,
    objectNamespaceHash: []const u8,
    recoveryDegradations: []const z3d.HistoricalPreviewDegradationWireV1,
};

pub const HistoricalPreviewReleaseRequestV1 = struct {
    version: u32,
    operation: enum { release },
    previewToken: []const u8,
};

pub fn historicalPreviewDegradationsAlloc(
    allocator: std.mem.Allocator,
    source: []const z3d.HistoricalPreviewDegradationWireV1,
) ![]mesh_face_table.RecoveryDegradation {
    const result = try allocator.alloc(mesh_face_table.RecoveryDegradation, source.len);
    for (source, result) |row, *target| {
        var actions: std.EnumSet(mesh_face_table.RecoveryDegradationAction) = .empty;
        for (row.actions) |action| actions.insert(action);
        var reasons: std.EnumSet(mesh_face_table.RecoveryDegradationReason) = .empty;
        for (row.reasons) |reason| reasons.insert(reason);
        if (row.actions.len == 0 or row.reasons.len == 0) return error.InvalidRecoveryProvenance;
        target.* = .{
            .channel = row.channel,
            .actions = actions,
            .reasons = reasons,
            .affected_count = row.affectedCount,
        };
    }
    return result;
}

pub fn historicalPreviewOpenJsonAlloc(
    allocator: std.mem.Allocator,
    request_json: []const u8,
    bytes: []const u8,
) ![]u8 {
    var parsed = std.json.parseFromSlice(z3d.HistoricalPreviewOpenRequestV1, allocator, request_json, .{}) catch
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid historical preview open request", false);
    defer parsed.deinit();
    const request = parsed.value;
    if (request.version != 1 or request.modelId.len == 0 or request.snapshotId.len == 0 or
        request.resolvedRevision.len != 64 or request.expectedSha256.len != 64 or
        request.objectNamespaceHash.len != 64 or
        (request.identityQuality == .exact) != (request.recoveryDegradations.len == 0))
    {
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid historical preview open request", false);
    }
    // The Lore capability proves the bytes, not which model is currently in
    // this Scene3D owner. Refuse before decoding/parking anything when a stale
    // Versions row from model A is invoked after the viewport moved to model B.
    if (!historical_preview.targetsResident(
        z3d.modelDocumentTokenForId(request.modelId),
        z3d.g_model_session_token,
        z3d.modelSessionResident(),
    ))
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "wrong_model", "historical preview does not target the resident Scene3D model", false);
    if (z3d.g_gizmo_snap != null or z3d.g_paint_session or z3d.g_lc != null or z3d.g_bevel != null or z3d.g_quadify != null or
        z3d.g_model_write_leases.owner() != null)
    {
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "lease_refused", "finish the active resident edit before opening historical preview", false);
    }
    const degradations = z3d.historicalPreviewDegradationsAlloc(allocator, request.recoveryDegradations) catch
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid historical preview recovery provenance", false);
    defer allocator.free(degradations);
    const token = z3d.g_historical_preview.open(.{
        .model_id = request.modelId,
        .snapshot_id = request.snapshotId,
        .revision = request.resolvedRevision,
        .sha256 = request.expectedSha256,
        .bytes = bytes,
        .identity_quality = request.identityQuality,
        .recovery_degradations = degradations,
        .max_vertices = z3d.MAX_DYN_VERTS,
    }) catch |err| return z3d.faceRecoveryErrorJsonAlloc(allocator, switch (err) {
        error.PreviewHashMismatch => "hash_mismatch",
        error.PreviewAlreadyOpen => "invalid_request",
        error.PreviewTooLarge => "invalid_request",
        else => "internal_error",
    }, @errorName(err), false);
    defer allocator.free(token);
    z3d.g_historical_preview_saved_orbit = z3d.g_orbit;
    const specimen = &z3d.g_historical_preview.active.?;
    z3d.orbitFrame(specimen.center, specimen.radius);
    errdefer {
        _ = z3d.g_historical_preview.release(token) catch {};
        if (z3d.g_historical_preview_saved_orbit) |saved| z3d.g_orbit = saved;
        z3d.g_historical_preview_saved_orbit = null;
    }
    return std.json.Stringify.valueAlloc(allocator, .{
        .ok = true,
        .version = 1,
        .previewToken = token,
        .modelId = specimen.model_id,
        .snapshotId = specimen.snapshot_id,
        .resolvedRevision = specimen.revision,
        .sha256 = &specimen.sha256,
        .formatVersion = specimen.document.version,
        .triangleCount = specimen.document.verts.len / 24,
        .readOnly = true,
    }, .{});
}

pub fn historicalPreviewReleaseJsonAlloc(
    allocator: std.mem.Allocator,
    request_json: []const u8,
) ![]u8 {
    var parsed = std.json.parseFromSlice(z3d.HistoricalPreviewReleaseRequestV1, allocator, request_json, .{}) catch
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid historical preview release request", false);
    defer parsed.deinit();
    if (parsed.value.version != 1 or parsed.value.previewToken.len == 0)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid historical preview release request", false);
    const released = z3d.g_historical_preview.release(parsed.value.previewToken) catch |err|
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "released_capability", @errorName(err), false);
    if (released.released) {
        if (z3d.g_historical_preview_saved_orbit) |saved| z3d.g_orbit = saved;
        z3d.g_historical_preview_saved_orbit = null;
    }
    return std.json.Stringify.valueAlloc(allocator, .{
        .ok = true,
        .version = 1,
        .released = released.released,
        .alreadyReleased = released.already_released,
    }, .{});
}

pub fn historicalPreviewActive() bool {
    return z3d.g_historical_preview.active != null;
}

pub const FaceObjectPublicationRowV1 = struct {
    rank: u32,
    objectId: []const u8,
};

pub const FaceObjectPublicationV1 = struct {
    version: u32,
    modelId: []const u8,
    sessionToken: []const u8,
    expectedGeneration: u64,
    ranges: []const z3d.FaceObjectPublicationRowV1,
};

pub const FaceSessionIdentityRequestV1 = struct {
    version: u32,
    modelId: []const u8,
};

pub const FacePlaneRequestV1 = struct {
    source: []const u8,
    sessionToken: ?[]const u8 = null,
    expectedGeneration: ?u64 = null,
    previewToken: ?[]const u8 = null,
    expectedSha256: ?[]const u8 = null,
};

pub const FaceAddressRequestV1 = struct {
    objectId: []const u8,
    group: u32,
    stability: []const u8,
    artifactFaceOrdinal: ?u32 = null,
};

pub const FaceSelectTargetRequestV1 = struct {
    kind: []const u8,
    address: ?z3d.FaceAddressRequestV1 = null,
    objectId: ?[]const u8 = null,
    sourceGroup: ?u32 = null,
};

pub const FaceSelectRequestV1 = struct {
    version: u32,
    modelId: []const u8,
    plane: z3d.FacePlaneRequestV1,
    target: z3d.FaceSelectTargetRequestV1,
    additive: bool,
    frame: bool,
};

pub const FaceSeekRequestV1 = struct {
    version: u32,
    modelId: []const u8,
    plane: z3d.FacePlaneRequestV1,
    address: z3d.FaceAddressRequestV1,
    sort: std.json.Value,
    filters: std.json.Value,
    limit: u32,
};

pub const FacePlaneKind = enum { resident, preview };

pub fn facePlaneKind(plane: z3d.FacePlaneRequestV1) ?z3d.FacePlaneKind {
    if (std.mem.eql(u8, plane.source, "resident")) {
        if (plane.sessionToken == null or plane.sessionToken.?.len == 0 or
            plane.expectedGeneration == null or plane.previewToken != null or plane.expectedSha256 != null) return null;
        return .resident;
    }
    if (std.mem.eql(u8, plane.source, "preview")) {
        if (plane.previewToken == null or plane.previewToken.?.len == 0 or
            plane.expectedSha256 == null or plane.expectedSha256.?.len == 0 or
            plane.sessionToken != null or plane.expectedGeneration != null) return null;
        return .preview;
    }
    return null;
}

pub fn faceAddressView(address: z3d.FaceAddressRequestV1) ?mesh_face_table.AddressView {
    if (address.objectId.len == 0) return null;
    if (std.mem.eql(u8, address.stability, "stable")) {
        if (address.artifactFaceOrdinal != null or address.group == indexed_edit_mesh.NO_GROUP) return null;
        return .{
            .object_id = address.objectId,
            .group = address.group,
            .stability = .stable,
        };
    }
    if (std.mem.eql(u8, address.stability, "artifact_rank")) {
        return .{
            .object_id = address.objectId,
            .group = address.group,
            .stability = .artifact_rank,
            .artifact_face_ordinal = address.artifactFaceOrdinal orelse return null,
        };
    }
    return null;
}

pub fn modelDocumentTokenForId(model_id: []const u8) u32 {
    var hash: u32 = 0x811c9dc5;
    for (model_id) |byte| hash = (hash ^ byte) *% 0x01000193;
    return (hash & 0x7fff_ffff) | @as(u32, @intFromBool((hash & 0x7fff_ffff) == 0));
}

pub fn faceSessionTokenMatches(text: []const u8) bool {
    const token = std.fmt.parseInt(u32, text, 10) catch return false;
    return token == z3d.g_model_session_token;
}

pub fn faceSessionTokenText(buffer: []u8) ?[]const u8 {
    return std.fmt.bufPrint(buffer, "{d}", .{z3d.g_model_session_token}) catch null;
}

pub fn faceRecoveryErrorJsonAlloc(
    allocator: std.mem.Allocator,
    code: []const u8,
    detail: []const u8,
    include_generation: bool,
) ![]u8 {
    if (include_generation) return std.json.Stringify.valueAlloc(allocator, .{
        .ok = false,
        .version = 1,
        .code = code,
        .detail = detail,
        .currentGeneration = z3d.g_edit_generation,
    }, .{});
    return std.json.Stringify.valueAlloc(allocator, .{
        .ok = false,
        .version = 1,
        .code = code,
        .detail = detail,
    }, .{});
}

pub fn objectNamespaceHash(model_id: []const u8, object_ids: []const []const u8, ranges: []const u32) [64]u8 {
    return meshdoc_format.objectNamespaceHashHex(model_id, object_ids, ranges);
}

/// Exact resident identity used before every face inspection and recovery
/// capture. The model id is verified against the active document token; a
/// caller cannot claim whichever model happens to be visible.
pub fn meshSessionIdentityJsonAlloc(allocator: std.mem.Allocator, request_json: []const u8) ![]u8 {
    var parsed = std.json.parseFromSlice(z3d.FaceSessionIdentityRequestV1, allocator, request_json, .{}) catch
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid mesh session identity request", false);
    defer parsed.deinit();
    if (parsed.value.version != 1 or parsed.value.modelId.len == 0)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid mesh session identity request", false);
    if (!z3d.modelSessionResident())
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "no_resident_session", "no resident model document", false);
    if (z3d.modelDocumentTokenForId(parsed.value.modelId) != z3d.g_model_session_token)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "wrong_model", "the requested model does not own the resident session", false);
    var token_buffer: [16]u8 = undefined;
    const token = z3d.faceSessionTokenText(&token_buffer) orelse
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "internal_error", "could not encode resident session token", false);
    const empty_ids = [_][]const u8{};
    const namespace = z3d.objectNamespaceHash(parsed.value.modelId, &empty_ids, &.{});
    return mesh_face_table.exactSessionIdentityJsonAlloc(
        allocator,
        parsed.value.modelId,
        token,
        z3d.g_edit_generation,
        &namespace,
    );
}

/// Publish stable object identity for the current range table. Any later range
/// mutation clears this publication in model_source; callers must republish the
/// new exact order before a durable face address can be returned.
pub fn meshPublishObjectIdsJsonAlloc(allocator: std.mem.Allocator, request_json: []const u8) ![]u8 {
    if (!z3d.residentMutationAllowed(.durable_channels))
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "historical preview is read-only; object-id publication is blocked", false);
    var parsed = std.json.parseFromSlice(z3d.FaceObjectPublicationV1, allocator, request_json, .{}) catch
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid object-id publication request", false);
    defer parsed.deinit();
    const request = parsed.value;
    if (request.version != 1 or request.modelId.len == 0 or request.sessionToken.len == 0 or request.ranges.len == 0)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid object-id publication request", false);
    if (!z3d.modelSessionResident())
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "no_resident_session", "no resident model document", false);
    if (z3d.modelDocumentTokenForId(request.modelId) != z3d.g_model_session_token or !z3d.faceSessionTokenMatches(request.sessionToken))
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "wrong_model", "object ids target a different resident session", false);
    if (request.expectedGeneration != z3d.g_edit_generation)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "stale_generation", "resident mesh generation changed", true);
    const part_ranges = model_source.partRanges() orelse
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "object_ids_unpublished", "resident mesh has no exact part-range table", false);
    if (part_ranges.len != request.ranges.len * 2)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "object_ids_unpublished", "object-id count differs from the resident part-range count", false);
    const object_ids = try allocator.alloc([]const u8, request.ranges.len);
    defer allocator.free(object_ids);
    for (request.ranges, 0..) |row, index| {
        if (row.rank != index or row.objectId.len == 0)
            return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "object ids must be unique and range-ranked", false);
        for (request.ranges[0..index]) |prior| if (std.mem.eql(u8, prior.objectId, row.objectId))
            return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "object ids must be unique and range-ranked", false);
        object_ids[index] = row.objectId;
    }
    switch (model_source.publishPartObjectIds(request.modelId, object_ids)) {
        .rejected => return z3d.faceRecoveryErrorJsonAlloc(allocator, "object_ids_unpublished", "native object-id publication was refused", false),
        .unchanged => {},
        .changed => z3d.g_face_table_worker.invalidateIdentity(),
    }
    const namespace = z3d.objectNamespaceHash(request.modelId, object_ids, part_ranges);
    return std.json.Stringify.valueAlloc(allocator, .{
        .ok = true,
        .version = 1,
        .modelId = request.modelId,
        .sessionToken = request.sessionToken,
        .generation = z3d.g_edit_generation,
        .objectCount = object_ids.len,
        .identityQuality = "exact",
        .objectNamespaceHash = &namespace,
        .recoveryDegradations = mesh_face_table.EMPTY_RECOVERY_DEGRADATIONS_V1,
    }, .{});
}

pub fn semanticRegionName(root: std.json.Value, region_id: u32) ?[]const u8 {
    const object = switch (root) {
        .object => |value| value,
        else => return null,
    };
    const regions = switch (object.get("regions") orelse return null) {
        .array => |value| value.items,
        else => return null,
    };
    for (regions) |region| {
        const row = switch (region) {
            .object => |value| value,
            else => continue,
        };
        const id: u32 = switch (row.get("id") orelse continue) {
            .integer => |value| if (value >= 0 and value <= std.math.maxInt(u32)) @intCast(value) else continue,
            else => continue,
        };
        if (id != region_id) continue;
        return switch (row.get("name") orelse return null) {
            .string => |value| if (value.len > 0) value else null,
            else => null,
        };
    }
    return null;
}

pub fn residentFaceAnalysisJobAlloc(
    allocator: std.mem.Allocator,
    model_id: []const u8,
    session_token: []const u8,
) !mesh_face_table_worker.PreparedJob {
    if (!z3d.ensureIndexedEditMesh()) return error.NoResidentMesh;
    const mesh = if (z3d.g_indexed_edit_mesh) |*resident| resident else return error.NoResidentMesh;
    const published_model = model_source.partObjectModelId() orelse return error.ObjectIdsUnpublished;
    if (!std.mem.eql(u8, published_model, model_id)) return error.WrongModel;
    const ids_json = model_source.partObjectIdsJson() orelse return error.ObjectIdsUnpublished;
    const ranges = model_source.partRanges() orelse return error.ObjectIdsUnpublished;

    var arena = std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    const temp = arena.allocator();
    var parsed_ids = try std.json.parseFromSlice(std.json.Value, temp, ids_json, .{});
    defer parsed_ids.deinit();
    const id_values = switch (parsed_ids.value) {
        .array => |value| value.items,
        else => return error.ObjectIdsUnpublished,
    };
    if (id_values.len == 0 or id_values.len * 2 != ranges.len) return error.ObjectIdsUnpublished;
    const object_ids = try temp.alloc([]const u8, id_values.len);
    const bindings = try temp.alloc(mesh_face_table.ObjectBinding, id_values.len);
    for (id_values, 0..) |value, index| {
        const object_id = switch (value) {
            .string => |text| if (text.len > 0) text else return error.ObjectIdsUnpublished,
            else => return error.ObjectIdsUnpublished,
        };
        object_ids[index] = object_id;
        bindings[index] = .{ .rank = @intCast(index), .object_id = object_id };
    }

    var parsed_semantics: ?std.json.Parsed(std.json.Value) = null;
    defer if (parsed_semantics) |*value| value.deinit();
    if (model_source.semanticTableJson()) |json| {
        parsed_semantics = std.json.parseFromSlice(std.json.Value, temp, json, .{}) catch null;
    }
    var labels = std.ArrayListUnmanaged(mesh_face_table.DurableFaceLabelInput).empty;
    defer labels.deinit(temp);
    if (parsed_semantics) |parsed| for (mesh.faces.items) |*face| {
        if (!face.alive) continue;
        const name = z3d.semanticRegionName(parsed.value, face.semantic.region) orelse continue;
        try labels.append(temp, .{
            .face_id = face.id,
            .face_name = name,
            .semantic_region_name = name,
        });
    };

    const render_classes = try temp.alloc(mesh_face_table.RenderClass, mesh.faces.items.len);
    @memset(render_classes, .@"opaque");
    for (mesh.faces.items) |*face| {
        if (!face.alive or face.id >= render_classes.len) continue;
        for (face.source_triangles.items) |triangle| {
            const color = model_source.colorOf(triangle) orelse continue;
            if (model_paint.isGlassAlpha(color[3])) {
                render_classes[face.id] = .glass;
                break;
            }
        }
    }
    const namespace = z3d.objectNamespaceHash(model_id, object_ids, ranges);
    return mesh_face_table_worker.PreparedJob.captureIndexedAlloc(allocator, .{
        .mesh = mesh,
        .identity = .{
            .source = .resident,
            .model_id = model_id,
            .session_token = session_token,
            .generation = z3d.g_edit_generation,
            .identity_quality = .exact,
            .object_namespace_hash = &namespace,
        },
        .object_bindings = bindings,
        .durable_labels = labels.items,
        .render_class_by_face = render_classes,
    });
}

pub fn residentFacePlaneHashAlloc(
    allocator: std.mem.Allocator,
    model_id: []const u8,
    session_token: []const u8,
) ![64]u8 {
    const published_model = model_source.partObjectModelId() orelse return error.ObjectIdsUnpublished;
    if (!std.mem.eql(u8, published_model, model_id)) return error.WrongModel;
    const ids_json = model_source.partObjectIdsJson() orelse return error.ObjectIdsUnpublished;
    const ranges = model_source.partRanges() orelse return error.ObjectIdsUnpublished;
    var parsed_ids = try std.json.parseFromSlice(std.json.Value, allocator, ids_json, .{});
    defer parsed_ids.deinit();
    const values = switch (parsed_ids.value) {
        .array => |value| value.items,
        else => return error.ObjectIdsUnpublished,
    };
    if (values.len == 0 or values.len * 2 != ranges.len) return error.ObjectIdsUnpublished;
    const object_ids = try allocator.alloc([]const u8, values.len);
    defer allocator.free(object_ids);
    for (values, 0..) |value, index| object_ids[index] = switch (value) {
        .string => |text| if (text.len > 0) text else return error.ObjectIdsUnpublished,
        else => return error.ObjectIdsUnpublished,
    };
    const namespace = z3d.objectNamespaceHash(model_id, object_ids, ranges);
    return mesh_face_table_worker.planeIdentityHash(.{
        .source = .resident,
        .model_id = model_id,
        .session_token = session_token,
        .generation = z3d.g_edit_generation,
        .identity_quality = .exact,
        .object_namespace_hash = &namespace,
    });
}

pub const ResidentAnalysisLookup = union(enum) {
    snapshot: *const mesh_face_table.FaceAnalysisSnapshot,
    response: []u8,
};

pub fn residentAnalysisErrorAlloc(
    allocator: std.mem.Allocator,
    err: anyerror,
) ![]u8 {
    return switch (err) {
        error.ObjectIdsUnpublished => z3d.faceRecoveryErrorJsonAlloc(allocator, "object_ids_unpublished", "stable resident object ids have not been published", false),
        error.WrongModel => z3d.faceRecoveryErrorJsonAlloc(allocator, "wrong_model", "published object ids belong to a different model", false),
        error.NoResidentMesh => z3d.faceRecoveryErrorJsonAlloc(allocator, "no_resident_session", "resident mesh has no editable topology", false),
        else => z3d.faceRecoveryErrorJsonAlloc(allocator, "internal_error", "resident face analysis capture failed", false),
    };
}

pub fn residentFaceAnalysisLookup(
    io: std.Io,
    allocator: std.mem.Allocator,
    model_id: []const u8,
    session_token: []const u8,
) !z3d.ResidentAnalysisLookup {
    if (!z3d.g_face_table_worker.isStarted()) {
        z3d.g_face_table_worker.start(io, allocator, 2) catch
            return .{ .response = try z3d.faceRecoveryErrorJsonAlloc(allocator, "internal_error", "resident face-analysis worker could not start", false) };
    }
    const identity_hash = z3d.residentFacePlaneHashAlloc(allocator, model_id, session_token) catch |err|
        return .{ .response = try z3d.residentAnalysisErrorAlloc(allocator, err) };
    if (z3d.g_face_table_worker.cacheView(io, identity_hash)) |cached| switch (cached) {
        .success => |snapshot| {
            _ = z3d.g_face_table_worker.selectCached(io, identity_hash);
            return .{ .snapshot = snapshot };
        },
        .diff => return .{ .response = try z3d.faceRecoveryErrorJsonAlloc(allocator, "internal_error", "resident face cache contains an invalid result kind", false) },
        .failure => |failure| return .{ .response = try z3d.faceRecoveryErrorJsonAlloc(
            allocator,
            @tagName(mesh_face_table_worker.publicFailureCode(.resident, failure.code)),
            failure.text(),
            false,
        ) },
    };
    if (z3d.g_face_table_worker.pendingReceipt(io, identity_hash)) |receipt|
        return .{ .response = try mesh_face_table_worker.pendingJsonAlloc(allocator, receipt) };

    var prepared = z3d.residentFaceAnalysisJobAlloc(allocator, model_id, session_token) catch |err|
        return .{ .response = try z3d.residentAnalysisErrorAlloc(allocator, err) };
    if (!std.mem.eql(u8, &prepared.identityHash(), &identity_hash)) {
        prepared.deinit();
        return .{ .response = try z3d.faceRecoveryErrorJsonAlloc(allocator, "internal_error", "resident capture identity changed during owner copy", false) };
    }
    return switch (z3d.g_face_table_worker.submitOwned(io, prepared)) {
        .queued => |receipt| .{ .response = try mesh_face_table_worker.pendingJsonAlloc(allocator, receipt) },
        .stopped => .{ .response = try z3d.faceRecoveryErrorJsonAlloc(allocator, "internal_error", "resident face-analysis worker stopped", false) },
    };
}

pub fn faceRequestIsDiff(allocator: std.mem.Allocator, request_json: []const u8) bool {
    var parsed = std.json.parseFromSlice(std.json.Value, allocator, request_json, .{}) catch return false;
    defer parsed.deinit();
    const root = switch (parsed.value) {
        .object => |object| object,
        else => return false,
    };
    const source = switch (root.get("source") orelse return false) {
        .string => |value| value,
        else => return false,
    };
    return std.mem.eql(u8, source, "diff");
}

pub fn diffQueryErrorJsonAlloc(
    allocator: std.mem.Allocator,
    err: mesh_face_diff.DiffError,
) ![]u8 {
    return switch (err) {
        error.OutOfMemory => error.OutOfMemory,
        error.InvalidQuery => z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid face-diff query", false),
        error.AuditUnavailable => z3d.faceRecoveryErrorJsonAlloc(allocator, "audit_unavailable", "requested diff audit facts were not computed", false),
        error.StaleCursor => z3d.faceRecoveryErrorJsonAlloc(allocator, "stale_cursor", "face-diff cursor belongs to another plane or query", false),
        error.AddressNotInQuery => z3d.faceRecoveryErrorJsonAlloc(allocator, "address_not_in_query", "face address is not present in this diff query", false),
        error.InvalidPlanes, error.InvalidReceipt => z3d.faceRecoveryErrorJsonAlloc(allocator, "internal_error", "native face-diff planes are inconsistent", false),
    };
}

pub fn meshFaceDiffJsonAlloc(
    io: std.Io,
    allocator: std.mem.Allocator,
    request_json: []const u8,
) ![]u8 {
    var parsed = mesh_face_diff.parseRequestAlloc(allocator, request_json) catch |err| switch (err) {
        error.OutOfMemory => return error.OutOfMemory,
        else => return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid face-diff v1 request", false),
    };
    defer parsed.deinit();
    const resident_query = parsed.resident.query;
    if (!z3d.modelSessionResident())
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "no_resident_session", "no resident model document", false);
    if (z3d.modelDocumentTokenForId(resident_query.model_id) != z3d.g_model_session_token or
        resident_query.session_token == null or !z3d.faceSessionTokenMatches(resident_query.session_token.?))
    {
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "wrong_model", "face-diff request targets a different resident session", false);
    }
    if (resident_query.expected_generation == null or resident_query.expected_generation.? != z3d.g_edit_generation)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "stale_generation", "resident mesh generation changed", true);

    var saved_query = resident_query;
    saved_query.source = .saved;
    saved_query.session_token = null;
    saved_query.expected_generation = null;
    saved_query.geometry_path = parsed.geometry_path;
    saved_query.expected_sha256 = parsed.expected_saved_sha256;

    if (!z3d.g_face_table_worker.isStarted()) z3d.g_face_table_worker.start(io, allocator, 2) catch
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "internal_error", "face-diff worker could not start", false);
    const resident_hash = z3d.residentFacePlaneHashAlloc(
        allocator,
        resident_query.model_id,
        resident_query.session_token.?,
    ) catch |err| return z3d.residentAnalysisErrorAlloc(allocator, err);
    const diff_hash = mesh_face_table_worker.diffPlaneIdentityHashAlloc(allocator, .{
        .model_id = resident_query.model_id,
        .session_token = resident_query.session_token.?,
        .generation = resident_query.expected_generation.?,
        .resident_plane_hash = resident_hash,
        .artifact_sha256 = parsed.expected_saved_sha256,
    }) catch |err| switch (err) {
        error.OutOfMemory => return error.OutOfMemory,
        else => return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid face-diff plane identity", false),
    };
    if (z3d.g_face_table_worker.cacheView(io, diff_hash)) |cached| switch (cached) {
        .diff => |snapshot| {
            _ = z3d.g_face_table_worker.selectCached(io, diff_hash);
            return mesh_face_diff.queryPageJsonAlloc(
                allocator,
                snapshot,
                mesh_face_diff.queryFromParsed(&parsed),
            ) catch |err| z3d.diffQueryErrorJsonAlloc(allocator, err);
        },
        .success => return z3d.faceRecoveryErrorJsonAlloc(allocator, "internal_error", "face-diff cache contains an invalid result kind", false),
        .failure => |failure| return z3d.faceRecoveryErrorJsonAlloc(
            allocator,
            @tagName(mesh_face_table_worker.publicFailureCode(.diff, failure.code)),
            failure.text(),
            false,
        ),
    };
    if (z3d.g_face_table_worker.pendingReceipt(io, diff_hash)) |receipt|
        return mesh_face_table_worker.pendingJsonAlloc(allocator, receipt);

    var bytes = mesh_face_table_package.readSavedQueryFromCwdAlloc(
        io,
        allocator,
        saved_query,
    ) catch |err| switch (err) {
        error.OutOfMemory => return error.OutOfMemory,
        error.InvalidRequest => return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "saved diff geometry is outside the model-package lane", false),
        error.WrongModel => return z3d.faceRecoveryErrorJsonAlloc(allocator, "wrong_model", "saved diff package belongs to a different model", false),
        else => return z3d.faceRecoveryErrorJsonAlloc(allocator, "unreadable_saved_document", "saved diff geometry could not be read", false),
    };
    defer if (bytes.len > 0) allocator.free(bytes);
    var resident_job = z3d.residentFaceAnalysisJobAlloc(
        allocator,
        resident_query.model_id,
        resident_query.session_token.?,
    ) catch |err| return z3d.residentAnalysisErrorAlloc(allocator, err);
    var resident_job_owned = true;
    defer if (resident_job_owned) resident_job.deinit();
    var prepared = mesh_face_table_worker.PreparedJob.attachSavedDiffAlloc(
        allocator,
        &resident_job,
        &bytes,
        .{
            .source = .saved,
            .model_id = resident_query.model_id,
            .expected_sha256 = parsed.expected_saved_sha256,
        },
        .{},
        .{},
    ) catch |err| switch (err) {
        error.OutOfMemory => return error.OutOfMemory,
        else => return z3d.faceRecoveryErrorJsonAlloc(allocator, "internal_error", "face-diff worker input could not be captured", false),
    };
    resident_job_owned = false;
    const prepared_hash = prepared.identityHash();
    if (!std.mem.eql(u8, &prepared_hash, &diff_hash)) {
        prepared.deinit();
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "internal_error", "face-diff identity changed during owner capture", false);
    }
    return switch (z3d.g_face_table_worker.submitOwned(io, prepared)) {
        .queued => |receipt| mesh_face_table_worker.pendingJsonAlloc(allocator, receipt),
        .stopped => z3d.faceRecoveryErrorJsonAlloc(allocator, "internal_error", "face-diff worker stopped", false),
    };
}

pub fn meshFaceTableJsonAlloc(io: std.Io, allocator: std.mem.Allocator, request_json: []const u8) ![]u8 {
    if (z3d.faceRequestIsDiff(allocator, request_json))
        return z3d.meshFaceDiffJsonAlloc(io, allocator, request_json);
    var parsed = mesh_face_table.parseQueryAlloc(allocator, request_json) catch
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid face-table v1 request", false);
    defer parsed.deinit();
    const query = parsed.query;
    if (query.source == .saved)
        return mesh_face_table_package.inspectSavedFromCwdAlloc(io, allocator, request_json);
    if (query.source == .preview) {
        const token = query.preview_token orelse
            return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "preview face table requires previewToken", false);
        const sha = query.expected_sha256 orelse
            return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "preview face table requires expectedSha256", false);
        const specimen = z3d.g_historical_preview.activeFor(token, query.model_id, sha) catch |err|
            return z3d.faceRecoveryErrorJsonAlloc(allocator, switch (err) {
                error.PreviewWrongModel => "wrong_model",
                error.PreviewHashMismatch => "hash_mismatch",
                else => "released_capability",
            }, @errorName(err), false);
        return specimen.analysis.requestJsonAlloc(allocator, request_json);
    }
    if (query.source != .resident)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "unknown face-table plane", false);
    if (!z3d.modelSessionResident())
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "no_resident_session", "no resident model document", false);
    if (z3d.modelDocumentTokenForId(query.model_id) != z3d.g_model_session_token or
        query.session_token == null or !z3d.faceSessionTokenMatches(query.session_token.?))
    {
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "wrong_model", "face-table request targets a different resident session", false);
    }
    if (query.expected_generation == null or query.expected_generation.? != z3d.g_edit_generation)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "stale_generation", "resident mesh generation changed", true);
    const lookup = try z3d.residentFaceAnalysisLookup(io, allocator, query.model_id, query.session_token.?);
    const analysis = switch (lookup) {
        .snapshot => |snapshot| snapshot,
        .response => |response| return response,
    };
    return mesh_face_table.queryPageAlloc(allocator, analysis, query) catch |err| switch (err) {
        error.InvalidRequest => z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid face-table query", false),
        error.WrongModel => z3d.faceRecoveryErrorJsonAlloc(allocator, "wrong_model", "face-table identity changed", false),
        error.StaleGeneration => z3d.faceRecoveryErrorJsonAlloc(allocator, "stale_generation", "resident mesh generation changed", true),
        error.AuditUnavailable => z3d.faceRecoveryErrorJsonAlloc(allocator, "audit_unavailable", "requested audit facts were not computed", false),
        error.StaleCursor => z3d.faceRecoveryErrorJsonAlloc(allocator, "stale_cursor", "face-table cursor belongs to another plane or query", false),
        error.AddressNotInQuery => z3d.faceRecoveryErrorJsonAlloc(allocator, "address_not_in_query", "face address is not present in this query", false),
        else => |unhandled| return unhandled,
    };
}

/// Main-thread completion drain. At most one compact event is returned per
/// call; full analysis snapshots remain owned by the resident/cold workers.
pub fn meshFaceAnalysisReadyJsonAlloc(
    io: std.Io,
    allocator: std.mem.Allocator,
) !?[]u8 {
    if (z3d.g_face_table_worker.isStarted()) {
        if (try z3d.g_face_table_worker.takeReadyEventJsonAlloc(io, allocator)) |event| return event;
    }
    return mesh_face_table_package.takeReadyEventJsonAlloc(io, allocator);
}

pub fn meshFaceAnalysisStop(io: std.Io) void {
    z3d.g_face_table_worker.stop(io);
    mesh_face_table_package.stopWorker(io);
}

pub fn faceSelectFaceReceiptJsonAlloc(
    allocator: std.mem.Allocator,
    request: z3d.FaceSelectRequestV1,
    address: mesh_face_table.AddressView,
    selected_triangles: u32,
) ![]u8 {
    if (address.artifact_face_ordinal) |ordinal| return std.json.Stringify.valueAlloc(allocator, .{
        .ok = true,
        .version = 1,
        .plane = .{
            .source = "resident",
            .sessionToken = request.plane.sessionToken.?,
            .generation = z3d.g_edit_generation,
        },
        .target = .{
            .kind = "face",
            .address = .{
                .objectId = address.object_id,
                .group = address.group,
                .stability = "artifact_rank",
                .artifactFaceOrdinal = ordinal,
            },
        },
        .selectedTriangles = selected_triangles,
    }, .{});
    return std.json.Stringify.valueAlloc(allocator, .{
        .ok = true,
        .version = 1,
        .plane = .{
            .source = "resident",
            .sessionToken = request.plane.sessionToken.?,
            .generation = z3d.g_edit_generation,
        },
        .target = .{
            .kind = "face",
            .address = .{
                .objectId = address.object_id,
                .group = address.group,
                .stability = "stable",
            },
        },
        .selectedTriangles = selected_triangles,
    }, .{});
}

pub fn faceSelectBuildIssueReceiptJsonAlloc(
    allocator: std.mem.Allocator,
    request: z3d.FaceSelectRequestV1,
    object_id: []const u8,
    source_group: u32,
    selected_triangles: u32,
) ![]u8 {
    return std.json.Stringify.valueAlloc(allocator, .{
        .ok = true,
        .version = 1,
        .plane = .{
            .source = "resident",
            .sessionToken = request.plane.sessionToken.?,
            .generation = z3d.g_edit_generation,
        },
        .target = .{
            .kind = "build_issue",
            .objectId = object_id,
            .sourceGroup = source_group,
        },
        .selectedTriangles = selected_triangles,
    }, .{});
}

/// Resolve a durable/local authored-face address, or one stored build issue, to
/// the resident triangle selection and optionally frame it. All identity and
/// membership validation completes before the live selection changes.
pub fn meshFaceSelectJsonAlloc(io: std.Io, allocator: std.mem.Allocator, request_json: []const u8) ![]u8 {
    var parsed = std.json.parseFromSlice(z3d.FaceSelectRequestV1, allocator, request_json, .{}) catch
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid face-select v1 request", false);
    defer parsed.deinit();
    const request = parsed.value;
    if (request.version != 1 or request.modelId.len == 0)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid face-select v1 request", false);
    const plane_kind = z3d.facePlaneKind(request.plane) orelse
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid face-select plane", false);
    if (plane_kind == .preview) {
        if (!std.mem.eql(u8, request.target.kind, "face") or request.target.address == null or
            request.target.objectId != null or request.target.sourceGroup != null)
        {
            return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "preview selection requires one face address", false);
        }
        const address = z3d.faceAddressView(request.target.address.?) orelse
            return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid preview face address", false);
        const token = request.plane.previewToken.?;
        const sha = request.plane.expectedSha256.?;
        const specimen = z3d.g_historical_preview.activeFor(token, request.modelId, sha) catch |err|
            return z3d.faceRecoveryErrorJsonAlloc(allocator, switch (err) {
                error.PreviewWrongModel => "wrong_model",
                error.PreviewHashMismatch => "hash_mismatch",
                else => "released_capability",
            }, @errorName(err), false);
        const selected = specimen.selectAddress(address, request.additive) catch |err|
            return z3d.faceRecoveryErrorJsonAlloc(allocator, "address_not_in_query", @errorName(err), false);
        if (request.frame) z3d.orbitFrame(specimen.center, specimen.radius);
        return std.json.Stringify.valueAlloc(allocator, .{
            .ok = true,
            .version = 1,
            .plane = .{
                .source = "preview",
                .previewToken = token,
                .sha256 = &specimen.sha256,
            },
            .target = request.target,
            .selectedTriangles = selected,
        }, .{});
    }
    if (z3d.g_historical_preview.blocksResidentMutation())
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "historical preview selection must target the preview plane", false);
    if (!z3d.modelSessionResident())
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "no_resident_session", "no resident model document", false);
    if (z3d.modelDocumentTokenForId(request.modelId) != z3d.g_model_session_token or
        !z3d.faceSessionTokenMatches(request.plane.sessionToken.?))
    {
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "wrong_model", "face selection targets a different resident session", false);
    }
    if (request.plane.expectedGeneration.? != z3d.g_edit_generation)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "stale_generation", "resident mesh generation changed", true);
    if (z3d.g_paint_session)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "face selection is unavailable during a paint stroke", false);

    const face_target = std.mem.eql(u8, request.target.kind, "face");
    const issue_target = std.mem.eql(u8, request.target.kind, "build_issue");
    if (!face_target and !issue_target)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "unknown face selection target", false);
    var address: ?mesh_face_table.AddressView = null;
    if (face_target) {
        if (request.target.objectId != null or request.target.sourceGroup != null)
            return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "face target fields do not match its kind", false);
        address = z3d.faceAddressView(request.target.address orelse
            return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "face target requires an address", false)) orelse
            return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid face address", false);
    } else {
        if (request.target.address != null or request.target.objectId == null or
            request.target.objectId.?.len == 0 or request.target.sourceGroup == null)
        {
            return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "build-issue target fields do not match its kind", false);
        }
    }

    const lookup = try z3d.residentFaceAnalysisLookup(io, allocator, request.modelId, request.plane.sessionToken.?);
    const analysis = switch (lookup) {
        .snapshot => |snapshot| snapshot,
        .response => |response| return response,
    };

    const triangle_count: usize = @intCast(z3d.g_edit_count / 3);
    if (triangle_count == 0 or model_paint.faceCount() != triangle_count)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "internal_error", "resident selection topology does not match face analysis", false);
    const selection_mask = try allocator.alloc(bool, triangle_count);
    defer allocator.free(selection_mask);
    @memset(selection_mask, false);
    var target_triangle_count: u32 = 0;

    if (face_target) {
        const row_index = analysis.findAddress(address.?) orelse
            return z3d.faceRecoveryErrorJsonAlloc(allocator, "address_not_in_query", "face address is not present in the resident analysis", false);
        const row = &analysis.rows.items[row_index];
        for (row.triangle_ids) |triangle| {
            if (triangle >= selection_mask.len)
                return z3d.faceRecoveryErrorJsonAlloc(allocator, "internal_error", "face address resolved outside resident selection topology", false);
            if (!selection_mask[triangle]) {
                selection_mask[triangle] = true;
                target_triangle_count += 1;
            }
        }
        if (target_triangle_count == 0 or target_triangle_count != row.triangle_ids.len)
            return z3d.faceRecoveryErrorJsonAlloc(allocator, "internal_error", "face address did not resolve exact triangle membership", false);
    } else {
        const object_id = request.target.objectId.?;
        const source_group = request.target.sourceGroup.?;
        var issue: ?*const mesh_face_table.FaceBuildIssue = null;
        for (analysis.build_issues.items) |*candidate| {
            if (candidate.source_group != source_group or !std.mem.eql(u8, candidate.object_id, object_id)) continue;
            if (issue != null)
                return z3d.faceRecoveryErrorJsonAlloc(allocator, "address_not_in_query", "build-issue target is ambiguous", false);
            issue = candidate;
        }
        const resolved_issue = issue orelse
            return z3d.faceRecoveryErrorJsonAlloc(allocator, "address_not_in_query", "build-issue target is not present in the resident analysis", false);
        for (resolved_issue.source_triangles) |triangle| {
            if (triangle >= selection_mask.len)
                return z3d.faceRecoveryErrorJsonAlloc(allocator, "internal_error", "build issue resolved outside resident selection topology", false);
            if (!selection_mask[triangle]) {
                selection_mask[triangle] = true;
                target_triangle_count += 1;
            }
        }
        if (target_triangle_count == 0 or target_triangle_count != resolved_issue.source_triangles.len)
            return z3d.faceRecoveryErrorJsonAlloc(allocator, "internal_error", "build issue did not resolve exact source-triangle membership", false);
    }

    if (request.additive) {
        for (selection_mask, 0..) |*selected, triangle| {
            selected.* = selected.* or mesh_edit.faceSelectedPub(@intCast(triangle));
        }
    }
    var selected_triangles: u32 = 0;
    for (selection_mask) |selected| selected_triangles += @intFromBool(selected);
    if (mesh_edit.selectFacesByTriangleMask(selection_mask) == 0)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "internal_error", "resident face selection could not be applied", false);
    if (request.frame) _ = z3d.orbitFrameCurrent(true);

    if (face_target) return z3d.faceSelectFaceReceiptJsonAlloc(allocator, request, address.?, selected_triangles);
    return z3d.faceSelectBuildIssueReceiptJsonAlloc(
        allocator,
        request,
        request.target.objectId.?,
        request.target.sourceGroup.?,
        selected_triangles,
    );
}

/// Return the page cursor and row offset containing an authored face under the
/// requested native sort/filter. `seekAddressAlloc` remains the sole owner of
/// sort order and cursor construction.
pub fn meshFaceSeekJsonAlloc(io: std.Io, allocator: std.mem.Allocator, request_json: []const u8) ![]u8 {
    var parsed = std.json.parseFromSlice(z3d.FaceSeekRequestV1, allocator, request_json, .{}) catch
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid face-seek v1 request", false);
    defer parsed.deinit();
    const request = parsed.value;
    if (request.version != 1 or request.modelId.len == 0)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid face-seek v1 request", false);
    const plane_kind = z3d.facePlaneKind(request.plane) orelse
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid face-seek plane", false);
    const address = z3d.faceAddressView(request.address) orelse
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid face address", false);

    if (plane_kind == .preview) {
        const token = request.plane.previewToken.?;
        const sha = request.plane.expectedSha256.?;
        const specimen = z3d.g_historical_preview.activeFor(token, request.modelId, sha) catch |err|
            return z3d.faceRecoveryErrorJsonAlloc(allocator, switch (err) {
                error.PreviewWrongModel => "wrong_model",
                error.PreviewHashMismatch => "hash_mismatch",
                else => "released_capability",
            }, @errorName(err), false);
        const canonical_query_json = try std.json.Stringify.valueAlloc(allocator, .{
            .version = request.version,
            .modelId = request.modelId,
            .source = "preview",
            .previewToken = token,
            .expectedSha256 = sha,
            .sort = request.sort,
            .filters = request.filters,
            .limit = request.limit,
        }, .{});
        defer allocator.free(canonical_query_json);
        var parsed_query = mesh_face_table.parseQueryAlloc(allocator, canonical_query_json) catch
            return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid preview face-seek query", false);
        defer parsed_query.deinit();
        var receipt = mesh_face_table.seekAddressAlloc(
            allocator,
            &specimen.analysis.snapshot,
            parsed_query.query,
            address,
        ) catch |err| return z3d.faceRecoveryErrorJsonAlloc(allocator, "address_not_in_query", @errorName(err), false);
        defer receipt.deinit();
        return std.json.Stringify.valueAlloc(allocator, .{
            .ok = true,
            .version = 1,
            .cursor = @as(?[]const u8, receipt.cursor),
            .rowOffset = receipt.row_offset,
        }, .{});
    }

    const canonical_query_json = try std.json.Stringify.valueAlloc(allocator, .{
        .version = request.version,
        .modelId = request.modelId,
        .source = "resident",
        .sessionToken = request.plane.sessionToken.?,
        .expectedGeneration = request.plane.expectedGeneration.?,
        .sort = request.sort,
        .filters = request.filters,
        .limit = request.limit,
    }, .{});
    defer allocator.free(canonical_query_json);
    var parsed_query = mesh_face_table.parseQueryAlloc(allocator, canonical_query_json) catch
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid face-seek sort, filter, or limit", false);
    defer parsed_query.deinit();
    const query = parsed_query.query;

    if (!z3d.modelSessionResident())
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "no_resident_session", "no resident model document", false);
    if (z3d.modelDocumentTokenForId(query.model_id) != z3d.g_model_session_token or
        query.session_token == null or !z3d.faceSessionTokenMatches(query.session_token.?))
    {
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "wrong_model", "face seek targets a different resident session", false);
    }
    if (query.expected_generation == null or query.expected_generation.? != z3d.g_edit_generation)
        return z3d.faceRecoveryErrorJsonAlloc(allocator, "stale_generation", "resident mesh generation changed", true);

    const lookup = try z3d.residentFaceAnalysisLookup(io, allocator, query.model_id, query.session_token.?);
    const analysis = switch (lookup) {
        .snapshot => |snapshot| snapshot,
        .response => |response| return response,
    };
    var receipt = mesh_face_table.seekAddressAlloc(allocator, analysis, query, address) catch |err| switch (err) {
        error.InvalidRequest => return z3d.faceRecoveryErrorJsonAlloc(allocator, "invalid_request", "invalid face-seek query", false),
        error.WrongModel => return z3d.faceRecoveryErrorJsonAlloc(allocator, "wrong_model", "face-seek identity changed", false),
        error.StaleGeneration => return z3d.faceRecoveryErrorJsonAlloc(allocator, "stale_generation", "resident mesh generation changed", true),
        error.AuditUnavailable => return z3d.faceRecoveryErrorJsonAlloc(allocator, "audit_unavailable", "requested audit facts were not computed", false),
        error.StaleCursor => return z3d.faceRecoveryErrorJsonAlloc(allocator, "stale_cursor", "face-seek cursor input is invalid", false),
        error.AddressNotInQuery => return z3d.faceRecoveryErrorJsonAlloc(allocator, "address_not_in_query", "face address is excluded from this query", false),
        else => |unhandled| return unhandled,
    };
    defer receipt.deinit();
    return std.json.Stringify.valueAlloc(allocator, .{
        .ok = true,
        .version = 1,
        .cursor = @as(?[]const u8, receipt.cursor),
        .rowOffset = receipt.row_offset,
    }, .{});
}

/// True when the ACTIVE session already holds a resident edit mesh — the cart's
/// "was this document parked here before?" probe (req_3850 slice 2).
pub fn modelSessionResident() bool {
    return z3d.g_edit_count > 0;
}

pub fn findModelSession(token: u32) ?*z3d.ModelSession {
    for (z3d.g_model_sessions.items) |session| {
        if (session.token == token) return session;
    }
    return null;
}

pub fn modelSessionRecord(token: u32) ?*z3d.ModelSession {
    if (z3d.findModelSession(token)) |session| return session;
    const session = z3d.jalloc.create(z3d.ModelSession) catch return null;
    session.* = .{ .token = token };
    z3d.g_model_sessions.append(z3d.jalloc, session) catch {
        z3d.jalloc.destroy(session);
        return null;
    };
    return session;
}

/// Park the active document's native session and restore (or freshly create)
/// the session keyed by `token`. Pointer-copy swaps — no deep copies, no frees.
/// A token seen before restores its parked mesh, journal, selection, paint and
/// semantics exactly as parked (reopening a closed document reclaims its
/// session). An unseen token starts from the modules' boot state; the caller
/// then loads the document into it through the normal load path.
pub fn modelSessionSelect(token: u32) bool {
    if (token == z3d.g_model_session_token) return true;
    if (z3d.g_historical_preview.blocksResidentMutation()) return false;
    // A retained restore/field transaction owns this exact resident session.
    // Parking it would turn that receipt into authority over another document.
    if (z3d.g_model_write_leases.owner() != null) return false;
    z3d.g_face_table_worker.invalidateIdentity();
    const current = z3d.modelSessionRecord(z3d.g_model_session_token) orelse return false;
    mesh_edit.sessionSave(&current.edit);
    model_source.sessionSave(&current.source);
    model_paint.sessionSave(&current.paint);
    z3d.docStateSave(&current.local);
    if (z3d.findModelSession(token)) |target| {
        mesh_edit.sessionLoad(&target.edit);
        model_source.sessionLoad(&target.source);
        model_paint.sessionLoad(&target.paint);
        z3d.docStateLoad(&target.local);
    } else {
        if (z3d.modelSessionRecord(token) == null) return false; // allocation failed
        mesh_edit.sessionReset();
        model_source.sessionReset();
        model_paint.sessionReset();
        z3d.docStateReset();
    }
    z3d.g_model_session_token = token;
    z3d.publishUvZoneMask();
    return true;
}
