//! part_ops.zig — split verbatim from framework/gpu/3d.zig (req_4375).
//! Generated by _tool/split3d.zig — edit 3d.zig's successor here, regenerate only from the manifest.
//! Cross-file references are qualified through the orchestrator (`z3d`).

const std = @import("std");
const builtin = @import("builtin");
const log = @import("../../diag/log.zig");
const wgpu = @import("wgpu");
const bu = @import("../buffer_upload.zig");
const shaders = @import("../shaders.zig");
const terrain_grid = @import("../terrain_grid.zig");
const core = @import("../../dev_modules/gpu_api.zig");
const capture = @import("../capture.zig");
const build_options = @import("build_options");
const math = @import("../../math/root.zig");
const layout = @import("../../layout.zig");
const effect_assemble = @import("../effect_assemble.zig");
const compile_progress = @import("../compile_progress.zig");
const static_instance_policy = @import("../static_instance_policy.zig");
const model_paint = @import("../model_paint.zig");
const gizmo_axis_map = @import("../gizmo_axis_map.zig");
const effects_ctx = @import("../effects_ctx.zig");
const paint_islands_mod = @import("../paint_islands.zig");
const paint_program = @import("../paint_program.zig");
const model_source = @import("../model_source.zig");
const meshdoc_format = @import("../meshdoc_format.zig");
const mesh_audit = @import("../mesh_audit.zig");
const mesh_face_table = @import("../mesh_face_table.zig");
const mesh_face_diff = @import("../mesh_face_diff.zig");
const mesh_face_field_candidate = @import("../mesh_face_field_candidate.zig");
const mesh_face_table_package = @import("../mesh_face_table_package.zig");
const mesh_face_table_worker = @import("../mesh_face_table_worker.zig");
const historical_preview = @import("../historical_preview.zig");
const mesh_edit = @import("../mesh_edit.zig");
const mesh_semantics = @import("../mesh_semantics.zig");
const mesh_semantic_restore = @import("../mesh_semantic_restore.zig");
const mesh_edge_semantics = @import("../mesh_edge_semantics.zig");
const indexed_edit_mesh = @import("../indexed_edit_mesh.zig");
const character_topology_promotion = @import("../character_topology_promotion.zig");
const mesh_journal_log = @import("../mesh_journal_log.zig");
const model_write_lease = @import("../model_write_lease.zig");
const model_adoption_receipt = @import("../model_adoption_receipt.zig");
const model_adoption_finalize = @import("../model_adoption_finalize.zig");
const path_array = @import("../path_array.zig");
const path_plane = @import("../path_plane.zig");
const stage_scale = @import("../stage_scale.zig");
const pack = @import("../pack.zig");
const stable_geometry_slot = @import("../stable_geometry_slot.zig");
const character_rig_session = @import("../../skeleton/character_rig_session.zig");
const character_skin_binding = @import("../../skeleton/skin_binding.zig");
const character_specimen = @import("../character_specimen.zig");
const mouse_state = @import("../../state/mouse_state.zig");
const Node = layout.Node;

const z3d = @import("3d.zig");

// ── Part-level ops: duplicate / mirror / detach / merge / glass / solidify ────────

/// Duplicate the part occupying authored-group range [lo, hi) — optionally REFLECTED
/// across the origin plane of `mirror_axis` (0=X 1=Y 2=Z; -1 = plain copy). The copy
/// appends as a fresh part (new group range) carrying the source's per-face paint;
/// mirrored copies reverse their winding so normals stay outward. The mirror workflow
/// matches the old studio: center the source, mirror across the plane, get the twin.
pub fn meshDuplicateGroupRange(lo: u32, hi: u32, mirror_axis: i32) z3d.AppendResult {
    const fail = z3d.AppendResult{ .ok = false, .lo = 0, .hi = 0, .count = 0 };
    if (!model_paint.hasTarget() or hi <= lo) return fail;
    const cur_verts = z3d.g_edit_verts orelse return fail;
    if (model_source.faceGroupOf(0) == model_source.NO_FACE_GROUP) return fail;
    const live_ranges = model_source.partRanges() orelse return fail;
    // Deep boundary: duplicate means one COMPLETE live outliner part. Topology
    // edits can renumber a part from e.g. [0,6) to [0,16); accepting the stale
    // subrange copied a plausible-looking 9/24-face fragment and only failed
    // after the user moved it. The viewer resolves same-rank renumber aliases;
    // anything still stale or malformed is rejected here without mutation.
    if (!mesh_journal_log.hasExactPartRange(live_ranges, lo, hi)) return fail;
    const cur_faces = z3d.g_edit_count / 3;

    var out: std.ArrayListUnmanaged(f32) = .empty;
    defer out.deinit(z3d.jalloc);
    var groups: std.ArrayListUnmanaged(u32) = .empty;
    defer groups.deinit(z3d.jalloc);
    var colors: std.ArrayListUnmanaged(u8) = .empty;
    defer colors.deinit(z3d.jalloc);
    var copied_materials: std.ArrayListUnmanaged(u32) = .empty;
    defer copied_materials.deinit(z3d.jalloc);
    var copied_semantic_regions: std.ArrayListUnmanaged(u32) = .empty;
    defer copied_semantic_regions.deinit(z3d.jalloc);
    var copied_semantic_instances: std.ArrayListUnmanaged(u32) = .empty;
    defer copied_semantic_instances.deinit(z3d.jalloc);
    var remap = std.AutoHashMapUnmanaged(u32, u32){};
    defer remap.deinit(z3d.jalloc);
    var next_local: u32 = 0;

    var f: u32 = 0;
    while (f < cur_faces) : (f += 1) {
        const g = model_source.faceGroupOf(f);
        if (g == model_source.NO_FACE_GROUP or g < lo or g >= hi) continue;
        const base = @as(usize, f) * 24;
        if (base + 24 > cur_verts.len) break;
        if (mirror_axis >= 0 and mirror_axis <= 2) {
            const ax: usize = @intCast(mirror_axis);
            var p: [3][3]f32 = undefined;
            var k: usize = 0;
            while (k < 3) : (k += 1) {
                p[k] = .{ cur_verts[base + k * 8], cur_verts[base + k * 8 + 1], cur_verts[base + k * 8 + 2] };
                p[k][ax] = -p[k][ax];
            }
            // A reflection flips handedness — swap two corners so winding stays outward.
            if (!z3d.appendTri(&out, p[0], p[2], p[1])) return fail;
        } else {
            if (!z3d.appendFloats(&out, cur_verts[base .. base + 24])) return fail;
        }
        const gop = remap.getOrPut(z3d.jalloc, g) catch return fail;
        if (!gop.found_existing) {
            gop.value_ptr.* = next_local;
            next_local += 1;
        }
        groups.append(z3d.jalloc, gop.value_ptr.*) catch return fail;
        const c = z3d.trueFaceColor(f);
        colors.appendSlice(z3d.jalloc, c[0..]) catch return fail;
        copied_materials.append(z3d.jalloc, model_source.faceMaterialOf(f)) catch return fail;
        const semantic = model_source.faceSemanticOf(f);
        copied_semantic_regions.append(z3d.jalloc, semantic.region) catch return fail;
        copied_semantic_instances.append(z3d.jalloc, semantic.instance) catch return fail;
    }
    if (groups.items.len == 0) return fail;

    var snap = z3d.journalSnapshotCurrent(if (mirror_axis >= 0) "mirror part" else "duplicate part");
    const first_new_face = model_paint.faceCount();
    const installed_materials = z3d.captureFaceMaterials(first_new_face + @as(u32, @intCast(copied_materials.items.len))) orelse {
        z3d.journalDiscard(&snap);
        return fail;
    };
    defer z3d.jalloc.free(installed_materials);
    @memcpy(installed_materials[first_new_face..], copied_materials.items);
    var installed_semantics = z3d.captureFaceSemantics(first_new_face + @as(u32, @intCast(copied_semantic_regions.items.len))) orelse {
        z3d.journalDiscard(&snap);
        return fail;
    };
    defer installed_semantics.deinit();
    @memcpy(installed_semantics.regions[first_new_face..], copied_semantic_regions.items);
    @memcpy(installed_semantics.instances[first_new_face..], copied_semantic_instances.items);
    mesh_semantics.reinstanceCopy(
        z3d.jalloc,
        installed_semantics.instances[0..first_new_face],
        installed_semantics.regions[first_new_face..],
        installed_semantics.instances[first_new_face..],
    ) catch {
        z3d.journalDiscard(&snap);
        return fail;
    };
    const r = z3d.appendGroupInner(out.items, @intCast(out.items.len / 8), groups.items);
    if (!r.ok) {
        z3d.journalDiscard(&snap);
        return r;
    }
    model_source.setFaceMaterials(installed_materials);
    if (!model_source.setFaceSemantics(installed_semantics.regions, installed_semantics.instances)) {
        if (snap) |*before| _ = z3d.journalInstall(before);
        z3d.journalDiscard(&snap);
        return fail;
    }
    // The copy keeps the source's per-face paint — a duplicate reads as a twin.
    var i: u32 = 0;
    while (i < groups.items.len) : (i += 1) {
        const c: [4]u8 = .{ colors.items[i * 4], colors.items[i * 4 + 1], colors.items[i * 4 + 2], colors.items[i * 4 + 3] };
        model_paint.paintFace(first_new_face + i, c);
        model_source.writeColor(@intCast(first_new_face + i), c[0], c[1], c[2]);
    }
    z3d.journalCommit(&snap);
    z3d.ensureGlassTrailing();
    return r;
}

pub const PathArrayAxis = path_array.Axis;
pub const PathArrayProfile = path_array.Profile;
pub const PathArrayParams = path_array.Params;
pub const PathArrayResult = struct {
    ok: bool,
    count: u32,
    /// Fresh [lo,hi) pairs in generated-bay-major, source-part-minor order.
    /// Owned by the allocator passed to meshPathArray when ok=true.
    ranges: ?[]u32,
};

pub fn pathArrayFail() z3d.PathArrayResult {
    return .{ .ok = false, .count = 0, .ranges = null };
}

pub fn knownPartRange(part_ranges: []const u32, lo: u32, hi: u32) bool {
    return mesh_journal_log.hasExactPartRange(part_ranges, lo, hi);
}

pub fn sourceRangeIndex(source_ranges: []const u32, group: u32) ?usize {
    var i: usize = 0;
    while (i + 1 < source_ranges.len) : (i += 2) {
        if (group >= source_ranges[i] and group < source_ranges[i + 1]) return i / 2;
    }
    return null;
}

pub fn pathDot(a: [3]f32, b: [3]f32) f32 {
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
}

/// Read-only source-bay spans for the cart's 3D-coordinate editor. Returns X/Z
/// model-space lengths; the cart expresses them in its ruled 16-u-per-tile scale.
pub fn meshPathArrayHorizontalSpans(source_ranges: []const u32) ?[2]f32 {
    if (source_ranges.len == 0 or source_ranges.len % 2 != 0) return null;
    const verts = z3d.g_edit_verts orelse return null;
    const groups = z3d.captureFaceGroups() orelse return null;
    defer z3d.jalloc.free(groups);
    var min_x = std.math.inf(f32);
    var max_x = -std.math.inf(f32);
    var min_z = std.math.inf(f32);
    var max_z = -std.math.inf(f32);
    var found = false;
    var f: u32 = 0;
    while (f < z3d.g_edit_count / 3) : (f += 1) {
        if (z3d.sourceRangeIndex(source_ranges, groups[f]) == null) continue;
        const base = @as(usize, f) * 24;
        if (base + 24 > verts.len) return null;
        var corner: usize = 0;
        while (corner < 3) : (corner += 1) {
            const x = verts[base + corner * 8];
            const z = verts[base + corner * 8 + 2];
            min_x = @min(min_x, x);
            max_x = @max(max_x, x);
            min_z = @min(min_z, z);
            max_z = @max(max_z, z);
            found = true;
        }
    }
    return if (found) .{ max_x - min_x, max_z - min_z } else null;
}

/// Grow one selected source bay into a curved/rising run without touching that source.
/// Every selected range remains an independent part in every generated bay. The whole
/// append is built before installation and journals as ONE "path array" undo unit.
/// Geometry comes from the resident edited mesh, never the cart's stale primitive seed.
pub fn meshPathArray(alloc: std.mem.Allocator, source_ranges: []const u32, params: z3d.PathArrayParams) z3d.PathArrayResult {
    return z3d.meshPathArrayInner(alloc, source_ranges, params, null);
}

pub fn meshPathArrayPoints(alloc: std.mem.Allocator, source_ranges: []const u32, axis: z3d.PathArrayAxis, points: []const path_array.Vec3) z3d.PathArrayResult {
    const bays: u32 = @intCast(points.len);
    return z3d.meshPathArrayInner(alloc, source_ranges, .{
        .axis = axis,
        .bays = bays,
        .turn_radians = 0,
        .rise = 0,
        .profile = .linear,
    }, points);
}

pub fn meshPathArrayInner(alloc: std.mem.Allocator, source_ranges: []const u32, params: z3d.PathArrayParams, point_path: ?[]const path_array.Vec3) z3d.PathArrayResult {
    const fail = z3d.pathArrayFail();
    if (!model_paint.hasTarget() or source_ranges.len == 0 or source_ranges.len % 2 != 0) return fail;
    const cur_verts = z3d.g_edit_verts orelse return fail;
    const part_ranges = model_source.partRanges() orelse return fail;
    const cur_groups = z3d.captureFaceGroups() orelse return fail;
    defer z3d.jalloc.free(cur_groups);
    const cur_colors = z3d.collectCurrentFaceColors() orelse return fail;
    defer z3d.jalloc.free(cur_colors);
    const cur_faces = z3d.g_edit_count / 3;
    if (cur_colors.len != @as(usize, cur_faces) * 4) return fail;

    // The bridge is strict: callers may only array complete, distinct live parts.
    var pair_i: usize = 0;
    while (pair_i + 1 < source_ranges.len) : (pair_i += 2) {
        const lo = source_ranges[pair_i];
        const hi = source_ranges[pair_i + 1];
        if (hi <= lo or !z3d.knownPartRange(part_ranges, lo, hi)) return fail;
        var earlier: usize = 0;
        while (earlier < pair_i) : (earlier += 2) {
            if (lo < source_ranges[earlier + 1] and hi > source_ranges[earlier]) return fail;
        }
    }

    const frame = path_array.basis(params.axis);
    var forward_min = std.math.inf(f32);
    var forward_max = -std.math.inf(f32);
    var lateral_min = std.math.inf(f32);
    var lateral_max = -std.math.inf(f32);
    var vertical_min = std.math.inf(f32);
    var vertical_max = -std.math.inf(f32);
    var source_faces: u32 = 0;
    var f: u32 = 0;
    while (f < cur_faces) : (f += 1) {
        if (z3d.sourceRangeIndex(source_ranges, cur_groups[f]) == null) continue;
        source_faces += 1;
        const base = @as(usize, f) * 24;
        if (base + 24 > cur_verts.len) return fail;
        var corner: usize = 0;
        while (corner < 3) : (corner += 1) {
            const p: [3]f32 = .{ cur_verts[base + corner * 8], cur_verts[base + corner * 8 + 1], cur_verts[base + corner * 8 + 2] };
            const forward = z3d.pathDot(p, frame.forward);
            const lateral = z3d.pathDot(p, frame.right);
            forward_min = @min(forward_min, forward);
            forward_max = @max(forward_max, forward);
            lateral_min = @min(lateral_min, lateral);
            lateral_max = @max(lateral_max, lateral);
            vertical_min = @min(vertical_min, p[1]);
            vertical_max = @max(vertical_max, p[1]);
        }
    }
    if (source_faces == 0) return fail;
    const template = path_array.Template{
        .forward_min = forward_min,
        .forward_max = forward_max,
        .lateral_center = (lateral_min + lateral_max) * 0.5,
        .vertical_origin = (vertical_min + vertical_max) * 0.5,
    };
    if (point_path) |points| {
        if (!path_array.validPointPath(template, points)) return fail;
    } else if (!path_array.valid(template, params)) return fail;

    var verts: std.ArrayListUnmanaged(f32) = .empty;
    defer verts.deinit(z3d.jalloc);
    var groups: std.ArrayListUnmanaged(u32) = .empty;
    defer groups.deinit(z3d.jalloc);
    var colors: std.ArrayListUnmanaged(u8) = .empty;
    defer colors.deinit(z3d.jalloc);
    var materials: std.ArrayListUnmanaged(u32) = .empty;
    defer materials.deinit(z3d.jalloc);
    var semantic_regions: std.ArrayListUnmanaged(u32) = .empty;
    defer semantic_regions.deinit(z3d.jalloc);
    var semantic_instances: std.ArrayListUnmanaged(u32) = .empty;
    defer semantic_instances.deinit(z3d.jalloc);
    var all_ranges: std.ArrayListUnmanaged(u32) = .empty;
    defer all_ranges.deinit(z3d.jalloc);
    var fresh_ranges: std.ArrayListUnmanaged(u32) = .empty;
    defer fresh_ranges.deinit(alloc);

    var logical = z3d.LogicalRowsBuilder.init() orelse return fail;
    defer logical.deinit();
    if (!logical.appendAllSource()) return fail;
    var cloned_logical = z3d.LogicalCloneMap{};
    defer cloned_logical.deinit();

    if (!z3d.appendFloats(&verts, cur_verts[0 .. @as(usize, z3d.g_edit_count) * 8])) return fail;
    groups.appendSlice(z3d.jalloc, cur_groups) catch return fail;
    colors.appendSlice(z3d.jalloc, cur_colors) catch return fail;
    var material_face: u32 = 0;
    while (material_face < cur_faces) : (material_face += 1) {
        materials.append(z3d.jalloc, model_source.faceMaterialOf(material_face)) catch return fail;
        const semantic = model_source.faceSemanticOf(material_face);
        semantic_regions.append(z3d.jalloc, semantic.region) catch return fail;
        semantic_instances.append(z3d.jalloc, semantic.instance) catch return fail;
    }
    all_ranges.appendSlice(z3d.jalloc, part_ranges) catch return fail;

    var next_group: u32 = z3d.nextFreeGroupId(cur_groups);
    const generated_bays: u32 = if (point_path) |points| @intCast(points.len - 1) else params.bays - 1;
    var bay: u32 = 0;
    while (bay < generated_bays) : (bay += 1) {
        var source_index: usize = 0;
        while (source_index * 2 + 1 < source_ranges.len) : (source_index += 1) {
            const lo = source_ranges[source_index * 2];
            const hi = source_ranges[source_index * 2 + 1];
            const range_start = next_group;
            var local_groups = std.AutoHashMapUnmanaged(u32, u32){};
            defer local_groups.deinit(z3d.jalloc);
            var next_local: u32 = 0;
            var copied_faces: u32 = 0;
            const semantic_copy_start = semantic_instances.items.len;

            f = 0;
            while (f < cur_faces) : (f += 1) {
                const source_group = cur_groups[f];
                if (source_group < lo or source_group >= hi) continue;
                const base = @as(usize, f) * 24;
                if (base + 24 > cur_verts.len) return fail;
                var mapped: [3][3]f32 = undefined;
                var corner: usize = 0;
                while (corner < 3) : (corner += 1) {
                    const p: [3]f32 = .{ cur_verts[base + corner * 8], cur_verts[base + corner * 8 + 1], cur_verts[base + corner * 8 + 2] };
                    mapped[corner] = if (point_path) |points|
                        path_array.mapPointPath(template, params.axis, points, bay, p)
                    else
                        path_array.mapPoint(template, params, bay, p);
                }
                const namespace = 1 + @as(u64, bay) * @as(u64, source_ranges.len / 2) + @as(u64, source_index);
                const source_ids = [3]u32{
                    logical.sourceCorner(f, 0) orelse return fail,
                    logical.sourceCorner(f, 1) orelse return fail,
                    logical.sourceCorner(f, 2) orelse return fail,
                };
                const mapped_ids = [3]u32{
                    cloned_logical.getOrMint(&logical, namespace, source_ids[0]) orelse return fail,
                    cloned_logical.getOrMint(&logical, namespace, source_ids[1]) orelse return fail,
                    cloned_logical.getOrMint(&logical, namespace, source_ids[2]) orelse return fail,
                };
                if (!z3d.appendTriLogical(&verts, &logical, mapped[0], mapped[1], mapped[2], mapped_ids)) return fail;
                const group_entry = local_groups.getOrPut(z3d.jalloc, source_group) catch return fail;
                if (!group_entry.found_existing) {
                    group_entry.value_ptr.* = next_local;
                    next_local += 1;
                }
                groups.append(z3d.jalloc, range_start + group_entry.value_ptr.*) catch return fail;
                colors.appendSlice(z3d.jalloc, cur_colors[@as(usize, f) * 4 .. @as(usize, f) * 4 + 4]) catch return fail;
                materials.append(z3d.jalloc, model_source.faceMaterialOf(f)) catch return fail;
                const semantic = model_source.faceSemanticOf(f);
                semantic_regions.append(z3d.jalloc, semantic.region) catch return fail;
                semantic_instances.append(z3d.jalloc, semantic.instance) catch return fail;
                copied_faces += 1;
            }
            if (copied_faces == 0 or next_local == 0) return fail;
            mesh_semantics.reinstanceCopy(
                z3d.jalloc,
                semantic_instances.items[0..semantic_copy_start],
                semantic_regions.items[semantic_copy_start..],
                semantic_instances.items[semantic_copy_start..],
            ) catch return fail;
            next_group += next_local;
            all_ranges.appendSlice(z3d.jalloc, &.{ range_start, next_group }) catch return fail;
            fresh_ranges.appendSlice(alloc, &.{ range_start, next_group }) catch return fail;
        }
    }

    const expected_fresh_pairs = @as(usize, generated_bays) * (source_ranges.len / 2) * 2;
    if (fresh_ranges.items.len != expected_fresh_pairs) return fail;
    const result_ranges = fresh_ranges.toOwnedSlice(alloc) catch return fail;
    const installed_count: u32 = @intCast(verts.items.len / 8);
    const logical_replacement = logical.replacement(installed_count) orelse {
        alloc.free(result_ranges);
        return fail;
    };
    var snap = z3d.journalSnapshotCurrent("path array");
    if (!z3d.replaceActiveEditMesh(verts.items, installed_count, logical_replacement)) {
        z3d.journalDiscard(&snap);
        alloc.free(result_ranges);
        return fail;
    }
    model_source.setFaceGroups(groups.items);
    model_source.setFaceMaterials(materials.items);
    if (!model_source.setFaceSemantics(semantic_regions.items, semantic_instances.items)) {
        if (snap) |*before| _ = z3d.journalInstall(before);
        z3d.journalDiscard(&snap);
        alloc.free(result_ranges);
        return fail;
    }
    model_source.setPartRanges(all_ranges.items);
    if (!z3d.applyExactFaceColors(colors.items, @intCast(groups.items.len))) {
        if (snap) |*before| _ = z3d.journalInstall(before);
        z3d.journalDiscard(&snap);
        alloc.free(result_ranges);
        return fail;
    }
    _ = z3d.ensureDisjointPartRanges("path array");
    _ = z3d.refreshPaintLayout();
    z3d.journalCommit(&snap);
    z3d.ensureGlassTrailing();
    return .{ .ok = true, .count = installed_count, .ranges = result_ranges };
}

/// Detach the selected faces (face mode) into a NEW part: their authored groups are
/// re-numbered into a fresh contiguous range past every existing group. Pure group
/// remap — no geometry moves, so paint and topology are untouched; the outliner gains
/// a part whose range is the returned [lo, hi). The old studio's "peel a panel off
/// the body" — here the panel keeps its exact triangles.
pub fn meshDetachSelection() z3d.AppendResult {
    const fail = z3d.AppendResult{ .ok = false, .lo = 0, .hi = 0, .count = 0 };
    if (!model_paint.hasTarget()) return fail;
    if (mesh_edit.mode() != .face) return fail;
    if (model_source.faceGroupOf(0) == model_source.NO_FACE_GROUP) return fail;
    // Group ids are per SOURCE face — require the displayed mesh to BE the source
    // (any edit at decimated quality already retains the displayed mesh as source).
    if (z3d.g_edit_count != model_source.count()) return fail;
    const tri_count = z3d.g_edit_count / 3;
    const mask = z3d.jalloc.alloc(bool, tri_count) catch return fail;
    defer z3d.jalloc.free(mask);
    var del = mesh_edit.buildDeleteMask(mask);
    if (del == 0) return fail;
    // Mirror (req_3797): the twin faces detach into the SAME new part — a symmetric
    // panel detaches as one piece.
    if (mesh_edit.mirrorMask() != 0) {
        if (z3d.g_edit_verts) |soup| {
            z3d.extendFaceMaskWithMirrorTwins(soup, tri_count, mask);
            del = 0;
            for (mask) |selected| {
                if (selected) del += 1;
            }
        }
    }
    if (del >= tri_count) return fail;

    const groups = z3d.captureFaceGroups() orelse return fail;
    defer z3d.jalloc.free(groups);
    var snap = z3d.journalSnapshotCurrent("detach faces");
    // Drop the selection FIRST — its saved-patch tint must restore before the
    // paint layout re-islands under the new grouping.
    mesh_edit.clearSelection();

    const offset: u32 = z3d.nextFreeGroupId(groups);
    var remap = std.AutoHashMapUnmanaged(u32, u32){};
    defer remap.deinit(z3d.jalloc);
    var next: u32 = offset;
    var f: u32 = 0;
    while (f < tri_count) : (f += 1) {
        if (!mask[f]) continue;
        const gop = remap.getOrPut(z3d.jalloc, groups[f]) catch {
            z3d.journalDiscard(&snap);
            return fail;
        };
        if (!gop.found_existing) {
            gop.value_ptr.* = next;
            next += 1;
        }
        groups[f] = gop.value_ptr.*;
    }
    model_source.setFaceGroups(groups);
    // The detached panel becomes a part in the host's range truth too (req_2644), and
    // the weld must re-key: its faces changed part, so coincident verts along the seam
    // now belong to two parts and may no longer merge.
    if (model_source.partRanges()) |pr| {
        var ranges: std.ArrayListUnmanaged(u32) = .empty;
        defer ranges.deinit(z3d.jalloc);
        if (ranges.appendSlice(z3d.jalloc, pr)) |_| {
            ranges.append(z3d.jalloc, offset) catch {};
            ranges.append(z3d.jalloc, next) catch {};
            if (ranges.items.len == pr.len + 2) model_source.setPartRanges(ranges.items);
        } else |_| {}
    }
    _ = z3d.ensureDisjointPartRanges("detach faces");
    if (!z3d.repartitionLogicalTopologyByCurrentParts()) {
        // Detach is one atomic ownership transaction. If its durable address
        // table cannot be re-keyed, put the exact pre-detach snapshot back rather
        // than leaving a live mesh whose guard and gizmo disagree about the seam.
        if (snap) |*entry| _ = z3d.journalInstall(entry);
        z3d.journalDiscard(&snap);
        return fail;
    }
    z3d.clearIndexedEditMesh();
    mesh_edit.reset();
    _ = z3d.refreshPaintLayout();
    z3d.journalCommit(&snap);
    return .{ .ok = true, .lo = offset, .hi = next, .count = z3d.g_edit_count };
}

/// Merge two parts into ONE: every face in either range gets re-numbered into a fresh
/// contiguous group range (n-gon grouping preserved across both). Pure group remap.
/// The outliner replaces both parts with one over the returned range — the old
/// studio's "merge down" (the durable re-attach path after a detach).
pub fn meshMergeGroupRanges(a_lo: u32, a_hi: u32, b_lo: u32, b_hi: u32) z3d.AppendResult {
    const fail = z3d.AppendResult{ .ok = false, .lo = 0, .hi = 0, .count = 0 };
    if (!model_paint.hasTarget()) return fail;
    if (model_source.faceGroupOf(0) == model_source.NO_FACE_GROUP) return fail;
    if (z3d.g_edit_count != model_source.count()) return fail;
    const tri_count = z3d.g_edit_count / 3;
    const groups = z3d.captureFaceGroups() orelse return fail;
    defer z3d.jalloc.free(groups);

    var snap = z3d.journalSnapshotCurrent("merge parts");
    mesh_edit.clearSelection();
    const offset: u32 = z3d.nextFreeGroupId(groups);
    var remap = std.AutoHashMapUnmanaged(u32, u32){};
    defer remap.deinit(z3d.jalloc);
    var next: u32 = offset;
    var touched = false;
    var f: u32 = 0;
    while (f < tri_count) : (f += 1) {
        const g = groups[f];
        if (g == model_source.NO_FACE_GROUP) continue;
        const in_a = g >= a_lo and g < a_hi;
        const in_b = g >= b_lo and g < b_hi;
        if (!in_a and !in_b) continue;
        const gop = remap.getOrPut(z3d.jalloc, g) catch {
            z3d.journalDiscard(&snap);
            return fail;
        };
        if (!gop.found_existing) {
            gop.value_ptr.* = next;
            next += 1;
        }
        groups[f] = gop.value_ptr.*;
        touched = true;
    }
    if (!touched) {
        z3d.journalDiscard(&snap);
        return fail;
    }
    model_source.setFaceGroups(groups);
    // Host range truth (req_2644): the two source ranges collapse into the fused pair.
    if (model_source.partRanges()) |pr| {
        var ranges: std.ArrayListUnmanaged(u32) = .empty;
        defer ranges.deinit(z3d.jalloc);
        var i: usize = 0;
        var copied = true;
        while (i + 1 < pr.len) : (i += 2) {
            const keep = !((pr[i] == a_lo and pr[i + 1] == a_hi) or (pr[i] == b_lo and pr[i + 1] == b_hi));
            if (!keep) continue;
            ranges.append(z3d.jalloc, pr[i]) catch {
                copied = false;
            };
            ranges.append(z3d.jalloc, pr[i + 1]) catch {
                copied = false;
            };
        }
        if (copied) {
            ranges.append(z3d.jalloc, offset) catch {};
            ranges.append(z3d.jalloc, next) catch {};
            model_source.setPartRanges(ranges.items);
        }
    }
    _ = z3d.ensureDisjointPartRanges("merge parts");
    z3d.clearIndexedEditMesh();
    mesh_edit.reset(); // part membership moved → weld re-keys
    _ = z3d.refreshPaintLayout();
    z3d.journalCommit(&snap);
    return .{ .ok = true, .lo = offset, .hi = next, .count = z3d.g_edit_count };
}

/// Winding repair at the import boundary (req_3450): flip every triangle wound
/// against its neighbors (and every wholly inside-out closed shell) so a
/// mixed-winding GLB/OBJ enters the editor coherent under back-face culling.
/// Pure data repair on a parsed soup BEFORE adoption — no journal, no resident
/// state. Returns the number of triangles flipped (0 = the mesh was clean).
pub fn normalizeSoupWinding(verts: []f32, vert_count: u32) u32 {
    return mesh_edit.normalizeTriangleWinding(verts, vert_count / 3);
}

/// Reverse the selected authored face(s) so their normals point to the opposite side.
/// This is the host-native port of Studio's `flipFace` (req_1182 / req_2883): every
/// member triangle reverses winding with its interleaved UV row, while face groups,
/// part ownership, paint, and triangle order remain unchanged. The selection is restored
/// after the resident mesh rekeys, so X can be tapped again to flip back immediately.
pub fn meshFlipSelectionWinding() bool {
    if (!model_paint.hasTarget()) return false;
    if (mesh_edit.mode() != .face) return false;
    const cur_verts = z3d.g_edit_verts orelse return false;
    const tri_count = z3d.g_edit_count / 3;
    if (tri_count == 0) return false;

    const mask = z3d.jalloc.alloc(bool, tri_count) catch return false;
    defer z3d.jalloc.free(mask);
    if (mesh_edit.buildDeleteMask(mask) == 0) return false;
    // Mirror (req_3797): flipping a face flips its twin — symmetry survives the wind.
    if (mesh_edit.mirrorMask() != 0) z3d.extendFaceMaskWithMirrorTwins(cur_verts, tri_count, mask);

    const needed = @as(usize, z3d.g_edit_count) * 8;
    if (cur_verts.len < needed) return false;
    const flipped_verts = z3d.jalloc.dupe(f32, cur_verts[0..needed]) catch return false;
    defer z3d.jalloc.free(flipped_verts);
    if (mesh_edit.flipSelectedTriangleWinding(flipped_verts, tri_count, mask) == 0) return false;
    const logical_vertex_count = model_source.logicalVertexCount();
    const flipped_logical_ids: ?[]u32 = if (model_source.renderCornerLogicalIds()) |rows| blk: {
        if (rows.len != z3d.g_edit_count) return false;
        const copy = z3d.jalloc.dupe(u32, rows) catch return false;
        var face: u32 = 0;
        while (face < tri_count) : (face += 1) {
            if (!mask[face]) continue;
            const base = @as(usize, face) * 3;
            std.mem.swap(u32, &copy[base + 1], &copy[base + 2]);
        }
        break :blk copy;
    } else null;
    defer if (flipped_logical_ids) |rows| z3d.jalloc.free(rows);

    // retain() inside replaceActiveEditMesh deliberately clears authored groups. Capture
    // and restore them around the replace; unchanged group ids also let the atlas carry
    // put every painted island back exactly where it was.
    const grouped = model_source.faceGroupOf(0) != model_source.NO_FACE_GROUP;
    const groups: ?[]u32 = if (grouped) (z3d.captureFaceGroups() orelse return false) else null;
    defer if (groups) |g| z3d.jalloc.free(g);

    var snap = z3d.journalSnapshotCurrent("flip faces");
    mesh_edit.suspendFaceTint();
    model_paint.snapshotAtlasForCarry();
    mesh_edit.clearSelection();
    mesh_edit.resumeFaceTint();

    if (!z3d.replaceActiveEditMesh(
        flipped_verts,
        z3d.g_edit_count,
        z3d.logicalReplacementExactOrAbsent(flipped_logical_ids, z3d.g_edit_count, logical_vertex_count),
    )) {
        model_paint.dropAtlasCarry();
        _ = mesh_edit.selectFacesByTriangleMask(mask);
        z3d.journalDiscard(&snap);
        return false;
    }
    if (groups) |g| model_source.setFaceGroups(g);
    _ = z3d.refreshPaintLayout();
    model_paint.dropAtlasCarry(); // refresh consumes it; this also clears a failed rebuild's stash
    _ = mesh_edit.selectFacesByTriangleMask(mask);
    z3d.journalCommit(&snap);
    return true;
}

/// Commit a group-only indexed topology change against the resident triangle rows.
/// This is the single strict boundary used by Merge Faces and Tris to Quads: geometry,
/// UVs, material identity, paint, and part ownership must all remain byte-stable.
pub fn commitIndexedFaceGrouping(
    indexed: *indexed_edit_mesh.Mesh,
    verts: []const f32,
    tri_count: u32,
    parts: ?[]const u32,
    materials: []const u32,
    label: []const u8,
) bool {
    const merged_groups = std.heap.c_allocator.alloc(u32, tri_count) catch return false;
    defer std.heap.c_allocator.free(merged_groups);
    const merged_parts = std.heap.c_allocator.alloc(u32, tri_count) catch return false;
    defer std.heap.c_allocator.free(merged_parts);
    const merged_materials = std.heap.c_allocator.alloc(u32, tri_count) catch return false;
    defer std.heap.c_allocator.free(merged_materials);
    if (!indexed.writeResidentMetadata(merged_groups, merged_parts, merged_materials)) return false;

    // Group-only operations are not allowed to re-parent or re-material a resident
    // triangle; that would turn a seam dissolve into a structural Outliner mutation.
    if (parts) |base_parts| {
        if (!std.mem.eql(u32, base_parts, merged_parts)) return false;
    } else {
        for (merged_parts) |part| if (part != indexed_edit_mesh.NO_PART) return false;
    }
    if (!std.mem.eql(u32, materials, merged_materials)) return false;

    // Selection tint is presentation state. Restore the true atlas first, then guard
    // the complete durable model state and commit only the requested group delta.
    mesh_edit.clearSelection();
    var guard = z3d.ResidentMetadataGuard.capture() orelse return false;
    defer guard.deinit();
    var snap: ?z3d.JournalEntry = z3d.journalSnapshotCurrent(label) orelse return false;

    model_source.setFaceGroups(merged_groups);
    mesh_edit.faceGroupsChanged();
    const live_parts: ?[]const u32 = if (parts) |rows| rows else null;
    const committed = guard.matchesGroupOnly(merged_groups) and
        indexed.residentMetadataMatches(tri_count, merged_groups, live_parts, model_source.faceMaterials()) and
        indexed.residentRenderChannelsMatch(verts, tri_count);
    if (!committed) {
        const old_groups = guard.groups orelse {
            z3d.journalDiscard(&snap);
            return false;
        };
        model_source.setFaceGroups(old_groups);
        mesh_edit.faceGroupsChanged();
        z3d.journalDiscard(&snap);
        log.print("[mesh] {s} rolled back: resident model-state invariant rejected the group commit\n", .{label});
        return false;
    }

    indexed.clearCutOrigins();
    z3d.clearIndexedEditMesh();
    z3d.g_indexed_edit_mesh = indexed.*;
    indexed.* = .{ .allocator = std.heap.c_allocator };
    z3d.journalCommit(&snap);
    return true;
}

/// Fuse selected faces into one authored face. When the fused boundary keeps every
/// source corner, the resident render mesh is untouched: shared seams disappear from
/// edit topology purely because the selected triangles now share one group, and their
/// exact winding, UVs, atlas pixels, materials, colours, part ownership, and Outliner
/// ranges stay byte-stable. When the clean boundary DROPS corners — the inverse of a
/// loop cut, where seam verts turn collinear or interior (req_3771) — and the loop is
/// convex, the face is re-tessellated from its clean loop through the same
/// lower()+install path Loop Cut uses, so those dead verts actually leave the mesh
/// instead of lingering as cornerless dots. (Concave fusions always stay byte-stable:
/// a re-fan would flip their render triangles.) The loop keeps its original
/// per-corner UVs, so paint that lived in one contiguous atlas region (the
/// cut-then-merge case) stays where it was.
pub fn meshMergeSelectedFaces() bool {
    if (!model_paint.hasTarget() or mesh_edit.mode() != .face) return false;
    const verts = z3d.g_edit_verts orelse return false;
    const tri_count = z3d.g_edit_count / 3;
    if (tri_count == 0 or model_source.faceGroups() == null) return false;
    const mask = z3d.jalloc.alloc(bool, tri_count) catch return false;
    defer z3d.jalloc.free(mask);
    if (mesh_edit.buildDeleteMask(mask) == 0) return false;
    // Mirror (req_3797): merge fuses ONE connected cluster, so the twin cluster gets
    // its own second fusion in the same commit rather than a mask extension.
    var twin_mask: ?[]bool = null;
    defer if (twin_mask) |rows| z3d.jalloc.free(rows);
    if (mesh_edit.mirrorMask() != 0) build_twin: {
        const extended = z3d.jalloc.dupe(bool, mask) catch break :build_twin;
        z3d.extendFaceMaskWithMirrorTwins(verts, tri_count, extended);
        var twin_any = false;
        for (extended, mask) |*slot, source| {
            slot.* = slot.* and !source;
            if (slot.*) twin_any = true;
        }
        if (twin_any) twin_mask = extended else z3d.jalloc.free(extended);
    }
    const groups = z3d.captureFaceGroups() orelse return false;
    defer std.heap.c_allocator.free(groups);
    const parts = z3d.capturePartOfFaces();
    defer if (parts) |rows| std.heap.c_allocator.free(rows);
    const materials = z3d.captureFaceMaterials(tri_count) orelse return false;
    defer std.heap.c_allocator.free(materials);
    const base_colors = z3d.collectCurrentFaceColors() orelse return false;
    defer std.heap.c_allocator.free(base_colors);
    if (base_colors.len != @as(usize, tri_count) * 4) return false;

    // A single authored face cannot straddle opaque and glass draw passes. RGB may
    // vary per source triangle (painted detail is retained), but alpha class may not.
    // Each cluster (source, twin) is checked on its own — they merge separately.
    for ([2]?[]const bool{ mask, twin_mask }) |cluster_opt| {
        const cluster = cluster_opt orelse continue;
        var selected_glass: ?bool = null;
        var triangle: usize = 0;
        while (triangle < tri_count) : (triangle += 1) {
            if (!cluster[triangle]) continue;
            const is_glass = model_paint.isGlassAlpha(base_colors[triangle * 4 + 3]);
            if (selected_glass) |expected| {
                if (expected != is_glass) return false;
            } else selected_glass = is_glass;
        }
    }

    var indexed = z3d.cloneIndexedEditMeshOrImport(verts, tri_count, groups, parts, model_source.faceMaterials()) orelse return false;
    defer indexed.deinit();
    const merged = (indexed.mergeSelected(mask) catch return false) orelse return false;
    const twin_merged: ?indexed_edit_mesh.MergedFace = if (twin_mask) |rows|
        (indexed.mergeSelected(rows) catch null)
    else
        null;
    var selected_count: usize = 0;
    for (mask) |selected| if (selected) {
        selected_count += 1;
    };
    const selected_faces = std.heap.c_allocator.alloc(u32, selected_count) catch return false;
    defer std.heap.c_allocator.free(selected_faces);
    var selected_at: usize = 0;
    for (mask, 0..) |selected, face| {
        if (!selected) continue;
        selected_faces[selected_at] = @intCast(face);
        selected_at += 1;
    }
    const before = mesh_edit.followPatchJson(std.heap.c_allocator, selected_faces, 2) orelse return false;
    defer std.heap.c_allocator.free(before);

    // With mirror on, either BOTH clusters merge or the op refuses — committing only
    // the source half would mint the exact silent asymmetry this mode exists to kill.
    if (twin_mask != null and twin_merged == null) return false;
    const any_retessellated = merged.retessellated or (twin_merged != null and twin_merged.?.retessellated);
    if (!any_retessellated) {
        // Every source corner survives on the fused boundary (or the loop is
        // concave, where a re-fan would flip triangles) — the byte-stable
        // group-only commit keeps geometry, UVs, and atlas pixels untouched.
        if (!z3d.commitIndexedFaceGrouping(&indexed, verts, tri_count, parts, materials, "merge faces")) return false;
        const after = mesh_edit.followPatchJson(std.heap.c_allocator, selected_faces, 2) orelse return true;
        defer std.heap.c_allocator.free(after);
        z3d.g_follow_action_queue.append(
            std.heap.c_allocator,
            @intFromEnum(mesh_journal_log.ActionKind.merge_faces),
            @intFromEnum(z3d.g_mesh_action_source),
            before,
            after,
        ) catch {};
        return true;
    }

    // Dissolve commit (req_3771): the fused boundary dropped seam corners, so the
    // resident rows must be rebuilt from the clean loop — the Loop Cut / Connect
    // Vertices install path. A group-only commit here would leave the dropped verts
    // alive in the soup as dots no authored edge runs through.
    var lowered = indexed.lower() catch return false;
    defer lowered.deinit();
    if (lowered.tri_count == 0) return false;
    const dissolve_colors = std.heap.c_allocator.alloc(u8, @as(usize, lowered.tri_count) * 4) catch return false;
    defer std.heap.c_allocator.free(dissolve_colors);
    if (!mesh_edit.inheritFaceRgba(base_colors, lowered.source_triangles, dissolve_colors)) return false;
    const part_count = z3d.hostPartCount();
    var snap = z3d.journalSnapshotCurrent("merge faces");
    const installed = z3d.lcInstallLowered(
        lowered.positions,
        lowered.uvs,
        lowered.tri_count,
        lowered.groups,
        lowered.materials,
        lowered.semantic_regions,
        lowered.semantic_instances,
        dissolve_colors,
        z3d.flattenedLogicalRows(lowered.triangle_vertices),
        @intCast(indexed.vertices.items.len),
    );
    if (!installed) {
        z3d.journalDiscard(&snap);
        return false;
    }
    if (parts != null) z3d.renormalizePartRanges(lowered.parts, part_count);
    z3d.adoptIndexedEditMesh(&indexed, &lowered);
    z3d.journalCommit(&snap);

    // Follow rows for the agent journal: the merged face's NEW resident triangles
    // (the pre-merge ids no longer exist after the re-tessellation).
    var after_faces = std.ArrayListUnmanaged(u32).empty;
    defer after_faces.deinit(std.heap.c_allocator);
    for (lowered.face_ids, 0..) |face_id, row| {
        const is_twin_face = twin_merged != null and face_id == twin_merged.?.face_id;
        if (face_id == merged.face_id or is_twin_face) after_faces.append(std.heap.c_allocator, @intCast(row)) catch break;
    }
    const after = mesh_edit.followPatchJson(std.heap.c_allocator, after_faces.items, 2) orelse return true;
    defer std.heap.c_allocator.free(after);
    z3d.g_follow_action_queue.append(
        std.heap.c_allocator,
        @intFromEnum(mesh_journal_log.ActionKind.merge_faces),
        @intFromEnum(z3d.g_mesh_action_source),
        before,
        after,
    ) catch {};
    return true;
}

/// Mirror quad symmetrize (req_3855): the retroactive half of live-mirror Merge Faces.
/// For every authored QUAD (two triangles, four distinct corners) in the active scope
/// whose reflection across the `axis_mask` plane subset is covered by two SEPARATE
/// single-triangle authored faces, fuse that twin pair into the matching quad. Pairing
/// is positional and quantized (mirror_corners) — a twin split on the opposite diagonal
/// still matches and keeps its own resident diagonal — so the common case commits as a
/// byte-stable group-only change: no vertex moves, UVs, paint, and part ownership all
/// untouched. One journal entry for the whole sweep. Returns the fused pair count.
/// The receipt half of meshMirrorMatchQuads: every counter a zero needs to explain
/// itself. `refused` counts discovered twin pairs the indexed merge still rejected
/// (cross-meaning, unwelded) — with the trusted merge the coplanarity gate is not
/// among the reasons.
pub const MirrorQuadStats = struct {
    fused: u32 = 0, // twin pairs actually fused into quads (0 ⇒ mesh unchanged)
    quads: u32 = 0, // source quads scanned (two tris, four corners, in scope)
    symmetric: u32 = 0, // quads whose reflection is already one authored face
    pairs: u32 = 0, // twin lone-triangle pairs discovered
    refused: u32 = 0, // discovered pairs the indexed merge rejected
};

pub fn meshMirrorMatchQuads(axis_mask_raw: u32) z3d.MirrorQuadStats {
    var stats: z3d.MirrorQuadStats = .{};
    if (!model_paint.hasTarget()) return stats;
    const verts = z3d.g_edit_verts orelse return stats;
    const tri_count = z3d.g_edit_count / 3;
    if (tri_count == 0) return stats;
    const mirror_axes: u8 = @intCast(axis_mask_raw & 7);
    if (mirror_axes == 0) return stats;
    if (model_source.faceGroups() == null) return stats; // no authored quads to copy
    const alloc = std.heap.c_allocator;
    const PosKey = z3d.mirror_corners.Key;
    const helpers = struct {
        pub fn sortTriple(keys: *[3]PosKey) void {
            var i: usize = 1;
            while (i < 3) : (i += 1) {
                var j = i;
                while (j > 0 and z3d.mirror_corners.posLess(keys[j], keys[j - 1])) : (j -= 1) {
                    std.mem.swap(PosKey, &keys[j], &keys[j - 1]);
                }
            }
        }
    };

    // Authored-face identity → triangles + deduped sorted corner keys, in-scope only.
    var tris_of = std.AutoHashMapUnmanaged(u32, std.ArrayListUnmanaged(u32)).empty;
    var keys_of = std.AutoHashMapUnmanaged(u32, std.ArrayListUnmanaged(PosKey)).empty;
    defer {
        var t_it = tris_of.valueIterator();
        while (t_it.next()) |list| list.deinit(alloc);
        tris_of.deinit(alloc);
        var k_it = keys_of.valueIterator();
        while (k_it.next()) |list| list.deinit(alloc);
        keys_of.deinit(alloc);
    }
    var f: u32 = 0;
    while (f < tri_count) : (f += 1) {
        if (@as(usize, f) * 24 + 24 > verts.len) return stats;
        if (!mesh_edit.faceInScopePub(f)) continue;
        const aid = z3d.authoredFaceIdOf(true, f);
        const t_gop = tris_of.getOrPut(alloc, aid) catch return stats;
        if (!t_gop.found_existing) t_gop.value_ptr.* = .empty;
        t_gop.value_ptr.append(alloc, f) catch return stats;
        const k_gop = keys_of.getOrPut(alloc, aid) catch return stats;
        if (!k_gop.found_existing) k_gop.value_ptr.* = .empty;
        var slot: usize = 0;
        while (slot < 3) : (slot += 1) {
            if (!z3d.mirror_corners.addKey(k_gop.value_ptr, alloc, z3d.mirror_corners.quant(z3d.mirror_corners.corner(verts, f, slot)))) return stats;
        }
    }

    // Whole-face identity (already-symmetric probe) + lone-triangle identity (twin probe).
    var aid_by_hash = std.AutoHashMapUnmanaged(u64, u32).empty;
    defer aid_by_hash.deinit(alloc);
    var lone_by_hash = std.AutoHashMapUnmanaged(u64, u32).empty; // 3-corner hash → face index
    defer lone_by_hash.deinit(alloc);
    var hash_it = keys_of.iterator();
    while (hash_it.next()) |entry| {
        aid_by_hash.put(alloc, z3d.mirror_corners.keyHash(entry.value_ptr.items), entry.key_ptr.*) catch return stats;
        const tris = tris_of.get(entry.key_ptr.*) orelse continue;
        if (tris.items.len == 1 and entry.value_ptr.items.len == 3) {
            lone_by_hash.put(alloc, z3d.mirror_corners.keyHash(entry.value_ptr.items), tris.items[0]) catch return stats;
        }
    }

    const colors = z3d.collectCurrentFaceColors() orelse return stats;
    defer std.heap.c_allocator.free(colors);
    if (colors.len != @as(usize, tri_count) * 4) return stats;

    // Discover the twin pairs to fuse. Each lone triangle may be claimed once.
    var pairs = std.ArrayListUnmanaged([2]u32).empty;
    defer pairs.deinit(alloc);
    var claimed = std.AutoHashMapUnmanaged(u32, void).empty;
    defer claimed.deinit(alloc);
    var source_it = tris_of.iterator();
    while (source_it.next()) |entry| {
        const source_tris = entry.value_ptr.items;
        if (source_tris.len != 2) continue;
        const source_keys = (keys_of.get(entry.key_ptr.*) orelse continue).items;
        if (source_keys.len != 4) continue; // wire/degenerate quads have no twin shape
        stats.quads += 1;
        // Split the quad's corners into its diagonal (shared by both triangles) and
        // the two off-diagonal tips.
        var tri_keys: [2][3]PosKey = undefined;
        for (source_tris, 0..) |tri, at| {
            var slot: usize = 0;
            while (slot < 3) : (slot += 1) {
                tri_keys[at][slot] = z3d.mirror_corners.quant(z3d.mirror_corners.corner(verts, tri, slot));
            }
        }
        var diag: [2]PosKey = undefined;
        var off: [2]PosKey = undefined;
        var diag_n: usize = 0;
        var off_n: usize = 0;
        var degenerate = false;
        for (source_keys) |k| {
            var in_first = false;
            var in_second = false;
            for (tri_keys[0]) |t| {
                if (t[0] == k[0] and t[1] == k[1] and t[2] == k[2]) in_first = true;
            }
            for (tri_keys[1]) |t| {
                if (t[0] == k[0] and t[1] == k[1] and t[2] == k[2]) in_second = true;
            }
            if (in_first and in_second) {
                if (diag_n >= 2) {
                    degenerate = true;
                    break;
                }
                diag[diag_n] = k;
                diag_n += 1;
            } else {
                if (off_n >= 2) {
                    degenerate = true;
                    break;
                }
                off[off_n] = k;
                off_n += 1;
            }
        }
        if (degenerate or diag_n != 2 or off_n != 2) continue;

        var subset: u8 = 1;
        subsets: while (subset <= 7) : (subset += 1) {
            if ((subset & mirror_axes) != subset) continue;
            var reflected = std.ArrayListUnmanaged(PosKey).empty;
            defer reflected.deinit(alloc);
            var bad = false;
            for (source_keys) |k| {
                if (!z3d.mirror_corners.addKey(&reflected, alloc, z3d.mirror_corners.reflect(k, subset))) {
                    bad = true;
                    break;
                }
            }
            if (bad or reflected.items.len != 4) continue; // straddles/collapses on the plane
            // An authored face already covering the reflected corners means this quad is
            // already symmetric across this subset (or is its own twin) — nothing owed.
            if (aid_by_hash.get(z3d.mirror_corners.keyHash(reflected.items))) |twin_aid| {
                if (keys_of.get(twin_aid)) |twin_keys| {
                    if (z3d.mirror_corners.sameKeys(twin_keys.items, reflected.items)) {
                        stats.symmetric += 1;
                        continue;
                    }
                }
            }
            const rd0 = z3d.mirror_corners.reflect(diag[0], subset);
            const rd1 = z3d.mirror_corners.reflect(diag[1], subset);
            const ro0 = z3d.mirror_corners.reflect(off[0], subset);
            const ro1 = z3d.mirror_corners.reflect(off[1], subset);
            // The twin pair may be split on either diagonal of the reflected quad.
            const splits = [2][2][3]PosKey{
                .{ .{ rd0, rd1, ro0 }, .{ rd0, rd1, ro1 } },
                .{ .{ ro0, ro1, rd0 }, .{ ro0, ro1, rd1 } },
            };
            for (splits) |split| {
                var found: [2]u32 = undefined;
                var found_ok = true;
                for (split, 0..) |triple_raw, at| {
                    var triple = triple_raw;
                    helpers.sortTriple(&triple);
                    const cand = lone_by_hash.get(z3d.mirror_corners.keyHash(triple[0..])) orelse {
                        found_ok = false;
                        break;
                    };
                    const cand_keys = keys_of.get(z3d.authoredFaceIdOf(true, cand)) orelse {
                        found_ok = false;
                        break;
                    };
                    if (!z3d.mirror_corners.sameKeys(cand_keys.items, triple[0..])) { // hash collision
                        found_ok = false;
                        break;
                    }
                    found[at] = cand;
                }
                if (!found_ok or found[0] == found[1]) continue;
                if (claimed.contains(found[0]) or claimed.contains(found[1])) continue;
                if (found[0] == source_tris[0] or found[0] == source_tris[1]) continue;
                if (found[1] == source_tris[0] or found[1] == source_tris[1]) continue;
                // A single authored face cannot straddle opaque and glass draw passes.
                const glass_a = model_paint.isGlassAlpha(colors[@as(usize, found[0]) * 4 + 3]);
                const glass_b = model_paint.isGlassAlpha(colors[@as(usize, found[1]) * 4 + 3]);
                if (glass_a != glass_b) continue;
                pairs.append(alloc, .{ found[0], found[1] }) catch return stats;
                claimed.put(alloc, found[0], {}) catch return stats;
                claimed.put(alloc, found[1], {}) catch return stats;
                stats.pairs += 1;
                break :subsets;
            }
        }
    }
    if (pairs.items.len == 0) return stats;

    const groups = z3d.captureFaceGroups() orelse return stats;
    defer std.heap.c_allocator.free(groups);
    const parts = z3d.capturePartOfFaces();
    defer if (parts) |rows| std.heap.c_allocator.free(rows);
    const materials = z3d.captureFaceMaterials(tri_count) orelse return stats;
    defer std.heap.c_allocator.free(materials);

    var indexed = z3d.cloneIndexedEditMeshOrImport(verts, tri_count, groups, parts, model_source.faceMaterials()) orelse return stats;
    defer indexed.deinit();
    const pair_mask = alloc.alloc(bool, tri_count) catch return stats;
    defer alloc.free(pair_mask);
    var fused: u32 = 0;
    var any_retessellated = false;
    for (pairs.items) |pair| {
        @memset(pair_mask, false);
        pair_mask[pair[0]] = true;
        pair_mask[pair[1]] = true;
        // TRUSTED merge — no coplanarity gate (req_3855): the source quad the model
        // already contains licenses an equally-warped mirror twin. Import-authored
        // quads are routinely millimetres out of plane, which the interactive gate
        // rightly refuses to CREATE but must not refuse to COPY. Other refusals
        // (cross-meaning, unwelded) still skip honestly and land in `refused`.
        const merged = (indexed.mergeSelectedTrusted(pair_mask) catch null) orelse continue;
        if (merged.retessellated) any_retessellated = true;
        fused += 1;
    }
    stats.refused = @intCast(pairs.items.len - fused);
    if (fused == 0) return stats;
    stats.fused = fused;

    if (!any_retessellated) {
        // Every fused boundary kept all four corners — the byte-stable group-only
        // commit keeps geometry, UVs, and atlas pixels untouched.
        if (!z3d.commitIndexedFaceGrouping(&indexed, verts, tri_count, parts, materials, "mirror match quads")) {
            stats.fused = 0;
            return stats;
        }
        return stats;
    }

    // Dissolve commit (req_3771 shape): some fused boundary dropped seam corners, so
    // the resident rows are rebuilt from the clean loops in one journal entry.
    stats.fused = 0; // restored below only when the install commits
    var lowered = indexed.lower() catch return stats;
    defer lowered.deinit();
    if (lowered.tri_count == 0) return stats;
    const dissolve_colors = std.heap.c_allocator.alloc(u8, @as(usize, lowered.tri_count) * 4) catch return stats;
    defer std.heap.c_allocator.free(dissolve_colors);
    if (!mesh_edit.inheritFaceRgba(colors, lowered.source_triangles, dissolve_colors)) return stats;
    const part_count = z3d.hostPartCount();
    var snap = z3d.journalSnapshotCurrent("mirror match quads");
    const installed = z3d.lcInstallLowered(
        lowered.positions,
        lowered.uvs,
        lowered.tri_count,
        lowered.groups,
        lowered.materials,
        lowered.semantic_regions,
        lowered.semantic_instances,
        dissolve_colors,
        z3d.flattenedLogicalRows(lowered.triangle_vertices),
        @intCast(indexed.vertices.items.len),
    );
    if (!installed) {
        z3d.journalDiscard(&snap);
        return stats;
    }
    if (parts != null) z3d.renormalizePartRanges(lowered.parts, part_count);
    z3d.adoptIndexedEditMesh(&indexed, &lowered);
    z3d.journalCommit(&snap);
    stats.fused = fused;
    return stats;
}

/// Selection-scoped mirror stamp (req_3864): reflect the SELECTED faces across the
/// model-origin plane of the lowest armed axis, deleting every whole twin face buried
/// in the stamped space and welding the seam + region border — the user's own retopo
/// unit ("delete the triangles, create the face in the space") applied to the twin
/// side in one journal entry. Unselected faces are never deleted and never reflected,
/// so deliberate asymmetry survives by simply not being selected.
pub fn meshMirrorReplaceSelection(axis_mask_raw: u32) indexed_edit_mesh.Mesh.MirrorReplaceStats {
    const empty: indexed_edit_mesh.Mesh.MirrorReplaceStats = .{};
    if (!model_paint.hasTarget()) return empty;
    if (mesh_edit.mode() != .face) return empty;
    const verts = z3d.g_edit_verts orelse return empty;
    const tri_count = z3d.g_edit_count / 3;
    if (tri_count == 0) return empty;
    const axis: u8 = blk: {
        const m: u8 = @intCast(axis_mask_raw & 7);
        if (m & 1 != 0) break :blk 0;
        if (m & 2 != 0) break :blk 1;
        if (m & 4 != 0) break :blk 2;
        return empty;
    };
    const mask = std.heap.c_allocator.alloc(bool, tri_count) catch return empty;
    defer std.heap.c_allocator.free(mask);
    if (mesh_edit.buildDeleteMask(mask) == 0) return empty;

    const base_colors = z3d.collectCurrentFaceColors() orelse return empty;
    defer std.heap.c_allocator.free(base_colors);
    const groups = z3d.captureFaceGroups();
    defer if (groups) |rows| std.heap.c_allocator.free(rows);
    const parts = z3d.capturePartOfFaces();
    defer if (parts) |rows| std.heap.c_allocator.free(rows);
    const part_count = z3d.hostPartCount();
    const groups_arg: ?[]const u32 = if (model_source.faceGroupOf(0) != model_source.NO_FACE_GROUP) groups else null;
    var indexed = z3d.cloneIndexedEditMeshOrImport(verts, tri_count, groups_arg, parts, model_source.faceMaterials()) orelse return empty;
    defer indexed.deinit();
    const stats = (indexed.mirrorReplaceSelection(mask, axis, mesh_edit.MIRROR_PLANE_CENTER[axis]) catch return empty) orelse return empty;
    var lowered = indexed.lower() catch return empty;
    defer lowered.deinit();
    if (lowered.tri_count == 0) return empty;
    const colors = std.heap.c_allocator.alloc(u8, @as(usize, lowered.tri_count) * 4) catch return empty;
    defer std.heap.c_allocator.free(colors);
    if (!mesh_edit.inheritFaceRgba(base_colors, lowered.source_triangles, colors)) return empty;
    var snap = z3d.journalSnapshotCurrent("mirror copy selection");
    const install_groups: ?[]const u32 = if (groups_arg != null) lowered.groups else null;
    const ok = z3d.lcInstallLowered(lowered.positions, lowered.uvs, lowered.tri_count, install_groups, lowered.materials, lowered.semantic_regions, lowered.semantic_instances, colors, z3d.flattenedLogicalRows(lowered.triangle_vertices), @intCast(indexed.vertices.items.len));
    if (!ok) {
        z3d.journalDiscard(&snap);
        return empty;
    }
    if (parts != null) z3d.renormalizePartRanges(lowered.parts, part_count);
    z3d.adoptIndexedEditMesh(&indexed, &lowered);
    mesh_edit.clearSelection();
    z3d.journalCommit(&snap);
    return stats;
}
