//! pipeline_init.zig — split verbatim from framework/gpu/3d.zig (req_4375).
//! Generated by _tool/split3d.zig — edit 3d.zig's successor here, regenerate only from the manifest.
//! Cross-file references are qualified through the orchestrator (`z3d`).

const std = @import("std");
const builtin = @import("builtin");
const log = @import("../../diag/log.zig");
const wgpu = @import("wgpu");
const bu = @import("../buffer_upload.zig");
const shaders = @import("../shaders.zig");
const terrain_grid = @import("../terrain_grid.zig");
const core = @import("../../dev_modules/gpu_api.zig");
const capture = @import("../capture.zig");
const build_options = @import("build_options");
const math = @import("../../math/root.zig");
const layout = @import("../../layout.zig");
const effect_assemble = @import("../effect_assemble.zig");
const compile_progress = @import("../compile_progress.zig");
const static_instance_policy = @import("../static_instance_policy.zig");
const model_paint = @import("../model_paint.zig");
const gizmo_axis_map = @import("../gizmo_axis_map.zig");
const effects_ctx = @import("../effects_ctx.zig");
const paint_islands_mod = @import("../paint_islands.zig");
const paint_program = @import("../paint_program.zig");
const model_source = @import("../model_source.zig");
const meshdoc_format = @import("../meshdoc_format.zig");
const mesh_audit = @import("../mesh_audit.zig");
const mesh_face_table = @import("../mesh_face_table.zig");
const mesh_face_diff = @import("../mesh_face_diff.zig");
const mesh_face_field_candidate = @import("../mesh_face_field_candidate.zig");
const mesh_face_table_package = @import("../mesh_face_table_package.zig");
const mesh_face_table_worker = @import("../mesh_face_table_worker.zig");
const historical_preview = @import("../historical_preview.zig");
const mesh_edit = @import("../mesh_edit.zig");
const mesh_semantics = @import("../mesh_semantics.zig");
const mesh_semantic_restore = @import("../mesh_semantic_restore.zig");
const mesh_edge_semantics = @import("../mesh_edge_semantics.zig");
const indexed_edit_mesh = @import("../indexed_edit_mesh.zig");
const character_topology_promotion = @import("../character_topology_promotion.zig");
const mesh_journal_log = @import("../mesh_journal_log.zig");
const model_write_lease = @import("../model_write_lease.zig");
const model_adoption_receipt = @import("../model_adoption_receipt.zig");
const model_adoption_finalize = @import("../model_adoption_finalize.zig");
const path_array = @import("../path_array.zig");
const path_plane = @import("../path_plane.zig");
const stage_scale = @import("../stage_scale.zig");
const pack = @import("../pack.zig");
const stable_geometry_slot = @import("../stable_geometry_slot.zig");
const character_rig_session = @import("../../skeleton/character_rig_session.zig");
const character_skin_binding = @import("../../skeleton/skin_binding.zig");
const character_specimen = @import("../character_specimen.zig");
const mouse_state = @import("../../state/mouse_state.zig");
const Node = layout.Node;

const z3d = @import("3d.zig");

// ════════════════════════════════════════════════════════════════════════
// Init / deinit (same as before — pipeline, bind groups, sampler)
// ════════════════════════════════════════════════════════════════════════

// ── Skinned-mesh path (SKIN-3499): matrix-palette LBS for figures ───────────
// A skinned node (layout scene3d_skin_*) draws as ONE palette-blended mesh:
// 28-byte vertices carrying bone indices/weights, a per-figure storage-buffer
// palette (BoneData: column-major model-space mat4 + rgba tint, 80 B std430),
// and the node's own TRS as the instance root. Wire verts are stride-16 f32
// [pos3, normal3, uv2, joint4, weight4]; packing happens once at upload,
// exactly like stageVertexRows does for the standard path.
pub const SkinnedVertex = extern struct {
    px: f32,
    py: f32,
    pz: f32,
    noct: [2]i16, // snorm16x2 octahedral normal
    u: f16,
    v: f16,
    joints: [4]u8, // bone indices (uint8x4)
    weights: [4]u8, // bone weights (unorm8x4)
};

comptime {
    if (@sizeOf(z3d.SkinnedVertex) != 28 or @alignOf(z3d.SkinnedVertex) != 4) {
        @compileError("SkinnedVertex must match the packed skinned vbuf0 layout (28 bytes)");
    }
}

/// Retained skinned-vertex budget: 1M verts × 28 B = 28 MiB — figures are
/// small next to the world's 256 MiB retained pool. Interned once per content
/// key, never evicted (same discipline as the standard geometry cache).
pub const MAX_SKINNED_VERTS: u64 = 1 << 20;
pub const SKIN_GEO_CACHE = 64;
/// Concurrent skinned figures per frame (player + a handful of NPCs today).
pub const SKIN_POOL = 8;
/// Bones per palette slot — u8 joint indices cap the wire at 256 anyway.
pub const MAX_SKIN_BONES = 256;
/// Floats per palette entry: column-major mat4 (16) + rgba tint (4) = 80 B.
pub const SKIN_BONE_FLOATS = 20;

pub const SkinGeoEntry = struct { hash: u64 = 0, offset_bytes: u64 = 0, count: u32 = 0, present: bool = false };
pub const SKIN_PACK_CHUNK = 32768;

pub fn init(environ: *const std.process.Environ.Map) void {
    z3d.g_perflog_on = environ.get("RJIT_PERFLOG") != null;
    z3d.g_census_on = environ.get("RJIT_R3D_CENSUS") != null;
    z3d.g_paint_probe_enabled = environ.get("RJIT_PAINTPROBE") != null;
    if (environ.get("RJIT_FPS")) |value| {
        z3d.g_fpshud_on = !std.mem.eql(u8, value, "0") and !std.mem.eql(u8, value, "");
    } else {
        const default_on = if (@hasDecl(build_options, "use_v8")) !build_options.use_v8 else false;
        z3d.g_fpshud_on = default_on or z3d.g_perflog_on;
    }
    const device = core.getDevice() orelse return;
    const shader_desc = wgpu.shaderModuleWGSLDescriptor(.{ .label = "render3d_shader", .code = shaders.scene3d_wgsl });
    const shader_module = device.createShaderModule(&shader_desc) orelse return;
    defer shader_module.release();

    z3d.g_vertex_buffer = device.createBuffer(&.{
        .label = wgpu.StringView.fromSlice("render3d_verts"),
        .size = z3d.MAX_FRAME_VERTS * @sizeOf(z3d.Vertex),
        .usage = wgpu.BufferUsages.vertex | wgpu.BufferUsages.copy_dst,
        .mapped_at_creation = 0,
    });
    // Retained buffer for interned registry geometry — uploaded once per unique
    // key, never reset per frame (unlike g_vertex_buffer which bump-resets).
    z3d.g_retained_vbuf = device.createBuffer(&.{
        .label = wgpu.StringView.fromSlice("render3d_retained_verts"),
        // Intern region [0, MAX_RETAINED_VERTS) + a reserved dynamic-slot tail.
        .size = (z3d.MAX_RETAINED_VERTS + z3d.DYN_REGION_VERTS) * @sizeOf(z3d.Vertex),
        .usage = wgpu.BufferUsages.vertex | wgpu.BufferUsages.copy_dst,
        .mapped_at_creation = 0,
    });
    // Scene uniforms — ONE set per frame (no dynamic offset). Was per-draw with
    // a 256-byte stride × MAX_DRAW_UNIFORMS; instancing moved per-mesh data (model
    // matrix, color) into the per-instance vertex buffer below.
    z3d.g_uniform_buffer = device.createBuffer(&.{
        .label = wgpu.StringView.fromSlice("render3d_scene_uniforms"),
        .size = @sizeOf(z3d.SceneUniforms),
        .usage = wgpu.BufferUsages.uniform | wgpu.BufferUsages.copy_dst,
        .mapped_at_creation = 0,
    });
    // Per-instance vertex buffer — packed InstanceData (model + color), step=instance.
    // drawScene writes one record per mesh, grouped by (geom_key, texture); each
    // group issues ONE pass.draw(vert_count, instance_count, ...).
    z3d.g_instance_buf = device.createBuffer(&.{
        .label = wgpu.StringView.fromSlice("render3d_instances"),
        .size = z3d.MAX_INSTANCES * @sizeOf(z3d.InstanceData),
        .usage = wgpu.BufferUsages.vertex | wgpu.BufferUsages.copy_dst,
        .mapped_at_creation = 0,
    });
    // Per-frame slim buffer for foliage-card overflow rows (24 B each → ~6.3 MB vs 21 MB).
    z3d.g_slim_inst_buf = device.createBuffer(&.{
        .label = wgpu.StringView.fromSlice("render3d_slim_instances"),
        .size = z3d.MAX_INSTANCES * @sizeOf(z3d.SlimInstance),
        .usage = wgpu.BufferUsages.vertex | wgpu.BufferUsages.copy_dst,
        .mapped_at_creation = 0,
    });
    // Placed-light storage buffer (group 0, binding 1). Allocated once at
    // MAX_LIGHTS; collectLights writes the live prefix each frame.
    z3d.g_lights_buf = device.createBuffer(&.{
        .label = wgpu.StringView.fromSlice("render3d_lights"),
        .size = z3d.MAX_LIGHTS * @sizeOf(z3d.Light),
        .usage = wgpu.BufferUsages.storage | wgpu.BufferUsages.copy_dst,
        .mapped_at_creation = 0,
    });
    // ── Shadow resources (group 0, bindings 2–4) ──
    // The shadow map is a sampleable depth texture rendered from the caster's POV;
    // the comparison sampler does hardware PCF; the uniform carries the light VP +
    // gate. Bound on every scene draw so the layout stays uniform across pipelines.
    z3d.g_shadow_tex = device.createTexture(&.{
        .label = wgpu.StringView.fromSlice("render3d_shadow_map"),
        .size = .{ .width = z3d.SHADOW_MAP_SIZE, .height = z3d.SHADOW_MAP_SIZE, .depth_or_array_layers = 1 },
        .mip_level_count = 1,
        .sample_count = 1,
        .dimension = .@"2d",
        .format = .depth32_float,
        .usage = wgpu.TextureUsages.render_attachment | wgpu.TextureUsages.texture_binding,
    });
    if (z3d.g_shadow_tex) |st| {
        z3d.g_shadow_view = st.createView(&.{
            .format = .depth32_float,
            .dimension = .@"2d",
            .base_mip_level = 0,
            .mip_level_count = 1,
            .base_array_layer = 0,
            .array_layer_count = 1,
            .aspect = .all,
        });
    }
    z3d.g_shadow_sampler = device.createSampler(&.{
        .address_mode_u = .clamp_to_edge,
        .address_mode_v = .clamp_to_edge,
        .mag_filter = .linear,
        .min_filter = .linear,
        .compare = .less, // depth-comparison sampler: passes (1) when frag is closer
    });
    z3d.g_shadow_uniform_buf = device.createBuffer(&.{
        .label = wgpu.StringView.fromSlice("render3d_shadow_uniform"),
        .size = @sizeOf(z3d.ShadowUniforms),
        .usage = wgpu.BufferUsages.uniform | wgpu.BufferUsages.copy_dst,
        .mapped_at_creation = 0,
    });
    z3d.g_shadow_vp_buf = device.createBuffer(&.{
        .label = wgpu.StringView.fromSlice("render3d_shadow_vp"),
        .size = 16 * @sizeOf(f32),
        .usage = wgpu.BufferUsages.uniform | wgpu.BufferUsages.copy_dst,
        .mapped_at_creation = 0,
    });
    z3d.g_shadow_inst_buf = device.createBuffer(&.{
        .label = wgpu.StringView.fromSlice("render3d_shadow_instances"),
        .size = z3d.MAX_INSTANCES * @sizeOf(z3d.InstanceData),
        .usage = wgpu.BufferUsages.vertex | wgpu.BufferUsages.copy_dst,
        .mapped_at_creation = 0,
    });
    const scene_bgl_entries = [_]wgpu.BindGroupLayoutEntry{
        .{
            .binding = 0,
            .visibility = wgpu.ShaderStages.vertex | wgpu.ShaderStages.fragment,
            .buffer = .{ .type = .uniform, .has_dynamic_offset = 0, .min_binding_size = @sizeOf(z3d.SceneUniforms) },
        },
        .{
            .binding = 1,
            .visibility = wgpu.ShaderStages.fragment,
            .buffer = .{ .type = .read_only_storage, .has_dynamic_offset = 0, .min_binding_size = 0 },
        },
        .{
            .binding = 2,
            .visibility = wgpu.ShaderStages.fragment,
            .buffer = .{ .type = .uniform, .has_dynamic_offset = 0, .min_binding_size = @sizeOf(z3d.ShadowUniforms) },
        },
        .{
            .binding = 3,
            .visibility = wgpu.ShaderStages.fragment,
            .texture = .{ .sample_type = .depth, .view_dimension = .@"2d", .multisampled = 0 },
        },
        .{
            .binding = 4,
            .visibility = wgpu.ShaderStages.fragment,
            .sampler = .{ .type = .comparison },
        },
    };
    z3d.g_bind_group_layout = device.createBindGroupLayout(&.{
        .entry_count = scene_bgl_entries.len,
        .entries = &scene_bgl_entries,
    }) orelse return;
    const scene_bg_entries = [_]wgpu.BindGroupEntry{
        .{ .binding = 0, .buffer = z3d.g_uniform_buffer.?, .offset = 0, .size = @sizeOf(z3d.SceneUniforms) },
        .{ .binding = 1, .buffer = z3d.g_lights_buf.?, .offset = 0, .size = z3d.MAX_LIGHTS * @sizeOf(z3d.Light) },
        .{ .binding = 2, .buffer = z3d.g_shadow_uniform_buf.?, .offset = 0, .size = @sizeOf(z3d.ShadowUniforms) },
        .{ .binding = 3, .texture_view = z3d.g_shadow_view.? },
        .{ .binding = 4, .sampler = z3d.g_shadow_sampler.? },
    };
    z3d.g_bind_group = device.createBindGroup(&.{
        .layout = z3d.g_bind_group_layout.?,
        .entry_count = scene_bg_entries.len,
        .entries = &scene_bg_entries,
    });

    // ── Texture bind group layout (group 1) ──
    // Per-mesh diffuse texture + sampler. Each mesh gets its own bind group
    // pointing at that mesh's texture; meshes without a texture point at
    // g_default_tex_bind_group (1×1 white).
    const tex_entries = [_]wgpu.BindGroupLayoutEntry{
        .{
            .binding = 0,
            .visibility = wgpu.ShaderStages.fragment,
            .texture = .{ .sample_type = .float, .view_dimension = .@"2d", .multisampled = 0 },
        },
        .{
            .binding = 1,
            .visibility = wgpu.ShaderStages.fragment,
            // NON-FILTERING to match the nearest diffuse sampler below. Linear
            // sampling averaged each atlas slot's edge texels with the neighbour
            // slot / gutter, drawing thin off-colour SEAM lines at every face
            // boundary and bleeding a neighbour's paint onto a face's corner
            // (the Studio paint seams, req_1321). Nearest samples exactly one
            // texel — no cross-slot blend — and flat paint loses nothing.
            .sampler = .{ .type = .non_filtering },
        },
        .{
            .binding = 2,
            .visibility = wgpu.ShaderStages.fragment,
            .buffer = .{ .type = .uniform, .has_dynamic_offset = 0, .min_binding_size = 4 * @sizeOf(f32) },
        },
    };
    z3d.g_tex_bind_group_layout = device.createBindGroupLayout(&.{
        .entry_count = tex_entries.len,
        .entries = &tex_entries,
    }) orelse return;

    z3d.g_diffuse_sampler = device.createSampler(&.{
        .address_mode_u = .clamp_to_edge,
        .address_mode_v = .clamp_to_edge,
        // NEAREST: no blend across atlas slot boundaries → no seam lines, no
        // neighbour-paint bleed onto a face edge (req_1321). Flat paint + the
        // crisp PSX look mean nearest loses nothing; the matching bind-group
        // layout above is .non_filtering.
        .mag_filter = .nearest,
        .min_filter = .nearest,
    });
    z3d.g_uv_unbounded_uniform = device.createBuffer(&.{
        .label = wgpu.StringView.fromSlice("render3d_uv_unbounded"),
        .size = 4 * @sizeOf(f32),
        .usage = wgpu.BufferUsages.uniform | wgpu.BufferUsages.copy_dst,
        .mapped_at_creation = 0,
    });
    z3d.g_uv_finite_uniform = device.createBuffer(&.{
        .label = wgpu.StringView.fromSlice("render3d_uv_finite"),
        .size = 4 * @sizeOf(f32),
        .usage = wgpu.BufferUsages.uniform | wgpu.BufferUsages.copy_dst,
        .mapped_at_creation = 0,
    });
    if (core.getQueue()) |queue| {
        const unbounded = [_]f32{ 0, 0, 0, 0 };
        const finite = [_]f32{ 1, 0, 0, 0 };
        if (z3d.g_uv_unbounded_uniform) |buffer| queue.writeBuffer(buffer, 0, @ptrCast(&unbounded), @sizeOf(@TypeOf(unbounded)));
        if (z3d.g_uv_finite_uniform) |buffer| queue.writeBuffer(buffer, 0, @ptrCast(&finite), @sizeOf(@TypeOf(finite)));
    }

    // 1×1 white default texture so untextured meshes sample white →
    // multiply with uniform color → unchanged visual.
    z3d.g_default_tex = device.createTexture(&.{
        .label = wgpu.StringView.fromSlice("r3d_default_white"),
        .size = .{ .width = 1, .height = 1, .depth_or_array_layers = 1 },
        .mip_level_count = 1,
        .sample_count = 1,
        .dimension = .@"2d",
        .format = .rgba8_unorm,
        .usage = wgpu.TextureUsages.texture_binding | wgpu.TextureUsages.copy_dst,
    });
    if (z3d.g_default_tex) |dtex| {
        const white_pixel = [_]u8{ 255, 255, 255, 255 };
        const queue = core.getQueue();
        if (queue) |q| {
            q.writeTexture(
                &.{ .texture = dtex, .mip_level = 0, .origin = .{}, .aspect = .all },
                @ptrCast(&white_pixel),
                white_pixel.len,
                &.{ .offset = 0, .bytes_per_row = 4, .rows_per_image = 1 },
                &.{ .width = 1, .height = 1, .depth_or_array_layers = 1 },
            );
        }
        z3d.g_default_tex_view = dtex.createView(&.{
            .format = .rgba8_unorm,
            .dimension = .@"2d",
            .base_mip_level = 0,
            .mip_level_count = 1,
            .base_array_layer = 0,
            .array_layer_count = 1,
            .aspect = .all,
        });
    }
    if (z3d.g_default_tex_view != null and z3d.g_diffuse_sampler != null and z3d.g_uv_unbounded_uniform != null) {
        const def_entries = [_]wgpu.BindGroupEntry{
            .{ .binding = 0, .texture_view = z3d.g_default_tex_view.? },
            .{ .binding = 1, .sampler = z3d.g_diffuse_sampler.? },
            .{ .binding = 2, .buffer = z3d.g_uv_unbounded_uniform.?, .offset = 0, .size = 4 * @sizeOf(f32) },
        };
        z3d.g_default_tex_bind_group = device.createBindGroup(&.{
            .layout = z3d.g_tex_bind_group_layout.?,
            .entry_count = def_entries.len,
            .entries = &def_entries,
        });
    }

    // Independent glass atlas. It deliberately uses unbounded sampling: every UV
    // resolves to this one texel, so glass can never fall back into, overlap, or
    // transfer opacity through the opaque model atlas.
    z3d.g_glass_aux_tex = device.createTexture(&.{
        .label = wgpu.StringView.fromSlice("r3d_glass_aux"),
        .size = .{ .width = 1, .height = 1, .depth_or_array_layers = 1 },
        .mip_level_count = 1,
        .sample_count = 1,
        .dimension = .@"2d",
        .format = .rgba8_unorm,
        .usage = wgpu.TextureUsages.texture_binding | wgpu.TextureUsages.copy_dst,
    });
    if (z3d.g_glass_aux_tex) |glass_tex| {
        const queue = core.getQueue();
        if (queue) |q| {
            q.writeTexture(
                &.{ .texture = glass_tex, .mip_level = 0, .origin = .{}, .aspect = .all },
                @ptrCast(&model_paint.GLASS_AUX_TEXEL),
                model_paint.GLASS_AUX_TEXEL.len,
                &.{ .offset = 0, .bytes_per_row = 4, .rows_per_image = 1 },
                &.{ .width = 1, .height = 1, .depth_or_array_layers = 1 },
            );
        }
        z3d.g_glass_aux_tex_view = glass_tex.createView(&.{
            .format = .rgba8_unorm,
            .dimension = .@"2d",
            .base_mip_level = 0,
            .mip_level_count = 1,
            .base_array_layer = 0,
            .array_layer_count = 1,
            .aspect = .all,
        });
    }
    if (z3d.g_glass_aux_tex_view != null and z3d.g_diffuse_sampler != null and z3d.g_uv_unbounded_uniform != null) {
        const glass_entries = [_]wgpu.BindGroupEntry{
            .{ .binding = 0, .texture_view = z3d.g_glass_aux_tex_view.? },
            .{ .binding = 1, .sampler = z3d.g_diffuse_sampler.? },
            .{ .binding = 2, .buffer = z3d.g_uv_unbounded_uniform.?, .offset = 0, .size = 4 * @sizeOf(f32) },
        };
        z3d.g_glass_aux_tex_bind_group = device.createBindGroup(&.{
            .layout = z3d.g_tex_bind_group_layout.?,
            .entry_count = glass_entries.len,
            .entries = &glass_entries,
        });
    }

    // ── Ground-formula group(1): one read-only storage buffer (the D ref stream).
    //    The pool of buffers + their bind groups is created up front; the PIPELINE
    //    is built lazily (ensureGroundPipeline) once a formula arrives. ──
    z3d.g_ground_bgl = device.createBindGroupLayout(&.{
        .entry_count = 1,
        .entries = @ptrCast(&wgpu.BindGroupLayoutEntry{
            .binding = 0,
            .visibility = wgpu.ShaderStages.vertex | wgpu.ShaderStages.fragment,
            .buffer = .{ .type = .read_only_storage, .has_dynamic_offset = 0, .min_binding_size = 0 },
        }),
    }) orelse return;
    {
        var gi: usize = 0;
        while (gi < z3d.GROUND_POOL) : (gi += 1) {
            const buf = device.createBuffer(&.{
                .label = wgpu.StringView.fromSlice("r3d_ground_data"),
                .size = z3d.GROUND_DATA_FLOATS * @sizeOf(f32),
                .usage = wgpu.BufferUsages.storage | wgpu.BufferUsages.copy_dst,
                .mapped_at_creation = 0,
            });
            z3d.g_ground_data_buf[gi] = buf;
            if (buf) |b| {
                z3d.g_ground_data_bg[gi] = device.createBindGroup(&.{
                    .layout = z3d.g_ground_bgl.?,
                    .entry_count = 1,
                    .entries = @ptrCast(&wgpu.BindGroupEntry{
                        .binding = 0,
                        .buffer = b,
                        .offset = 0,
                        .size = z3d.GROUND_DATA_FLOATS * @sizeOf(f32),
                    }),
                });
            }
        }
    }
    // The ground pass's own instance buffer — one InstanceData per drawn chunk, so the
    // ground never competes with foliage for the shared per-frame g_instance_buf (req_1659).
    z3d.g_ground_inst_buf = device.createBuffer(&.{
        .label = wgpu.StringView.fromSlice("r3d_ground_instances"),
        .size = z3d.GROUND_POOL * @sizeOf(z3d.InstanceData),
        .usage = wgpu.BufferUsages.vertex | wgpu.BufferUsages.copy_dst,
        .mapped_at_creation = 0,
    });
    // ── Live-material-region group(1) pool (req_3397): the SAME storage shape
    //    as ground, so g_ground_bgl serves both pipelines. Slot i of g_regions
    //    owns buffer/bind-group i — data uploads only when a region's data is
    //    dirty, never per frame. ──
    {
        var region_i: usize = 0;
        while (region_i < z3d.REGION_POOL) : (region_i += 1) {
            const buf = device.createBuffer(&.{
                .label = wgpu.StringView.fromSlice("r3d_region_data"),
                .size = z3d.REGION_DATA_FLOATS * @sizeOf(f32),
                .usage = wgpu.BufferUsages.storage | wgpu.BufferUsages.copy_dst,
                .mapped_at_creation = 0,
            });
            z3d.g_region_data_buf[region_i] = buf;
            if (buf) |b| {
                z3d.g_region_data_bg[region_i] = device.createBindGroup(&.{
                    .layout = z3d.g_ground_bgl.?,
                    .entry_count = 1,
                    .entries = @ptrCast(&wgpu.BindGroupEntry{
                        .binding = 0,
                        .buffer = b,
                        .offset = 0,
                        .size = z3d.REGION_DATA_FLOATS * @sizeOf(f32),
                    }),
                });
            }
        }
    }
    z3d.g_region_inst_buf = device.createBuffer(&.{
        .label = wgpu.StringView.fromSlice("r3d_region_instances"),
        .size = z3d.REGION_POOL * @sizeOf(z3d.InstanceData),
        .usage = wgpu.BufferUsages.vertex | wgpu.BufferUsages.copy_dst,
        .mapped_at_creation = 0,
    });
    z3d.initGroundGridTopology(device);
    z3d.g_ground_data_ptr = @splat(0);
    z3d.g_ground_data_version = @splat(0);
    z3d.g_ground_data_len = @splat(0);

    // ── Skinned-figure resources (SKIN-3499): the retained skinned-vertex
    //    buffer, the palette pool (one storage buffer + bind group per figure
    //    slot, g_ground_bgl-style), and the tiny per-figure instance buffer. ──
    z3d.g_skinned_vbuf = device.createBuffer(&.{
        .label = wgpu.StringView.fromSlice("render3d_skinned_verts"),
        .size = z3d.MAX_SKINNED_VERTS * @sizeOf(z3d.SkinnedVertex),
        .usage = wgpu.BufferUsages.vertex | wgpu.BufferUsages.copy_dst,
        .mapped_at_creation = 0,
    });
    z3d.g_skin_bgl = device.createBindGroupLayout(&.{
        .entry_count = 1,
        .entries = @ptrCast(&wgpu.BindGroupLayoutEntry{
            .binding = 0,
            .visibility = wgpu.ShaderStages.vertex,
            .buffer = .{ .type = .read_only_storage, .has_dynamic_offset = 0, .min_binding_size = 0 },
        }),
    });
    if (z3d.g_skin_bgl) |sbgl| {
        var ski: usize = 0;
        while (ski < z3d.SKIN_POOL) : (ski += 1) {
            const buf = device.createBuffer(&.{
                .label = wgpu.StringView.fromSlice("r3d_skin_palette"),
                .size = z3d.MAX_SKIN_BONES * z3d.SKIN_BONE_FLOATS * @sizeOf(f32),
                .usage = wgpu.BufferUsages.storage | wgpu.BufferUsages.copy_dst,
                .mapped_at_creation = 0,
            });
            z3d.g_skin_palette_buf[ski] = buf;
            if (buf) |b| {
                z3d.g_skin_palette_bg[ski] = device.createBindGroup(&.{
                    .layout = sbgl,
                    .entry_count = 1,
                    .entries = @ptrCast(&wgpu.BindGroupEntry{
                        .binding = 0,
                        .buffer = b,
                        .offset = 0,
                        .size = z3d.MAX_SKIN_BONES * z3d.SKIN_BONE_FLOATS * @sizeOf(f32),
                    }),
                });
            }
        }
    }
    z3d.g_skin_inst_buf = device.createBuffer(&.{
        .label = wgpu.StringView.fromSlice("r3d_skin_instances"),
        .size = z3d.SKIN_POOL * @sizeOf(z3d.InstanceData),
        .usage = wgpu.BufferUsages.vertex | wgpu.BufferUsages.copy_dst,
        .mapped_at_creation = 0,
    });

    const layouts = [_]?*wgpu.BindGroupLayout{ z3d.g_bind_group_layout.?, z3d.g_tex_bind_group_layout.? };
    const pipeline_layout = device.createPipelineLayout(&.{
        .bind_group_layout_count = layouts.len,
        .bind_group_layouts = @ptrCast(&layouts),
    }) orelse return;
    defer pipeline_layout.release();
    // Per-vertex attributes (vertex buffer 0, step=vertex) — position/normal/uv.
    const vert_attrs = [_]wgpu.VertexAttribute{
        .{ .format = .float32x3, .offset = 0, .shader_location = 0 },
        .{ .format = .snorm16x2, .offset = 12, .shader_location = 1 }, // oct normal
        .{ .format = .float16x2, .offset = 16, .shader_location = 2 }, // uv
    };
    // Per-instance attributes (vertex buffer 1, step=instance) — packed TRS+rgba
    // (32-byte InstanceData): pos f32x3 @3, euler u16x4 @4, scale f16x4 @5, rgba
    // unorm8x4 @6. The shaders rebuild the model matrix from these.
    const inst_attrs = [_]wgpu.VertexAttribute{
        .{ .format = .float32x3, .offset = 0, .shader_location = 3 },
        .{ .format = .uint16x4, .offset = 12, .shader_location = 4 },
        .{ .format = .float16x4, .offset = 20, .shader_location = 5 },
        .{ .format = .unorm8x4, .offset = 28, .shader_location = 6 },
    };
    const vert_layouts = [_]wgpu.VertexBufferLayout{
        .{ .step_mode = .vertex, .array_stride = @sizeOf(z3d.Vertex), .attribute_count = vert_attrs.len, .attributes = &vert_attrs },
        .{ .step_mode = .instance, .array_stride = @sizeOf(z3d.InstanceData), .attribute_count = inst_attrs.len, .attributes = &inst_attrs },
    };
    // Slim per-instance attributes for the FROND pipeline ONLY — the 24-byte
    // SlimInstance (pos f32x3 @3, pitch/yaw u16x2 @4, wide/len unorm16x2 @5, rgb
    // unorm8x4 @6). frond_wgsl rebuilds the model matrix from these. Same per-vertex
    // layout as everyone (vbuf 0), different instance buffer + stride (vbuf 1).
    const slim_inst_attrs = [_]wgpu.VertexAttribute{
        .{ .format = .float32x3, .offset = 0, .shader_location = 3 },
        .{ .format = .uint16x2, .offset = 12, .shader_location = 4 },
        .{ .format = .unorm16x2, .offset = 16, .shader_location = 5 },
        .{ .format = .unorm8x4, .offset = 20, .shader_location = 6 },
    };
    const slim_vert_layouts = [_]wgpu.VertexBufferLayout{
        .{ .step_mode = .vertex, .array_stride = @sizeOf(z3d.Vertex), .attribute_count = vert_attrs.len, .attributes = &vert_attrs },
        .{ .step_mode = .instance, .array_stride = @sizeOf(z3d.SlimInstance), .attribute_count = slim_inst_attrs.len, .attributes = &slim_inst_attrs },
    };
    const color_target = wgpu.ColorTargetState{
        .format = .rgba8_unorm,
        .blend = &wgpu.BlendState.premultiplied_alpha_blending,
        .write_mask = wgpu.ColorWriteMasks.all,
    };
    const frag = wgpu.FragmentState{
        .module = shader_module,
        .entry_point = wgpu.StringView.fromSlice("fs_main"),
        .target_count = 1,
        .targets = @ptrCast(&color_target),
    };
    const depth_stencil = wgpu.DepthStencilState{
        .format = .depth24_plus,
        .depth_write_enabled = .true,
        .depth_compare = .less,
        .stencil_front = .{},
        .stencil_back = .{},
    };
    z3d.g_pipeline = device.createRenderPipeline(&.{
        .layout = pipeline_layout,
        .vertex = .{ .module = shader_module, .entry_point = wgpu.StringView.fromSlice("vs_main"), .buffer_count = vert_layouts.len, .buffers = &vert_layouts },
        .primitive = .{ .topology = .triangle_list, .cull_mode = .back, .front_face = .ccw },
        .depth_stencil = &depth_stencil,
        .multisample = .{},
        .fragment = &frag,
    });
    // Transparent companion: identical layout/shader/blend, depth-test on but
    // depth-write OFF, so translucent meshes drawn after the opaque batch read
    // the depth buffer (hidden behind walls) without writing it (no self-occlusion
    // between panes). `less_equal` lets intentional coplanar overlays (painted
    // stencil over the face's underlay material) draw on top of the base face.
    // Reuses pipeline_layout/shader_module/frag, which the createRenderPipeline
    // calls retain — both stay valid until this fn's deferred releases fire.
    const depth_stencil_transparent = wgpu.DepthStencilState{
        .format = .depth24_plus,
        .depth_write_enabled = .false,
        .depth_compare = .less_equal,
        .stencil_front = .{},
        .stencil_back = .{},
    };
    z3d.g_pipeline_transparent = device.createRenderPipeline(&.{
        .layout = pipeline_layout,
        .vertex = .{ .module = shader_module, .entry_point = wgpu.StringView.fromSlice("vs_main"), .buffer_count = vert_layouts.len, .buffers = &vert_layouts },
        .primitive = .{ .topology = .triangle_list, .cull_mode = .back, .front_face = .ccw },
        .depth_stencil = &depth_stencil_transparent,
        .multisample = .{},
        .fragment = &frag,
    });

    // ── Skinned pipeline (SKIN-3499): scene3d with a matrix-palette vertex
    //    stage. Same group0/group1 as the standard path plus group2 = the bone
    //    palette; 28-byte skinned vertices at locations 0-2 + 7-8. Opaque,
    //    depth-write on — figures draw with the world, not the glass pass. ──
    const skinned_vert_attrs = [_]wgpu.VertexAttribute{
        .{ .format = .float32x3, .offset = 0, .shader_location = 0 },
        .{ .format = .snorm16x2, .offset = 12, .shader_location = 1 }, // oct normal
        .{ .format = .float16x2, .offset = 16, .shader_location = 2 }, // uv
        .{ .format = .uint8x4, .offset = 20, .shader_location = 7 }, // joints
        .{ .format = .unorm8x4, .offset = 24, .shader_location = 8 }, // weights
    };
    const skinned_vert_layouts = [_]wgpu.VertexBufferLayout{
        .{ .step_mode = .vertex, .array_stride = @sizeOf(z3d.SkinnedVertex), .attribute_count = skinned_vert_attrs.len, .attributes = &skinned_vert_attrs },
        .{ .step_mode = .instance, .array_stride = @sizeOf(z3d.InstanceData), .attribute_count = inst_attrs.len, .attributes = &inst_attrs },
    };
    if (z3d.g_skin_bgl != null) {
        const skin_layouts = [_]?*wgpu.BindGroupLayout{ z3d.g_bind_group_layout.?, z3d.g_tex_bind_group_layout.?, z3d.g_skin_bgl.? };
        const skin_pl = device.createPipelineLayout(&.{
            .bind_group_layout_count = skin_layouts.len,
            .bind_group_layouts = @ptrCast(&skin_layouts),
        });
        const skinned_desc = wgpu.shaderModuleWGSLDescriptor(.{ .label = "render3d_skinned_shader", .code = shaders.scene3d_skinned_wgsl });
        const skinned_module = device.createShaderModule(&skinned_desc);
        if (skin_pl != null and skinned_module != null) {
            const skinned_frag = wgpu.FragmentState{
                .module = skinned_module.?,
                .entry_point = wgpu.StringView.fromSlice("fs_main"),
                .target_count = 1,
                .targets = @ptrCast(&color_target),
            };
            z3d.g_skinned_pipeline = device.createRenderPipeline(&.{
                .layout = skin_pl.?,
                .vertex = .{ .module = skinned_module.?, .entry_point = wgpu.StringView.fromSlice("vs_main"), .buffer_count = skinned_vert_layouts.len, .buffers = &skinned_vert_layouts },
                .primitive = .{ .topology = .triangle_list, .cull_mode = .back, .front_face = .ccw },
                .depth_stencil = &depth_stencil,
                .multisample = .{},
                .fragment = &skinned_frag,
            });
        }
        if (skinned_module) |sm| sm.release();
        if (skin_pl) |spl| spl.release();
    }

    // ── Shadow depth pipeline (renders geometry from a light's POV, depth only) ──
    // Reuses vert_layouts (same vbuf0 verts + vbuf1 packed InstanceData), so the
    // caster instances staged for shadows replay through the exact vertex path. Its
    // own group0 = just the light VP. No fragment / no color target (depth-only).
    const shadow_bgl_entry = wgpu.BindGroupLayoutEntry{
        .binding = 0,
        .visibility = wgpu.ShaderStages.vertex,
        .buffer = .{ .type = .uniform, .has_dynamic_offset = 0, .min_binding_size = 16 * @sizeOf(f32) },
    };
    const shadow_bgl = device.createBindGroupLayout(&.{
        .entry_count = 1,
        .entries = @ptrCast(&shadow_bgl_entry),
    });
    if (shadow_bgl) |sbgl| {
        z3d.g_shadow_pass_bind_group = device.createBindGroup(&.{
            .layout = sbgl,
            .entry_count = 1,
            .entries = @ptrCast(&wgpu.BindGroupEntry{ .binding = 0, .buffer = z3d.g_shadow_vp_buf.?, .offset = 0, .size = 16 * @sizeOf(f32) }),
        });
        const shadow_layouts = [_]?*wgpu.BindGroupLayout{sbgl};
        const shadow_pl = device.createPipelineLayout(&.{
            .bind_group_layout_count = shadow_layouts.len,
            .bind_group_layouts = @ptrCast(&shadow_layouts),
        });
        const shadow_desc = wgpu.shaderModuleWGSLDescriptor(.{ .label = "shadow_depth_shader", .code = shaders.shadow_depth_wgsl });
        const shadow_module = device.createShaderModule(&shadow_desc);
        const shadow_depth_stencil = wgpu.DepthStencilState{
            .format = .depth32_float,
            .depth_write_enabled = .true,
            .depth_compare = .less,
            .stencil_front = .{},
            .stencil_back = .{},
        };
        if (shadow_pl != null and shadow_module != null) {
            z3d.g_shadow_pipeline = device.createRenderPipeline(&.{
                .layout = shadow_pl.?,
                .vertex = .{ .module = shadow_module.?, .entry_point = wgpu.StringView.fromSlice("vs_main"), .buffer_count = vert_layouts.len, .buffers = &vert_layouts },
                .primitive = .{ .topology = .triangle_list, .cull_mode = .back, .front_face = .ccw },
                .depth_stencil = &shadow_depth_stencil,
                .multisample = .{},
            });
        }
        // Skinned shadow companion (SKIN-3499): group(0) = the light VP,
        // group(1) = the bone palette; skinned vertices + the same packed
        // instances. Figures keep casting shadows on the palette path.
        if (z3d.g_skin_bgl != null) {
            const sshadow_layouts = [_]?*wgpu.BindGroupLayout{ sbgl, z3d.g_skin_bgl.? };
            const sshadow_pl = device.createPipelineLayout(&.{
                .bind_group_layout_count = sshadow_layouts.len,
                .bind_group_layouts = @ptrCast(&sshadow_layouts),
            });
            const sshadow_desc = wgpu.shaderModuleWGSLDescriptor(.{ .label = "shadow_depth_skinned_shader", .code = shaders.shadow_depth_skinned_wgsl });
            const sshadow_module = device.createShaderModule(&sshadow_desc);
            if (sshadow_pl != null and sshadow_module != null) {
                z3d.g_skinned_shadow_pipeline = device.createRenderPipeline(&.{
                    .layout = sshadow_pl.?,
                    .vertex = .{ .module = sshadow_module.?, .entry_point = wgpu.StringView.fromSlice("vs_main"), .buffer_count = skinned_vert_layouts.len, .buffers = &skinned_vert_layouts },
                    .primitive = .{ .topology = .triangle_list, .cull_mode = .back, .front_face = .ccw },
                    .depth_stencil = &shadow_depth_stencil,
                    .multisample = .{},
                });
            }
            if (sshadow_module) |sm| sm.release();
            if (sshadow_pl) |spl| spl.release();
        }
        if (shadow_module) |sm| sm.release();
        if (shadow_pl) |spl| spl.release();
        sbgl.release();
    }
    // Grass companion: same layout/vertex/blend as g_pipeline, depth-write ON (the
    // blade is alpha-TESTED via discard in the shader, so it's opaque), only the
    // module differs — wind + procedural wisp cutout + root→tip gradient. The
    // createRenderPipeline call retains the module, so we release it right after.
    {
        const grass_desc = wgpu.shaderModuleWGSLDescriptor(.{ .label = "render3d_grass_shader", .code = shaders.grass_wgsl });
        if (device.createShaderModule(&grass_desc)) |grass_module| {
            const grass_frag = wgpu.FragmentState{
                .module = grass_module,
                .entry_point = wgpu.StringView.fromSlice("fs_main"),
                .target_count = 1,
                .targets = @ptrCast(&color_target),
            };
            z3d.g_grass_pipeline = device.createRenderPipeline(&.{
                .layout = pipeline_layout,
                .vertex = .{ .module = grass_module, .entry_point = wgpu.StringView.fromSlice("vs_main"), .buffer_count = slim_vert_layouts.len, .buffers = &slim_vert_layouts },
                .primitive = .{ .topology = .triangle_list, .cull_mode = .back, .front_face = .ccw },
                .depth_stencil = &depth_stencil,
                .multisample = .{},
                .fragment = &grass_frag,
            });
            grass_module.release();
        }
    }
    // Water companion: same layout/vertex/blend, depth-write ON (alpha-hashed via
    // discard → opaque), cull OFF so wave troughs/edges never drop out. Only the
    // module differs — FBM waves + deep/shallow/foam/Bayer-dither.
    {
        const water_desc = wgpu.shaderModuleWGSLDescriptor(.{ .label = "render3d_water_shader", .code = shaders.water_wgsl });
        if (device.createShaderModule(&water_desc)) |water_module| {
            const water_frag = wgpu.FragmentState{
                .module = water_module,
                .entry_point = wgpu.StringView.fromSlice("fs_main"),
                .target_count = 1,
                .targets = @ptrCast(&color_target),
            };
            z3d.g_water_pipeline = device.createRenderPipeline(&.{
                .layout = pipeline_layout,
                .vertex = .{ .module = water_module, .entry_point = wgpu.StringView.fromSlice("vs_main"), .buffer_count = vert_layouts.len, .buffers = &vert_layouts },
                .primitive = .{ .topology = .triangle_list, .cull_mode = .none, .front_face = .ccw },
                .depth_stencil = &depth_stencil,
                .multisample = .{},
                .fragment = &water_frag,
            });
            water_module.release();
        }
    }
    // Frond companion: same layout/vertex/blend, depth-write ON (alpha-tested via
    // discard → opaque), cull OFF so a wind-bent frond reads from both faces. Only
    // the module differs — wind sway + palm/leaf cutout + green gradient.
    {
        const frond_desc = wgpu.shaderModuleWGSLDescriptor(.{ .label = "render3d_frond_shader", .code = shaders.frond_wgsl });
        if (device.createShaderModule(&frond_desc)) |frond_module| {
            const frond_frag = wgpu.FragmentState{
                .module = frond_module,
                .entry_point = wgpu.StringView.fromSlice("fs_main"),
                .target_count = 1,
                .targets = @ptrCast(&color_target),
            };
            z3d.g_frond_pipeline = device.createRenderPipeline(&.{
                .layout = pipeline_layout,
                .vertex = .{ .module = frond_module, .entry_point = wgpu.StringView.fromSlice("vs_main"), .buffer_count = slim_vert_layouts.len, .buffers = &slim_vert_layouts },
                .primitive = .{ .topology = .triangle_list, .cull_mode = .none, .front_face = .ccw },
                .depth_stencil = &depth_stencil,
                .multisample = .{},
                .fragment = &frond_frag,
            });
            frond_module.release();
        }
    }
    z3d.g_sampler = device.createSampler(&.{
        .address_mode_u = .clamp_to_edge,
        .address_mode_v = .clamp_to_edge,
        .mag_filter = .linear,
        .min_filter = .linear,
    });

    // ── Skybox pipeline ──
    // One uniform buffer (group 0), a fullscreen triangle generated from
    // @builtin(vertex_index) (no vertex buffer), no culling, and depth
    // compare = always with depth-write off so the sky never occludes the
    // meshes drawn after it. Same rgba8 color target as the mesh pipeline.
    const sky_desc = wgpu.shaderModuleWGSLDescriptor(.{ .label = "skybox_shader", .code = shaders.skybox_wgsl });
    const sky_shader = device.createShaderModule(&sky_desc);
    if (sky_shader) |sky_mod| {
        defer sky_mod.release();
        z3d.g_sky_uniform_buffer = device.createBuffer(&.{
            .label = wgpu.StringView.fromSlice("skybox_uniforms"),
            .size = @sizeOf(z3d.SkyUniforms),
            .usage = wgpu.BufferUsages.uniform | wgpu.BufferUsages.copy_dst,
            .mapped_at_creation = 0,
        });
        z3d.g_sky_bind_group_layout = device.createBindGroupLayout(&.{
            .entry_count = 1,
            .entries = @ptrCast(&wgpu.BindGroupLayoutEntry{
                .binding = 0,
                .visibility = wgpu.ShaderStages.vertex | wgpu.ShaderStages.fragment,
                .buffer = .{ .type = .uniform, .has_dynamic_offset = 0, .min_binding_size = @sizeOf(z3d.SkyUniforms) },
            }),
        });
        if (z3d.g_sky_bind_group_layout != null and z3d.g_sky_uniform_buffer != null) {
            z3d.g_sky_bind_group = device.createBindGroup(&.{
                .layout = z3d.g_sky_bind_group_layout.?,
                .entry_count = 1,
                .entries = @ptrCast(&wgpu.BindGroupEntry{
                    .binding = 0,
                    .buffer = z3d.g_sky_uniform_buffer.?,
                    .offset = 0,
                    .size = @sizeOf(z3d.SkyUniforms),
                }),
            });
            const sky_layout = [_]?*wgpu.BindGroupLayout{z3d.g_sky_bind_group_layout.?};
            const sky_pipeline_layout = device.createPipelineLayout(&.{
                .bind_group_layout_count = sky_layout.len,
                .bind_group_layouts = @ptrCast(&sky_layout),
            });
            if (sky_pipeline_layout) |spl| {
                defer spl.release();
                const sky_color_target = wgpu.ColorTargetState{
                    .format = .rgba8_unorm,
                    .blend = &wgpu.BlendState.premultiplied_alpha_blending,
                    .write_mask = wgpu.ColorWriteMasks.all,
                };
                const sky_frag = wgpu.FragmentState{
                    .module = sky_mod,
                    .entry_point = wgpu.StringView.fromSlice("sky_fs"),
                    .target_count = 1,
                    .targets = @ptrCast(&sky_color_target),
                };
                const sky_depth = wgpu.DepthStencilState{
                    .format = .depth24_plus,
                    .depth_write_enabled = .false,
                    .depth_compare = .always,
                    .stencil_front = .{},
                    .stencil_back = .{},
                };
                z3d.g_sky_pipeline = device.createRenderPipeline(&.{
                    .layout = spl,
                    .vertex = .{ .module = sky_mod, .entry_point = wgpu.StringView.fromSlice("sky_vs"), .buffer_count = 0 },
                    .primitive = .{ .topology = .triangle_list, .cull_mode = .none, .front_face = .ccw },
                    .depth_stencil = &sky_depth,
                    .multisample = .{},
                    .fragment = &sky_frag,
                });
            }
        }
    }

    z3d.g_initialized = z3d.g_pipeline != null;
}

pub fn getTexBindGroupLayout() ?*wgpu.BindGroupLayout {
    return z3d.g_tex_bind_group_layout;
}

/// The NEAREST, non-filtering diffuse sampler. Any bind group built against
/// getTexBindGroupLayout() MUST bind this (the layout is .non_filtering, so a
/// filtering sampler is a validation error — req_1321). StaticSurface-textured
/// meshes use it so the paint atlas samples crisply with no cross-slot seams.
pub fn getDiffuseSampler() ?*wgpu.Sampler {
    return z3d.g_diffuse_sampler;
}

pub fn getUvSamplingUniform(finite_atlas: bool) ?*wgpu.Buffer {
    return if (finite_atlas) z3d.g_uv_finite_uniform else z3d.g_uv_unbounded_uniform;
}

pub fn deinit() void {
    z3d.g_historical_preview.deinit();
    z3d.g_historical_preview_saved_orbit = null;
    // Face analysis executes code owned by this replaceable Scene3D module.
    // Join both workers before any module teardown can unmap that code.
    z3d.g_face_table_worker.stopCaptured();
    mesh_face_table_package.stopWorkerCaptured();
    z3d.g_authorized_model_write_receipt = 0;
    z3d.g_model_write_leases.reset();
    z3d.g_model_adoption_receipts.reset();
    // Release every pool slot's resources.
    for (0..z3d.MAX_RT_POOL) |i| {
        const slot = &z3d.g_rt_pool[i];
        if (slot.composite_bind_group) |bg| bg.release();
        if (slot.depth_view) |v| v.release();
        if (slot.depth_texture) |t| t.destroy();
        if (slot.color_view) |v| v.release();
        if (slot.color_texture) |t| t.destroy();
        slot.* = .{};
    }
    z3d.g_rt_cursor = 0;
    for (&z3d.g_tex_cache) |*e| z3d.dropTexEntry(e);
    if (z3d.g_sampler) |s| s.release();
    if (z3d.g_default_tex_bind_group) |bg| bg.release();
    if (z3d.g_default_tex_view) |v| v.release();
    if (z3d.g_default_tex) |t| t.destroy();
    if (z3d.g_glass_aux_tex_bind_group) |bg| bg.release();
    if (z3d.g_glass_aux_tex_view) |v| v.release();
    if (z3d.g_glass_aux_tex) |t| t.destroy();
    if (z3d.g_diffuse_sampler) |s| s.release();
    if (z3d.g_uv_unbounded_uniform) |b| b.release();
    if (z3d.g_uv_finite_uniform) |b| b.release();
    if (z3d.g_tex_bind_group_layout) |l| l.release();
    if (z3d.g_bind_group) |bg| bg.release();
    if (z3d.g_bind_group_layout) |l| l.release();
    if (z3d.g_uniform_buffer) |b| b.release();
    if (z3d.g_lights_buf) |b| b.release();
    if (z3d.g_shadow_view) |v| v.release();
    if (z3d.g_shadow_tex) |t| t.release();
    if (z3d.g_shadow_sampler) |s| s.release();
    if (z3d.g_shadow_uniform_buf) |b| b.release();
    if (z3d.g_shadow_vp_buf) |b| b.release();
    if (z3d.g_shadow_inst_buf) |b| b.release();
    if (z3d.g_shadow_pipeline) |p| p.release();
    if (z3d.g_shadow_pass_bind_group) |bg| bg.release();
    if (z3d.g_instance_buf) |b| b.release();
    if (z3d.g_slim_inst_buf) |b| b.release();
    if (z3d.g_slim_static_buf) |b| b.release();
    if (z3d.g_ground_inst_buf) |b| b.release();
    if (z3d.g_ground_grid_vbuf) |b| b.release();
    for (0..z3d.GROUND_POOL) |i| {
        if (z3d.g_ground_data_bg[i]) |bg| bg.release();
        if (z3d.g_ground_data_buf[i]) |b| b.release();
        z3d.g_ground_data_bg[i] = null;
        z3d.g_ground_data_buf[i] = null;
    }
    if (z3d.g_ground_pipeline) |p| p.release();
    // Live material regions: GPU pool + per-region index buffers; the CPU-side
    // bindings (indices/data/formula) survive so a re-init redraws them.
    if (z3d.g_region_inst_buf) |b| b.release();
    z3d.g_region_inst_buf = null;
    for (0..z3d.REGION_POOL) |i| {
        if (z3d.g_region_data_bg[i]) |bg| bg.release();
        if (z3d.g_region_data_buf[i]) |b| b.release();
        z3d.g_region_data_bg[i] = null;
        z3d.g_region_data_buf[i] = null;
        if (z3d.g_regions[i].ibuf) |b| b.release();
        z3d.g_regions[i].ibuf = null;
        z3d.g_regions[i].ibuf_count = 0;
        z3d.g_regions[i].ibuf_dirty = true;
        z3d.g_regions[i].data_dirty = true;
    }
    if (z3d.g_region_pipeline) |p| p.release();
    z3d.g_region_pipeline = null;
    z3d.g_region_built_hash = 0;
    if (z3d.g_ground_bgl) |l| l.release();
    z3d.g_ground_pipeline = null;
    z3d.g_ground_bgl = null;
    z3d.g_ground_grid_vbuf = null;
    z3d.g_ground_grid_vert_count = 0;
    if (z3d.g_vertex_buffer) |b| b.release();
    if (z3d.g_pipeline) |p| p.release();
    if (z3d.g_grass_pipeline) |p| p.release();
    if (z3d.g_water_pipeline) |p| p.release();
    if (z3d.g_frond_pipeline) |p| p.release();
    if (z3d.g_sky_bind_group) |bg| bg.release();
    if (z3d.g_sky_bind_group_layout) |l| l.release();
    if (z3d.g_sky_uniform_buffer) |b| b.release();
    if (z3d.g_sky_pipeline) |p| p.release();
    z3d.g_initialized = false;
}

/// Reset the per-frame RT cursor so the next frame reuses pool slots from
/// the top. Slots themselves stay alive across frames — only resized when
/// a tile changes dimensions. Must be called AFTER images.drawAll() so the
/// previous frame's quads have all been sampled.
pub fn frameCleanup() void {
    z3d.g_rt_cursor = 0;
}

/// Drop every retained-geometry registration so the next bundle re-interns
/// from scratch. The dev hot-reload path calls this while tearing down the
/// tree: the JS world re-evals in a fresh V8 context, so its ship-once-per-key
/// set (runtime/geometries/intern.ts) resets and every first-per-key mesh
/// re-ships its verts. The HOST intern caches, by contrast, are append-only
/// bump allocators that NEVER evict (g_retained_top / g_static_inst_top) and
/// persist across the reload — so without this reset they accumulate dead
/// geometry from every prior map version across edit→reload cycles until they
/// hit GEO_CACHE_SIZE / MAX_RETAINED_VERTS. Past that point internGeometry
/// returns null and pass 1 SILENTLY DROPS the mesh, and because the shared Box
/// geometry (the grid AND every building bucket) interns late in the fill
/// order, every building + the grid vanish while props survive (req_0725/0727,
/// reproduced as "turn the camera after a reload and the world disappears").
/// Resetting the bump cursors here makes the re-shipped verts repopulate a
/// clean cache, so geometry survives the reload exactly like a fresh boot.
/// The GPU buffer memory is reused in place (cursors rewind to 0); no GPU
/// resource is freed. The per-frame dynamic instance staging buffer and the
/// content-hashed FIFO texture cache are NOT touched — they self-evict and
/// never overflow-to-drop.
pub fn resetForReload() void {
    z3d.g_geo_cache_len = 0;
    z3d.g_retained_top = 0;
    for (&z3d.g_geo_cache) |*e| e.* = .{};
    z3d.g_static_inst_cache_len = 0;
    z3d.g_static_inst_top = 0;
    for (&z3d.g_static_inst_cache) |*e| e.* = .{};
    z3d.g_slim_static_cache_len = 0;
    z3d.g_slim_static_top = 0;
    for (&z3d.g_slim_static_cache) |*e| e.* = .{};
    z3d.g_dyn_len = 0;
    z3d.g_dyn_bump_verts = 0;
    z3d.g_dyn_warned = false;
    z3d.g_static_retain_warned = false;
    z3d.g_frame_pool_warned = false;
    for (&z3d.g_dyn_slots) |*s| s.* = .{};
    // Ground D buffers persist across reload just like retained geometry. New
    // runtime allocations may reuse an old pointer/version/length tuple, so the
    // upload memo must not let stale material or height data survive remount.
    z3d.g_ground_data_ptr = @splat(0);
    z3d.g_ground_data_version = @splat(0);
    z3d.g_ground_data_len = @splat(0);
    // The geo cache (above) was cleared, so any stashed-but-not-yet-interned host
    // mesh would re-intern fine — but free the host copies so a reload doesn't leak
    // them, and so a re-drop re-parses cleanly.
    for (&z3d.g_host_stash) |*s| {
        if (s.verts) |old| std.heap.c_allocator.free(old);
        s.* = .{};
    }
    // The texture hash memo keys on buffer POINTERS; a reload frees + recycles
    // those addresses, so a stale (ptr,len) could collide with a new buffer. Clear
    // it (the fingerprint guards the rare same-address+len case, but a clean memo
    // is free and removes all doubt — every texture just re-walks once).
    for (&z3d.g_tex_hash_memo) |*e| e.* = .{};
    // The mesh-editor SESSION survives the reload (req_2913 — this line was the bug
    // that broke the req_2898 resume: clearActiveEditMesh() here wiped g_edit_key,
    // so the remounted viewer's session readback came back empty and it fell back
    // to re-loading seed geometry over your edits). The session's CPU copy
    // (g_edit_verts, duped by setPaintTarget) is the durable truth: the GPU intern
    // + the consumed stash copy died with the cache clears above, so RE-STASH it —
    // the first post-reload draw re-interns it into the fresh cache exactly like a
    // fresh load. Selection (mesh_edit), journal, paint atlas, and orbit were never
    // cleared here and keep surviving untouched.
    if (z3d.g_edit_key) |key| {
        if (z3d.g_edit_verts) |verts| _ = z3d.stashHostMesh(key, verts, z3d.g_edit_count);
    }
}

/// Acquire the next RT slot for this frame. Returns null on pool exhaustion
/// or device failure. Slots are reused across frames; resized lazily when
/// a tile's dimensions change.
pub fn acquireRt(w: u32, h: u32) ?*z3d.Rt {
    if (w == 0 or h == 0) return null;
    if (z3d.g_rt_cursor >= z3d.MAX_RT_POOL) {
        if (!z3d.g_rt_pool_warned) {
            z3d.g_rt_pool_warned = true;
            log.print("[r3d-rt] RT POOL EXHAUSTED: >{d} Scene3D views in one frame — views past the cap (incl. the build pane if painted last) get no render target and stay blank.\n", .{z3d.MAX_RT_POOL});
        }
        return null;
    }
    const slot = &z3d.g_rt_pool[z3d.g_rt_cursor];
    z3d.g_rt_cursor += 1;
    const rt = z3d.ensureRt(slot, w, h);
    if (rt == null and !z3d.g_rt_alloc_warned) {
        z3d.g_rt_alloc_warned = true;
        log.print("[r3d-rt] RT TEXTURE ALLOC FAILED at {d}x{d} — GPU could not create the render target (out of memory from this map's capture surfaces/geometry?). That view stays blank.\n", .{ w, h });
    }
    return rt;
}

/// (Re)build a render-target slot at the given size — shared by the per-frame
/// pool (acquireRt) and detached targets (WORLDWIN-0611). No-op when the slot
/// already matches.
pub fn ensureRt(slot: *z3d.Rt, w: u32, h: u32) ?*z3d.Rt {
    if (slot.width == w and slot.height == h and slot.color_view != null) return slot;

    const device = core.getDevice() orelse return null;

    // Drop the slot's previous resources. Frame loop is serial — by the
    // time we recycle a slot across frames, the prior frame's quads have
    // already been drawn and the bind group is no longer in flight.
    if (slot.composite_bind_group) |bg| bg.release();
    if (slot.depth_view) |v| v.release();
    if (slot.depth_texture) |t| t.destroy();
    if (slot.color_view) |v| v.release();
    if (slot.color_texture) |t| t.destroy();
    slot.* = .{};

    slot.color_texture = device.createTexture(&.{
        .label = wgpu.StringView.fromSlice("r3d_color"),
        .size = .{ .width = w, .height = h, .depth_or_array_layers = 1 },
        .mip_level_count = 1,
        .sample_count = 1,
        .dimension = .@"2d",
        .format = .rgba8_unorm,
        .usage = wgpu.TextureUsages.render_attachment | wgpu.TextureUsages.texture_binding | wgpu.TextureUsages.copy_src,
    }) orelse return null;
    slot.color_view = slot.color_texture.?.createView(&.{
        .format = .rgba8_unorm,
        .dimension = .@"2d",
        .base_mip_level = 0,
        .mip_level_count = 1,
        .base_array_layer = 0,
        .array_layer_count = 1,
        .aspect = .all,
    }) orelse return null;
    slot.depth_texture = device.createTexture(&.{
        .label = wgpu.StringView.fromSlice("r3d_depth"),
        .size = .{ .width = w, .height = h, .depth_or_array_layers = 1 },
        .mip_level_count = 1,
        .sample_count = 1,
        .dimension = .@"2d",
        .format = .depth24_plus,
        .usage = wgpu.TextureUsages.render_attachment,
    }) orelse return null;
    slot.depth_view = slot.depth_texture.?.createView(&.{
        .format = .depth24_plus,
        .dimension = .@"2d",
        .base_mip_level = 0,
        .mip_level_count = 1,
        .base_array_layer = 0,
        .array_layer_count = 1,
        .aspect = .all,
    }) orelse return null;
    if (z3d.g_sampler) |sampler| slot.composite_bind_group = core.createImageBindGroup(slot.color_view.?, sampler);
    slot.width = w;
    slot.height = h;
    return slot;
}

pub fn max3(a: f32, b: f32, c: f32) f32 {
    return @max(a, @max(b, c));
}

pub fn estimateMeshRadius(node: *const Node) f32 {
    const sx = @abs(node.scene3d_scale_x);
    const sy = @abs(node.scene3d_scale_y);
    const sz = @abs(node.scene3d_scale_z);
    // The generator ships its own unscaled bounds — cull off that × max scale. No
    // per-shape switch; this is what lets the framework cull a shape it knows
    // nothing about. A node without bounds (broken legacy mesh) culls as ~unit.
    if (node.scene3d_bounds_radius > 0) {
        return node.scene3d_bounds_radius * z3d.max3(sx, sy, sz);
    }
    return z3d.max3(sx, sy, sz);
}
