//! quadify_glass.zig — split verbatim from framework/gpu/3d.zig (req_4375).
//! Generated by _tool/split3d.zig — edit 3d.zig's successor here, regenerate only from the manifest.
//! Cross-file references are qualified through the orchestrator (`z3d`).

const std = @import("std");
const builtin = @import("builtin");
const log = @import("../../diag/log.zig");
const wgpu = @import("wgpu");
const bu = @import("../buffer_upload.zig");
const shaders = @import("../shaders.zig");
const terrain_grid = @import("../terrain_grid.zig");
const core = @import("../../dev_modules/gpu_api.zig");
const capture = @import("../capture.zig");
const build_options = @import("build_options");
const math = @import("../../math/root.zig");
const layout = @import("../../layout.zig");
const effect_assemble = @import("../effect_assemble.zig");
const compile_progress = @import("../compile_progress.zig");
const static_instance_policy = @import("../static_instance_policy.zig");
const model_paint = @import("../model_paint.zig");
const gizmo_axis_map = @import("../gizmo_axis_map.zig");
const effects_ctx = @import("../effects_ctx.zig");
const paint_islands_mod = @import("../paint_islands.zig");
const paint_program = @import("../paint_program.zig");
const model_source = @import("../model_source.zig");
const meshdoc_format = @import("../meshdoc_format.zig");
const mesh_audit = @import("../mesh_audit.zig");
const mesh_face_table = @import("../mesh_face_table.zig");
const mesh_face_diff = @import("../mesh_face_diff.zig");
const mesh_face_field_candidate = @import("../mesh_face_field_candidate.zig");
const mesh_face_table_package = @import("../mesh_face_table_package.zig");
const mesh_face_table_worker = @import("../mesh_face_table_worker.zig");
const historical_preview = @import("../historical_preview.zig");
const mesh_edit = @import("../mesh_edit.zig");
const mesh_semantics = @import("../mesh_semantics.zig");
const mesh_semantic_restore = @import("../mesh_semantic_restore.zig");
const mesh_edge_semantics = @import("../mesh_edge_semantics.zig");
const indexed_edit_mesh = @import("../indexed_edit_mesh.zig");
const character_topology_promotion = @import("../character_topology_promotion.zig");
const mesh_journal_log = @import("../mesh_journal_log.zig");
const model_write_lease = @import("../model_write_lease.zig");
const model_adoption_receipt = @import("../model_adoption_receipt.zig");
const model_adoption_finalize = @import("../model_adoption_finalize.zig");
const path_array = @import("../path_array.zig");
const path_plane = @import("../path_plane.zig");
const stage_scale = @import("../stage_scale.zig");
const pack = @import("../pack.zig");
const stable_geometry_slot = @import("../stable_geometry_slot.zig");
const character_rig_session = @import("../../skeleton/character_rig_session.zig");
const character_skin_binding = @import("../../skeleton/skin_binding.zig");
const character_specimen = @import("../character_specimen.zig");
const mouse_state = @import("../../state/mouse_state.zig");
const Node = layout.Node;

const z3d = @import("3d.zig");

// ── Whole-topology triangle → quad dry-run session ────────────────────────────
// The popup owns only phase/evaluation controls. The captured base, exact maximum
// matching, live authored-edge preview, cancel restore, and one-entry commit stay
// host-native so a dry run can never leak into the durable model.
pub const QuadifySession = struct {
    base_mesh: indexed_edit_mesh.Mesh,
    guard: z3d.ResidentMetadataGuard,
    base_groups: []u32,
    base_parts: ?[]u32,
    base_materials: []u32,
    base_selection: []bool,
    opaque_mask: []bool,
    glass_mask: []bool,
    base_paint_layout_stale: bool,
    snap: ?z3d.JournalEntry,
    last_stats: indexed_edit_mesh.QuadifyStats = .{},
    last_evaluation: indexed_edit_mesh.QuadEvaluation = .balanced,
    last_preview_ok: bool = false,
};

pub const QuadifyBeginInfo = struct {
    resident_triangles: u32,
};

pub const QuadifyEndInfo = struct {
    ok: bool,
    changed: u32,
};

pub fn quadifyRelease(session: *z3d.QuadifySession) void {
    session.base_mesh.deinit();
    session.guard.deinit();
    std.heap.c_allocator.free(session.base_groups);
    if (session.base_parts) |parts| std.heap.c_allocator.free(parts);
    std.heap.c_allocator.free(session.base_materials);
    std.heap.c_allocator.free(session.base_selection);
    std.heap.c_allocator.free(session.opaque_mask);
    std.heap.c_allocator.free(session.glass_mask);
    z3d.journalDiscard(&session.snap);
}

pub fn quadifyDrop() void {
    var session = z3d.g_quadify orelse return;
    z3d.quadifyRelease(&session);
    z3d.g_quadify = null;
}

pub fn quadifyRestoreBase(session: *const z3d.QuadifySession, restore_selection: bool) bool {
    var restored = session.base_mesh.clone() catch return false;
    mesh_edit.clearSelection();
    model_source.setFaceGroups(session.base_groups);
    mesh_edit.faceGroupsChanged();
    z3d.clearIndexedEditMesh();
    z3d.g_indexed_edit_mesh = restored;
    restored = .{ .allocator = std.heap.c_allocator };
    z3d.g_paint_layout_stale = session.base_paint_layout_stale;
    mesh_edit.setMode(.face);
    if (restore_selection) _ = mesh_edit.selectFacesByTriangleMask(session.base_selection);
    return true;
}

pub fn quadifyInstallPreview(session: *const z3d.QuadifySession, preview: *indexed_edit_mesh.Mesh) bool {
    const tri_count = z3d.g_edit_count / 3;
    const verts = z3d.g_edit_verts orelse return false;
    const groups = std.heap.c_allocator.alloc(u32, tri_count) catch return false;
    defer std.heap.c_allocator.free(groups);
    const parts = std.heap.c_allocator.alloc(u32, tri_count) catch return false;
    defer std.heap.c_allocator.free(parts);
    const materials = std.heap.c_allocator.alloc(u32, tri_count) catch return false;
    defer std.heap.c_allocator.free(materials);
    if (!preview.writeResidentMetadata(groups, parts, materials)) return false;
    if (session.base_parts) |base_parts| {
        if (!std.mem.eql(u32, base_parts, parts)) return false;
    } else {
        for (parts) |part| if (part != indexed_edit_mesh.NO_PART) return false;
    }
    if (!std.mem.eql(u32, session.base_materials, materials) or
        !preview.residentRenderChannelsMatch(verts, tri_count))
    {
        return false;
    }

    // The render triangles never move. Only the authored grouping changes, which
    // makes the real topology overlay hide each proposed source diagonal. This is
    // a reversible visual preview: no journal event and no paint-layout invalidation.
    mesh_edit.clearSelection();
    model_source.setFaceGroups(groups);
    mesh_edit.faceGroupsChanged();
    z3d.clearIndexedEditMesh();
    z3d.g_indexed_edit_mesh = preview.*;
    preview.* = .{ .allocator = std.heap.c_allocator };
    z3d.g_paint_layout_stale = session.base_paint_layout_stale;
    mesh_edit.setMode(.face);
    return true;
}

/// Capture the complete live model as the dry-run base. No triangle is selected or
/// changed here; the cart can paint its scanning card before requesting evaluation 0.
pub fn meshQuadifyBegin() ?z3d.QuadifyBeginInfo {
    if (z3d.g_lc != null or z3d.g_bevel != null or z3d.g_quadify != null) return null;
    if (!model_paint.hasTarget() or mesh_edit.mode() != .face) return null;
    const verts = z3d.g_edit_verts orelse return null;
    const tri_count = z3d.g_edit_count / 3;
    if (tri_count < 2 or model_source.faceGroups() == null) return null;

    const base_groups = z3d.captureFaceGroups() orelse return null;
    var adopted = false;
    defer if (!adopted) std.heap.c_allocator.free(base_groups);
    const base_parts = z3d.capturePartOfFaces();
    defer if (!adopted) if (base_parts) |parts| std.heap.c_allocator.free(parts);
    const base_materials = z3d.captureFaceMaterials(tri_count) orelse return null;
    defer if (!adopted) std.heap.c_allocator.free(base_materials);
    const base_selection = std.heap.c_allocator.alloc(bool, tri_count) catch return null;
    defer if (!adopted) std.heap.c_allocator.free(base_selection);
    _ = mesh_edit.buildDeleteMask(base_selection);
    const base_colors = z3d.collectCurrentFaceColors() orelse return null;
    defer std.heap.c_allocator.free(base_colors);
    if (base_colors.len != @as(usize, tri_count) * 4) return null;
    const opaque_mask = std.heap.c_allocator.alloc(bool, tri_count) catch return null;
    defer if (!adopted) std.heap.c_allocator.free(opaque_mask);
    const glass_mask = std.heap.c_allocator.alloc(bool, tri_count) catch return null;
    defer if (!adopted) std.heap.c_allocator.free(glass_mask);
    for (opaque_mask, glass_mask, 0..) |*opaque_slot, *glass_slot, triangle| {
        const is_glass = model_paint.isGlassAlpha(base_colors[triangle * 4 + 3]);
        opaque_slot.* = !is_glass;
        glass_slot.* = is_glass;
    }

    var base_mesh = z3d.cloneIndexedEditMeshOrImport(
        verts,
        tri_count,
        base_groups,
        base_parts,
        model_source.faceMaterials(),
    ) orelse return null;
    defer if (!adopted) base_mesh.deinit();
    var guard = z3d.ResidentMetadataGuard.capture() orelse return null;
    defer if (!adopted) guard.deinit();
    const snap = z3d.journalSnapshotCurrent("tris to quads") orelse return null;
    defer if (!adopted) {
        var pending: ?z3d.JournalEntry = snap;
        z3d.journalDiscard(&pending);
    };

    z3d.g_quadify = .{
        .base_mesh = base_mesh,
        .guard = guard,
        .base_groups = base_groups,
        .base_parts = base_parts,
        .base_materials = base_materials,
        .base_selection = base_selection,
        .opaque_mask = opaque_mask,
        .glass_mask = glass_mask,
        .base_paint_layout_stale = z3d.g_paint_layout_stale,
        .snap = snap,
    };
    adopted = true;
    return .{ .resident_triangles = tri_count };
}

/// Evaluate one deterministic ordering, always returning an exact maximum-cardinality
/// plan. Re-evaluation starts from the captured base, never from the prior preview.
pub fn meshQuadifyPreview(evaluation_index: u32) ?indexed_edit_mesh.QuadifyStats {
    const session: *z3d.QuadifySession = if (z3d.g_quadify) |*active| active else return null;
    session.last_preview_ok = false;
    const evaluation = indexed_edit_mesh.QuadEvaluation.fromIndex(evaluation_index);
    var preview = session.base_mesh.clone() catch return null;
    defer preview.deinit();
    const opaque_stats = preview.quadifySelectedWithEvaluation(session.opaque_mask, evaluation) catch return null;
    const glass_stats = preview.quadifySelectedWithEvaluation(session.glass_mask, evaluation) catch return null;
    const quads = opaque_stats.quads + glass_stats.quads;
    const combined = indexed_edit_mesh.QuadifyStats{
        .authored_faces_before = opaque_stats.authored_faces_before,
        .authored_faces_after = opaque_stats.authored_faces_before - quads,
        .triangle_faces = opaque_stats.triangle_faces + glass_stats.triangle_faces,
        .candidate_pairs = opaque_stats.candidate_pairs + glass_stats.candidate_pairs,
        .ambiguous_triangles = opaque_stats.ambiguous_triangles + glass_stats.ambiguous_triangles,
        .quads = quads,
        .plan_signature = (opaque_stats.plan_signature *% 16777619) ^ glass_stats.plan_signature,
    };
    if (quads > 0) {
        if (!z3d.quadifyInstallPreview(session, &preview)) return null;
    } else if (!z3d.quadifyRestoreBase(session, false)) {
        return null;
    }
    session.last_stats = combined;
    session.last_evaluation = evaluation;
    session.last_preview_ok = true;
    return combined;
}

/// Apply keeps the current preview as one `tris to quads` undo entry. Cancel restores
/// the exact authored groups and face selection captured before the scan.
pub fn meshQuadifyEnd(commit: bool) z3d.QuadifyEndInfo {
    var session = z3d.g_quadify orelse return .{ .ok = false, .changed = 0 };
    z3d.g_quadify = null;
    var ok = true;
    var changed: u32 = 0;
    if (commit and session.last_preview_ok and session.last_stats.quads > 0) {
        const tri_count = z3d.g_edit_count / 3;
        const verts = z3d.g_edit_verts orelse {
            z3d.quadifyRelease(&session);
            return .{ .ok = false, .changed = 0 };
        };
        const groups = z3d.captureFaceGroups() orelse {
            z3d.quadifyRelease(&session);
            return .{ .ok = false, .changed = 0 };
        };
        defer std.heap.c_allocator.free(groups);
        const indexed = if (z3d.g_indexed_edit_mesh) |*mesh| mesh else {
            z3d.quadifyRelease(&session);
            return .{ .ok = false, .changed = 0 };
        };
        const valid = session.guard.matchesGroupOnly(groups) and
            indexed.residentMetadataMatches(
                tri_count,
                groups,
                session.base_parts,
                session.base_materials,
            ) and indexed.residentRenderChannelsMatch(verts, tri_count);
        if (valid) {
            changed = session.last_stats.quads;
            z3d.journalCommit(&session.snap);
            mesh_edit.clearSelection();
            mesh_edit.setMode(.face);
        } else {
            ok = z3d.quadifyRestoreBase(&session, true);
        }
    } else {
        ok = z3d.quadifyRestoreBase(&session, true);
    }
    z3d.quadifyRelease(&session);
    return .{ .ok = ok, .changed = changed };
}

/// Legacy automation convenience: run the new whole-topology session through its
/// balanced preview and immediately apply. The interactive editor never uses this
/// shortcut; it always presents the dry-run confirmation.
pub fn meshTrianglesToQuads() u32 {
    _ = z3d.meshQuadifyBegin() orelse return 0;
    const stats = z3d.meshQuadifyPreview(0) orelse {
        _ = z3d.meshQuadifyEnd(false);
        return 0;
    };
    if (stats.quads == 0) {
        _ = z3d.meshQuadifyEnd(false);
        return 0;
    }
    const ended = z3d.meshQuadifyEnd(true);
    return if (ended.ok) ended.changed else 0;
}

/// Toggle the selected faces (face mode) as GLASS: face metadata changes and the mesh
/// re-partitions so every glass face sits in one trailing run drawn through the
/// transparent pipeline with the independent auxiliary glass atlas.
/// Toggling faces that are already glass makes them opaque again.
pub fn meshSetSelectionGlass() bool {
    if (!z3d.residentMutationAllowed(.durable_channels)) return false;
    if (!model_paint.hasTarget()) return false;
    if (mesh_edit.mode() != .face) return false;
    const tri_count = z3d.g_edit_count / 3;
    if (tri_count == 0) return false;
    const mask = z3d.jalloc.alloc(bool, tri_count) catch return false;
    defer z3d.jalloc.free(mask);
    const selected = mesh_edit.buildDeleteMask(mask);
    if (selected == 0) return false;
    // Mirror (req_3797): glass toggles land on the twin faces too.
    if (mesh_edit.mirrorMask() != 0) {
        if (z3d.g_edit_verts) |soup| z3d.extendFaceMaskWithMirrorTwins(soup, tri_count, mask);
    }

    var snap = z3d.journalSnapshotCurrent("glass faces");
    mesh_edit.clearSelection(); // restore the tinted patches before colours are read

    const colors = z3d.collectCurrentFaceColors() orelse {
        z3d.journalDiscard(&snap);
        return false;
    };
    defer z3d.jalloc.free(colors);
    // Toggle by the first selected face: already glass → un-glass the selection.
    var first: u32 = 0;
    var f: u32 = 0;
    while (f < tri_count) : (f += 1) {
        if (mask[f]) {
            first = f;
            break;
        }
    }
    const make_glass = !model_paint.isGlassAlpha(colors[@as(usize, first) * 4 + 3]);
    f = 0;
    while (f < tri_count) : (f += 1) {
        if (!mask[f]) continue;
        colors[@as(usize, f) * 4 + 3] = if (make_glass) model_paint.GLASS_ALPHA else 255;
    }
    if (!z3d.partitionGlassFaces(colors)) {
        if (snap) |*before| _ = z3d.journalInstall(before);
        z3d.journalDiscard(&snap);
        return false;
    }
    z3d.journalCommit(&snap);
    return true;
}

/// Restore the saved glass run on load (req_3402). Glass's durable truth is
/// doc.blob's glass_first_vertex + the already-partitioned face order — the
/// paint baseline/program are RGB-only BY DESIGN (req_2928), so hydration used
/// to rebuild an all-opaque atlas and every restart silently dropped the glass.
/// ALPHA ONLY, NO REBUILD (req_3412): the document guarantees the glass faces
/// are already the trailing run, and running partitionGlassFaces' wholesale
/// mesh replacement at mount blanked the entire viewport (the Lavalampsad
/// repro). paintFaceAlpha is the sanctioned restore-time metadata writer — it
/// re-asserts retained per-face opacity without touching the opaque atlas, and
/// editGlassFirstVert derives the transparent split live from those alphas. The source colour table mirrors
/// the run so the next save re-serializes the boundary. A LOAD, not an edit:
/// nothing journals.
pub fn meshRestoreGlass(glass_first_vertex: u32) bool {
    if (!z3d.residentMutationAllowed(.durable_channels)) return false;
    if (!model_paint.hasTarget()) return false;
    const tri_count = z3d.g_edit_count / 3;
    if (tri_count == 0) return false;
    const first_tri = glass_first_vertex / 3;
    if (first_tri >= tri_count) return true; // no glass run — nothing to restore
    var f: u32 = first_tri;
    while (f < tri_count) : (f += 1) {
        model_paint.paintFaceAlpha(f, model_paint.GLASS_ALPHA);
    }
    if (model_source.colors()) |src| {
        var g: u32 = first_tri;
        while (g < tri_count) : (g += 1) {
            const at = @as(usize, g) * 4 + 3;
            if (at < src.len) src[at] = model_paint.GLASS_ALPHA;
        }
    }
    return true;
}

/// Rebuild the mesh with a STABLE opaque-then-glass partition (face order otherwise
/// preserved), applying `colors` (per PRE-partition face, alpha authoritative)
/// permuted to the new order. Group ids ride along, so part identity is untouched.
pub fn partitionGlassFaces(colors: []const u8) bool {
    const cur_verts = z3d.g_edit_verts orelse return false;
    const tri_count = z3d.g_edit_count / 3;
    if (colors.len < @as(usize, tri_count) * 4) return false;
    const source_verts = model_source.verts() orelse return false;
    const vertex_words = @as(usize, z3d.g_edit_count) * 8;
    if (model_source.count() != z3d.g_edit_count or source_verts.len < vertex_words or cur_verts.len < vertex_words) return false;
    const has_groups = model_source.faceGroupOf(0) != model_source.NO_FACE_GROUP;
    const cur_groups: ?[]u32 = if (has_groups) z3d.captureFaceGroups() else null;
    defer if (cur_groups) |g| z3d.jalloc.free(g);
    const cur_logical_ids = model_source.renderCornerLogicalIds();
    if (cur_logical_ids) |rows| if (rows.len != z3d.g_edit_count) return false;
    const logical_vertex_count = model_source.logicalVertexCount();

    var out: std.ArrayListUnmanaged(f32) = .empty;
    defer out.deinit(z3d.jalloc);
    var out_source: std.ArrayListUnmanaged(f32) = .empty;
    defer out_source.deinit(z3d.jalloc);
    var order: std.ArrayListUnmanaged(u32) = .empty;
    defer order.deinit(z3d.jalloc);
    var new_groups: std.ArrayListUnmanaged(u32) = .empty;
    defer new_groups.deinit(z3d.jalloc);
    var new_colors: std.ArrayListUnmanaged(u8) = .empty;
    defer new_colors.deinit(z3d.jalloc);
    var new_materials: std.ArrayListUnmanaged(u32) = .empty;
    defer new_materials.deinit(z3d.jalloc);
    var new_semantic_regions: std.ArrayListUnmanaged(u32) = .empty;
    defer new_semantic_regions.deinit(z3d.jalloc);
    var new_semantic_instances: std.ArrayListUnmanaged(u32) = .empty;
    defer new_semantic_instances.deinit(z3d.jalloc);
    var new_logical_ids: std.ArrayListUnmanaged(u32) = .empty;
    defer new_logical_ids.deinit(z3d.jalloc);

    inline for (.{ true, false }) |want_opaque| {
        var f: u32 = 0;
        while (f < tri_count) : (f += 1) {
            const is_opaque = !model_paint.isGlassAlpha(colors[@as(usize, f) * 4 + 3]);
            if (is_opaque != want_opaque) continue;
            order.append(z3d.jalloc, f) catch return false;
        }
    }
    if (order.items.len != tri_count) return false;

    for (order.items) |f| {
        const base = @as(usize, f) * 24;
        if (!z3d.appendFloats(&out, cur_verts[base .. base + 24])) return false;
        if (!z3d.appendFloats(&out_source, source_verts[base .. base + 24])) return false;
        if (cur_groups) |g| new_groups.append(z3d.jalloc, g[f]) catch return false;
        new_colors.appendSlice(z3d.jalloc, colors[@as(usize, f) * 4 .. @as(usize, f) * 4 + 4]) catch return false;
        new_materials.append(z3d.jalloc, model_source.faceMaterialOf(f)) catch return false;
        const semantic = model_source.faceSemanticOf(f);
        new_semantic_regions.append(z3d.jalloc, semantic.region) catch return false;
        new_semantic_instances.append(z3d.jalloc, semantic.instance) catch return false;
        if (cur_logical_ids) |rows| {
            const logical_base = @as(usize, f) * 3;
            new_logical_ids.appendSlice(z3d.jalloc, rows[logical_base .. logical_base + 3]) catch return false;
        }
    }

    const permute_u16 = struct {
        pub fn run(rows: []const u16, face_order: []const u32) ?[]u16 {
            if (rows.len != face_order.len) return null;
            const reordered = z3d.jalloc.alloc(u16, rows.len) catch return null;
            for (face_order, 0..) |old_face, new_face| reordered[new_face] = rows[old_face];
            return reordered;
        }
    }.run;
    var new_manual_bands: ?[]u16 = if (z3d.g_retopo_manual_bands) |rows| permute_u16(rows, order.items) else null;
    defer if (new_manual_bands) |rows| z3d.jalloc.free(rows);
    if (z3d.g_retopo_manual_bands != null and new_manual_bands == null) return false;
    var new_planned_bands: ?[]u16 = if (z3d.g_retopo_band_plan) |*plan| permute_u16(plan.faces, order.items) else null;
    defer if (new_planned_bands) |rows| z3d.jalloc.free(rows);
    if (z3d.g_retopo_band_plan != null and new_planned_bands == null) return false;
    var new_uv_zones: ?[]u16 = if (z3d.g_uv_zone) |rows| permute_u16(rows, order.items) else null;
    defer if (new_uv_zones) |rows| z3d.jalloc.free(rows);
    if (z3d.g_uv_zone != null and new_uv_zones == null) return false;

    const count: u32 = @intCast(out.items.len / 8);
    if (count != z3d.g_edit_count) return false;
    const was_layout_stale = z3d.g_paint_layout_stale;
    if (!z3d.replaceActiveEditMeshPreservingAtlas(
        out.items,
        count,
        if (cur_groups != null) new_groups.items else null,
        new_colors.items,
        z3d.logicalReplacementExactOrAbsent(
            if (cur_logical_ids != null) new_logical_ids.items else null,
            count,
            logical_vertex_count,
        ),
    )) return false;
    if (cur_logical_ids != null) {
        if (!model_source.replaceGeometryAndLogicalTopologySameTriangleCount(
            out_source.items,
            count,
            new_logical_ids.items,
            logical_vertex_count,
        )) return false;
    } else if (!model_source.replaceGeometrySameTriangleCount(out_source.items, count)) return false;
    model_source.setFaceMaterials(new_materials.items);
    if (!model_source.setFaceSemantics(new_semantic_regions.items, new_semantic_instances.items)) return false;

    var face: u32 = 0;
    while (face < tri_count) : (face += 1) {
        model_paint.paintFaceAlpha(face, new_colors.items[@as(usize, face) * 4 + 3]);
    }
    if (new_manual_bands) |rows| {
        if (z3d.g_retopo_manual_bands) |old| z3d.jalloc.free(old);
        z3d.g_retopo_manual_bands = rows;
        new_manual_bands = null;
    }
    if (new_planned_bands) |rows| {
        if (z3d.g_retopo_band_plan) |*plan| {
            z3d.jalloc.free(plan.faces);
            plan.faces = rows;
            new_planned_bands = null;
        }
    }
    if (new_uv_zones) |rows| {
        if (z3d.g_uv_zone) |old| z3d.jalloc.free(old);
        z3d.g_uv_zone = rows;
        new_uv_zones = null;
        z3d.publishUvZoneMask();
    }
    paint_program.invalidateFaceKeys();
    z3d.g_paint_layout_stale = was_layout_stale;
    return true;
}

/// Glass faces must occupy ONE trailing run (the draw splits the mesh there). Anything
/// that appends opaque faces after them (add part, duplicate, solidify) re-partitions.
pub fn ensureGlassTrailing() void {
    const fc = model_paint.faceCount();
    if (fc == 0) return;
    var first_glass: ?u32 = null;
    var needs = false;
    var f: u32 = 0;
    while (f < fc) : (f += 1) {
        const is_glass = model_paint.faceIsGlass(f);
        if (is_glass and first_glass == null) first_glass = f;
        if (!is_glass and first_glass != null) needs = true;
    }
    if (!needs) return;
    const colors = z3d.collectCurrentFaceColors() orelse return;
    defer z3d.jalloc.free(colors);
    _ = z3d.partitionGlassFaces(colors);
}

/// First vertex of the trailing GLASS run (== displayed vert count when no glass).
/// Derived live from the per-face alphas, so it's correct after any op or restore.
pub fn editGlassFirstVert() u32 {
    const fc = model_paint.faceCount();
    var k = fc;
    while (k > 0) : (k -= 1) {
        if (!model_paint.faceIsGlass(k - 1)) break;
    }
    return k * 3;
}

/// Durable model-document boundary: first vertex of the trailing per-face glass
/// run. Meshdoc v2 stores this beside the source soup so an exported resident
/// mesh can recreate the transparent, depth-write-off draw after leaving Studio.
pub fn modelGlassFirstVertex() u32 {
    const verts = model_source.verts() orelse return 0;
    const face_count: usize = verts.len / 24;
    const colors = model_source.colors() orelse return @intCast(face_count * 3);
    if (colors.len < face_count * 4) return @intCast(face_count * 3);
    var first = face_count;
    while (first > 0) : (first -= 1) {
        if (!model_paint.isGlassAlpha(colors[(first - 1) * 4 + 3])) break;
    }
    return @intCast(first * 3);
}

/// Solidify the selected faces (face mode) IN PLACE: an inner skin offset by the
/// selected AUTHORED face planes plus wall quads around the selection's boundary edges.
/// Render triangles sharing a quad/ngon group collapse to one plane before the inset is
/// solved, so triangulation diagonals cannot skew the shell.  New logical faces mint
/// fresh authored identities (one inner cap per source face, one per wall quad), while
/// retaining their source colour and part ownership. Thickness in meters; <= 0 uses the
/// studio default 2/16.
pub fn meshSolidifySelection(thickness_raw: f32) bool {
    if (!model_paint.hasTarget()) return false;
    if (mesh_edit.mode() != .face) return false;
    if (!mesh_edit.ensureTopologyPub()) return false;
    const cur_verts = z3d.g_edit_verts orelse return false;
    const tri_count = z3d.g_edit_count / 3;
    if (tri_count == 0) return false;
    const mask = z3d.jalloc.alloc(bool, tri_count) catch return false;
    defer z3d.jalloc.free(mask);
    const selected = mesh_edit.buildDeleteMask(mask);
    if (selected == 0) return false;
    // Mirror (req_3797): solidify thickens the twin faces too — each authored plane
    // already offsets along its own normal, so disjoint twin clusters compose freely.
    if (mesh_edit.mirrorMask() != 0) z3d.extendFaceMaskWithMirrorTwins(cur_verts, tri_count, mask);
    const t: f32 = if (thickness_raw > 1e-5) thickness_raw else mesh_edit.SolidifyTuning.default_thickness_m;

    const has_groups = model_source.faceGroupOf(0) != model_source.NO_FACE_GROUP;
    const cur_groups: ?[]u32 = if (has_groups) z3d.captureFaceGroups() else null;
    defer if (cur_groups) |g| z3d.jalloc.free(g);
    const base_part = z3d.capturePartOfFaces();
    defer if (base_part) |p| z3d.jalloc.free(p);
    const part_count = z3d.hostPartCount();

    // Selected render triangles are reduced to authored planes by mesh_edit's deep
    // solidify boundary. Keeping that reduction outside this host orchestration is the
    // guard against ever weighting a quad's diagonal endpoints twice again.
    var solidify_triangles: std.ArrayListUnmanaged(mesh_edit.SolidifyTriangle) = .empty;
    defer solidify_triangles.deinit(z3d.jalloc);
    // Selection-boundary edges: welded-vert pair → incident selected-face count, plus
    // the (face, corner) that owns the edge in winding order (for the wall's winding).
    const EdgeUse = struct { count: u32, face: u32, corner: u32 };
    var euse = std.AutoHashMapUnmanaged(u64, EdgeUse){};
    defer euse.deinit(z3d.jalloc);

    var f: u32 = 0;
    while (f < tri_count) : (f += 1) {
        if (!mask[f]) continue;
        const base = @as(usize, f) * 24;
        if (base + 24 > cur_verts.len) break;
        const p0: [3]f32 = .{ cur_verts[base + 0], cur_verts[base + 1], cur_verts[base + 2] };
        const p1: [3]f32 = .{ cur_verts[base + 8], cur_verts[base + 9], cur_verts[base + 10] };
        const p2: [3]f32 = .{ cur_verts[base + 16], cur_verts[base + 17], cur_verts[base + 18] };
        const corners = [3]u32{
            mesh_edit.cornerVertPub(f, 0),
            mesh_edit.cornerVertPub(f, 1),
            mesh_edit.cornerVertPub(f, 2),
        };
        solidify_triangles.append(z3d.jalloc, .{
            .face = f,
            .group = model_source.faceGroupOf(f),
            .corners = corners,
            .positions = .{ p0, p1, p2 },
        }) catch return false;
        var k: u32 = 0;
        while (k < 3) : (k += 1) {
            const a = corners[k];
            const b = corners[(k + 1) % 3];
            if (a == b) continue;
            const key = (@as(u64, @min(a, b)) << 32) | @as(u64, @max(a, b));
            const egop = euse.getOrPut(z3d.jalloc, key) catch return false;
            if (!egop.found_existing) {
                egop.value_ptr.* = .{ .count = 1, .face = f, .corner = k };
            } else {
                egop.value_ptr.count += 1;
            }
        }
    }

    var offsets = mesh_edit.solidifyOffsets(z3d.jalloc, solidify_triangles.items, t) catch return false;
    defer offsets.deinit();

    var out: std.ArrayListUnmanaged(f32) = .empty;
    defer out.deinit(z3d.jalloc);
    if (!z3d.appendCurrentDisplayed(&out)) return false;
    var logical = z3d.LogicalRowsBuilder.init() orelse return false;
    defer logical.deinit();
    if (!logical.appendAllSource()) return false;
    var inner_logical = z3d.LogicalCloneMap{};
    defer inner_logical.deinit();
    var add_groups: std.ArrayListUnmanaged(u32) = .empty;
    defer add_groups.deinit(z3d.jalloc);
    var add_colors: std.ArrayListUnmanaged(u8) = .empty;
    defer add_colors.deinit(z3d.jalloc);
    var add_materials: std.ArrayListUnmanaged(u32) = .empty;
    defer add_materials.deinit(z3d.jalloc);
    var add_semantic_regions: std.ArrayListUnmanaged(u32) = .empty;
    defer add_semantic_regions.deinit(z3d.jalloc);
    var add_semantic_instances: std.ArrayListUnmanaged(u32) = .empty;
    defer add_semantic_instances.deinit(z3d.jalloc);
    var add_part: std.ArrayListUnmanaged(u32) = .empty;
    defer add_part.deinit(z3d.jalloc);
    var next_group: u32 = if (has_groups) z3d.nextFreeGroupId(cur_groups.?) else 0;
    var inner_groups = std.AutoHashMapUnmanaged(u32, u32){};
    defer inner_groups.deinit(z3d.jalloc);

    // Inner skin: one reversed, offset triangle per selected face (group + colour inherit).
    f = 0;
    while (f < tri_count) : (f += 1) {
        if (!mask[f]) continue;
        const base = @as(usize, f) * 24;
        if (base + 24 > cur_verts.len) break;
        var p: [3][3]f32 = undefined;
        var k: usize = 0;
        while (k < 3) : (k += 1) {
            p[k] = .{ cur_verts[base + k * 8], cur_verts[base + k * 8 + 1], cur_verts[base + k * 8 + 2] };
            const off = offsets.get(mesh_edit.cornerVertPub(f, @intCast(k)));
            p[k] = .{ p[k][0] + off[0], p[k][1] + off[1], p[k][2] + off[2] };
        }
        const inner_ids = [3]u32{
            inner_logical.getOrMint(&logical, 1, logical.sourceCorner(f, 0) orelse return false) orelse return false,
            inner_logical.getOrMint(&logical, 1, logical.sourceCorner(f, 2) orelse return false) orelse return false,
            inner_logical.getOrMint(&logical, 1, logical.sourceCorner(f, 1) orelse return false) orelse return false,
        };
        if (!z3d.appendTriLogical(&out, &logical, p[0], p[2], p[1], inner_ids)) return false;
        if (has_groups) {
            const gop = inner_groups.getOrPut(z3d.jalloc, model_source.faceGroupOf(f)) catch return false;
            if (!gop.found_existing) {
                gop.value_ptr.* = next_group;
                next_group += 1;
            }
            add_groups.append(z3d.jalloc, gop.value_ptr.*) catch return false;
        }
        const c = z3d.trueFaceColor(f);
        add_colors.appendSlice(z3d.jalloc, c[0..]) catch return false;
        add_materials.append(z3d.jalloc, model_source.faceMaterialOf(f)) catch return false;
        const semantic = model_source.faceSemanticOf(f);
        add_semantic_regions.append(z3d.jalloc, semantic.region) catch return false;
        add_semantic_instances.append(z3d.jalloc, semantic.instance) catch return false;
        if (base_part) |bp| add_part.append(z3d.jalloc, bp[f]) catch return false;
    }
    // Rim walls on the selection's boundary edges (incident to exactly ONE selected face).
    var it = euse.iterator();
    while (it.next()) |entry| {
        const use = entry.value_ptr.*;
        if (use.count != 1) continue;
        const fa = use.face;
        const a = mesh_edit.vertPosPub(mesh_edit.cornerVertPub(fa, use.corner));
        const b = mesh_edit.vertPosPub(mesh_edit.cornerVertPub(fa, (use.corner + 1) % 3));
        const oa = offsets.get(mesh_edit.cornerVertPub(fa, use.corner));
        const ob = offsets.get(mesh_edit.cornerVertPub(fa, (use.corner + 1) % 3));
        const ai: [3]f32 = .{ a[0] + oa[0], a[1] + oa[1], a[2] + oa[2] };
        const bi: [3]f32 = .{ b[0] + ob[0], b[1] + ob[1], b[2] + ob[2] };
        // Edge a→b runs in the face's winding, so (a, ai, bi, b) faces outward.
        const a_id = logical.sourceCorner(fa, use.corner) orelse return false;
        const b_id = logical.sourceCorner(fa, (use.corner + 1) % 3) orelse return false;
        const ai_id = inner_logical.getOrMint(&logical, 1, a_id) orelse return false;
        const bi_id = inner_logical.getOrMint(&logical, 1, b_id) orelse return false;
        if (!z3d.appendQuadSplitLogical(&out, &logical, a, ai, bi, b, .{ a_id, ai_id, bi_id, b_id })) return false;
        if (has_groups) {
            const wall_group = next_group;
            next_group += 1;
            add_groups.append(z3d.jalloc, wall_group) catch return false;
            add_groups.append(z3d.jalloc, wall_group) catch return false;
        }
        const c = z3d.trueFaceColor(fa);
        add_colors.appendSlice(z3d.jalloc, c[0..]) catch return false;
        add_colors.appendSlice(z3d.jalloc, c[0..]) catch return false;
        add_materials.append(z3d.jalloc, indexed_edit_mesh.NO_MATERIAL) catch return false;
        add_materials.append(z3d.jalloc, indexed_edit_mesh.NO_MATERIAL) catch return false;
        const semantic = model_source.faceSemanticOf(fa);
        add_semantic_regions.append(z3d.jalloc, semantic.region) catch return false;
        add_semantic_regions.append(z3d.jalloc, semantic.region) catch return false;
        add_semantic_instances.append(z3d.jalloc, semantic.instance) catch return false;
        add_semantic_instances.append(z3d.jalloc, semantic.instance) catch return false;
        if (base_part) |bp| {
            add_part.append(z3d.jalloc, bp[fa]) catch return false;
            add_part.append(z3d.jalloc, bp[fa]) catch return false;
        }
    }

    var snap = z3d.journalSnapshotCurrent("solidify faces");
    mesh_edit.clearSelection();
    const first_new_face = tri_count;
    const new_count: u32 = @intCast(out.items.len / 8);
    const materials = z3d.captureFaceMaterials(new_count / 3) orelse {
        z3d.journalDiscard(&snap);
        return false;
    };
    defer z3d.jalloc.free(materials);
    if (add_materials.items.len != materials.len - first_new_face) {
        z3d.journalDiscard(&snap);
        return false;
    }
    @memcpy(materials[first_new_face..], add_materials.items);
    var semantics = z3d.captureFaceSemantics(new_count / 3) orelse {
        z3d.journalDiscard(&snap);
        return false;
    };
    defer semantics.deinit();
    if (add_semantic_regions.items.len != semantics.regions.len - first_new_face or
        add_semantic_instances.items.len != semantics.instances.len - first_new_face)
    {
        z3d.journalDiscard(&snap);
        return false;
    }
    @memcpy(semantics.regions[first_new_face..], add_semantic_regions.items);
    @memcpy(semantics.instances[first_new_face..], add_semantic_instances.items);
    const logical_replacement = logical.replacement(new_count) orelse {
        z3d.journalDiscard(&snap);
        return false;
    };
    if (!z3d.replaceActiveEditMesh(out.items, new_count, logical_replacement)) {
        z3d.journalDiscard(&snap);
        return false;
    }
    model_source.setFaceMaterials(materials);
    if (!model_source.setFaceSemantics(semantics.regions, semantics.instances)) {
        if (snap) |*before| _ = z3d.journalInstall(before);
        z3d.journalDiscard(&snap);
        return false;
    }
    if (has_groups) {
        var all_groups: std.ArrayListUnmanaged(u32) = .empty;
        defer all_groups.deinit(z3d.jalloc);
        for (cur_groups.?) |g| all_groups.append(z3d.jalloc, g) catch {};
        for (add_groups.items) |g| all_groups.append(z3d.jalloc, g) catch {};
        model_source.setFaceGroups(all_groups.items);
        // Fresh ids must join the source part's contiguous interval; preserve each
        // output face's pre-solidify owner while re-numbering the whole partition.
        if (base_part) |bp| {
            const face_part = z3d.jalloc.alloc(u32, new_count / 3) catch null;
            if (face_part) |fp| {
                defer z3d.jalloc.free(fp);
                var old_face: u32 = 0;
                while (old_face < tri_count) : (old_face += 1) fp[old_face] = bp[old_face];
                var new_face: u32 = 0;
                while (new_face < add_part.items.len) : (new_face += 1) fp[tri_count + new_face] = add_part.items[new_face];
                z3d.renormalizePartRanges(fp, part_count);
            }
        }
    }
    // The added skin/walls take their source face's colour.
    var i: u32 = 0;
    while (i * 4 < add_colors.items.len) : (i += 1) {
        const c: [4]u8 = .{ add_colors.items[i * 4], add_colors.items[i * 4 + 1], add_colors.items[i * 4 + 2], add_colors.items[i * 4 + 3] };
        model_paint.paintFace(first_new_face + i, c);
        model_source.writeColor(@intCast(first_new_face + i), c[0], c[1], c[2]);
    }
    _ = z3d.refreshPaintLayout();
    z3d.journalCommit(&snap);
    z3d.ensureGlassTrailing();
    return true;
}

pub fn faceCrossFromPositions(pos: []const f32, face: u32) [3]f32 {
    const b = @as(usize, face) * 9;
    if (b + 8 >= pos.len) return .{ 0, 0, 0 };
    const a: [3]f32 = .{ pos[b + 0], pos[b + 1], pos[b + 2] };
    const p1: [3]f32 = .{ pos[b + 3], pos[b + 4], pos[b + 5] };
    const p2: [3]f32 = .{ pos[b + 6], pos[b + 7], pos[b + 8] };
    return z3d.vcross(z3d.vsub(p1, a), z3d.vsub(p2, a));
}

// The unsafe-edit predicate is the studio's concave Auto-Fix over ordered indexed
// faces (editMesh.ts isFaceConcave/newConcaveFaces, req_2823). The differential
// normal/area heuristics that lived here false-fired
// on rotates (req_2754), pre-degenerate meshes (req_2755), loop-cut slivers, and
// hinge edits (req_2816) — "changed a lot" is not "became invalid".

/// True if Split Quads would actually change topology: authored groups exist, the
/// displayed mesh IS the source (group ids are per source face), and at least one
/// offending tri sits in a group with 2+ members (splitting a singleton is a no-op).
pub fn guardSplitPossible(bad_list: []const u32) bool {
    if (bad_list.len == 0) return false;
    if (!model_paint.hasTarget()) return false;
    if (model_source.faceGroupOf(0) == model_source.NO_FACE_GROUP) return false;
    if (z3d.g_edit_count != model_source.count()) return false;
    const tri_count = z3d.g_edit_count / 3;
    const groups = z3d.captureFaceGroups() orelse return false;
    defer std.heap.c_allocator.free(groups);
    for (bad_list) |bf| {
        if (bf >= tri_count) continue;
        const g = groups[bf];
        if (g == model_source.NO_FACE_GROUP) continue;
        var members: u32 = 0;
        for (groups) |og| {
            if (og != g) continue;
            members += 1;
            if (members >= 2) return true;
        }
    }
    return false;
}

/// Split Quads (guard action 0, req_2757): every authored group that contains an
/// offending tri breaks into per-triangle groups, so the fold the drag created becomes
/// explicit topology instead of a hidden artifact inside a "flat" quad. Pure group
/// remap — no geometry moves; part membership is preserved by re-deriving it from the
/// ORIGINAL ids and renormalizing the per-part contiguous ranges after the renumber.
pub fn guardSplitQuads() bool {
    const bad_list = z3d.g_guard_bad_list orelse return false;
    if (!z3d.guardSplitPossible(bad_list)) return false;
    const tri_count = z3d.g_edit_count / 3;
    const groups = z3d.captureFaceGroups() orelse return false;
    defer z3d.jalloc.free(groups);

    var affected = std.AutoHashMapUnmanaged(u32, void){};
    defer affected.deinit(z3d.jalloc);
    for (bad_list) |bf| {
        if (bf >= tri_count) continue;
        const g = groups[bf];
        if (g == model_source.NO_FACE_GROUP) continue;
        affected.put(z3d.jalloc, g, {}) catch return false;
    }
    if (affected.count() == 0) return false;

    // Part membership must be read off the ORIGINAL ids before the renumber moves
    // them past every part range.
    var face_part: ?[]u32 = null;
    defer if (face_part) |fp| z3d.jalloc.free(fp);
    var part_count: u32 = 0;
    if (model_source.partRanges()) |pr| {
        part_count = @intCast(pr.len / 2);
        const fp = z3d.jalloc.alloc(u32, tri_count) catch return false;
        for (fp, 0..) |*slot, f| {
            slot.* = model_source.NO_PART;
            const g = groups[f];
            if (g == model_source.NO_FACE_GROUP) continue;
            var p: u32 = 0;
            while (p < part_count) : (p += 1) {
                if (g >= pr[p * 2] and g < pr[p * 2 + 1]) {
                    slot.* = p;
                    break;
                }
            }
        }
        face_part = fp;
    }

    var snap = z3d.journalSnapshotCurrent("split quads");
    // Selection tint must restore before the paint layout re-islands (detach's rule).
    mesh_edit.clearSelection();
    var next: u32 = @intCast(z3d.maxGroupId(groups) + 1);
    var f: u32 = 0;
    while (f < tri_count) : (f += 1) {
        if (groups[f] == model_source.NO_FACE_GROUP) continue;
        if (!affected.contains(groups[f])) continue;
        groups[f] = next;
        next += 1;
    }
    model_source.setFaceGroups(groups);
    if (face_part) |fp| {
        z3d.renormalizePartRanges(fp, part_count);
    } else {
        mesh_edit.reset();
        _ = z3d.refreshPaintLayout();
    }
    z3d.journalCommit(&snap);
    return true;
}
