//! rig_inspect.zig — split verbatim from framework/gpu/3d.zig (req_4375).
//! Generated by _tool/split3d.zig — edit 3d.zig's successor here, regenerate only from the manifest.
//! Cross-file references are qualified through the orchestrator (`z3d`).

const std = @import("std");
const builtin = @import("builtin");
const log = @import("../../diag/log.zig");
const wgpu = @import("wgpu");
const bu = @import("../buffer_upload.zig");
const shaders = @import("../shaders.zig");
const terrain_grid = @import("../terrain_grid.zig");
const core = @import("../../dev_modules/gpu_api.zig");
const capture = @import("../capture.zig");
const build_options = @import("build_options");
const math = @import("../../math/root.zig");
const layout = @import("../../layout.zig");
const effect_assemble = @import("../effect_assemble.zig");
const compile_progress = @import("../compile_progress.zig");
const static_instance_policy = @import("../static_instance_policy.zig");
const model_paint = @import("../model_paint.zig");
const gizmo_axis_map = @import("../gizmo_axis_map.zig");
const effects_ctx = @import("../effects_ctx.zig");
const paint_islands_mod = @import("../paint_islands.zig");
const paint_program = @import("../paint_program.zig");
const model_source = @import("../model_source.zig");
const meshdoc_format = @import("../meshdoc_format.zig");
const mesh_audit = @import("../mesh_audit.zig");
const mesh_face_table = @import("../mesh_face_table.zig");
const mesh_face_diff = @import("../mesh_face_diff.zig");
const mesh_face_field_candidate = @import("../mesh_face_field_candidate.zig");
const mesh_face_table_package = @import("../mesh_face_table_package.zig");
const mesh_face_table_worker = @import("../mesh_face_table_worker.zig");
const historical_preview = @import("../historical_preview.zig");
const mesh_edit = @import("../mesh_edit.zig");
const mesh_semantics = @import("../mesh_semantics.zig");
const mesh_semantic_restore = @import("../mesh_semantic_restore.zig");
const mesh_edge_semantics = @import("../mesh_edge_semantics.zig");
const indexed_edit_mesh = @import("../indexed_edit_mesh.zig");
const character_topology_promotion = @import("../character_topology_promotion.zig");
const mesh_journal_log = @import("../mesh_journal_log.zig");
const model_write_lease = @import("../model_write_lease.zig");
const model_adoption_receipt = @import("../model_adoption_receipt.zig");
const model_adoption_finalize = @import("../model_adoption_finalize.zig");
const path_array = @import("../path_array.zig");
const path_plane = @import("../path_plane.zig");
const stage_scale = @import("../stage_scale.zig");
const pack = @import("../pack.zig");
const stable_geometry_slot = @import("../stable_geometry_slot.zig");
const character_rig_session = @import("../../skeleton/character_rig_session.zig");
const character_skin_binding = @import("../../skeleton/skin_binding.zig");
const character_specimen = @import("../character_specimen.zig");
const mouse_state = @import("../../state/mouse_state.zig");
const Node = layout.Node;

const z3d = @import("3d.zig");

// ── Character Rig Inspect resident presentation ───────────────────────────
// The skeleton session publishes one ephemeral FK/weight view after each
// revision. GPU owns the durable copies, render-corner expansion, heatmap
// palette, native overlay, and screen-space picking. Nothing here is model data.
pub const CHARACTER_RIG_SKIN_HOST_KEY = character_specimen.RESIDENT_DEFORMED_SKIN_HOST_KEY;
pub const CHARACTER_RIG_BONE_CAP = character_rig_session.MAX_BONES;
pub const CHARACTER_RIG_NAME_BYTES = 64;
pub const CHARACTER_RIG_PALETTE_FLOATS = 20;
pub const CHARACTER_RIG_JOINT_HIT_RADIUS_PX: f32 = 14;

pub const CharacterRigGpuBone = struct {
    parent_index: ?u8 = null,
    local_pos: [3]f32 = .{ 0, 0, 0 },
    local_rot: [4]f32 = .{ 0, 0, 0, 1 },
    local_scale: [3]f32 = .{ 1, 1, 1 },
    local_tip: ?[3]f32 = null,
    fit_source: character_rig_session.schema.FitSource = .template,
    name: [z3d.CHARACTER_RIG_NAME_BYTES]u8 = @splat(0),
    name_len: u8 = 0,
};

pub const CharacterRigGpuState = struct {
    active: bool = false,
    source_hash: u64 = 0,
    geometry_fingerprint: u64 = 0,
    skin_key: [80]u8 = @splat(0),
    skin_key_len: u8 = 0,
    skin_vertices: ?[]f32 = null,
    skin_vertex_count: u32 = 0,
    has_skin: bool = false,
    bind_mesh: bool = true,
    deformed_mesh: bool = true,
    axes: bool = true,
    names: bool = true,
    heatmap: bool = false,
    selected_bone: ?u8 = null,
    hovered_joint: ?character_specimen.HoveredJoint = null,
    selected_vertex_position: ?[3]f32 = null,
    joint_editable: bool = false,
    specimen_separation: f32 = 0,
    axis_length: f32 = 0.08,
    bone_count: u16 = 0,
    bones: [z3d.CHARACTER_RIG_BONE_CAP]z3d.CharacterRigGpuBone = @splat(.{}),
    bind_global: [z3d.CHARACTER_RIG_BONE_CAP][16]f32 = undefined,
    pose_global: [z3d.CHARACTER_RIG_BONE_CAP][16]f32 = undefined,
    skin_matrices: [z3d.CHARACTER_RIG_BONE_CAP][16]f32 = undefined,
    palette: [z3d.CHARACTER_RIG_BONE_CAP * z3d.CHARACTER_RIG_PALETTE_FLOATS]f32 = @splat(0),
};

pub const CharacterRigGizmoDrag = struct {
    active: bool = false,
    code: u8 = 0, // 0..2 translate XYZ, 3..5 rotate XYZ
    bone_index: u8 = 0,
    raw_delta: f32 = 0,
    applied_delta: f32 = 0,
    start_pos: [3]f32 = .{ 0, 0, 0 },
    start_rot: [4]f32 = .{ 0, 0, 0, 1 },
    start_scale: [3]f32 = .{ 1, 1, 1 },
};

pub const CharacterRigGizmoCommit = struct {
    bone_index: u8,
    pos: [3]f32,
    rot: [4]f32,
    scale: [3]f32,
};

pub fn characterRigReleaseSkin() void {
    if (z3d.g_character_rig.skin_vertices) |vertices| std.heap.c_allocator.free(vertices);
    z3d.g_character_rig.skin_vertices = null;
    z3d.g_character_rig.skin_vertex_count = 0;
    z3d.g_character_rig.has_skin = false;
    z3d.g_character_rig.geometry_fingerprint = 0;
    z3d.g_character_rig.skin_key_len = 0;
}

pub fn characterRigClearViewport() void {
    z3d.characterRigReleaseSkin();
    z3d.g_character_rig = .{};
    z3d.g_character_rig_gizmo = .{};
}

pub fn characterRigGeometryFingerprint(state: *const character_rig_session.RigViewportState) u64 {
    var hasher = std.hash.Wyhash.init(0x52494731);
    hasher.update(std.mem.sliceAsBytes(state.snapshot.verts));
    if (state.snapshot.render_corner_logical_ids) |logical_ids| hasher.update(std.mem.sliceAsBytes(logical_ids));
    if (state.logical_weights) |weights| hasher.update(std.mem.sliceAsBytes(weights));
    return hasher.final();
}

pub fn characterRigBuildSkin(state: *const character_rig_session.RigViewportState, fingerprint: u64) bool {
    const weights = state.logical_weights orelse {
        z3d.characterRigReleaseSkin();
        return true;
    };
    const logical_ids = state.snapshot.render_corner_logical_ids orelse {
        z3d.characterRigReleaseSkin();
        return false;
    };
    const corner_count = logical_ids.len;
    if (corner_count == 0 or state.snapshot.verts.len != corner_count * 8 or
        weights.len != state.snapshot.logical_vertex_count)
    {
        z3d.characterRigReleaseSkin();
        return false;
    }
    if (z3d.g_character_rig.geometry_fingerprint == fingerprint and z3d.g_character_rig.skin_vertices != null) {
        z3d.g_character_rig.has_skin = true;
        return true;
    }
    const vertices = std.heap.c_allocator.alloc(f32, corner_count * 16) catch return false;
    for (logical_ids, 0..) |logical_id, corner| {
        if (logical_id >= weights.len) {
            std.heap.c_allocator.free(vertices);
            return false;
        }
        const source_at = corner * 8;
        const target_at = corner * 16;
        @memcpy(vertices[target_at .. target_at + 8], state.snapshot.verts[source_at .. source_at + 8]);
        const row = weights[logical_id];
        const packed_weights = character_skin_binding.quantizeWeights(row.weights) catch {
            std.heap.c_allocator.free(vertices);
            return false;
        };
        for (0..4) |influence| {
            const bone_index = row.bone_indices[influence];
            vertices[target_at + 8 + influence] = @floatFromInt(if (bone_index == character_skin_binding.UNUSED_BONE) 0 else bone_index);
            vertices[target_at + 12 + influence] = @as(f32, @floatFromInt(packed_weights[influence])) / 255.0;
        }
    }
    z3d.characterRigReleaseSkin();
    z3d.g_character_rig.skin_vertices = vertices;
    z3d.g_character_rig.skin_vertex_count = @intCast(corner_count);
    z3d.g_character_rig.geometry_fingerprint = fingerprint;
    const key = std.fmt.bufPrint(&z3d.g_character_rig.skin_key, "character-rig:{x}", .{fingerprint}) catch return false;
    z3d.g_character_rig.skin_key_len = @intCast(key.len);
    z3d.g_character_rig.has_skin = true;
    return true;
}

pub fn characterRigFrameSpecimens(state: *const character_rig_session.RigViewportState) void {
    if (state.snapshot.verts.len < 8) return;
    var minimum: [3]f32 = @splat(std.math.inf(f32));
    var maximum: [3]f32 = @splat(-std.math.inf(f32));
    var corner: usize = 0;
    while (corner < state.snapshot.verts.len / 8) : (corner += 1) {
        const at = corner * 8;
        for (0..3) |axis| {
            const value = state.snapshot.verts[at + axis];
            if (!std.math.isFinite(value)) continue;
            minimum[axis] = @min(minimum[axis], value);
            maximum[axis] = @max(maximum[axis], value);
        }
    }
    for (0..3) |axis| {
        if (!std.math.isFinite(minimum[axis]) or !std.math.isFinite(maximum[axis])) return;
    }
    const source_width = @max(0.001, maximum[0] - minimum[0]);
    z3d.g_character_rig.axis_length = @max(0.025, source_width * 0.075);
    const union_min = minimum;
    var union_max = maximum;
    union_max[0] += state.specimen_separation;
    const center = [3]f32{
        (union_min[0] + union_max[0]) * 0.5,
        (union_min[1] + union_max[1]) * 0.5,
        (union_min[2] + union_max[2]) * 0.5,
    };
    const half = [3]f32{
        (union_max[0] - union_min[0]) * 0.5,
        (union_max[1] - union_min[1]) * 0.5,
        (union_max[2] - union_min[2]) * 0.5,
    };
    const radius = @sqrt(half[0] * half[0] + half[1] * half[1] + half[2] * half[2]);
    z3d.orbitFrame(center, @max(radius * 1.08, source_width));
}

pub fn characterRigSyncViewport(state: *const character_rig_session.RigViewportState) void {
    if (state.bones.len == 0 or state.bones.len > z3d.CHARACTER_RIG_BONE_CAP or
        state.bind_global.len != state.bones.len or
        state.pose_global.len != state.bones.len or
        state.skin_matrices.len != state.bones.len)
    {
        z3d.characterRigClearViewport();
        return;
    }
    const source_hash = z3d.hashKey(state.source_key);
    const entering = !z3d.g_character_rig.active or z3d.g_character_rig.source_hash != source_hash;
    if (entering) z3d.characterRigFrameSpecimens(state);
    z3d.g_character_rig.active = true;
    z3d.g_character_rig.source_hash = source_hash;
    z3d.g_character_rig.bind_mesh = state.bind_mesh;
    z3d.g_character_rig.deformed_mesh = state.deformed_mesh;
    z3d.g_character_rig.axes = state.axes;
    z3d.g_character_rig.names = state.names;
    z3d.g_character_rig.heatmap = state.heatmap;
    z3d.g_character_rig.selected_bone = state.selected_bone;
    z3d.g_character_rig.joint_editable = state.joint_editable;
    z3d.g_character_rig.bone_count = @intCast(state.bones.len);
    if (!state.joint_editable) z3d.g_character_rig_gizmo = .{};
    z3d.g_character_rig.specimen_separation = state.specimen_separation;

    for (state.bones, 0..) |bone, index| {
        var stored = z3d.CharacterRigGpuBone{
            .parent_index = bone.parent_index,
            .local_pos = bone.local_transform.pos,
            .local_rot = bone.local_transform.rot,
            .local_scale = bone.local_transform.scale,
            .local_tip = bone.local_tip,
            .fit_source = bone.fit_source,
        };
        const name_len = @min(bone.display_name.len, z3d.CHARACTER_RIG_NAME_BYTES);
        @memcpy(stored.name[0..name_len], bone.display_name[0..name_len]);
        stored.name_len = @intCast(name_len);
        z3d.g_character_rig.bones[index] = stored;
        z3d.g_character_rig.bind_global[index] = state.bind_global[index];
        z3d.g_character_rig.pose_global[index] = state.pose_global[index];
        z3d.g_character_rig.skin_matrices[index] = state.skin_matrices[index];
        const palette_at = index * z3d.CHARACTER_RIG_PALETTE_FLOATS;
        @memcpy(z3d.g_character_rig.palette[palette_at .. palette_at + 16], &state.skin_matrices[index]);
        const selected = state.selected_bone != null and state.selected_bone.? == index;
        const color: [4]f32 = if (state.heatmap)
            if (selected) .{ 1.0, 0.18, 0.03, 1.0 } else .{ 0.04, 0.16, 0.72, 1.0 }
        else
            .{ 1.0, 1.0, 1.0, 1.0 };
        @memcpy(z3d.g_character_rig.palette[palette_at + 16 .. palette_at + 20], &color);
    }

    z3d.g_character_rig.selected_vertex_position = null;
    if (state.selected_vertex) |logical_id| {
        if (state.snapshot.render_corner_logical_ids) |logical_ids| {
            for (logical_ids, 0..) |candidate, corner| if (candidate == logical_id) {
                const at = corner * 8;
                z3d.g_character_rig.selected_vertex_position = .{
                    state.snapshot.verts[at],
                    state.snapshot.verts[at + 1],
                    state.snapshot.verts[at + 2],
                };
                break;
            };
        }
    }
    _ = z3d.characterRigBuildSkin(state, z3d.characterRigGeometryFingerprint(state));
}

pub const CharacterRigSkinSource = struct {
    key: []const u8,
    vertices: []const f32,
    vertex_count: u32,
    palette: []const f32,
    bone_count: u32,
};

pub fn characterRigSkinSource(node_key: []const u8) ?z3d.CharacterRigSkinSource {
    if (!character_specimen.ownsResidentViewportCamera(
        node_key,
        z3d.g_character_rig.active,
        z3d.g_character_rig.has_skin,
        z3d.g_character_rig.deformed_mesh,
    )) return null;
    return .{
        .key = z3d.g_character_rig.skin_key[0..z3d.g_character_rig.skin_key_len],
        .vertices = z3d.g_character_rig.skin_vertices.?,
        .vertex_count = z3d.g_character_rig.skin_vertex_count,
        .palette = z3d.g_character_rig.palette[0 .. @as(usize, z3d.g_character_rig.bone_count) * z3d.CHARACTER_RIG_PALETTE_FLOATS],
        .bone_count = z3d.g_character_rig.bone_count,
    };
}

pub fn characterRigTransformPoint(matrix: [16]f32, point: [3]f32) [3]f32 {
    return .{
        matrix[0] * point[0] + matrix[4] * point[1] + matrix[8] * point[2] + matrix[12],
        matrix[1] * point[0] + matrix[5] * point[1] + matrix[9] * point[2] + matrix[13],
        matrix[2] * point[0] + matrix[6] * point[1] + matrix[10] * point[2] + matrix[14],
    };
}

pub fn characterRigWorldPoint(matrix: [16]f32, local: [3]f32, x_offset: f32) [3]f32 {
    var result = z3d.characterRigTransformPoint(matrix, local);
    result[0] += x_offset;
    return result;
}

pub fn characterRigOrigin(matrix: [16]f32, x_offset: f32) [3]f32 {
    return .{ matrix[12] + x_offset, matrix[13], matrix[14] };
}

pub fn characterRigParentAxis(bone_index: usize, axis: usize) [3]f32 {
    const bone = z3d.g_character_rig.bones[bone_index];
    if (bone.parent_index) |parent_index| {
        const matrix = z3d.g_character_rig.bind_global[parent_index];
        return z3d.vnorm(.{ matrix[axis * 4], matrix[axis * 4 + 1], matrix[axis * 4 + 2] });
    }
    return switch (axis) {
        0 => .{ 1, 0, 0 },
        1 => .{ 0, 1, 0 },
        else => .{ 0, 0, 1 },
    };
}

pub fn characterRigGizmoPivot(bone_index: usize) [3]f32 {
    var pivot = z3d.characterRigOrigin(z3d.g_character_rig.bind_global[bone_index], 0);
    if (z3d.g_character_rig_gizmo.active and z3d.g_character_rig_gizmo.bone_index == bone_index and z3d.g_character_rig_gizmo.code < 3) {
        const axis = z3d.characterRigParentAxis(bone_index, z3d.g_character_rig_gizmo.code);
        pivot = z3d.vadd(pivot, z3d.vmul(axis, z3d.g_character_rig_gizmo.applied_delta));
    }
    return pivot;
}

pub fn characterRigQuatMultiply(left: [4]f32, right: [4]f32) [4]f32 {
    return .{
        left[3] * right[0] + left[0] * right[3] + left[1] * right[2] - left[2] * right[1],
        left[3] * right[1] - left[0] * right[2] + left[1] * right[3] + left[2] * right[0],
        left[3] * right[2] + left[0] * right[1] - left[1] * right[0] + left[2] * right[3],
        left[3] * right[3] - left[0] * right[0] - left[1] * right[1] - left[2] * right[2],
    };
}

pub fn characterRigQuatNormalize(value: [4]f32) [4]f32 {
    const length = @sqrt(value[0] * value[0] + value[1] * value[1] + value[2] * value[2] + value[3] * value[3]);
    if (!std.math.isFinite(length) or length <= 1.0e-8) return .{ 0, 0, 0, 1 };
    return .{ value[0] / length, value[1] / length, value[2] / length, value[3] / length };
}

pub fn characterRigActive() bool {
    return z3d.g_character_rig.active;
}

/// Hit-test the selected joint's native two-ended gizmo. Positive arms are
/// translation handles; the compact negative dots are rotation handles.
pub fn characterRigGizmoHit(mx: f32, my: f32) i32 {
    if (!z3d.g_character_rig.active or !z3d.g_character_rig.joint_editable or z3d.g_character_rig.selected_bone == null) return -1;
    const bone_index: usize = z3d.g_character_rig.selected_bone.?;
    const cam = model_paint.Camera{ .eye = z3d.g_paint_eye, .target = z3d.g_paint_target, .fov_deg = z3d.g_paint_fov };
    const pivot = z3d.characterRigGizmoPivot(bone_index);
    var best_distance = std.math.inf(f32);
    var best_code: i32 = -1;
    const face_on = z3d.gizmoFaceOnPxPerUnit(cam, pivot);
    for (0..3) |axis_index| {
        const direction = z3d.characterRigParentAxis(bone_index, axis_index);
        const screen = z3d.axisScreenInfo(cam, pivot, direction) orelse continue;
        if (!z3d.gizmoAxisGrabbable(screen, face_on)) continue; // no arm drawn → no grab
        const ax = screen.ax + z3d.g_paint_vp_x;
        const ay = screen.ay + z3d.g_paint_vp_y;
        const tx = ax + screen.dx * z3d.GIZMO_ARM_PX;
        const ty = ay + screen.dy * z3d.GIZMO_ARM_PX;
        const translation_distance = z3d.segDist2(mx, my, ax, ay, tx, ty);
        if (translation_distance <= z3d.GIZMO_HIT_PX * z3d.GIZMO_HIT_PX and translation_distance < best_distance) {
            best_distance = translation_distance;
            best_code = @intCast(axis_index);
        }
        const rx = ax - screen.dx * (z3d.GIZMO_ARM_PX * 0.72);
        const ry = ay - screen.dy * (z3d.GIZMO_ARM_PX * 0.72);
        const rdx = mx - rx;
        const rdy = my - ry;
        const rotation_distance = rdx * rdx + rdy * rdy;
        if (rotation_distance <= z3d.GIZMO_HIT_PX * z3d.GIZMO_HIT_PX and rotation_distance < best_distance) {
            best_distance = rotation_distance;
            best_code = @intCast(axis_index + 3);
        }
    }
    return best_code;
}

pub fn characterRigGizmoBegin(code: i32) bool {
    if (!z3d.g_character_rig.joint_editable or code < 0 or code > 5 or z3d.g_character_rig.selected_bone == null) return false;
    const bone_index = z3d.g_character_rig.selected_bone.?;
    const bone = z3d.g_character_rig.bones[bone_index];
    z3d.g_character_rig_gizmo = .{
        .active = true,
        .code = @intCast(code),
        .bone_index = bone_index,
        .start_pos = bone.local_pos,
        .start_rot = bone.local_rot,
        .start_scale = bone.local_scale,
    };
    return true;
}

pub fn characterRigGizmoDrag(dx: f32, dy: f32, fine: bool) bool {
    if (!z3d.g_character_rig.joint_editable or !z3d.g_character_rig_gizmo.active) return false;
    const bone_index: usize = z3d.g_character_rig_gizmo.bone_index;
    const axis_index: usize = z3d.g_character_rig_gizmo.code % 3;
    const cam = model_paint.Camera{ .eye = z3d.g_paint_eye, .target = z3d.g_paint_target, .fov_deg = z3d.g_paint_fov };
    const pivot = z3d.characterRigGizmoPivot(bone_index);
    const direction = z3d.characterRigParentAxis(bone_index, axis_index);
    const screen = z3d.axisScreenInfo(cam, pivot, direction) orelse return false;
    if (z3d.g_character_rig_gizmo.code < 3) {
        const pixels = dx * screen.dx + dy * screen.dy;
        z3d.g_character_rig_gizmo.raw_delta += pixels * z3d.worldUnitsPerPixel(cam, pivot);
        const step: f32 = if (fine) 0.001 else 0.01;
        z3d.g_character_rig_gizmo.applied_delta = @round(z3d.g_character_rig_gizmo.raw_delta / step) * step;
    } else {
        const tangent_pixels = -dx * screen.dy + dy * screen.dx;
        z3d.g_character_rig_gizmo.raw_delta += tangent_pixels * 0.012;
        const step_degrees: f32 = if (fine) 1 else 5;
        const step = step_degrees * std.math.pi / 180.0;
        z3d.g_character_rig_gizmo.applied_delta = @round(z3d.g_character_rig_gizmo.raw_delta / step) * step;
    }
    return true;
}

pub fn characterRigGizmoCancel() void {
    z3d.g_character_rig_gizmo = .{};
}

pub fn characterRigGizmoEnd() ?z3d.CharacterRigGizmoCommit {
    if (!z3d.g_character_rig.joint_editable or !z3d.g_character_rig_gizmo.active) return null;
    const drag = z3d.g_character_rig_gizmo;
    z3d.g_character_rig_gizmo = .{};
    if (@abs(drag.applied_delta) <= 1.0e-8) return null;
    var pos = drag.start_pos;
    var rot = drag.start_rot;
    const axis_index: usize = drag.code % 3;
    if (drag.code < 3) {
        pos[axis_index] += drag.applied_delta;
    } else {
        const half = drag.applied_delta * 0.5;
        var delta: [4]f32 = .{ 0, 0, 0, @cos(half) };
        delta[axis_index] = @sin(half);
        rot = z3d.characterRigQuatNormalize(z3d.characterRigQuatMultiply(rot, delta));
    }
    return .{
        .bone_index = drag.bone_index,
        .pos = pos,
        .rot = rot,
        .scale = drag.start_scale,
    };
}

pub fn characterRigDrawSkeleton(
    cam: model_paint.Camera,
    matrices: *const [z3d.CHARACTER_RIG_BONE_CAP][16]f32,
    x_offset: f32,
    ox: f32,
    oy: f32,
    base_color: [3]f32,
) void {
    // Parent-child/terminal segments first, then origins, so every joint sphere
    // remains inspectable over its connected lines.
    for (z3d.g_character_rig.bones[0..z3d.g_character_rig.bone_count], 0..) |bone, index| {
        const origin = z3d.characterRigOrigin(matrices[index], x_offset);
        const endpoint = if (bone.parent_index) |parent_index|
            z3d.characterRigOrigin(matrices[parent_index], x_offset)
        else if (bone.local_tip) |tip|
            z3d.characterRigWorldPoint(matrices[index], tip, x_offset)
        else
            origin;
        const a = z3d.ovProject(cam, origin, ox, oy) orelse continue;
        const b = z3d.ovProject(cam, endpoint, ox, oy) orelse continue;
        z3d.overlayLine(a[0], a[1], b[0], b[1], base_color[0], base_color[1], base_color[2], 2.2);
        if (bone.local_tip) |tip| {
            const tip_screen = z3d.ovProject(cam, z3d.characterRigWorldPoint(matrices[index], tip, x_offset), ox, oy) orelse continue;
            z3d.overlayLine(a[0], a[1], tip_screen[0], tip_screen[1], base_color[0], base_color[1], base_color[2], 2.2);
        }
    }
    for (z3d.g_character_rig.bones[0..z3d.g_character_rig.bone_count], 0..) |_, index| {
        const origin = z3d.characterRigOrigin(matrices[index], x_offset);
        const screen = z3d.ovProject(cam, origin, ox, oy) orelse continue;
        const selected = z3d.g_character_rig.selected_bone != null and z3d.g_character_rig.selected_bone.? == index;
        const color = if (selected) z3d.OV_ORANGE else base_color;
        z3d.overlayDot(screen[0], screen[1], color[0], color[1], color[2], if (selected) 11 else 7);
        if (z3d.g_character_rig.axes) {
            for (0..3) |axis| {
                const local_axis: [3]f32 = switch (axis) {
                    0 => .{ z3d.g_character_rig.axis_length, 0, 0 },
                    1 => .{ 0, z3d.g_character_rig.axis_length, 0 },
                    else => .{ 0, 0, z3d.g_character_rig.axis_length },
                };
                const axis_end = z3d.characterRigWorldPoint(matrices[index], local_axis, x_offset);
                const end_screen = z3d.ovProject(cam, axis_end, ox, oy) orelse continue;
                const axis_color = z3d.axisColor(@intCast(axis));
                z3d.overlayLine(screen[0], screen[1], end_screen[0], end_screen[1], axis_color[0], axis_color[1], axis_color[2], if (selected) 2.2 else 1.2);
            }
        }
    }
}

pub fn characterRigDrawHoveredName(
    cam: model_paint.Camera,
    matrices: *const [z3d.CHARACTER_RIG_BONE_CAP][16]f32,
    x_offset: f32,
    ox: f32,
    oy: f32,
    specimen: character_specimen.RigSpecimen,
) void {
    const hovered = z3d.g_character_rig.hovered_joint orelse return;
    if (!character_specimen.jointNameVisible(
        z3d.g_character_rig.names,
        specimen,
        hovered.bone_index,
        hovered,
    )) return;
    const index: usize = hovered.bone_index;
    if (index >= z3d.g_character_rig.bone_count) return;
    const bone = z3d.g_character_rig.bones[index];
    const screen = z3d.ovProject(cam, z3d.characterRigOrigin(matrices[index], x_offset), ox, oy) orelse return;
    const status = switch (bone.fit_source) {
        .boundary => "B",
        .template => "T",
        .external => "E",
        .manual => "M",
    };
    var label_buffer: [z3d.CHARACTER_RIG_NAME_BYTES + 6]u8 = undefined;
    const label = std.fmt.bufPrint(&label_buffer, "{s} [{s}]", .{ bone.name[0..bone.name_len], status }) catch bone.name[0..bone.name_len];
    core.drawTextLine(label, screen[0] + 8, screen[1] - 8, 10, 0.86, 0.91, 1.0, 0.96);
}

pub fn characterRigDrawGizmo(cam: model_paint.Camera, ox: f32, oy: f32) void {
    if (!z3d.g_character_rig.joint_editable) return;
    const selected = z3d.g_character_rig.selected_bone orelse return;
    const pivot = z3d.characterRigGizmoPivot(selected);
    const face_on = z3d.gizmoFaceOnPxPerUnit(cam, pivot);
    for (0..3) |axis_index| {
        const direction = z3d.characterRigParentAxis(selected, axis_index);
        const screen = z3d.axisScreenInfo(cam, pivot, direction) orelse continue;
        if (!z3d.gizmoAxisGrabbable(screen, face_on)) continue;
        const ax = screen.ax + ox;
        const ay = screen.ay + oy;
        const tx = ax + screen.dx * z3d.GIZMO_ARM_PX;
        const ty = ay + screen.dy * z3d.GIZMO_ARM_PX;
        const translate_active = z3d.g_character_rig_gizmo.active and z3d.g_character_rig_gizmo.code == axis_index;
        const rotate_active = z3d.g_character_rig_gizmo.active and z3d.g_character_rig_gizmo.code == axis_index + 3;
        const base_color = z3d.axisColor(@intCast(axis_index));
        const translation_color = if (translate_active) z3d.GIZMO_ACTIVE else base_color;
        z3d.overlayLine(ax, ay, tx, ty, translation_color[0], translation_color[1], translation_color[2], z3d.GIZMO_SHAFT_W);
        z3d.drawGizmoArrowHead(tx, ty, screen.dx, screen.dy, translation_color);

        const rx = ax - screen.dx * (z3d.GIZMO_ARM_PX * 0.72);
        const ry = ay - screen.dy * (z3d.GIZMO_ARM_PX * 0.72);
        const rotation_color = if (rotate_active) z3d.GIZMO_ACTIVE else base_color;
        z3d.overlayDot(rx, ry, rotation_color[0], rotation_color[1], rotation_color[2], 9);
        core.drawTextLine("R", rx - 3, ry - 6, 10, 0.04, 0.05, 0.09, 0.95);
    }
    if (z3d.g_character_rig_gizmo.active) {
        var readout_buffer: [32]u8 = undefined;
        const readout = if (z3d.g_character_rig_gizmo.code < 3)
            std.fmt.bufPrint(&readout_buffer, "{d:.3} m", .{z3d.g_character_rig_gizmo.applied_delta}) catch ""
        else
            std.fmt.bufPrint(&readout_buffer, "{d:.1} deg", .{z3d.g_character_rig_gizmo.applied_delta * 180.0 / std.math.pi}) catch "";
        if (z3d.ovProject(cam, pivot, ox, oy)) |screen| {
            core.drawTextLine(readout, screen[0] + 12, screen[1] + 12, 11, 1.0, 0.86, 0.38, 0.98);
        }
    }
}

pub fn drawCharacterRigOverlay(cam: model_paint.Camera, ox: f32, oy: f32) void {
    if (!z3d.g_character_rig.active) return;
    // Sample the host-owned pointer during native paint. This stays current as
    // the camera, pose, or pane moves without introducing a pointer-motion
    // callback or a React render loop.
    z3d.characterRigUpdateHoveredJoint(mouse_state.g_mouse_x, mouse_state.g_mouse_y);
    if (z3d.g_character_rig.bind_mesh) {
        z3d.characterRigDrawSkeleton(cam, &z3d.g_character_rig.bind_global, 0, ox, oy, .{ 0.30, 0.82, 1.0 });
    }
    if (z3d.g_character_rig.deformed_mesh) {
        z3d.characterRigDrawSkeleton(cam, &z3d.g_character_rig.pose_global, z3d.g_character_rig.specimen_separation, ox, oy, .{ 0.42, 0.94, 0.62 });
    }
    z3d.characterRigDrawGizmo(cam, ox, oy);
    if (z3d.g_character_rig.selected_vertex_position) |position| if (z3d.g_character_rig.bind_mesh) {
        if (z3d.ovProject(cam, position, ox, oy)) |screen| {
            z3d.overlayDot(screen[0], screen[1], z3d.OV_ORANGE[0], z3d.OV_ORANGE[1], z3d.OV_ORANGE[2], 10);
        }
    };
    z3d.overlayLayerBreak(ox, oy);
    if (z3d.g_character_rig.bind_mesh) z3d.characterRigDrawHoveredName(cam, &z3d.g_character_rig.bind_global, 0, ox, oy, .bind);
    if (z3d.g_character_rig.deformed_mesh) z3d.characterRigDrawHoveredName(cam, &z3d.g_character_rig.pose_global, z3d.g_character_rig.specimen_separation, ox, oy, .deformed);
}

pub fn characterRigBoneHitInSkeleton(
    cam: model_paint.Camera,
    matrices: *const [z3d.CHARACTER_RIG_BONE_CAP][16]f32,
    x_offset: f32,
    mx: f32,
    my: f32,
    best_distance: *f32,
    best_index: *?u8,
) void {
    for (z3d.g_character_rig.bones[0..z3d.g_character_rig.bone_count], 0..) |bone, index| {
        const origin = z3d.ovProject(cam, z3d.characterRigOrigin(matrices[index], x_offset), z3d.g_paint_vp_x, z3d.g_paint_vp_y) orelse continue;
        const dx = origin[0] - mx;
        const dy = origin[1] - my;
        const point_distance = dx * dx + dy * dy;
        if (point_distance <= z3d.CHARACTER_RIG_JOINT_HIT_RADIUS_PX * z3d.CHARACTER_RIG_JOINT_HIT_RADIUS_PX and point_distance < best_distance.*) {
            best_distance.* = point_distance;
            best_index.* = @intCast(index);
        }
        const endpoint_world = if (bone.parent_index) |parent_index|
            z3d.characterRigOrigin(matrices[parent_index], x_offset)
        else if (bone.local_tip) |tip|
            z3d.characterRigWorldPoint(matrices[index], tip, x_offset)
        else
            continue;
        const endpoint = z3d.ovProject(cam, endpoint_world, z3d.g_paint_vp_x, z3d.g_paint_vp_y) orelse continue;
        const line_distance = z3d.segDist2(mx, my, origin[0], origin[1], endpoint[0], endpoint[1]);
        if (line_distance <= 7.0 * 7.0 and line_distance < best_distance.*) {
            best_distance.* = line_distance;
            best_index.* = @intCast(index);
        }
    }
}

pub fn characterRigJointHoverInSkeleton(
    cam: model_paint.Camera,
    matrices: *const [z3d.CHARACTER_RIG_BONE_CAP][16]f32,
    x_offset: f32,
    specimen: character_specimen.RigSpecimen,
    mx: f32,
    my: f32,
    best_distance: *f32,
    best_target: *?character_specimen.HoveredJoint,
) void {
    for (z3d.g_character_rig.bones[0..z3d.g_character_rig.bone_count], 0..) |_, index| {
        const origin = z3d.ovProject(cam, z3d.characterRigOrigin(matrices[index], x_offset), z3d.g_paint_vp_x, z3d.g_paint_vp_y) orelse continue;
        const dx = origin[0] - mx;
        const dy = origin[1] - my;
        const distance = dx * dx + dy * dy;
        if (distance <= z3d.CHARACTER_RIG_JOINT_HIT_RADIUS_PX * z3d.CHARACTER_RIG_JOINT_HIT_RADIUS_PX and distance < best_distance.*) {
            best_distance.* = distance;
            best_target.* = .{
                .specimen = specimen,
                .bone_index = @intCast(index),
            };
        }
    }
}

pub fn characterRigHoveredJointAt(mx: f32, my: f32) ?character_specimen.HoveredJoint {
    if (!z3d.g_character_rig.active or !z3d.g_character_rig.names or
        z3d.g_paint_vp_w <= 0 or z3d.g_paint_vp_h <= 0 or
        mx < z3d.g_paint_vp_x or mx > z3d.g_paint_vp_x + z3d.g_paint_vp_w or
        my < z3d.g_paint_vp_y or my > z3d.g_paint_vp_y + z3d.g_paint_vp_h)
    {
        return null;
    }
    const cam = model_paint.Camera{ .eye = z3d.g_paint_eye, .target = z3d.g_paint_target, .fov_deg = z3d.g_paint_fov };
    var best_distance = std.math.inf(f32);
    var best_target: ?character_specimen.HoveredJoint = null;
    if (z3d.g_character_rig.bind_mesh) {
        z3d.characterRigJointHoverInSkeleton(cam, &z3d.g_character_rig.bind_global, 0, .bind, mx, my, &best_distance, &best_target);
    }
    if (z3d.g_character_rig.deformed_mesh) {
        z3d.characterRigJointHoverInSkeleton(
            cam,
            &z3d.g_character_rig.pose_global,
            z3d.g_character_rig.specimen_separation,
            .deformed,
            mx,
            my,
            &best_distance,
            &best_target,
        );
    }
    return best_target;
}

pub fn characterRigUpdateHoveredJoint(mx: f32, my: f32) void {
    z3d.g_character_rig.hovered_joint = z3d.characterRigHoveredJointAt(mx, my);
}

pub fn characterRigPickBone(mx: f32, my: f32) ?u8 {
    if (!z3d.g_character_rig.active or z3d.g_paint_vp_w <= 0 or z3d.g_paint_vp_h <= 0) return null;
    const cam = model_paint.Camera{ .eye = z3d.g_paint_eye, .target = z3d.g_paint_target, .fov_deg = z3d.g_paint_fov };
    var best_distance = std.math.inf(f32);
    var best_index: ?u8 = null;
    if (z3d.g_character_rig.bind_mesh) z3d.characterRigBoneHitInSkeleton(cam, &z3d.g_character_rig.bind_global, 0, mx, my, &best_distance, &best_index);
    if (z3d.g_character_rig.deformed_mesh) z3d.characterRigBoneHitInSkeleton(cam, &z3d.g_character_rig.pose_global, z3d.g_character_rig.specimen_separation, mx, my, &best_distance, &best_index);
    return best_index;
}

/// Raycast the exact drawn character surface and return its nearest triangle
/// corner's durable logical id. UV/normal duplicates therefore collapse to the
/// same inspection record without any position-based weld discovery.
pub fn characterRigPickLogicalVertex(mx: f32, my: f32) ?u32 {
    if (!model_paint.hasTarget() or z3d.g_paint_vp_w <= 0 or z3d.g_paint_vp_h <= 0) return null;
    const logical_ids = model_source.renderCornerLogicalIds() orelse return null;
    const cam = model_paint.Camera{ .eye = z3d.g_paint_eye, .target = z3d.g_paint_target, .fov_deg = z3d.g_paint_fov };
    const hit = model_paint.pickBary(cam, z3d.g_paint_vp_w, z3d.g_paint_vp_h, z3d.vpLocalX(mx), z3d.vpLocalY(my)) orelse return null;
    const source_face = model_source.sourceFaceOf(hit.face) orelse return null;
    const corner: usize = if (hit.u >= hit.v and hit.u >= 1.0 - hit.u - hit.v)
        1
    else if (hit.v >= 1.0 - hit.u - hit.v)
        2
    else
        0;
    const at = @as(usize, source_face) * 3 + corner;
    return if (at < logical_ids.len) logical_ids[at] else null;
}

/// The visible outliner part under the pointer when it is outside the current
/// edit scope.  The engine asks before an element pick so one click can focus a
/// different part and then perform the requested vertex/edge/face selection.
pub fn meshEditOutOfScopePartAt(mx: f32, my: f32) i32 {
    if (!model_paint.hasTarget()) return -1;
    const cam = model_paint.Camera{ .eye = z3d.g_paint_eye, .target = z3d.g_paint_target, .fov_deg = z3d.g_paint_fov };
    const face = model_paint.pick(cam, z3d.g_paint_vp_w, z3d.g_paint_vp_h, z3d.vpLocalX(mx), z3d.vpLocalY(my));
    if (face < 0 or mesh_edit.faceInScopePub(@intCast(face))) return -1;
    const part = model_source.partIndexOf(model_source.faceGroupOf(@intCast(face)));
    return if (part == model_source.NO_PART) -1 else @intCast(part);
}
pub fn meshEditClear() void {
    mesh_edit.clearSelection();
}
/// Mesh-editor Ctrl+A — select every element of the current mode within the focused part
/// (or the whole model). Returns the selected count, -1 if no mesh.
pub fn meshEditSelectAll() i32 {
    if (z3d.g_paint_session) return -1;
    return mesh_edit.selectAll();
}
pub fn meshSetMarquee(x0: f32, y0: f32, x1: f32, y1: f32) void {
    z3d.g_mq = .{ x0, y0, x1, y1 };
    z3d.g_mq_active = true;
}
pub fn meshClearMarquee() void {
    z3d.g_mq_active = false;
}

// Overlay colours (0..1) + sizes (px). Orange matches the face tint. Each dot/line is drawn
// twice — a dark HALO under a bright fill — so it pops on a white model AND a dark void (a
// single colour can't contrast with both).
pub const OV_ORANGE = [3]f32{ 1.0, 0.52, 0.16 }; // selected
pub const OV_HALO = [4]f32{ 0.02, 0.03, 0.07, 0.95 }; // dark outline behind every marker
pub const OV_MARQUEE = [4]f32{ 0.62, 0.78, 1.0, 0.98 };
