import { classifier, classifiers as C, getColors, setStyleTokens, setTokens } from '../../runtime/classifier';
import { EDITOR_COLORS, EDITOR_STYLES } from './theme';

setTokens(EDITOR_COLORS);
setStyleTokens(EDITOR_STYLES);

export function accentFor(token: string): string {
  return (getColors() as Record<string, string>)[token] ?? token;
}

const MONO = 'monospace';

classifier({
  HW_App: { type: 'Box', style: { width: '100%', height: '100%', flexDirection: 'column', position: 'relative', backgroundColor: 'theme:bg', overflow: 'hidden' } },
  HW_Chrome: { type: 'Box', style: { height: 37, flexDirection: 'row', alignItems: 'center', gap: 10, paddingLeft: 10, paddingRight: 10, backgroundColor: 'theme:surface', borderBottomWidth: 'theme:borderThin', borderBottomColor: 'theme:border' } },
  HW_Brand: { type: 'Box', style: { width: 136, height: '100%', flexDirection: 'row', alignItems: 'center', gap: 7, borderRightWidth: 'theme:borderThin', borderRightColor: 'theme:borderSoft' } },
  HW_BrandText: { type: 'Text', fontSize: 10, color: 'theme:textSecondary', style: { fontFamily: MONO, fontWeight: 800, letterSpacing: 2 } },
  HW_MenuBar: { type: 'Box', style: { flexDirection: 'row', alignItems: 'center', gap: 2, height: '100%' } },
  HW_MenuItem: { type: 'Pressable', style: { height: 28, alignItems: 'center', justifyContent: 'center', paddingLeft: 9, paddingRight: 9, borderRadius: 'theme:radiusLg' }, hoverStyle: { backgroundColor: 'theme:surfaceHover' } },
  HW_MenuItemOn: { type: 'Pressable', style: { height: 28, alignItems: 'center', justifyContent: 'center', paddingLeft: 9, paddingRight: 9, borderRadius: 'theme:radiusLg', backgroundColor: 'theme:bgElevated' } },
  HW_MenuText: { type: 'Text', fontSize: 11, color: 'theme:textSecondary' },
  HW_MenuTextOn: { type: 'Text', fontSize: 11, color: 'theme:text' },
  HW_Spacer: { type: 'Box', style: { flexGrow: 1, minWidth: 0 } },
  HW_Pill: { type: 'Pressable', style: { height: 24, flexDirection: 'row', alignItems: 'center', gap: 6, paddingLeft: 8, paddingRight: 8, borderRadius: 'theme:radiusLg', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' }, hoverStyle: { borderColor: 'theme:textDim' } },
  HW_PillOn: { type: 'Pressable', style: { height: 24, flexDirection: 'row', alignItems: 'center', gap: 6, paddingLeft: 9, paddingRight: 9, borderRadius: 'theme:radiusLg', backgroundColor: 'theme:segActiveBg', borderWidth: 'theme:borderThin', borderColor: 'theme:primary' } },
  HW_PillText: { type: 'Text', fontSize: 10, color: 'theme:textSecondary', style: { fontFamily: MONO, fontWeight: 700 } },
  HW_PillTextOn: { type: 'Text', fontSize: 10, color: 'theme:segActiveText', style: { fontFamily: MONO, fontWeight: 800 } },
  HW_Compile: { type: 'Pressable', style: { height: 26, flexDirection: 'row', alignItems: 'center', gap: 7, paddingLeft: 12, paddingRight: 12, borderRadius: 'theme:radiusLg', borderWidth: 'theme:borderThin', borderColor: 'theme:primary', backgroundColor: 'theme:compileBg' }, hoverStyle: { backgroundColor: 'theme:compileBgHover' } },
  HW_BuildDock: { type: 'Box', style: { height: 31, flexDirection: 'row', alignItems: 'center', gap: 10, paddingLeft: 10, paddingRight: 10, backgroundColor: 'theme:surface', borderTopWidth: 'theme:borderThin', borderTopColor: 'theme:border' } },
  HW_DockBuild: { type: 'Pressable', style: { height: 24, flexDirection: 'row', alignItems: 'center', gap: 7, paddingLeft: 7, paddingRight: 7, borderRadius: 'theme:radiusMd', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' }, hoverStyle: { borderColor: 'theme:primary' } },
  HW_DockGroup: { type: 'Box', style: { height: 24, flexDirection: 'row', alignItems: 'center', gap: 7 } },
  HW_DockDivider: { type: 'Box', style: { width: 1, height: 18, backgroundColor: 'theme:borderSoft' } },
  HW_DockLabel: { type: 'Text', fontSize: 9, color: 'theme:textFaint', style: { fontFamily: MONO, fontWeight: 800 } },
  HW_DockValue: { type: 'Text', fontSize: 10, color: 'theme:textSecondary', style: { fontFamily: MONO, fontWeight: 800 } },
  HW_DockCoord: { type: 'Text', fontSize: 10, color: 'theme:valNum', style: { fontFamily: MONO, fontWeight: 900 } },
  HW_DockPopover: { type: 'Box', style: { position: 'absolute', left: 188, bottom: 36, width: 760, height: 360, flexDirection: 'column', borderRadius: 'theme:radiusLg', backgroundColor: 'theme:bgAlt', borderWidth: 'theme:borderThin', borderColor: 'theme:primary', overflow: 'hidden' } },
  HW_DockPopoverHead: { type: 'Box', style: { height: 39, flexDirection: 'row', alignItems: 'center', gap: 8, paddingLeft: 10, paddingRight: 10, backgroundColor: 'theme:surface', borderBottomWidth: 'theme:borderThin', borderBottomColor: 'theme:border' } },
  HW_DockPerfGrid: { type: 'Box', style: { height: 78, flexDirection: 'row', gap: 8, padding: 10, borderBottomWidth: 'theme:borderThin', borderBottomColor: 'theme:borderSoft' } },
  HW_PerfTile: { type: 'Box', style: { flexGrow: 1, minWidth: 0, alignItems: 'center', justifyContent: 'center', gap: 3, borderRadius: 'theme:radiusMd', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' } },
  HW_PerfValue: { type: 'Text', fontSize: 17, color: 'theme:valNum', style: { fontFamily: MONO, fontWeight: 900 } },
  HW_PerfLabel: { type: 'Text', fontSize: 9, color: 'theme:textDim', style: { fontFamily: MONO, fontWeight: 800 } },
  HW_DockPerfButton: { type: 'Pressable', style: { height: 24, flexDirection: 'row', alignItems: 'center', gap: 7, paddingLeft: 7, paddingRight: 7, borderRadius: 'theme:radiusMd', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' }, hoverStyle: { borderColor: 'theme:primary' } },
  HW_PerfPopover: { type: 'Box', style: { position: 'absolute', right: 18, bottom: 36, width: 900, height: 650, flexDirection: 'column', borderRadius: 'theme:radiusLg', backgroundColor: 'theme:bgAlt', borderWidth: 'theme:borderThin', borderColor: 'theme:primary', overflow: 'hidden' } },
  HW_PerfSummarySurface: { type: 'StaticSurface', style: { height: 78 } },
  HW_ChurnSummary: { type: 'Box', style: { height: 32, flexDirection: 'row', alignItems: 'center', gap: 8, paddingLeft: 12, paddingRight: 12, borderBottomWidth: 'theme:borderThin', borderBottomColor: 'theme:borderSoft' } },
  HW_ChurnSummarySurface: { type: 'StaticSurface', style: { height: 32 } },
  HW_MemoryConsumers: { type: 'Box', style: { height: 116, flexDirection: 'column', gap: 0, paddingTop: 8, paddingBottom: 8, backgroundColor: 'theme:bgAlt', borderBottomWidth: 'theme:borderThin', borderBottomColor: 'theme:borderSoft', overflow: 'hidden' } },
  HW_TopConsumers: { type: 'Box', style: { height: 139, flexDirection: 'column', gap: 0, paddingTop: 8, paddingBottom: 8, backgroundColor: 'theme:bgElevated', borderBottomWidth: 'theme:borderThin', borderBottomColor: 'theme:borderSoft', overflow: 'hidden' } },
  HW_TopConsumerScroll: { type: 'ScrollView', style: { flexGrow: 1, minHeight: 0, paddingLeft: 10, paddingRight: 10 }, contentContainerStyle: { flexDirection: 'column', gap: 5, paddingBottom: 4 } },
  HW_TopConsumerRows: { type: 'Box', style: { flexDirection: 'column', gap: 5 } },
  HW_TopConsumerRow: { type: 'Box', style: { height: 18, flexDirection: 'row', alignItems: 'center', gap: 7, paddingLeft: 8, paddingRight: 8, borderRadius: 'theme:radiusMd', backgroundColor: 'theme:cardBg', borderWidth: 'theme:borderThin', borderColor: 'theme:borderSoft' } },
  HW_ChurnColumns: { type: 'Box', style: { flexGrow: 1, minHeight: 0, flexDirection: 'row', gap: 10, padding: 10 } },
  HW_ChurnSurface: { type: 'StaticSurface', style: { flexGrow: 1, minWidth: 0, height: '100%' } },
  HW_ChurnColumn: { type: 'Box', style: { flexGrow: 1, minWidth: 0, flexDirection: 'column', gap: 5, borderRadius: 'theme:radiusMd', backgroundColor: 'theme:cardBg', borderWidth: 'theme:borderThin', borderColor: 'theme:borderSoft', paddingTop: 7, paddingBottom: 7, overflow: 'scroll' } },
  HW_ChurnRow: { type: 'Box', style: { height: 22, flexDirection: 'row', alignItems: 'center', gap: 7, paddingLeft: 9, paddingRight: 9 } },
  HW_ChurnBar: { type: 'Box', style: { flexGrow: 1, minWidth: 0, height: 5, borderRadius: 3, backgroundColor: 'theme:track', overflow: 'hidden' } },
  HW_ChurnFill: { type: 'Box', style: { height: '100%', borderRadius: 3, backgroundColor: 'theme:primary' } },
  HW_ChurnStatRow: { type: 'Box', style: { height: 24, flexDirection: 'row', alignItems: 'center', gap: 7, paddingLeft: 9, paddingRight: 9, borderTopWidth: 'theme:borderThin', borderTopColor: 'theme:borderSoft' } },
  HW_ChurnFactGrid: { type: 'Box', style: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, paddingLeft: 9, paddingRight: 9 } },
  HW_ChurnFact: { type: 'Box', style: { width: 76, height: 30, alignItems: 'center', justifyContent: 'center', borderRadius: 'theme:radiusMd', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' } },
  HW_ChurnEmpty: { type: 'Box', style: { position: 'absolute', right: 22, bottom: 12, height: 24, flexDirection: 'row', alignItems: 'center', gap: 7, paddingLeft: 9, paddingRight: 9, borderRadius: 'theme:radiusMd', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:borderSoft' } },
  HW_DockTrace: { type: 'Box', style: { height: 82, flexDirection: 'column', paddingTop: 8, borderBottomWidth: 'theme:borderThin', borderBottomColor: 'theme:borderSoft' } },
  HW_Sparkline: { type: 'Box', style: { flexGrow: 1, minHeight: 0, flexDirection: 'row', alignItems: 'flex-end', gap: 5, paddingLeft: 12, paddingRight: 12, paddingBottom: 10 } },
  HW_SparkCell: { type: 'Box', style: { width: 15, borderRadius: 'theme:radiusSm', backgroundColor: 'theme:primary' } },
  HW_EventSummary: { type: 'Box', style: { height: 33, flexDirection: 'row', alignItems: 'center', gap: 12, paddingLeft: 12, paddingRight: 12, borderBottomWidth: 'theme:borderThin', borderBottomColor: 'theme:borderSoft' } },
  HW_DockHistoryRows: { type: 'Box', style: { flexGrow: 1, minHeight: 0, flexDirection: 'column', paddingTop: 6, paddingBottom: 6, overflow: 'scroll' } },
  HW_DockHistoryRow: { type: 'Box', style: { height: 24, flexDirection: 'row', alignItems: 'center', gap: 8, paddingLeft: 12, paddingRight: 12, borderBottomWidth: 'theme:borderThin', borderBottomColor: 'theme:borderSoft' } },
  HW_DialogScrim: { type: 'Box', blocksPointerEvents: true, style: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 31, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(0,0,0,0.48)' } },
  HW_BuildDialog: { type: 'Box', style: { width: 900, height: 620, flexDirection: 'column', borderRadius: 'theme:radiusLg', backgroundColor: 'theme:bgAlt', borderWidth: 'theme:borderThin', borderColor: 'theme:primary', overflow: 'hidden' } },
  HW_DialogHead: { type: 'Box', style: { height: 42, flexDirection: 'row', alignItems: 'center', gap: 9, paddingLeft: 12, paddingRight: 10, backgroundColor: 'theme:surface', borderBottomWidth: 'theme:borderThin', borderBottomColor: 'theme:border' } },
  HW_DialogBody: { type: 'Box', style: { flexGrow: 1, minHeight: 0, flexDirection: 'column', padding: 12, gap: 10 } },
  HW_JournalIntro: { type: 'Box', style: { minHeight: 58, gap: 6, padding: 10, borderRadius: 'theme:radiusLg', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' } },
  HW_JournalLayout: { type: 'Box', style: { flexGrow: 1, minHeight: 0, flexDirection: 'row', gap: 12 } },
  HW_JournalColumn: { type: 'Box', style: { flexGrow: 1, minWidth: 0, flexDirection: 'column', gap: 8, overflow: 'scroll' } },
  HW_BuildNoteCard: { type: 'Box', style: { minHeight: 92, gap: 6, padding: 9, borderRadius: 'theme:radiusLg', backgroundColor: 'theme:cardBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' } },
  HW_BuildNoteHead: { type: 'Box', style: { minHeight: 21, flexDirection: 'row', alignItems: 'center', gap: 7 } },
  HW_TraceRow: { type: 'Box', style: { flexDirection: 'row', flexWrap: 'wrap', gap: 5 } },
  HW_TraceChip: { type: 'Box', style: { height: 19, justifyContent: 'center', paddingLeft: 7, paddingRight: 7, borderRadius: 'theme:radiusMd', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:borderSoft' } },
  HW_ThreadCard: { type: 'Box', style: { minHeight: 108, gap: 6, padding: 9, borderRadius: 'theme:radiusLg', backgroundColor: 'theme:cardBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' } },

  HW_Body: { type: 'Box', style: { flexGrow: 1, minHeight: 0, flexDirection: 'row' } },
  HW_LeftRail: { type: 'Box', style: { width: 48, height: '100%', alignItems: 'center', gap: 7, paddingTop: 8, paddingBottom: 8, backgroundColor: 'theme:surface', borderRightWidth: 'theme:borderThin', borderRightColor: 'theme:border' } },
  HW_RailButton: { type: 'Pressable', style: { width: 32, height: 32, alignItems: 'center', justifyContent: 'center', borderRadius: 'theme:radiusLg' }, hoverStyle: { backgroundColor: 'theme:surfaceHover' } },
  HW_RailButtonOn: { type: 'Pressable', style: { width: 34, height: 34, alignItems: 'center', justifyContent: 'center', borderRadius: 'theme:radiusLg', borderWidth: 'theme:borderThin', borderColor: 'theme:primary', backgroundColor: 'theme:segActiveBg' } },
  HW_SidePanel: { type: 'Box', style: { width: 350, height: '100%', flexDirection: 'column', backgroundColor: 'theme:bgAlt', borderRightWidth: 'theme:borderThin', borderRightColor: 'theme:border' } },
  HW_PanelHead: { type: 'Box', style: { height: 30, flexDirection: 'row', alignItems: 'center', gap: 7, paddingLeft: 12, paddingRight: 10, borderBottomWidth: 'theme:borderThin', borderBottomColor: 'theme:border' } },
  HW_Kicker: { type: 'Text', fontSize: 9, color: 'theme:textFaint', style: { fontFamily: MONO, fontWeight: 800, letterSpacing: 1.5 } },
  HW_HeadTitle: { type: 'Text', fontSize: 12, color: 'theme:text', style: { fontWeight: 800 } },
  HW_Search: { type: 'TextInput', style: { height: 25, marginLeft: 10, marginRight: 10, marginTop: 7, marginBottom: 5, paddingLeft: 9, paddingRight: 8, borderRadius: 'theme:radiusLg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder', backgroundColor: 'theme:controlBg', color: 'theme:textSecondary', fontSize: 11 } },
  HW_ContentTree: { type: 'Box', style: { height: 100, flexShrink: 0, flexDirection: 'column', paddingLeft: 7, paddingRight: 7, paddingTop: 2, paddingBottom: 3, borderBottomWidth: 'theme:borderThin', borderBottomColor: 'theme:border', overflow: 'scroll' } },
  HW_TreeRow: { type: 'Pressable', style: { height: 15, flexDirection: 'row', alignItems: 'center', gap: 4, paddingLeft: 2, paddingRight: 6, borderRadius: 'theme:radiusMd' }, hoverStyle: { backgroundColor: 'theme:surfaceHover' } },
  HW_TreeRowOn: { type: 'Pressable', style: { height: 15, flexDirection: 'row', alignItems: 'center', gap: 4, paddingLeft: 2, paddingRight: 6, borderRadius: 'theme:radiusMd', backgroundColor: 'theme:segActiveBg', borderWidth: 'theme:borderThin', borderColor: 'theme:borderSoft' } },
  HW_TreeIndent: { type: 'Box', style: { width: 10, height: 1, backgroundColor: 'transparent' } },
  HW_TreeToggle: { type: 'Pressable', style: { width: 12, height: 14, alignItems: 'center', justifyContent: 'center' }, hoverStyle: { backgroundColor: 'theme:controlBg' } },
  HW_TreeLabel: { type: 'Text', fontSize: 10, color: 'theme:textSecondary', style: { fontFamily: MONO, fontWeight: 800 } },
  HW_TreeCount: { type: 'Text', fontSize: 8, color: 'theme:textFaint', style: { fontFamily: MONO, fontWeight: 800 } },
  HW_ContentCrumb: { type: 'Box', style: { height: 25, flexDirection: 'row', alignItems: 'center', gap: 7, paddingLeft: 12, paddingRight: 10, borderBottomWidth: 'theme:borderThin', borderBottomColor: 'theme:borderSoft' } },
  HW_FolderSummary: { type: 'Box', style: { height: 142, alignItems: 'center', justifyContent: 'center', gap: 8, marginLeft: 10, marginRight: 10, marginBottom: 8, borderRadius: 'theme:radiusLg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder', backgroundColor: 'theme:controlBg' } },
  HW_TabRow: { type: 'Box', style: { flexDirection: 'row', gap: 5, paddingLeft: 10, paddingRight: 10, marginBottom: 8 } },
  HW_Tab: { type: 'Pressable', style: { flexGrow: 1, height: 24, alignItems: 'center', justifyContent: 'center', borderRadius: 'theme:radiusMd', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' } },
  HW_TabOn: { type: 'Pressable', style: { flexGrow: 1, height: 24, alignItems: 'center', justifyContent: 'center', borderRadius: 'theme:radiusMd', backgroundColor: 'theme:segActiveBg', borderWidth: 'theme:borderThin', borderColor: 'theme:primary' } },
  HW_TabText: { type: 'Text', fontSize: 10, color: 'theme:textDim', style: { fontFamily: MONO, fontWeight: 700 } },
  HW_TabTextOn: { type: 'Text', fontSize: 10, color: 'theme:segActiveText', style: { fontFamily: MONO, fontWeight: 800 } },
  HW_AssetGrid: { type: 'Box', style: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, paddingLeft: 10, paddingRight: 10, paddingBottom: 8 } },
  HW_EmptyState: { type: 'Box', style: { width: '100%', height: 78, alignItems: 'center', justifyContent: 'center', gap: 7, borderRadius: 'theme:radiusLg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder', backgroundColor: 'theme:controlBg' } },
  HW_AssetCard: { type: 'Pressable', style: { width: 76, height: 68, borderRadius: 'theme:radiusLg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder', backgroundColor: 'theme:cardBg', overflow: 'hidden' }, hoverStyle: { borderColor: 'theme:textDim' } },
  HW_AssetCardOn: { type: 'Pressable', style: { width: 76, height: 68, borderRadius: 'theme:radiusLg', borderWidth: 2, borderColor: 'theme:primary', backgroundColor: 'theme:cardBg', overflow: 'hidden' } },
  HW_AssetSwatch: { type: 'Box', style: { height: 42, borderBottomWidth: 'theme:borderThin', borderBottomColor: 'theme:borderSoft' } },
  HW_AssetLabel: { type: 'Text', fontSize: 9, color: 'theme:textSecondary', style: { fontFamily: MONO, textAlign: 'center', paddingTop: 5 } },
  HW_AssetMeta: { type: 'Text', fontSize: 8, color: 'theme:textFaint', style: { fontFamily: MONO, textAlign: 'center', paddingTop: 1 } },
  HW_PageBar: { type: 'Box', style: { height: 25, flexDirection: 'row', alignItems: 'center', gap: 6, paddingLeft: 10, paddingRight: 10, marginBottom: 2 } },
  HW_PageText: { type: 'Text', fontSize: 9, color: 'theme:textDim', style: { fontFamily: MONO, fontWeight: 700 } },
  HW_ModelBrowser: { type: 'Box', style: { height: 421, flexDirection: 'column', gap: 5, paddingLeft: 10, paddingRight: 10, paddingBottom: 6, overflow: 'hidden' } },
  HW_ModelCard: { type: 'Pressable', style: { height: 68, flexDirection: 'row', alignItems: 'center', gap: 7, padding: 6, borderRadius: 'theme:radiusLg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder', backgroundColor: 'theme:cardBg' }, hoverStyle: { borderColor: 'theme:textDim' } },
  HW_ModelThumb: { type: 'Box', style: { width: 44, height: 52, borderRadius: 'theme:radiusMd', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' } },
  HW_ModelCardMain: { type: 'Box', style: { flexGrow: 1, minWidth: 0, flexDirection: 'column', gap: 3 } },
  HW_ModelPath: { type: 'Text', fontSize: 8, color: 'theme:textDim', style: { fontFamily: MONO, fontWeight: 800 } },
  HW_ModelMetaRow: { type: 'Box', style: { minHeight: 11, flexDirection: 'row', alignItems: 'center', gap: 8 } },
  HW_ModelHomePanel: { type: 'Box', style: { flexGrow: 1, minHeight: 0, flexDirection: 'column', gap: 5 } },
  HW_ModelTop: { type: 'Box', style: { height: 60, flexDirection: 'row', alignItems: 'center', gap: 8, padding: 6, borderRadius: 'theme:radiusLg', borderWidth: 'theme:borderThin', borderColor: 'theme:primary', backgroundColor: 'theme:segActiveBg' } },
  HW_ModelSection: { type: 'Box', style: { flexDirection: 'column', gap: 4, paddingTop: 2 } },
  HW_ModelSectionHead: { type: 'Box', style: { height: 17, flexDirection: 'row', alignItems: 'center', gap: 6 } },
  HW_ModelDataRow: { type: 'Pressable', style: { height: 19, flexDirection: 'row', alignItems: 'center', gap: 7, paddingLeft: 7, paddingRight: 7, borderRadius: 'theme:radiusMd', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:borderSoft' }, hoverStyle: { borderColor: 'theme:primary' } },
  HW_ModelAtlasCard: { type: 'Pressable', style: { height: 34, flexDirection: 'row', alignItems: 'center', gap: 7, paddingLeft: 7, paddingRight: 7, borderRadius: 'theme:radiusMd', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' }, hoverStyle: { borderColor: 'theme:primary' } },
  HW_ModelPaintGrid: { type: 'Box', style: { height: 50, flexDirection: 'row', gap: 6 } },
  HW_ModelPaintCard: { type: 'Pressable', style: { flexGrow: 1, minWidth: 0, alignItems: 'center', justifyContent: 'center', gap: 2, borderRadius: 'theme:radiusLg', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' }, hoverStyle: { borderColor: 'theme:primary' } },
  HW_MaterialGrid: { type: 'Box', style: { height: 284, flexShrink: 0, flexDirection: 'row', flexWrap: 'wrap', alignContent: 'flex-start', justifyContent: 'space-between', gap: 4, paddingLeft: 10, paddingRight: 10, paddingBottom: 4, overflow: 'hidden' } },
  HW_MaterialTile: { type: 'Pressable', style: { width: 68, height: 68, position: 'relative', borderRadius: 'theme:radiusMd', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder', backgroundColor: 'theme:cardBg', overflow: 'hidden' }, hoverStyle: { borderColor: 'theme:textDim' } },
  HW_MaterialTileOn: { type: 'Pressable', style: { width: 68, height: 68, position: 'relative', borderRadius: 'theme:radiusMd', borderWidth: 2, borderColor: 'theme:primary', backgroundColor: 'theme:segActiveBg', overflow: 'hidden' } },
  HW_MaterialTileEmpty: { type: 'Box', style: { width: 68, height: 68, borderRadius: 'theme:radiusMd', borderWidth: 'theme:borderThin', borderColor: 'theme:borderSoft', backgroundColor: 'theme:controlBg' } },
  HW_MaterialTilePreview: { type: 'Box', style: { width: 68, height: 68, overflow: 'hidden', backgroundColor: 'theme:controlBg' } },
  HW_MaterialTileImage: { type: 'Image', style: { width: '100%', height: '100%', objectFit: 'cover' } },
  HW_MaterialTileName: { type: 'Text', fontSize: 7, color: 'theme:text', style: { position: 'absolute', left: 0, right: 0, bottom: 0, height: 12, backgroundColor: 'rgba(4, 10, 14, 0.78)', fontFamily: MONO, fontWeight: 800, paddingTop: 1, paddingLeft: 3, paddingRight: 3, textAlign: 'center' } },
  HW_PreviewFallback: { type: 'Box', style: { width: '100%', height: '100%' } },
  HW_DecalPreviewFrame: { type: 'Box', style: { width: 68, height: 68, overflow: 'hidden' } },
  HW_MaterialList: { type: 'Box', style: { height: 421, flexDirection: 'column', gap: 5, paddingLeft: 10, paddingRight: 10, paddingBottom: 6, overflow: 'hidden' } },
  HW_MaterialCard: { type: 'Pressable', style: { height: 64, flexDirection: 'row', gap: 7, padding: 6, borderRadius: 'theme:radiusLg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder', backgroundColor: 'theme:cardBg' }, hoverStyle: { borderColor: 'theme:textDim' } },
  HW_MaterialCardOn: { type: 'Pressable', style: { height: 64, flexDirection: 'row', gap: 7, padding: 6, borderRadius: 'theme:radiusLg', borderWidth: 2, borderColor: 'theme:primary', backgroundColor: 'theme:segActiveBg' } },
  HW_MaterialSlotEmpty: { type: 'Box', style: { height: 64, alignItems: 'center', justifyContent: 'center', borderRadius: 'theme:radiusLg', borderWidth: 'theme:borderThin', borderColor: 'theme:borderSoft', backgroundColor: 'theme:controlBg' } },
  HW_MaterialSwatch: { type: 'Box', style: { width: 43, height: 50, borderRadius: 'theme:radiusMd', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' } },
  HW_MaterialInfo: { type: 'Box', style: { flexGrow: 1, minWidth: 0, flexDirection: 'column', gap: 3 } },
  HW_MaterialTitleRow: { type: 'Box', style: { height: 15, flexDirection: 'row', alignItems: 'center', gap: 6 } },
  HW_MaterialName: { type: 'Text', fontSize: 11, color: 'theme:text', style: { fontFamily: MONO, fontWeight: 900 } },
  HW_MaterialStatsRow: { type: 'Box', style: { height: 11, flexDirection: 'row', gap: 8, alignItems: 'center' } },
  HW_MaterialStat: { type: 'Text', fontSize: 8, color: 'theme:textDim', style: { fontFamily: MONO, fontWeight: 700 } },
  HW_VariantStrip: { type: 'Box', style: { flexDirection: 'row', gap: 5 } },
  HW_VariantPill: { type: 'Pressable', style: { flexGrow: 1, height: 20, flexDirection: 'row', alignItems: 'center', gap: 5, paddingLeft: 5, paddingRight: 5, borderRadius: 'theme:radiusMd', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' }, hoverStyle: { borderColor: 'theme:primary' } },
  HW_VariantSwatch: { type: 'Box', style: { width: 13, height: 12, borderRadius: 'theme:radiusSm', borderWidth: 'theme:borderThin', borderColor: 'theme:borderSoft' } },
  HW_VariantLabel: { type: 'Text', fontSize: 8, color: 'theme:textSecondary', style: { fontFamily: MONO, fontWeight: 800 } },
  HW_MaterialActions: { type: 'Box', style: { width: 26, alignItems: 'center' } },
  HW_IconMiniButton: { type: 'Pressable', style: { width: 22, height: 22, alignItems: 'center', justifyContent: 'center', borderRadius: 'theme:radiusMd', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' }, hoverStyle: { borderColor: 'theme:primary' } },
  HW_ToolPanel: { type: 'Box', style: { borderTopWidth: 'theme:borderThin', borderTopColor: 'theme:border', paddingTop: 6, paddingBottom: 6 } },
  HW_RenameRow: { type: 'Box', style: { height: 27, flexDirection: 'row', alignItems: 'center', gap: 7, paddingLeft: 12, paddingRight: 12, marginBottom: 5 } },
  HW_RenameInput: { type: 'TextInput', style: { flexGrow: 1, minWidth: 0, height: 24, paddingLeft: 8, paddingRight: 8, borderRadius: 'theme:radiusMd', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder', backgroundColor: 'theme:controlBg', color: 'theme:text', fontSize: 11, fontFamily: MONO, fontWeight: 800 } },
  HW_StatGrid: { type: 'Box', style: { flexDirection: 'row', gap: 7, paddingLeft: 12, paddingRight: 12, marginBottom: 5 } },
  HW_StatCell: { type: 'Box', style: { flexGrow: 1, height: 34, alignItems: 'center', justifyContent: 'center', borderRadius: 'theme:radiusMd', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder', backgroundColor: 'theme:controlBg' } },
  HW_StatValue: { type: 'Text', fontSize: 13, color: 'theme:valNum', style: { fontFamily: MONO, fontWeight: 900 } },
  HW_StatLabel: { type: 'Text', fontSize: 8, color: 'theme:textFaint', style: { fontFamily: MONO, fontWeight: 800 } },
  HW_SelectedVariants: { type: 'Box', style: { flexDirection: 'row', gap: 7, paddingLeft: 12, paddingRight: 12, marginBottom: 5 } },
  HW_SelectedVariant: { type: 'Pressable', style: { flexGrow: 1, height: 49, alignItems: 'center', justifyContent: 'center', gap: 3, borderRadius: 'theme:radiusLg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder', backgroundColor: 'theme:controlBg' }, hoverStyle: { borderColor: 'theme:primary' } },
  HW_SelectedVariantSwatch: { type: 'Box', style: { width: 43, height: 17, borderRadius: 'theme:radiusMd', borderWidth: 'theme:borderThin', borderColor: 'theme:borderSoft' } },
  HW_ToolRow: { type: 'Box', style: { minHeight: 21, flexDirection: 'row', alignItems: 'center', gap: 8, paddingLeft: 12, paddingRight: 12 } },
  HW_ToolLabel: { type: 'Text', fontSize: 9, color: 'theme:textDim', style: { fontFamily: MONO, minWidth: 74 } },
  HW_ToolValue: { type: 'Text', fontSize: 10, color: 'theme:text', style: { fontFamily: MONO, fontWeight: 800 } },
  HW_ToolHint: { type: 'Text', fontSize: 8, color: 'theme:textFaint', style: { fontFamily: MONO } },
  HW_MiniBar: { type: 'Box', style: { flexGrow: 1, height: 4, backgroundColor: 'theme:track', borderRadius: 2, overflow: 'hidden' } },
  HW_MiniFill: { type: 'Box', style: { height: '100%', backgroundColor: 'theme:primary', borderRadius: 2 } },
  HW_ChipRow: { type: 'Box', style: { flexDirection: 'row', gap: 4, flexWrap: 'wrap' } },
  HW_Group: { type: 'Box', style: { borderTopWidth: 'theme:borderThin', borderTopColor: 'theme:borderSoft', paddingTop: 8, paddingBottom: 8 } },
  HW_GroupTitle: { type: 'Box', style: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingLeft: 12, paddingRight: 12, marginBottom: 7 } },
  HW_GroupText: { type: 'Text', fontSize: 10, color: 'theme:primary', style: { fontFamily: MONO, fontWeight: 800, letterSpacing: 1.1 } },
  HW_MemoryRow: { type: 'Pressable', style: { flexDirection: 'row', alignItems: 'center', gap: 8, height: 24, paddingLeft: 12, paddingRight: 12 }, hoverStyle: { backgroundColor: 'theme:surfaceHover' } },
  HW_MemoryLabel: { type: 'Text', fontSize: 10, color: 'theme:textDim', style: { fontFamily: MONO, minWidth: 72 } },
  HW_MemoryValue: { type: 'Text', fontSize: 11, color: 'theme:text', style: { fontWeight: 700 } },

  HW_Workspace: { type: 'Box', style: { flexGrow: 1, minWidth: 0, height: '100%', flexDirection: 'column', backgroundColor: 'theme:bg' } },
  HW_ToolOptions: { type: 'Box', style: { height: 36, flexDirection: 'row', alignItems: 'center', gap: 7, paddingLeft: 10, paddingRight: 10, backgroundColor: 'theme:surface', borderBottomWidth: 'theme:borderThin', borderBottomColor: 'theme:border' } },
  HW_IconButton: { type: 'Pressable', style: { width: 28, height: 26, alignItems: 'center', justifyContent: 'center', borderRadius: 'theme:radiusLg' }, hoverStyle: { backgroundColor: 'theme:surfaceHover' } },
  HW_IconButtonOn: { type: 'Pressable', style: { width: 30, height: 28, alignItems: 'center', justifyContent: 'center', borderRadius: 'theme:radiusLg', borderWidth: 'theme:borderThin', borderColor: 'theme:primary', backgroundColor: 'theme:segActiveBg' } },
  HW_OptionDivider: { type: 'Box', style: { width: 1, height: 21, backgroundColor: 'theme:border' } },
  HW_OptionLabel: { type: 'Text', fontSize: 9, color: 'theme:textFaint', style: { fontFamily: MONO, fontWeight: 800, letterSpacing: 1.1 } },
  HW_Stage: { type: 'Pressable', style: { flexGrow: 1, minHeight: 0, position: 'relative', backgroundColor: 'theme:stageBg', overflow: 'hidden' } },
  HW_StagePanel: { type: 'Box', style: { flexGrow: 1, minHeight: 0, flexDirection: 'column', backgroundColor: 'theme:stageBg', overflow: 'hidden' } },
  HW_StageViewport: { type: 'Box', style: { flexGrow: 1, minHeight: 0, position: 'relative', backgroundColor: 'theme:stageBg', overflow: 'hidden' } },
  HW_WorldEditorSurface: { type: 'Box', style: { width: '100%', height: '100%', minHeight: 0, backgroundColor: '#0d141f', overflow: 'hidden' } },
  HW_StageTabStrip: { type: 'Box', style: { height: 31, flexDirection: 'row', alignItems: 'center', gap: 3, paddingLeft: 8, paddingRight: 8, backgroundColor: 'theme:surface', borderTopWidth: 'theme:borderThin', borderTopColor: 'theme:border', overflow: 'hidden' } },
  HW_StageTab: { type: 'Pressable', style: { height: 25, width: 154, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 6, paddingLeft: 9, paddingRight: 5, borderRadius: 'theme:radiusMd', borderWidth: 'theme:borderThin', borderColor: 'theme:borderSoft', backgroundColor: 'theme:controlBg' }, hoverStyle: { backgroundColor: 'theme:surfaceHover', borderColor: 'theme:textDim' } },
  HW_StageTabOn: { type: 'Pressable', style: { height: 25, width: 162, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 6, paddingLeft: 9, paddingRight: 5, borderRadius: 'theme:radiusMd', borderWidth: 'theme:borderThin', borderColor: 'theme:primary', backgroundColor: 'theme:segActiveBg' } },
  HW_StageTabTextStack: { type: 'Box', style: { flexGrow: 1, minWidth: 0, flexDirection: 'column', gap: 0 } },
  HW_StageTabText: { type: 'Text', fontSize: 9, color: 'theme:textSecondary', style: { fontFamily: MONO, fontWeight: 900 } },
  HW_StageTabTextOn: { type: 'Text', fontSize: 9, color: 'theme:segActiveText', style: { fontFamily: MONO, fontWeight: 900 } },
  HW_StageTabMeta: { type: 'Text', fontSize: 7, color: 'theme:textFaint', style: { fontFamily: MONO, fontWeight: 800 } },
  HW_StageTabMetaOn: { type: 'Text', fontSize: 7, color: 'theme:textDim', style: { fontFamily: MONO, fontWeight: 800 } },
  HW_StageTabClose: { type: 'Pressable', style: { width: 17, height: 17, alignItems: 'center', justifyContent: 'center', borderRadius: 'theme:radiusSm', backgroundColor: 'transparent' }, hoverStyle: { backgroundColor: 'theme:surfaceHover' } },
  HW_StageTabCloseText: { type: 'Text', fontSize: 10, color: 'theme:textDim', style: { fontFamily: MONO, fontWeight: 900 } },
  HW_StageSocket: { type: 'Pressable', style: { position: 'absolute', left: 0, top: 0, right: 0, bottom: 0, alignItems: 'center', justifyContent: 'center', gap: 6, backgroundColor: 'transparent' } },
  HW_StageSocketTitle: { type: 'Text', fontSize: 14, color: 'theme:textSecondary', style: { fontFamily: MONO, fontWeight: 900, letterSpacing: 1.4 } },
  HW_StageSocketMeta: { type: 'Text', fontSize: 10, color: 'theme:textFaint', style: { fontFamily: MONO, fontWeight: 800 } },
  HW_ModelDocument: { type: 'Box', style: { width: '100%', height: '100%', minHeight: 0, flexDirection: 'column', backgroundColor: 'theme:stageBg', overflow: 'hidden' } },
  HW_ModelDocShell: { type: 'Box', style: { flexGrow: 1, minHeight: 0, flexDirection: 'column', gap: 10, padding: 14, overflow: 'scroll' } },
  HW_ModelDocEmpty: { type: 'Box', style: { flexGrow: 1, minHeight: 0, alignItems: 'center', justifyContent: 'center', gap: 8 } },
  HW_ModelDocHeader: { type: 'Box', style: { height: 58, flexDirection: 'row', alignItems: 'center', gap: 10, paddingLeft: 10, paddingRight: 10, borderRadius: 'theme:radiusMd', backgroundColor: 'theme:surface', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' } },
  HW_ModelDocThumb: { type: 'Box', style: { width: 38, height: 38, borderRadius: 'theme:radiusMd', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' } },
  HW_ModelDocTitleBlock: { type: 'Box', style: { flexGrow: 1, minWidth: 0, flexDirection: 'column', gap: 4 } },
  HW_ModelDocTitle: { type: 'Text', fontSize: 16, color: 'theme:text', style: { fontFamily: MONO, fontWeight: 900 } },
  HW_ModelDocPath: { type: 'Text', fontSize: 10, color: 'theme:textDim', style: { fontFamily: MONO, fontWeight: 800 } },
  HW_ModelDocBadge: { type: 'Box', style: { height: 22, justifyContent: 'center', paddingLeft: 8, paddingRight: 8, borderRadius: 'theme:radiusMd', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' } },
  HW_ModelDocStats: { type: 'Box', style: { height: 52, flexDirection: 'row', gap: 8 } },
  HW_ModelDocStat: { type: 'Box', style: { flexGrow: 1, minWidth: 0, alignItems: 'center', justifyContent: 'center', borderRadius: 'theme:radiusMd', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' } },
  HW_ModelDocGrid: { type: 'Box', style: { minHeight: 166, flexDirection: 'row', gap: 10 } },
  HW_ModelDocPanel: { type: 'Box', style: { flexGrow: 1, minWidth: 0, flexDirection: 'column', gap: 6, padding: 10, borderRadius: 'theme:radiusMd', backgroundColor: 'theme:bgAlt', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' } },
  HW_ModelDocPanelHead: { type: 'Box', style: { height: 20, flexDirection: 'row', alignItems: 'center', gap: 7 } },
  HW_ModelDocRow: { type: 'Box', style: { height: 25, flexDirection: 'row', alignItems: 'center', gap: 8, paddingLeft: 7, paddingRight: 7, borderRadius: 'theme:radiusSm', backgroundColor: 'theme:cardBg', borderWidth: 'theme:borderThin', borderColor: 'theme:borderSoft' } },
  HW_CanvasGrid: { type: 'Box', style: { position: 'absolute', left: 0, top: 0, right: 0, bottom: 0, backgroundColor: 'theme:stageGridBg' } },
  HW_MaterialFocus: { type: 'Box', style: { position: 'absolute', left: 18, top: 18, right: 18, bottom: 18, flexDirection: 'column', gap: 12 } },
  HW_FocusHeader: { type: 'Box', style: { height: 42, flexDirection: 'row', alignItems: 'center', gap: 9, paddingLeft: 12, paddingRight: 12, borderRadius: 'theme:radiusLg', backgroundColor: 'theme:surface', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' } },
  HW_FocusLayout: { type: 'Box', style: { flexGrow: 1, minHeight: 0, flexDirection: 'row', gap: 12 } },
  HW_FocusRail: { type: 'Box', style: { width: 276, minHeight: 0, flexDirection: 'column', borderRadius: 'theme:radiusLg', backgroundColor: 'theme:bgAlt', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder', paddingTop: 12, paddingBottom: 12 } },
  HW_FocusPreview: { type: 'Box', style: { flexGrow: 1, minWidth: 0, flexDirection: 'column', borderRadius: 'theme:radiusLg', backgroundColor: 'theme:surface', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder', overflow: 'hidden' } },
  HW_PreviewToolbar: { type: 'Box', style: { height: 42, flexDirection: 'row', alignItems: 'center', gap: 7, paddingLeft: 10, paddingRight: 10, borderBottomWidth: 'theme:borderThin', borderBottomColor: 'theme:border' } },
  HW_PreviewGrid: { type: 'Box', style: { flexGrow: 1, minHeight: 0, flexDirection: 'row', flexWrap: 'wrap', gap: 6, padding: 16, backgroundColor: 'theme:stageBg' } },
  HW_PreviewTile: { type: 'Box', style: { width: 62, height: 62, borderWidth: 'theme:borderThin', borderColor: 'theme:stageTileBorder' } },
  HW_LayerRow: { type: 'Pressable', style: { minHeight: 30, flexDirection: 'row', alignItems: 'center', gap: 8, paddingLeft: 12, paddingRight: 12, borderTopWidth: 'theme:borderThin', borderTopColor: 'theme:borderSoft' }, hoverStyle: { backgroundColor: 'theme:surfaceHover' } },
  HW_LayerRowOn: { type: 'Pressable', style: { minHeight: 30, flexDirection: 'row', alignItems: 'center', gap: 8, paddingLeft: 12, paddingRight: 12, borderTopWidth: 'theme:borderThin', borderTopColor: 'theme:borderSoft', backgroundColor: 'theme:segActiveBg' } },
  HW_BrushGrid: { type: 'Box', style: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, paddingLeft: 12, paddingRight: 12 } },
  HW_BrushCell: { type: 'Pressable', style: { width: 116, height: 70, alignItems: 'center', justifyContent: 'center', gap: 6, borderRadius: 'theme:radiusLg', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' }, hoverStyle: { borderColor: 'theme:primary' } },
  HW_BrushDot: { type: 'Box', style: { backgroundColor: 'theme:primary', borderWidth: 'theme:borderThin', borderColor: 'theme:stageBadgeEdge' } },
  HW_ColorStudioShell: { type: 'Box', style: { flexGrow: 1, minHeight: 0, flexDirection: 'column', gap: 10 } },
  HW_ColorMaterialStrip: { type: 'Box', style: { height: 66, flexDirection: 'row', gap: 8 } },
  HW_ColorMaterialCard: { type: 'Pressable', style: { flexGrow: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 9, paddingLeft: 10, paddingRight: 9, borderRadius: 'theme:radiusLg', backgroundColor: 'theme:cardBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' }, hoverStyle: { borderColor: 'theme:textDim' } },
  HW_ColorMaterialCardOn: { type: 'Pressable', style: { flexGrow: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 9, paddingLeft: 10, paddingRight: 9, borderRadius: 'theme:radiusLg', backgroundColor: 'theme:segActiveBg', borderWidth: 'theme:borderMedium', borderColor: 'theme:primary' } },
  HW_ColorMaterialMini: { type: 'Box', style: { width: 42, height: 42, flexDirection: 'column', borderRadius: 'theme:radiusLg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder', overflow: 'hidden' } },
  HW_ColorMiniBand: { type: 'Box', style: { flexGrow: 1, minHeight: 0 } },
  HW_ColorMaterialText: { type: 'Box', style: { flexGrow: 1, minWidth: 0, flexDirection: 'column', gap: 4 } },
  HW_ColorStudioBody: { type: 'Box', style: { flexGrow: 1, minHeight: 0, flexDirection: 'row', gap: 10 } },
  HW_ColorPreviewPanel: { type: 'Box', style: { flexGrow: 1, minWidth: 0, flexDirection: 'column', borderRadius: 'theme:radiusLg', backgroundColor: 'theme:surface', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder', overflow: 'hidden' } },
  HW_ColorPreviewHead: { type: 'Box', style: { height: 43, flexDirection: 'row', alignItems: 'center', gap: 7, paddingLeft: 11, paddingRight: 11, borderBottomWidth: 'theme:borderThin', borderBottomColor: 'theme:border' } },
  HW_ColorPreviewGrid: { type: 'Box', style: { flexGrow: 1, minHeight: 0, flexDirection: 'row', flexWrap: 'wrap', gap: 3, padding: 12, backgroundColor: 'theme:stageBg' } },
  HW_ColorPreviewCell: { type: 'Box', style: { width: 35, height: 40, borderRadius: 'theme:radiusSm', borderWidth: 'theme:borderThin', borderColor: 'theme:borderSoft' } },
  HW_ColorControlRow: { type: 'Box', style: { height: 61, flexDirection: 'row', alignItems: 'center', gap: 10, paddingLeft: 12, paddingRight: 12, borderTopWidth: 'theme:borderThin', borderTopColor: 'theme:border' } },
  HW_ColorControlGroup: { type: 'Box', style: { width: 132, flexDirection: 'column', gap: 5 } },
  HW_ColorControlGroupWide: { type: 'Box', style: { flexGrow: 1, minWidth: 0, flexDirection: 'column', gap: 5 } },
  HW_ColorSegmentTrack: { type: 'Box', style: { height: 28, flexDirection: 'row', gap: 3, padding: 3, borderRadius: 'theme:radiusLg', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' } },
  HW_ColorSegment: { type: 'Pressable', style: { flexGrow: 1, minWidth: 0, alignItems: 'center', justifyContent: 'center', borderRadius: 'theme:radiusMd', backgroundColor: 'transparent' }, hoverStyle: { backgroundColor: 'theme:surfaceHover' } },
  HW_ColorSegmentOn: { type: 'Pressable', style: { flexGrow: 1, minWidth: 0, alignItems: 'center', justifyContent: 'center', borderRadius: 'theme:radiusMd', backgroundColor: 'theme:text', borderWidth: 'theme:borderThin', borderColor: 'theme:text' } },
  HW_ColorSegmentLabel: { type: 'Text', fontSize: 9, color: 'theme:textDim', style: { fontFamily: MONO, fontWeight: 900 } },
  HW_ColorSegmentLabelOn: { type: 'Text', fontSize: 9, color: '#071014', style: { fontFamily: MONO, fontWeight: 900 } },
  HW_ColorSeedButton: { type: 'Pressable', style: { height: 28, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, borderRadius: 'theme:radiusLg', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' }, hoverStyle: { borderColor: 'theme:primary' } },
  HW_ColorSlotHead: { type: 'Box', style: { height: 40, flexDirection: 'row', alignItems: 'center', gap: 8, paddingRight: 12, borderTopWidth: 'theme:borderThin', borderTopColor: 'theme:border' } },
  HW_ColorSlotGrid: { type: 'Box', style: { height: 92, flexDirection: 'row', gap: 8, paddingLeft: 12, paddingRight: 12, paddingBottom: 12 } },
  HW_ColorSlot: { type: 'Pressable', style: { flexGrow: 1, minWidth: 0, flexDirection: 'column', gap: 6, padding: 8, borderRadius: 'theme:radiusLg', backgroundColor: 'theme:cardBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' }, hoverStyle: { borderColor: 'theme:textDim' } },
  HW_ColorSlotOn: { type: 'Pressable', style: { flexGrow: 1, minWidth: 0, flexDirection: 'column', gap: 6, padding: 8, borderRadius: 'theme:radiusLg', backgroundColor: 'theme:segActiveBg', borderWidth: 'theme:borderMedium', borderColor: 'theme:primary' } },
  HW_ColorSlotSwatch: { type: 'Box', style: { height: 22, borderRadius: 'theme:radiusMd', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' } },
  HW_ColorSlotText: { type: 'Box', style: { minHeight: 0, flexDirection: 'column', gap: 3 } },
  HW_ColorAssistPanel: { type: 'Box', style: { width: 386, minHeight: 0, flexDirection: 'column', gap: 9, paddingTop: 12, paddingBottom: 12, borderRadius: 'theme:radiusLg', backgroundColor: 'theme:bgAlt', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' } },
  HW_ColorActiveSlot: { type: 'Box', style: { minHeight: 82, flexDirection: 'row', gap: 10, paddingLeft: 12, paddingRight: 12, paddingBottom: 5 } },
  HW_ColorActiveSwatch: { type: 'Box', style: { width: 58, height: 58, borderRadius: 'theme:radiusLg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' } },
  HW_ColorActiveText: { type: 'Box', style: { flexGrow: 1, minWidth: 0, flexDirection: 'column', gap: 5 } },
  HW_ColorCode: { type: 'Text', fontSize: 9, color: 'theme:textDim', style: { fontFamily: MONO, fontWeight: 800 } },
  HW_ColorReadoutGrid: { type: 'Box', style: { height: 55, flexDirection: 'row', gap: 6, paddingLeft: 12, paddingRight: 12 } },
  HW_ColorAssistGrid: { type: 'Box', style: { height: 92, flexDirection: 'row', flexWrap: 'wrap', gap: 6, paddingLeft: 12, paddingRight: 12 } },
  HW_ColorAssistSwatch: { type: 'Pressable', style: { width: 114, height: 39, flexDirection: 'row', alignItems: 'center', gap: 7, paddingLeft: 7, paddingRight: 7, borderRadius: 'theme:radiusLg', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' }, hoverStyle: { borderColor: 'theme:primary' } },
  HW_ColorAssistChip: { type: 'Box', style: { width: 24, height: 24, borderRadius: 'theme:radiusMd', borderWidth: 'theme:borderThin', borderColor: 'theme:borderSoft' } },
  HW_ColorLibraryList: { type: 'Box', style: { flexGrow: 1, minHeight: 0, flexDirection: 'column', gap: 6, paddingLeft: 12, paddingRight: 12 } },
  HW_ColorLibraryRow: { type: 'Box', style: { height: 48, flexDirection: 'row', alignItems: 'center', gap: 8, paddingLeft: 8, paddingRight: 8, borderRadius: 'theme:radiusLg', backgroundColor: 'theme:cardBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' } },
  HW_ColorLibraryName: { type: 'Box', style: { width: 126, flexDirection: 'column', gap: 3 } },
  HW_ColorLibrarySwatches: { type: 'Box', style: { flexGrow: 1, minWidth: 0, height: 30, flexDirection: 'row', gap: 4 } },
  HW_ColorLibrarySwatch: { type: 'Pressable', style: { flexGrow: 1, minWidth: 0, height: 30, borderRadius: 'theme:radiusMd', borderWidth: 'theme:borderThin', borderColor: 'theme:borderSoft' }, hoverStyle: { borderColor: 'theme:primary' } },
  HW_MapDeck: { type: 'Box', style: { position: 'absolute', left: 315, top: 158, width: 470, height: 300 } },
  HW_Tile: { type: 'Box', style: { position: 'absolute', width: 54, height: 32, borderWidth: 'theme:borderThin', borderColor: 'theme:stageTileBorder', backgroundColor: 'theme:stageTile' } },
  HW_Block: { type: 'Box', style: { position: 'absolute', borderWidth: 'theme:borderThin', borderColor: 'theme:stageBlockBorder', backgroundColor: 'theme:stageBlock' } },
  HW_BlockHit: { type: 'Pressable', style: { position: 'absolute', backgroundColor: 'transparent' } },
  HW_SelectionBox: { type: 'Box', style: { position: 'absolute', borderWidth: 2, borderColor: 'theme:primary', backgroundColor: 'theme:stageSelect' } },
  HW_PointBadge: { type: 'Box', style: { position: 'absolute', width: 19, height: 19, alignItems: 'center', justifyContent: 'center', borderRadius: 10, backgroundColor: 'theme:primary', borderWidth: 2, borderColor: 'theme:stageBadgeEdge' } },
  HW_PointText: { type: 'Text', fontSize: 10, color: 'theme:stageBadgeText', style: { fontFamily: MONO, fontWeight: 900 } },
  HW_ContextMenu: { type: 'Box', style: { position: 'absolute', left: 120, top: 124, width: 254, borderRadius: 'theme:radiusLg', backgroundColor: 'theme:surface', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder', overflow: 'hidden' } },
  HW_ContextHead: { type: 'Box', style: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingLeft: 10, paddingRight: 10, paddingTop: 8, paddingBottom: 6, borderBottomWidth: 'theme:borderThin', borderBottomColor: 'theme:borderSoft' } },
  HW_ContextRow: { type: 'Pressable', style: { height: 26, flexDirection: 'row', alignItems: 'center', gap: 8, paddingLeft: 10, paddingRight: 8 }, hoverStyle: { backgroundColor: 'theme:surfaceHover' } },
  HW_ContextText: { type: 'Text', fontSize: 11, color: 'theme:textSecondary' },
  HW_KeyText: { type: 'Text', fontSize: 9, color: 'theme:textFaint', style: { fontFamily: MONO, fontWeight: 700 } },
  HW_FloatingCard: { type: 'Box', style: { position: 'absolute', borderRadius: 'theme:radiusLg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder', backgroundColor: 'theme:surface', overflow: 'hidden' } },
  HW_MiniMap: { type: 'Box', style: { width: 278, height: 166, position: 'relative', backgroundColor: 'theme:miniMapBg' } },
  HW_MiniLine: { type: 'Box', style: { position: 'absolute', backgroundColor: 'theme:miniMapGrid' } },
  HW_MiniShape: { type: 'Pressable', style: { position: 'absolute', backgroundColor: 'theme:miniShape', borderWidth: 'theme:borderThin', borderColor: 'theme:miniShapeBorder' }, hoverStyle: { borderColor: 'theme:primary' } },
  HW_StatusBar: { type: 'Box', style: { height: 28, flexDirection: 'row', alignItems: 'center', gap: 12, paddingLeft: 10, paddingRight: 10, backgroundColor: 'theme:surface', borderTopWidth: 'theme:borderThin', borderTopColor: 'theme:border' } },
  HW_StatusText: { type: 'Text', fontSize: 10, color: 'theme:textDim', style: { fontFamily: MONO, fontWeight: 700 } },

  HW_RightPanel: { type: 'Box', style: { width: 326, height: '100%', flexDirection: 'row', backgroundColor: 'theme:bgAlt', borderLeftWidth: 'theme:borderThin', borderLeftColor: 'theme:border' } },
  HW_Inspector: { type: 'Box', style: { flexGrow: 1, minWidth: 0, flexDirection: 'column' } },
  HW_RightRail: { type: 'Box', style: { width: 40, height: '100%', alignItems: 'center', gap: 7, paddingTop: 8, backgroundColor: 'theme:surface', borderLeftWidth: 'theme:borderThin', borderLeftColor: 'theme:border' } },
  HW_ObjectHead: { type: 'Box', style: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingLeft: 12, paddingRight: 12, paddingTop: 10, paddingBottom: 10, borderBottomWidth: 'theme:borderThin', borderBottomColor: 'theme:border' } },
  HW_Tag: { type: 'Box', style: { paddingLeft: 6, paddingRight: 6, paddingTop: 2, paddingBottom: 2, borderRadius: 'theme:radiusSm', backgroundColor: 'theme:success' } },
  HW_TagText: { type: 'Text', fontSize: 8, color: '#061015', style: { fontFamily: MONO, fontWeight: 900, letterSpacing: 1 } },
  HW_ObjectTitle: { type: 'Text', fontSize: 16, color: 'theme:text', style: { fontWeight: 800 } },
  HW_Swatch: { type: 'Box', style: { width: 22, height: 22, borderRadius: 'theme:radiusMd', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' } },
  HW_MetricRow: { type: 'Box', style: { flexDirection: 'row', alignItems: 'center', paddingLeft: 12, paddingRight: 12, paddingTop: 9, paddingBottom: 8, gap: 15 } },
  HW_Metric: { type: 'Box', style: { flexGrow: 1, flexDirection: 'column', gap: 2 } },
  HW_MetricValue: { type: 'Text', fontSize: 13, color: 'theme:valNum', style: { fontFamily: MONO, fontWeight: 800 } },
  HW_MetricLabel: { type: 'Text', fontSize: 8, color: 'theme:textFaint', style: { fontFamily: MONO, fontWeight: 800 } },
  HW_Section: { type: 'Box', style: { borderTopWidth: 'theme:borderThin', borderTopColor: 'theme:borderSoft', paddingTop: 8, paddingBottom: 8 } },
  HW_SectionHead: { type: 'Box', style: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingLeft: 12, paddingRight: 12, marginBottom: 5 } },
  HW_AccentBar: { type: 'Box', style: { width: 3, height: 12, backgroundColor: 'theme:primary' } },
  HW_SectionTitle: { type: 'Text', fontSize: 10, color: 'theme:primary', style: { fontFamily: MONO, fontWeight: 900, letterSpacing: 1.2 } },
  HW_FormRow: { type: 'Box', style: { height: 25, flexDirection: 'row', alignItems: 'center', gap: 8, paddingLeft: 12, paddingRight: 12 } },
  HW_ReadRow: { type: 'Box', style: { minHeight: 21, flexDirection: 'row', alignItems: 'center', gap: 8, paddingLeft: 12, paddingRight: 12 } },
  HW_FormLabel: { type: 'Text', fontSize: 10, color: 'theme:textDim', style: { fontFamily: MONO, minWidth: 82 } },
  HW_FormValue: { type: 'Text', fontSize: 11, color: 'theme:text', style: { fontFamily: MONO, fontWeight: 700 } },
  HW_ReadValue: { type: 'Text', fontSize: 10, color: 'theme:textSecondary', style: { fontFamily: MONO, fontWeight: 700 } },
  HW_DropChip: { type: 'Box', style: { height: 21, flexDirection: 'row', alignItems: 'center', gap: 5, paddingLeft: 8, paddingRight: 8, borderRadius: 'theme:radiusMd', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' } },
  HW_SelectRow: { type: 'Box', style: { height: 26, flexDirection: 'row', alignItems: 'center', gap: 8, paddingLeft: 12, paddingRight: 12, paddingBottom: 4 } },
  HW_SelectControl: { type: 'Pressable', style: { flexGrow: 1, minWidth: 0, height: 23, flexDirection: 'row', alignItems: 'center', gap: 6, paddingLeft: 8, paddingRight: 7, borderRadius: 'theme:radiusMd', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' }, hoverStyle: { borderColor: 'theme:primary' } },
  HW_SelectMenu: { type: 'Box', style: { marginLeft: 94, marginRight: 12, marginBottom: 5, borderRadius: 'theme:radiusMd', backgroundColor: 'theme:surface', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder', overflow: 'hidden' } },
  HW_SelectOption: { type: 'Pressable', style: { height: 23, flexDirection: 'row', alignItems: 'center', gap: 7, paddingLeft: 8, paddingRight: 7, borderBottomWidth: 'theme:borderThin', borderBottomColor: 'theme:borderSoft' }, hoverStyle: { backgroundColor: 'theme:surfaceHover' } },
  HW_PresetChip: { type: 'Pressable', style: { height: 21, flexDirection: 'row', alignItems: 'center', gap: 5, paddingLeft: 8, paddingRight: 8, borderRadius: 'theme:radiusMd', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' }, hoverStyle: { borderColor: 'theme:primary' } },
  HW_PresetChipOn: { type: 'Pressable', style: { height: 21, flexDirection: 'row', alignItems: 'center', gap: 5, paddingLeft: 8, paddingRight: 8, borderRadius: 'theme:radiusMd', backgroundColor: 'theme:segActiveBg', borderWidth: 'theme:borderThin', borderColor: 'theme:primary' } },
  HW_ButtonRow: { type: 'Box', style: { flexDirection: 'row', gap: 6, paddingLeft: 12, paddingRight: 12, paddingTop: 4 } },
  HW_SmallButton: { type: 'Pressable', style: { flexGrow: 1, height: 24, alignItems: 'center', justifyContent: 'center', borderRadius: 'theme:radiusMd', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' }, hoverStyle: { borderColor: 'theme:textDim' } },

  HW_FileExplorerDialog: { type: 'Box', style: { width: 1220, height: 760, flexDirection: 'column', borderRadius: 'theme:radiusLg', backgroundColor: 'theme:bgAlt', borderWidth: 'theme:borderThin', borderColor: 'theme:primary', overflow: 'hidden' } },
  HW_FileExplorerHead: { type: 'Box', style: { height: 42, flexDirection: 'row', alignItems: 'center', gap: 9, paddingLeft: 12, paddingRight: 10, backgroundColor: 'theme:surface', borderBottomWidth: 'theme:borderThin', borderBottomColor: 'theme:border' } },
  HW_FileExplorerSearchRow: { type: 'Box', style: { height: 42, flexDirection: 'row', alignItems: 'center', gap: 8, paddingLeft: 12, paddingRight: 12, borderBottomWidth: 'theme:borderThin', borderBottomColor: 'theme:borderSoft' } },
  HW_FileSearch: { type: 'TextInput', style: { flexGrow: 1, minWidth: 0, height: 26, paddingLeft: 9, paddingRight: 8, borderRadius: 'theme:radiusLg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder', backgroundColor: 'theme:controlBg', color: 'theme:textSecondary', fontSize: 11, fontFamily: MONO } },
  HW_FileExplorerBody: { type: 'Box', style: { flexGrow: 1, minHeight: 0, flexDirection: 'row' } },
  HW_FileExplorerNav: { type: 'Box', style: { width: 280, minHeight: 0, flexDirection: 'column', paddingTop: 10, borderRightWidth: 'theme:borderThin', borderRightColor: 'theme:border' } },
  HW_FileTree: { type: 'Box', style: { flexGrow: 1, minHeight: 0, flexDirection: 'column', paddingLeft: 8, paddingRight: 8, overflow: 'scroll' } },
  HW_FileTreeRow: { type: 'Pressable', style: { height: 24, flexDirection: 'row', alignItems: 'center', gap: 5, paddingLeft: 2, paddingRight: 6, borderRadius: 'theme:radiusMd' }, hoverStyle: { backgroundColor: 'theme:surfaceHover' } },
  HW_FileTreeRowOn: { type: 'Pressable', style: { height: 24, flexDirection: 'row', alignItems: 'center', gap: 5, paddingLeft: 2, paddingRight: 6, borderRadius: 'theme:radiusMd', backgroundColor: 'theme:segActiveBg', borderWidth: 'theme:borderThin', borderColor: 'theme:borderSoft' } },
  HW_FileTreeLabel: { type: 'Text', fontSize: 10, color: 'theme:textSecondary', style: { fontFamily: MONO, fontWeight: 800 } },
  HW_FileResults: { type: 'Box', style: { width: 440, minHeight: 0, flexDirection: 'column', paddingTop: 9, paddingLeft: 10, paddingRight: 10, borderRightWidth: 'theme:borderThin', borderRightColor: 'theme:border' } },
  HW_FileResultsHead: { type: 'Box', style: { height: 25, flexDirection: 'row', alignItems: 'center', gap: 7, paddingLeft: 2, paddingRight: 2 } },
  HW_FileResult: { type: 'Pressable', style: { height: 52, flexDirection: 'row', alignItems: 'center', gap: 8, paddingLeft: 8, paddingRight: 7, marginBottom: 6, borderRadius: 'theme:radiusLg', backgroundColor: 'theme:cardBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' }, hoverStyle: { borderColor: 'theme:textDim' } },
  HW_FileResultOn: { type: 'Pressable', style: { height: 52, flexDirection: 'row', alignItems: 'center', gap: 8, paddingLeft: 8, paddingRight: 7, marginBottom: 6, borderRadius: 'theme:radiusLg', backgroundColor: 'theme:segActiveBg', borderWidth: 2, borderColor: 'theme:primary' } },
  HW_FileResultEmpty: { type: 'Box', style: { height: 52, alignItems: 'center', justifyContent: 'center', marginBottom: 6, borderRadius: 'theme:radiusLg', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:borderSoft' } },
  HW_FileResultMain: { type: 'Box', style: { flexGrow: 1, minWidth: 0, flexDirection: 'column', gap: 2 } },
  HW_FileResultTitleRow: { type: 'Box', style: { height: 15, flexDirection: 'row', alignItems: 'center', gap: 6 } },
  HW_FileName: { type: 'Text', fontSize: 11, color: 'theme:text', style: { fontFamily: MONO, fontWeight: 900 } },
  HW_FilePath: { type: 'Text', fontSize: 8, color: 'theme:textDim', style: { fontFamily: MONO, fontWeight: 700 } },
  HW_FileSummary: { type: 'Text', fontSize: 8, color: 'theme:textFaint', style: { fontFamily: MONO } },
  HW_FileStat: { type: 'Text', fontSize: 8, color: 'theme:textFaint', style: { fontFamily: MONO, fontWeight: 800 } },
  HW_FileBadge: { type: 'Box', style: { height: 17, justifyContent: 'center', paddingLeft: 6, paddingRight: 6, borderRadius: 'theme:radiusMd', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:borderSoft' } },
  HW_FilePreview: { type: 'Box', style: { flexGrow: 1, minWidth: 0, flexDirection: 'column' } },
  HW_FilePreviewHead: { type: 'Box', style: { height: 48, flexDirection: 'row', alignItems: 'center', gap: 9, paddingLeft: 12, paddingRight: 12, borderBottomWidth: 'theme:borderThin', borderBottomColor: 'theme:borderSoft' } },
  HW_FilePreviewBody: { type: 'Box', style: { flexGrow: 1, minHeight: 0, flexDirection: 'column', gap: 9, padding: 12 } },
  HW_FilePathBlock: { type: 'Text', fontSize: 10, color: 'theme:primary', style: { fontFamily: MONO, fontWeight: 900 } },
  HW_FileSummaryBlock: { type: 'Text', fontSize: 11, color: 'theme:textSecondary', style: { lineHeight: 16 } },
  HW_FileMetaGrid: { type: 'Box', style: { height: 42, flexDirection: 'row', gap: 8 } },
  HW_FileSection: { type: 'Box', style: { borderTopWidth: 'theme:borderThin', borderTopColor: 'theme:borderSoft', paddingTop: 8, gap: 3 } },
  HW_FileMiniRow: { type: 'Box', style: { minHeight: 20, flexDirection: 'row', alignItems: 'center', gap: 7 } },
  HW_FileDot: { type: 'Box', style: { width: 5, height: 5, borderRadius: 3, backgroundColor: 'theme:primary' } },
  HW_FileTagWrap: { type: 'Box', style: { flexDirection: 'row', flexWrap: 'wrap', gap: 5 } },
  HW_FileHint: { type: 'Text', fontSize: 9, color: 'theme:textFaint', style: { fontFamily: MONO, paddingLeft: 12, paddingRight: 12, paddingTop: 4 } },
  HW_FileModelBlock: { type: 'Box', style: { height: 174, flexDirection: 'row', gap: 10 } },
  HW_FileModelViewport: { type: 'Box', style: { width: 226, minHeight: 0, flexDirection: 'column', borderRadius: 'theme:radiusLg', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder', overflow: 'hidden' } },
  HW_ModelViewportTop: { type: 'Box', style: { height: 28, flexDirection: 'row', alignItems: 'center', gap: 6, paddingLeft: 8, paddingRight: 8, borderBottomWidth: 'theme:borderThin', borderBottomColor: 'theme:borderSoft' } },
  HW_ModelStage: { type: 'Box', style: { flexGrow: 1, minHeight: 0, alignItems: 'center', justifyContent: 'center', backgroundColor: 'theme:bg' } },
  HW_ModelGround: { type: 'Box', style: { width: 170, height: 92, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'center', gap: 8, borderBottomWidth: 'theme:borderThin', borderBottomColor: 'theme:primary' } },
  HW_ModelShapeTall: { type: 'Box', style: { width: 40, height: 78, borderRadius: 'theme:radiusSm', backgroundColor: 'theme:surfaceHover', borderWidth: 'theme:borderThin', borderColor: 'theme:textDim' } },
  HW_ModelShapeWide: { type: 'Box', style: { width: 72, height: 46, borderRadius: 'theme:radiusSm', backgroundColor: 'theme:segActiveBg', borderWidth: 'theme:borderThin', borderColor: 'theme:primary' } },
  HW_ModelShapeSmall: { type: 'Box', style: { width: 32, height: 28, borderRadius: 'theme:radiusSm', backgroundColor: 'theme:cardBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' } },
  HW_ModelViewportFoot: { type: 'Box', style: { height: 25, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', borderTopWidth: 'theme:borderThin', borderTopColor: 'theme:borderSoft' } },
  HW_ModelMetaColumn: { type: 'Box', style: { flexGrow: 1, minWidth: 0, flexDirection: 'column', gap: 7 } },
  HW_DirectoryMemory: { type: 'Box', style: { height: 158, flexDirection: 'column', borderTopWidth: 'theme:borderThin', borderTopColor: 'theme:border', backgroundColor: 'theme:bgAlt' } },
  HW_DirMemoryRows: { type: 'Box', style: { flexGrow: 1, minHeight: 0, flexDirection: 'column', gap: 5, paddingLeft: 8, paddingRight: 8, paddingBottom: 9 } },
  HW_DirMemoryRow: { type: 'Pressable', style: { height: 25, flexDirection: 'row', alignItems: 'center', gap: 6, paddingLeft: 7, paddingRight: 7, borderRadius: 'theme:radiusMd', backgroundColor: 'theme:controlBg', borderWidth: 'theme:borderThin', borderColor: 'theme:borderSoft' }, hoverStyle: { borderColor: 'theme:primary' } },
  HW_DirMemoryRowOn: { type: 'Pressable', style: { height: 25, flexDirection: 'row', alignItems: 'center', gap: 6, paddingLeft: 7, paddingRight: 7, borderRadius: 'theme:radiusMd', backgroundColor: 'theme:segActiveBg', borderWidth: 'theme:borderThin', borderColor: 'theme:primary' } },
  HW_FileHistory: { type: 'Box', style: { height: 112, flexDirection: 'column', borderTopWidth: 'theme:borderThin', borderTopColor: 'theme:border' } },
  HW_FileHistoryHead: { type: 'Box', style: { height: 30, flexDirection: 'row', alignItems: 'center', gap: 7, paddingLeft: 12, paddingRight: 12 } },
  HW_FileHistoryCards: { type: 'Box', style: { flexGrow: 1, minHeight: 0, flexDirection: 'row', gap: 8, paddingLeft: 12, paddingRight: 12, paddingBottom: 10 } },
  HW_FileHistoryCard: { type: 'Pressable', style: { flexGrow: 1, minWidth: 0, flexDirection: 'column', gap: 4, padding: 8, borderRadius: 'theme:radiusLg', backgroundColor: 'theme:cardBg', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' }, hoverStyle: { borderColor: 'theme:primary' } },

  HW_MenuDropdown: { type: 'Box', style: { position: 'absolute', left: 236, top: 34, width: 420, borderRadius: 'theme:radiusLg', backgroundColor: 'theme:surface', borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder', overflow: 'hidden' } },
  HW_MenuDropHead: { type: 'Box', style: { flexDirection: 'row', alignItems: 'center', gap: 7, paddingLeft: 10, paddingRight: 10, paddingTop: 8, paddingBottom: 7, backgroundColor: 'theme:bgElevated', borderBottomWidth: 'theme:borderThin', borderBottomColor: 'theme:border' } },
  HW_MenuDropRow: { type: 'Pressable', style: { minHeight: 27, flexDirection: 'row', alignItems: 'center', gap: 8, paddingLeft: 10, paddingRight: 9, borderBottomWidth: 'theme:borderThin', borderBottomColor: 'theme:borderSoft' }, hoverStyle: { backgroundColor: 'theme:surfaceHover' } },
  HW_MenuDropText: { type: 'Text', fontSize: 11, color: 'theme:text' },
  HW_MenuDropSub: { type: 'Text', fontSize: 9, color: 'theme:textDim', style: { fontFamily: MONO } },
  HW_CheckCell: { type: 'Box', style: { width: 13, height: 13, alignItems: 'center', justifyContent: 'center', borderRadius: 7, backgroundColor: 'theme:segActiveBg', borderWidth: 'theme:borderThin', borderColor: 'theme:primary' } },
  HW_CheckCellOff: { type: 'Box', style: { width: 13, height: 13, borderRadius: 7, borderWidth: 'theme:borderThin', borderColor: 'theme:controlBorder' } },
  HW_HistoryTitle: { type: 'Text', fontSize: 11, color: 'theme:text', style: { fontWeight: 800 } },
  HW_HistoryMeta: { type: 'Text', fontSize: 9, color: 'theme:textDim', style: { fontFamily: MONO } },
});

export { C };
